var quiz = [
    {
        q: `A 26-year-old woman with postpartum sepsis is afebrile on antibiotic therapy, but she has had worsening oxygenation over the past 3 days. Her chest radiograph shows scattered bilateral pulmonary opacifications. A ventilation-perfusion scan shows areas of mismatch. Which of the following microscopic findings is most likely to be present in her lungs?`,
        q2: ``,
        q3: [],
        option: [`Alveolar hyaline membranes`, `Pulmonary arteriolosclerosis`, `Interstitial fibrosis`,`Lymphocytic infiltrates`,`Respiratory bronchiolar destruction`],
        optionFeedback: [`Sepsis is the most common cause of acute lung injury and acute respiratory distress syndrome (ARDS), in which pulmonary endothelial damage, often mediated by activated leukocytes, leads to pulmonary inflammation and edema that organizes into alveolar hyaline membranes composed of fibrin and cellular debris. Ventilation-perfusion mismatch refers to continued perfusion of poorly aerated areas. It occurs due to thickening of the interstitium and the presence of intraalveolar edema fluid and hyaline membranes. `,`Pulmonary arteriosclerosis usually occurs secondary to longstanding pulmonary hypertension. `,`Interstitial fibrosis could be a late feature of healed acute lung injury, but the timing is wrong for this.`,`Sepsis and lung injury are associated with innate immune cell infiltrates (neutrophils and macrophages).`,`Respiratory bronchiolar destruction is a feature of emphysema, a chronic lung disorder.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Sepsis is the most common cause of acute lung injury and acute respiratory distress syndrome (ARDS), in which pulmonary endothelial damage, often mediated by activated leukocytes, leads to pulmonary inflammation and edema that organizes into alveolar hyaline membranes composed of fibrin and cellular debris. Ventilation-perfusion mismatch refers to continued perfusion of poorly aerated areas. It occurs due to thickening of the interstitium and the presence of intraalveolar edema fluid and hyaline membranes.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `After a hemicolectomy to remove a colon carcinoma, a 56-year-old man develops respiratory distress. He is intubated and receives mechanical ventilation with 100% oxygen. His hemoglobin (Hb) is 11.2g/dL (13.5–17.5 g/dL), white blood cell (WBC) count is 8,500/mm<sup>3</sup> (4,500–11,000/mm<sup>3</sup>) and PT and PTT are within reference range. Three days later, his arterial oxygen saturation decreases to 60%. A chest radiograph shows increasing opacification in all lung fields. Microscopic examination of a lung biopsy shows hyaline membranes lining distended alveolar ducts and sacs. Which of the following is the most likely mechanism underlying these morphologic changes?`,
        q2: ``,
        q3: [],
        option: [`Viral pneumonia`, `Disseminated intravascular coagulation (DIC)`,`Inflammation-mediated injury to alveolar capillaries`,`Reduced production of surfactant`,`Release of fibrogenic cytokines by macrophages`],
        optionFeedback: [`Viral pneumonia can also lead to hyaline membrane formation, but in the absence of fever and cough viral pneumonia is highly unlikely.`,`DIC may accompany sepsis but is not believed to induce ARDS itself directly. `,`Systemic inflammation, regardless of cause, that results in damage to pulmonary endothelium can lead to the acute respiratory distress syndrome, the pathologic hallmark of which is alveolar hyaline membranes. Both cytokine-mediated endothelial injury and activation of leukocytes, particularly neutrophils, may be contributory. High levels of inhaled oxygen can also cause oxidant-mediated injury, worsening the diffuse alveolar damage.`,`Reduced production of surfactant is a feature of respiratory distress syndrome occurring in premature infants. `,`Release of fibrogenic cytokines by macrophages is associated with organization of the intraalveolar exudate, sometimes resulting in post-ARDS pulmonary fibrosis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale:-  Systemic inflammation, regardless of cause, that results in damage to pulmonary endothelium can lead to the acute respiratory distress syndrome, the pathologic hallmark of which is alveolar hyaline membranes. Both cytokine-mediated endothelial injury and activation of leukocytes, particularly neutrophils, may be contributory. High levels of inhaled oxygen can also cause oxidant-mediated injury, worsening the diffuse alveolar damage. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 58-year-old man has gradually increasing dyspnea and a 4-kg weight loss over the past 2 years. He has smoked two packs of cigarettes per day for 20 years, but not for the past year. Physical examination shows an increase in the anteroposterior diameter of the chest. Auscultation of the chest shows decreased breath sounds. A chest radiograph shows bilateral hyperlucent lungs; pulmonary function tests show that FEV<sub>1</sub> is markedly decreased, but FVC (forced vital capacity) is normal, and the FEV<sub>1</sub>:FVC ratio is decreased. Which of the following is most likely to contribute to reduction in FEV<sub>1</sub>?`,
        q2: ``,
        q3: [],
        option: [` Abnormal epithelial cell chloride ion transport`, `Spasm of bronchioles`,`Impaired hepatic release of α1-antitrypsin`,`Macrophage activation and release of interferon-γ`,`Release of elastase from neutrophils`],
        optionFeedback: [`Abnormal epithelial cell chloride ion transport is a feature of cystic fibrosis, which is characterized by recurrent pulmonary infections. `,`Spasm of bronchioles is a feature of asthma.`,`Impaired hepatic release of α1-antitrypsin due to inherited mutations in this “antiprotease” can lead to emphysema due to elevated elastase activity and typically presents in younger patients.  It is uncommon and unlikely to be involved in this case.`,`Macrophage activation and release of interferon-γ is a feature of granulomatous pulmonary disorders of excessive Th1 cell activity, such as tuberculosis. `,`Smoking is a common cause of emphysematous changes in the lung, marked by hyperlucent lungs and a decrease in FEV<sub>1</sub> due to loss of elastic tissue, which causes the bronchioles to collapse during expiration. The loss of elastin is due to elastase released from neutrophils, which are recruited to the lung by smoking-related lung injury.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-Smoking is a common cause of emphysematous changes in the lung, marked by hyperlucent lungs and a decrease in FEV<sub>1</sub> due to loss of elastic tissue, which causes the bronchioles to collapse during expiration. The loss of elastin is due to elastase released from neutrophils, which are recruited to the lung by smoking-related lung injury. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 59-year-old man with a 30-pack-year smoking history has had increasing dyspnea for the past 4 years. He has an occasional cough with minimal sputum production. On physical examination, his lungs are hyperresonant with expiratory wheezes. Pulmonary function tests show increased total lung capacity (TLC) with slightly increased FVC and decreased FEV<sub>1</sub> and FEV<sub>1</sub>:FVC ratio. Which of the following morphologic changes in the lung is most likely to give rise to this clinical picture?`,
        q2: ``,
        q3: [],
        option: [` Permanent dilation of bronchi and bronchioles with destruction of their walls`, `Destruction of elastic tissue in the walls of alveoli`,`Diffuse alveolar damage`,`Hypertrophy of bronchial smooth muscles`,`Diffuse interstitial fibrosis`],
        optionFeedback: [`Permanent dilation of bronchi is a feature of bronchiectasis, which is associated with pulmonary opacities and copious sputum production. `,`The smoking history, the depressed FEV<sub>1</sub> and FEV<sub>1</sub>:FVC, and the hyperresonant (e.g., overinflated) lungs all point to emphysematous changes, which stem from loss of elastic tissue in the walls of alveoli leading to collapse of bronchioles during expiration.  `,`Diffuse alveolar damage is a feature of acute respiratory distress syndrome whereas this patient has chronic disease. `,`Hypertrophy of bronchial smooth muscle cells is a feature of asthma, which usually causes paroxysms of wheezing during “attacks”. `,`Diffuse interstitial fibrosis is a form of restrictive lung disease. It is associated with bilateral increase in lung markings (honeycomb lung), rather than hyperlucent lungs. FEV<sub>1</sub>:FVC ratio is near normal in restrictive lung disease due to proportionate decrease in FEV<sub>1</sub> and FVC.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The smoking history, the depressed FEV<sub>1</sub> and FEV<sub>1</sub>:FVC, and the hyperresonant (e.g., overinflated) lungs all point to emphysematous changes, which stem from loss of elastic tissue in the walls of alveoli leading to collapse of bronchioles during expiration. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 33-year-old man has had increasing dyspnea for the past 8 years. He does not smoke. On examination, there are decreased breath sounds over lower lung fields. The abdomen is distended due to ascites, and an ultrasound reveals splenic enlargement. Pedal edema is also noted. A chest radiograph shows flattened diaphragms; pulmonary function tests show decreased FEV<sub>1</sub> and FEV<sub>1</sub>:FVC ratio. Serum albumin level is reduced. A liver biopsy shows histologic changes of cirrhosis. A sibling is similarly affected. What is the most likely mechanism for his pulmonary disease?`,
        q2: ``,
        q3: [],
        option: [`Atopy with IgE binding to mast cells`, `CFTR mutation`,`Increased neutrophil proteases`,`HFE mutation `,`α1-Antitrypsin gene mutation`],
        optionFeedback: [`Atopy with IgE binding to mast cells is associated with bronchial asthma. `,`CFTR mutation is the cause of cystic fibrosis, which can cause both liver and lung disease, but typically comes to clinical attention early in life, often in the neonatal period. `,`The amount of neutrophil-associated proteases is not altered in α1-antitrypsin deficiency, but instead protease activity is increased due to the deficit in α1-antitrypsin, which acts as an inhibitor of elastase and other proteases.`,`HFE mutation is associated with hereditary hemochromatosis, which is associated with a risk of cirrhosis but not lung disease.`,`The patient’s symptoms are consistent with a genetic condition that leads to pulmonary emphysema and hepatic cirrhosis. Among the possible answers, only α1-antitrypsin deficiency fits these findings. Mutant α1-antitrypsin is retained in hepatocytes and not secreted in the plasma. Lack of this enzyme causes unchecked activity of neutrophil elastase, which in turn damages elastic tissue in alveolar walls leading to emphysema.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The patient’s symptoms are consistent with a genetic condition that leads to pulmonary emphysema and hepatic cirrhosis. Among the possible answers, only α1-antitrypsin deficiency fits these findings. Mutant α1-antitrypsin is retained in hepatocytes and not secreted in the plasma. Lack of this enzyme causes unchecked activity of neutrophil elastase, which in turn damages elastic tissue in alveolar walls leading to emphysema.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 55-year-old man has smoked two packs of cigarettes per day for 35 years. For the past 4 years, he has had a chronic cough with copious mucoid expectoration. During the past year, he has had multiple respiratory tract infections diagnosed as “viral flu.” He has also developed difficulty breathing, tightness of the chest, and audible wheezing. His breathing difficulty is relieved by inhalation of a β-adrenergic agonist and disappears after the chest infection has resolved. Which of the following pathologic changes is most likely to be present in this patient?`,
        q2: ``,
        q3: [],
        option: [`Destruction of alveolar walls with airspace enlargement`, `Permanent dilation of bronchi with destruction of their walls`,`Interstitial pneumonia`,`Enlargement of mucus-secreting glands in bronchial walls`,`Accumulation of misfolded α1-antitrypsin in hepatocytes`],
        optionFeedback: [`Destruction of alveolar walls is a feature of emphysema, which is typically not associated with productive cough. `,`Permanent dilation of bronchi with wall destruction defines bronchiectasis, which is associated with copious sputum production. It is treated with antibiotics and does not respond to bronchodilators. `,`Interstitial pneumonia (e.g., due to viral infection) is associated with cough but little sputum production. `,`The clinical scenario is consistent with chronic bronchitis, a form of smoking-related chronic obstructive pulmonary disease associated with productive cough due to hypersecretion of mucus from bronchial glands. It often is exacerbated by infection and hyperresponsiveness of airway smooth muscle, leading to constriction of airways that is relieved by β-adrenergic agonists, as occurs in bronchial asthma. Eventually, symptoms of both chronic bronchitis and bronchial asthma may develop, a condition called asthmatic bronchitis. `,`α1-antitrypsin disease may lead to emphysema, which does not fit the clinical scenario.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The clinical scenario is consistent with chronic bronchitis, a form of smoking-related chronic obstructive pulmonary disease associated with productive cough due to hypersecretion of mucus from bronchial glands. It often is exacerbated by infection and hyperresponsiveness of airway smooth muscle, leading to constriction of airways that is relieved by β-adrenergic agonists, as occurs in bronchial asthma. Eventually, symptoms of both chronic bronchitis and bronchial asthma may develop, a condition called asthmatic bronchitis.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 16-year-old girl has a 7-year history of coughing and wheezing and repeated attacks of difficulty breathing. During an episode of acute respiratory difficulty, a physical examination shows that she is afebrile, her lungs are hyperresonant on percussion, and a chest radiograph shows increased lucency of all lung fields. Laboratory tests show an elevated serum IgE level and peripheral blood eosinophilia. A sputum sample examined microscopically also has increased numbers of eosinophils. Which of the following histologic features is most likely to characterize the lung in her condition?`,
        q2: ``,
        q3: [],
        option: [`Dilation of respiratory bronchioles with loss of elastic fibers`, `Inflammatory destruction of bronchial walls`,`Interstitial and alveolar edema with hyaline membrane formation`,`Patchy areas of consolidation with leukocytic exudates in alveoli`,`Remodeling of airways with smooth muscle hyperplasia`],
        optionFeedback: [`Dilation of respiratory bronchioles due to loss of elastic fibers is a feature of emphysema.`,`Inflammatory destruction of bronchial walls defines bronchiectasis. `,`Interstitial and alveolar edema with hyaline membrane formation are features of acute respiratory distress syndrome.`,`Patchy areas of consolidation with alveolar leukocytic infiltrates are features of bronchopneumonia.`,`The clinical scenario is consistent with atopic asthma complicated by acute attacks leading to “air-trapping” due to bronchoconstriction. Characteristic morphologic changes, collectively called <b>airway remodeling</b>, include thickening of the airway wall, submucosal fibrosis, increased submucosal vascularity, an increase in the size of submucosal glands, goblet cell metaplasia, and hypertrophy of bronchial smooth muscle.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The clinical scenario is consistent with atopic asthma complicated by acute attacks leading to “air-trapping” due to bronchoconstriction. Characteristic morphologic changes, collectively called <b>airway remodeling</b>, include thickening of the airway wall, submucosal fibrosis, increased submucosal vascularity, an increase in the size of submucosal glands, goblet cell metaplasia, and hypertrophy of bronchial smooth muscle.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 35-year-old man has a 5-year history of episodic wheezing and coughing. The episodes are more common during the winter months, and he has noticed that they often follow minor respiratory tract infections. In the period between the episodes, he can breathe normally. There is no family history of asthma or other allergies. On physical examination, there are no remarkable findings. A chest radiograph shows no abnormalities. A serum IgE level and WBC count are normal. Which of the following is the most likely mechanism that contributes to the findings in his illness?`,
        q2: ``,
        q3: [],
        option: [`Accumulation of alveolar neutrophilic exudate`, `Bronchial hyperreactivity to viral infections`,`Emigration of eosinophils into bronchi`,`Cross linking of IgE Fc receptors`,`Secretion of interleukin (IL)-2 and interferon (IFN)-γ by T cells`],
        optionFeedback: [`Accumulation of neutrophils in alveolar spaces is a feature of acute bacterial pneumonia, typically associated with an elevated WBC count and acute symptoms.`,`The clinical scenario is consistent with nonatopic asthma, in which exposure to certain triggers such as viral infections leads to bronchospasm and airway obstruction. The pathogenesis is incompletely understood but involves hyperreactive bronchial smooth muscle cells.  `,`Emigration of eosinophils into bronchi is seen in atopic asthma, which this patient does not appear to have based on the normal IgE level.`,`Crosslinking of IgE Fc receptors is seen in atopic asthma, which this patient does not appear to have based on the normal IgE level. `,`Secretion of IL-2 and IFN-γ by T cells are features of granulomatous disease, such as sarcoidosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The clinical scenario is consistent with nonatopic asthma, in which exposure to certain triggers such as viral infections leads to bronchospasm and airway obstruction. The pathogenesis is incompletely understood but involves hyperreactive bronchial smooth muscle cells.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A study of individuals with longstanding atopic asthma reveals that the late-phase inflammatory response to allergens potentiates epithelial-cell cytokine production that promotes airway remodeling. A biotech company is interested in developing an antagonist of the late-phase inflammatory response. Targeting which of the following immune cells is most likely to be beneficial?`,
        q2: ``,
        q3: [],
        option: [`CD8+ T cells`, `Mast cells`,`Th1 lymphocytes`,`Th2 lymphocytes`,` Th17 lymphocytes`],
        optionFeedback: [`CD8+ T cells are not involved in atopic asthma, whereas they have central roles in other lung diseases, such as viral infections.`,`Mast cells are responsible for the early-phase response in asthma; they are primed by IgE, which is produced under the direction of Th2 cells. `,`Th1 cells are not involved in atopic asthma, whereas they have central roles in other lung diseases, such as granulomatous disorders.`,`Cytokines released by Th2 cells account for most of the features of atopic asthma. IL-4 and IL-13 stimulate IgE production, IL-5 activates eosinophils, and IL-13 also stimulates mucus production. IgE binds to submucosal mast cells, which on exposure to allergens release their granule contents and secrete cytokines and other mediators. Thus, Th2 cells are rational targets in this disorder.  `,`Th17 cells have central roles in other lung diseases, such as fungal infections. They may contribute to the neutrophilic inflammation sometimes seen in asthma but are not the primary mediators of this disease. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Cytokines released by Th2 cells account for most of the features of atopic asthma. IL-4 and IL-13 stimulate IgE production, IL-5 activates eosinophils, and IL-13 also stimulates mucus production. IgE binds to submucosal mast cells, which on exposure to allergens release their granule contents and secrete cytokines and other mediators. Thus, Th2 cells are rational targets in this disorder.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 35-year-old woman has experienced multiple bouts of severe necrotizing pneumonia since childhood caused by Haemophilus influenzae, Staphylococcus aureus, Pseudomonas aeruginosa, and Serratia marcescens. She now has a cough productive of large amounts of purulent sputum. On physical examination, there is dullness to percussion with decreased breath sounds over the right mid to lower lung fields. A chest radiograph shows areas of right lower lobe consolidation. A bronchogram shows marked dilation of right lower lobe bronchi and milder dilation of left lower lobe bronchi. Which of the following mechanisms is the most likely cause of her disease?`,
        q2: ``,
        q3: [],
        option: [`Congenital malformation of the bronchial walls`, `Damage to bronchial mucosa by major basic protein of eosinophils`,`Diffuse infiltration by bronchogenic carcinoma`,`Recurrent inflammation with bronchial wall destruction`,` Unopposed action of neutrophil-derived elastase on bronchi`],
        optionFeedback: [`Congenital malformation of bronchial walls may lead to bronchiectasis but is usually localized to a single portion of the lung. `,`Damage of bronchial mucosa by the products of eosinophils is a feature of atopic asthma. `,`Bronchogenic carcinoma is unlikely in a young woman with onset of symptoms in childhood.`,`The clinical scenario is suggestive of some disorder of immune function, ciliary function, or infection clearance (e.g., cystic fibrosis) that promotes chronic pulmonary bacterial infection, destruction of bronchial walls, and the development of bronchiectasis (as evident from the dilated bronchi).  `,`Excessive elastase activity is seen in emphysema and is not associated with bronchiectasis or recurrent pneumonia.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The clinical scenario is suggestive of some disorder of immune function, ciliary function, or infection clearance (e.g., cystic fibrosis) that promotes chronic pulmonary bacterial infection, destruction of bronchial walls, and the development of bronchiectasis (as evident from the dilated bronchi).`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 67-year-old man has a 6-year history of increasing shortness of breath and weakness. On physical examination, he is afebrile and normotensive. A radiograph of his chest shows diffuse interstitial markings. Pulmonary function tests indicate diminished FVC, decreased DLCO (diffusion capacity of lungs for carbon monoxide, which measures the efficiency of gas transfer from the alveoli to the blood), and a normal FEV<sub>1</sub>:FVC ratio. Which of the following sets of pathologic changes is most likely to be found in his lungs?`,
        q2: ``,
        q3: [],
        option: [`Acute inflammation of bronchial walls with prominence of eosinophils`, `Chronic inflammation with bronchial mucus gland hypertrophy`,`Dilation of airspaces distal to respiratory bronchioles`,` Honeycomb lung with extensive alveolar septal fibrosis`,`Diffuse alveolar epithelial necrosis and prominent hyaline membranes`],
        optionFeedback: [`Acute inflammation of bronchial walls and prominence of eosinophils are features of atopic asthma, which is associated with obstructive pulmonary function tests.`,`Chronic inflammation with smooth muscle hypertrophy are features of chronic bronchitis, which is associated with pulmonary function tests typical of obstructive lung disease. `,`Dilation of airspaces distal to respiratory bronchioles defines emphysema, which is associated with obstructive pulmonary function tests and hyperlucent lungs. `,`The clinical scenario is consistent with interstitial fibrosis leading to so-called honeycomb lung associated with, pulmonary function tests typical of restrictive lung disease (diminished FVC, and DLCO and normal FEV<sub>1</sub>: FVC ratio), and respiratory failure.  `,`Diffuse alveolar epithelial necrosis and prominent hyaline membranes are features of acute lung injury and acute respiratory distress syndrome, which is associated with severe illness.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The clinical scenario is consistent with interstitial fibrosis leading to so-called honeycomb lung associated with, pulmonary function tests typical of restrictive lung disease (diminished FVC, and DLCO and normal FEV<sub>1</sub>: FVC ratio), and respiratory failure.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 68-year-old man has had worsening dyspnea with a nonproductive cough for the past 9 months. On physical examination, he is afebrile and normotensive. Auscultation of the chest reveals diffuse dry crackles in all lung fields. A chest radiograph shows irregular opacifications throughout both lungs. A transbronchial biopsy is obtained and the microscopic findings are shown in the figure. Laboratory studies include negative serologic tests for antinuclear antibodies (ANA), anti–DNA topoisomerase I, antineutrophil cytoplasmic antibodies (ANCA), and anticentromere antibody. Which of the following class of drugs is most likely to be beneficial in cases like this?`,
        q2: `<img src="../images/f010-q013-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [` Drugs that inhibit fibrosis`, `Histamine antagonists`,`Lipoxygenase antagonists`,`Antiviral drugs`,`Broad-spectrum antibiotics`],
        optionFeedback: [`The clinical scenario and the presence of fibrous thickening of alveolar walls seen on microscopy is consistent with idiopathic pulmonary fibrosis. This disorder is more common in males, almost never appears before the age of 50 years, and is associated with inherited defects in several genes, including genes encoding telomerase, surfactant, and a particular mucin. Some antifibrosis therapies are approved for treating affected patients, but the overall outcome remains poor.  `,`Antihistaminic drugs are used for treatment of early acute phase reactions in type I hypersensitivity disorders like hay fever and urticaria.`,`Lipoxygenase antagonists are used to treat asthma, for which there is no evidence in this patient. `,`Viral infections can cause interstitial pneumonitis that usually resolves without sequelae. Infrequently, viral infections cause diffuse alveolar damage and acute respiratory distress syndrome`,`The clinical, laboratory, and pathologic findings are inconsistent with bacterial infection, and therefore broad-spectrum antibiotics are not indicated.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The clinical scenario and the presence of fibrous thickening of alveolar walls seen on microscopy is consistent with idiopathic pulmonary fibrosis. This disorder is more common in males, almost never appears before the age of 50 years, and is associated with inherited defects in several genes, including genes encoding telomerase, surfactant, and a particular mucin. Some antifibrosis therapies are approved for treating affected patients, but the overall outcome remains poor `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 63-year-old stone mason has had progressively worsening dyspnea over the past 10 years. He has noticed a 5-kg weight loss in the past 2 years. He has a chronic cough with minimal sputum production and no chest pain. On physical examination, he is afebrile and normotensive. A chest radiograph shows extensive interstitial disease. Pulmonary function tests show diminished diffusion capacity, low FVC, and normal FEV<sub>1</sub>:FVC ratio. Increased exposure to which of the following pollutants is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Carbon monoxide`, `Ozone`,`Silica`,`Tobacco smoke`,`Coal dust`],
        optionFeedback: [`Carbon monoxide poisoning is typically an acute event that is not associated with lung pathology.`,`Ozone exposure can exacerbate pulmonary and cardiovascular disease by causing inflammation but is not associated with pulmonary fibrosis.`,`Interstitial fibrosis and pulmonary function tests are indicative of restrictive lung disease. Among the exposures listed, silica is most likely to be associated with this clinical picture.  `,`Tobacco smoke exposure is associated with chronic obstructive pulmonary disease, which can take the form of emphysema and/or chronic bronchitis, but is not associated with pulmonary fibrosis.`,`Coal dust can produce changes similar to those produced by exposure to silica but has decreased as a cause of restrictive lung disease in the western world as work in coal mines has declined. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Interstitial fibrosis and pulmonary function tests are indicative of restrictive lung disease. Among the exposures listed, silica is most likely to be associated with this clinical picture.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    
    {
        q: `A 69-year-old man with a 30-pack-year smoking history has experienced increasing dyspnea for the past 10 years. He works for a home builder and his job includes removal and installation of insulation. On physical examination, he is afebrile, with a pulse of 70 beats/min, respirations 30 breaths/min, and blood pressure 120/75 mm Hg. A chest radiograph shows increased interstitial markings, but no effusions. The right heart border and the pulmonary arteries are prominent. A transbronchial biopsy reveals the presence of a squamous cell carcinoma. The cancer spreads to distant organs resulting in death. The figure shows a portion of the lung. The pathogenesis of the pleural lesions is most likely to involve which of the following processes?`,
        q2: `<img src="../images/f010-q015-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Activation of inflammasome in macrophages`, `Development of cell-mediated immunity to inhaled dust particles`,` Development of allergic alveolitis to inhaled dust particles`,`Development of bronchial hyperresponsiveness`,` Recurrent infections with Aspergillus sp`],
        optionFeedback: [`Workplace exposure to insulation suggests the diagnosis of asbestosis, a cause of interstitial fibrosis and pleural fibrous plaques seen in the figure. Asbestos exposure increases the risk of mesothelioma and lung cancer (the latter particularly in those who also smoke). Asbestos fibers are phagocytosed by macrophages and cause inflammation by activating the inflammasome in macrophages. `,`Development of cell-mediated immunity to inhaled dust particles corresponds to hypersensitivity pneumonitis secondary to inhalation of allergens, which is not associated with pleural plaques or cancer.`,`Development of allergic alveolitis to inhaled dust particles corresponds to hypersensitivity pneumonitis secondary to inhalation of allergens, which is not associated with pleural plaques or cancer. `,`Bronchial hyperresponsiveness is a feature of asthma, which also does not fit the clinical or pathologic features. `,`Recurrent infection with Aspergillus is most common in immunosuppressed individuals, particularly those who have neutropenia. Aspergillus has a predilection for invading blood vessels giving rise to areas of hemorrhagic necrosis. Asbestosis is not associated with fungal infections.`],
        optionStyleType:`st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Workplace exposure to insulation suggests the diagnosis of asbestosis, a cause of interstitial fibrosis and pleural fibrous plaques seen in the figure. Asbestos exposure increases the risk of mesothelioma and lung cancer (the latter particularly in those who also smoke). Asbestos fibers are phagocytosed by macrophages and cause inflammation by activating the inflammasome in macrophages `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 36-year-old woman has had a low-grade fever and worsening nonproductive cough and dyspnea for the past 2 years. On examination, she has breath sounds in all lung fields.. Pulmonary function tests show patterns typical of a restrictive lung disease. A transbronchial biopsy is shown in the figure. Which of the following cells and mediator pairs are most likely to be found in the inflammatory infiltrate?`,
        q2: `<img src="../images/f010-q016-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`CD8+ T cells and perforin`, `CD4+ T cells and IFN-gamma`,`CD4+ T cells and IL-17`,`Mast cells and tumor necrosis factor (TNF)`,`B cells and IL-4`],
        optionFeedback: [`CD8+ T cells and perforin are relevant in T-cell mediated cytotoxicity against virally infected cells.`,`The figure shows noncaseating granulomas made up of circumscribed collections of epithelioid cells, consistent with a diagnosis of sarcoidosis. Granulomatous inflammation is mediated by CD4+ Th1 cells that produce IL-2, which activates and stimulates the proliferation of these T cells. Activated CD4+ Th1 cells in turn release additional factors such as IFN-γ that recruit and activate macrophages and transform them into epithelioid cells.  `,`CD4+ T cells and IL-17 are important in responses to fungal infections with recruitment of neutrophils.`,`Mast cells and TNF participate in type 1 hypersensitivity reactions, including atopic asthma.`,`B cells and IL-4 contribute to reactions that are directed by CD4+ Th2 cells, such as responses to helminthic infections. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The figure shows noncaseating granulomas made up of circumscribed collections of epithelioid cells, consistent with a diagnosis of sarcoidosis. Granulomatous inflammation is mediated by CD4+ Th1 cells that produce IL-2, which activates and stimulates the proliferation of these T cells. Activated CD4+ Th1 cells in turn release additional factors such as IFN-γ that recruit and activate macrophages and transform them into epithelioid cells.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 61-year-old woman has noted increasing dyspnea and a nonproductive cough for 5 months. A chest radiograph shows prominent hilar lymphadenopathy with interstitial infiltrates bilaterally. A transbronchial biopsy is performed, and the microscopic findings include interstitial fibrosis and small, noncaseating granulomas. One granuloma contains an asteroid body in a giant cell. The medical history indicates that she smoked cigarettes for 10 years but stopped 5 years ago. Which of the following is the most likely cause of her illness?`,
        q2: ``,
        q3: [],
        option: [`T cell-mediated response to unknown antigen`, `Antibody-mediated diffuse alveolar damage`,`Deposition of immune complexes`,`Infection with atypical mycobacteria`,`Smoke inhalation with bronchiolitis`],
        optionFeedback: [`The presence of noncaseating granulomas with interstitial fibrosis is consistent with sarcoidosis, a disorder caused by a chronic Th1 T cell response to an unknown antigen or antigens.  `,`Antibody-mediated lung diseases such as Goodpasture syndrome do not produce granulomatous inflammation. `,`Vasculitis caused by immune complex deposition does not produce granulomatous inflammation. `,`Infection with atypical mycobacteria often occurs in patients with marked impairment of T-cell immunity such as those with HIV disease, and is usually associated with nonspecific (and ineffective) chronic inflammation.  Severe impairment of T cell immunity often prevents the formation of granulomas.`,`Smoke inhalation causes acute injury to airways and may cause diffuse alveolar damage. It is not associated with granulomatous inflammation or interstitial fibrosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The presence of noncaseating granulomas with interstitial fibrosis is consistent with sarcoidosis, a disorder caused by a chronic Th1 T cell response to an unknown antigen or antigens. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 64-year-old alfalfa farmer has a 15-year history of increasing dyspnea. A chest radiograph shows a bilateral increase in linear markings. Pulmonary function tests show reduced FVC with a normal FEV<sub>1</sub>. A transbronchial lung biopsy specimen shows interstitial infiltrates of lymphocytes and plasma cells, minimal interstitial fibrosis, and small granulomas. What is the most likely cause of this clinical and pathologic picture?`,
        q2: ``,
        q3: [],
        option: [`Autoantibodies against alveolar basement membranes`, `Chronic inhalation of silica particles`,`Hypersensitivity to spores of actinomycetes`,`Infection with Mycobacterium tuberculosis`,`Prolonged exposure to inorganic dusts`],
        optionFeedback: [`Autoantibodies against alveolar basement membranes are seen in Goodpasture syndrome, which is associated with hemoptysis and diffuse alveolar damage. `,`Silica particles may induce granulomas, but mainly cause extensive pulmonary fibrosis. `,`The findings are consistent with “farmer’s lung”, a chronic hypersensitivity pneumonitis that is triggered by exposure to organisms such as the spores of actinomycetes. Unlike bacterial pneumonias, hypersensitivity pneumonitis has interstitial mononuclear cell infiltrates. Occasional granulomas and mild interstitial fibrosis can also be seen. Pulmonary function tests are typical of a restrictive lung disease.  `,`M.   tuberculosis infection classically causes the appearance of granulomas with caseous necrosis and follows a more acute or subacute course. `,`Prolonged exposure to other inorganic dusts (e.g., beryllium) is associated with much more pronounced fibrosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The findings are consistent with “farmer’s lung”, a chronic hypersensitivity pneumonitis that is triggered by exposure to organisms such as the spores of actinomycetes. Unlike bacterial pneumonias, hypersensitivity pneumonitis has interstitial mononuclear cell infiltrates. Occasional granulomas and mild interstitial fibrosis can also be seen. Pulmonary function tests are typical of a restrictive lung disease.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 61-year-old man had a myocardial infarction 1 year ago and now has congestive heart failure, reducing his ability to ambulate. Over the past 24 hours, he has developed right-sided chest pain. On auscultation, a pleural friction rub is located over the base of the right lung. He is afebrile, his pulse is 70 beats/min, his respirations are 27/min and shallow, and his blood pressure is 130/85 mm Hg. He is afebrile. The appearance of his right lower lobe is shown in the figure. Which of the following disorders is most likely to precede the appearance of the lesion shown?`,
        q2: `<img src="../images/f010-q019-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Chronic obstructive pulmonary disease (COPD)`, ` Viral pneumonia`,`Infective endocarditis`,`Deep vein thrombosis`,` Polyarteritis nodosa`],
        optionFeedback: [`Nothing in the history suggests the possibility of COPD, which would be associated with other lung findings (emphysema, chronic productive cough, interstitial pneumonitis, etc.).`,`Nothing in the history suggests the possibility of viral pneumonia, which would be associated with other symptoms (e.g., fever, headache, myalgias).`,`Right-sided infective endocarditis conceivably could lead to thromboembolism and pulmonary infarction, but other features of this disorder (e.g., evidence of infection) are absent, and endocarditis affecting the right side of the heart is very rare except in intravenous drug users.`,`The subpleural hemorrhagic area is typical of a pulmonary infarct, the most likely cause of which is embolism from a deep vein thrombosis (DVT). Risk factors for DVT in this case include male sex, age over 50, and decreased mobility.  `,`Polyarteritis nodosa is a vasculitis affecting small- to medium-sized arteries in multiple visceral organs that typically spares the lung. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The subpleural hemorrhagic area is typical of a pulmonary infarct, the most likely cause of which is embolism from a deep vein thrombosis (DVT). Risk factors for DVT in this case include male sex, age over 50, and decreased mobility.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 68-year-old woman had a cerebral infarction and was hospitalized for 3 weeks. Her condition improved, and she was able to get up and move about with assistance. A few minutes after walking to the bathroom, she experienced sudden onset of severe dyspnea with chest pain and diaphoresis. Despite resuscitative measures, she was declared dead 30 minutes later. The major autopsy finding is shown in the figure. Which of the following is the most likely mechanism for sudden death in this patient?`,
        q2: `<img src="../images/f010-q020-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Severe bronchospasm`, `Pneumothorax`,`Hemorrhagic infarction`,`Interstitial edema`,`Acute cor pulmonale`],
        optionFeedback: [`Severe bronchospasm (e.g., status asthmaticus) would be associated with wheezing and hyperinflated lungs.`,`Pneumothorax may lead to sudden onset of respiratory symptoms but does not usually cause cardiac compromise and is not a cause of sudden death.`,`Hemorrhagic infarction (usually in those in whom pulmonary embolism [PE] is superimposed on chronic cardiac or pulmonary disease) takes hours to develop. `,`Interstitial edema is usually of slower onset and does not cause sudden death.`,`The patient experienced a large pulmonary thromboembolus, one of the few causes of virtually instantaneous death, due to acute right-sided-sided heart failure (cor pulmonale). The primary acute effects of pulmonary emboli are right heart strain due to increased resistance to pumping of the blood and hypoxemia due to ventilation/perfusion mismatch (lack of perfusion in ventilated air spaces).  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The patient experienced a large pulmonary thromboembolus, one of the few causes of virtually instantaneous death, due to acute right-sided-sided heart failure (cor pulmonale). The primary acute effects of pulmonary emboli are right heart strain due to increased resistance to pumping of the blood and hypoxemia due to ventilation/perfusion mismatch (lack of perfusion in ventilated air spaces).  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 25-year-old woman has had progressive dyspnea and fatigue for the past 2 years. On physical examination, she has pedal edema, jugular venous distention, and hepatomegaly. Lung fields are clear on auscultation. Chest CT scan shows right heart enlargement. Cardiac catheterization is performed, and the pulmonary arterial pressure is noted to be increased, without gradients across the pulmonic valve, and no shunts are identified. A transbronchial biopsy is performed, and microscopic examination shows marked medial hypertrophy and intimal fibrosis of arterioles and small arteries. A mutation in a gene encoding for which of the following is most likely to cause her pulmonary disease?`,
        q2: ``,
        q3: [],
        option: [`α1-antitrypsin`, `Bone morphogenetic protein receptor 2 (BMPR2)`,`Low density lipoprotein receptor`,`Fibrillin1`,`Lysyl hydroxylase`],
        optionFeedback: [`α1-Antitrypsin mutations cause emphysema and cirrhosis.`,`The clinical findings are consistent with pulmonary hypertension. In a young woman with no risk factors, a genetic predisposition is likely, and among the genes listed, only mutations in BMPR2 are associated with pulmonary hypertension.  `,`Low density lipoprotein receptor mutations are associated with systemic atherosclerosis, not pulmonary vascular changes.`,`Mutations in fibrillin 1 cause Marfan syndrome.`,`Lysyl hydroxylase mutations underlie some forms of Ehlers-Danlos syndrome. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The clinical findings are consistent with pulmonary hypertension. In a young woman with no risk factors, a genetic predisposition is likely, and among the genes listed, only mutations in BMPR2 are associated with pulmonary hypertension.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 29-year-old man who smokes tobacco and has had no major illnesses experiences the acute onset of hemoptysis. On physical examination, he has a temperature of 37&#176; C, pulse of 83 beats/min, respirations of 28 breaths/min, and blood pressure of 150/95 mm Hg. A chest radiograph shows bilateral fluffy infiltrates. A transbronchial lung biopsy shows focal necrosis of alveolar walls associated with prominent intra-alveolar hemorrhage. Two days later, he has oliguria. The serum creatinine level is 2.9 mg/dL (0.6–1.2 mg/dL), and urea nitrogen is 31 mg/dL (7–18 mg/dL). Which of the following antibodies is most likely involved in the pathogenesis of his condition?`,
        q2: ``,
        q3: [],
        option: [`Anti–DNA topoisomerase I antibody`, `Anti–glomerular basement membrane antibody`,`Antimitochondrial antibody`,`Antineutrophil cytoplasmic antibody`,`Antinuclear antibody`],
        optionFeedback: [`Topoisomerase I antibodies are associated with systemic sclerosis (scleroderma).`,`The clinical findings are consistent with Goodpasture syndrome, in which binding of autoantibodies to collagen in basement membrane antigens of the lung and kidney damages these organs, causing hemoptysis and acute renal failure.  `,`Antimitochondrial antibodies are associated with primary biliary cholangitis. `,`Antineutrophil cytoplasmic antibodies are associated with polyangiitis with granulomatosis and other forms of vasculitis.`,`Antinuclear antibodies are associated with systemic lupus erythematosus and other so-called collagen vascular disorders.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical findings are consistent with Goodpasture syndrome, in which binding of autoantibodies to collagen in basement membrane antigens of the lung and kidney damages these organs, causing hemoptysis and acute renal failure.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 42-year-old man has had chronic sinusitis for 7 months. He now has malaise and a mild fever that have persisted for 3 weeks. On physical examination, his temperature is 37.9&#176; C.    On auscultation, a few crackles are heard over the lungs. Laboratory studies show serum urea nitrogen of 35 mg/dL (7–18 mg/dL); creatinine, 4.3 mg/dL (0.6–1.2 mg/dL); ALT, 167 U/L (8–20 U/L); AST, 154 U/L (8–20 U/L); and total bilirubin, 1.1 mg/dL (0.1–1.0 mg/dL). A chest radiograph shows scattered 1-cm pulmonary nodules. A transbronchial lung biopsy is performed, and microscopic examination shows necrotizing granulomatous capillaritis, a poorly formed granuloma, and intra-alveolar hemorrhage. Urinalysis shows red cells (RBCs) with RBC casts. Autoantibodies to which of the following are most likely to be present in this man?`,
        q2: ``,
        q3: [],
        option: [`DNA topoisomerase I (Scl-70)`, ` Double-stranded DNA (dsDNA)`,` Glomerular basement membrane (GBM)`,`Proteinase 3 antineutrophil cytoplasmic antibodies (PR3-ANCA)`,`Endothelial cells`],
        optionFeedback: [`Topoisomerase I antibodies are associated with systemic sclerosis (scleroderma).`,`Anti–doubled stranded DNA antibodies are associated with systemic lupus erythematosus and other so-called collagen vascular disorders. `,`Anti–glomerular basement membrane antibodies are associated with Goodpasture syndrome.`,`Nasopharyngeal, pulmonary, and renal involvement associated with a granulomatous vasculitis are all typical of polyangiitis with granulomatosis, a disorder that is strongly associated with PR3-ANCA (formerly known as c-ANCA).  Previously, this disorder was called Wegener granulomatosis. `,`Anti–endothelial cell antibodies are not associated with autoimmune disorders but are causative in hyperacute rejection of organ transplants.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-     Nasopharyngeal, pulmonary, and renal involvement associated with a granulomatous vasculitis are all typical of polyangiitis with granulomatosis, a disorder that is strongly associated with PR3-ANCA (formerly known as c-ANCA).   Previously, this disorder was called Wegener granulomatosis.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 54-year-old woman has had an increasingly severe cough productive of yellowish sputum for four days. On physical examination, her temperature is 38.9&#176; C, and diffuse crackles are heard in the left lower lung posteriorly. Laboratory studies show a WBC count of 11,990/mm<sup>3</sup> (4,500-11,000/mm<sup>3</sup>) with 71% segmented neutrophils, 9% bands, 16% lymphocytes, and 4% monocytes. The representative gross appearance of the affected lung is shown in the figure. Which of the following pathogens is most likely to be cultured from this patient’s sputum?`,
        q2: `<img src="../images/f010-q024-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Cryptococcus neoformans`, `Mycobacterium kansasii`,`Mycoplasma pneumoniae`,`Pneumocystis jiroveci`,`Streptococcus pneumoniae`],
        optionFeedback: [`Cryptococcus is mainly confined to immunosuppressed individuals and does not produce lobar pneumonias.`,`Atypical mycobacterial infection is seen in immunosuppressed individuals and does not produce lobar pneumonias.`,`Mycoplasma pneumoniae is also community-acquired but produces an interstitial pneumonia that usually is not productive of sputum. `,`Pneumocystis infection is seen in immunosuppressed individuals and does not produce lobar pneumonias.`,`The patient has cough and polymorphonuclear leukocytosis suggesting bacterial infection in the lung. On gross examination, the entire lower lobe of the lung seems consolidated (solidified). These findings suggest a community-acquired lobar pneumonia, which is most likely to be caused by S.   pneumoniae infection.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The patient has cough and polymorphonuclear leukocytosis suggesting bacterial infection in the lung. On gross examination, the entire lower lobe of the lung seems consolidated (solidified). These findings suggest a community-acquired lobar pneumonia, which is most likely to be caused by S.    pneumoniae infection.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 51-year-old man has a history of chronic alcohol abuse. He is found in a stuporous condition after 3 days of binge drinking. On physical examination, his temperature is 39.2&#176; C.    A few crackles are heard on auscultation of the right lung base. A chest radiograph shows a 3-cm round lesion with an air-fluid level in the right lower lobe. Which pair of the following organisms is most likely to be detected in his sputum?`,
        q2: ``,
        q3: [],
        option: [`Cryptococcus neoformans and Candida albicans`, `Cytomegalovirus and Pneumocystis jiroveci`,`Mycobacterium tuberculosis and Aspergillus fumigatus`,`Nocardia asteroides and Actinomyces israelii`,`Staphylococcus aureus and Bacteroides fragilis`],
        optionFeedback: [`Cytomegalovirus and Pneumocystis mainly produce pulmonary infections in immunosuppressed patients and are not likely in this clinical setting.`,`Cryptococcus and Candida mainly produce pulmonary infections in immunosuppressed patients and are not likely in this clinical setting.`,`M. tuberculosis and Aspergillus may produce cavitary lesions, but they are unlikely to be involved in this case of acute-onset disease secondary to probable aspiration.`,`Nocardia asteroides and Actinomyces israelii may produce cavitary lesions, but they are unlikely to be involved in this case of acute-onset disease secondary to probable aspiration. `,`A cavitary lesion in a man at high risk for aspiration is likely to represent a lung abscess with mixed bacterial flora, including anaerobic bacteria that inhabit the oral cavity such as Bacteroides.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-A cavitary lesion in a man at high risk for aspiration is likely to represent a lung abscess with mixed bacterial flora, including anaerobic bacteria that inhabit the oral cavity such as Bacteroides.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 20-year-old otherwise healthy man has had a mild fever with nonproductive cough, headache, and myalgias for the past week. On physical examination he has a temperature of 37.9&#176; C and erythema of the pharynx. Diffuse crackles are heard on auscultation of the lungs. A chest radiograph shows bilateral extensive patchy infiltrates. A sputum gram stain shows normal flora. Cold agglutinin titer is elevated. He receives a course of erythromycin therapy, and his condition improves. Infection with which of the following organisms is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Legionella pneumophila`, `Mycobacterium fortuitum`,`Mycoplasma pneumoniae`,`Nocardia asteroides`,`Respiratory syncytial virus`],
        optionFeedback: [`Legionella can cause similar x-ray and clinical findings but is not associated with cold agglutinins and is less likely to produce symptomatic disease in otherwise young and healthy individuals. `,`Atypical mycobacterial infection mainly occurs in immunosuppressed patients.`,`This appears to be a community-acquired interstitial pneumonia, the most common cause of which is Mycoplasma pneumoniae. Cold agglutinins are IgM antibodies that bind to red cells and agglutinate them. They appear transiently in mycoplasma infections but do not cause significant hemolysis. Diagnosis of mycoplasma infections is made by detection of mycoplasma antigens in the serum and by PCR detection of the organism. Erythromycin is effective in mycoplasma pneumonia. `,`Nocardia infection mainly occurs in immunosuppressed patients. `,`Respiratory syncytial virus mainly produces disease in children. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- This appears to be a community-acquired interstitial pneumonia, the most common cause of which is Mycoplasma pneumoniae. Cold agglutinins are IgM antibodies that bind to red cells and agglutinate them. They appear transiently in mycoplasma infections but do not cause significant hemolysis. Diagnosis of mycoplasma infections is made by detection of mycoplasma antigens in the serum and by PCR detection of the organism. Erythromycin is effective in mycoplasma pneumonia.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `An epidemiologic study shows that a highly pathogenic strain of influenza A virus with the antigenic type H5N1 that normally causes disease in birds has been increasingly found to cause influenza in humans. Unlike other strains of influenza A virus, this H5N1 virus is associated with a 60% mortality rate. The enhanced pathogenicity of this avian flu virus is primarily due to a mutation in its genome that enables it to do which of the following?`,
        q2: ``,
        q3: [],
        option: [`Elicit a weak cytotoxic T-cell response`, ` Escape neutralization by host antibodies`,`Escape inactivation by macrophages`,`Infect CD4+ helper T cells`,`Spread from humans to humans`],
        optionFeedback: [`A cytotoxic T-cell response does not contribute to defense against influenza A.`,`Effective immunity to influenza A is largely mediated through neutralizing antibodies against viral hemagglutinin (H) and neuraminidase (N) that prevent the virus from infecting host cells. Influenza viruses can escape immune detection by acquiring mutations in their H  and  N  genes (antigenic drift), or by acquiring a completely new set of H and N genes through genetic reassortment (antigenic shift). If a bird virus with different genes for H and N proteins acquires the ability to infect human cells, human populations are defenseless. This occurs because they do not have antibodies against H or N proteins of the bird influenza virus from prior exposures to human influenza viruses, and leads to high morbidity and mortality.  `,`There is no evidence that macrophages inactivate influenza virus.`,`Influenza virus does not infect T cells.`,`For influenza A strains to cause pandemics they must also acquire the ability to spread readily from human to human; fortunately, this has yet to occur with the H5N1 avian virus. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Effective immunity to influenza A is largely mediated through neutralizing antibodies against viral hemagglutinin (H) and neuraminidase (N) that prevent the virus from infecting host cells. Influenza viruses can escape immune detection by acquiring mutations in their H  and  N  genes (antigenic drift), or by acquiring a completely new set of H and N genes through genetic reassortment (antigenic shift). If a bird virus with different genes for H and N proteins acquires the ability to infect human cells, human populations are defenseless. This occurs because they do not have antibodies against H or N proteins of the bird influenza virus from prior exposures to human influenza viruses, and leads to high morbidity and mortality. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 46-year-old woman has a routine health maintenance examination. She has noticed cough with expectoration in the past month. On physical examination, there are no remarkable findings. Her body mass index is 22. She does not smoke. A chest radiograph shows a solitary, 3-cm left upper lobe mass without calcifications. The mass is removed at thoracotomy by wedge resection. The microscopic appearance of this lesion is shown in the figure. Which of the following is the most likely diagnosis?`,
        q2: `<img src="../images/f010-q028-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Mycobacterium tuberculosis infection`, `Necrotizing granulomatous vasculitis`,`Poorly differentiated adenocarcinoma`,`Staphylococcus aureus abscess`,`Thromboembolism with infarction`],
        optionFeedback: [`The presence of granulomatous inflammation with caseous necrosis in an upper lung lobe of a patient is highly characteristic of secondary tuberculosis. All of the other proposed answers produce different patterns of tissue reaction.  `,`Necrotizing vasculitis (e.g., polyangiitis with granulomatosis) may produce a granulomatous reaction, but necrosis in such cases is not associated with well-formed granulomas and is associated with acute inflammation with numerous neutrophils, which are not usually seen in granulomatous responses to tuberculosis. `,`Poorly differentiated adenocarcinoma produces tissue effacement due to invasion and fibrosis but is not associated with granulomatous responses.`,`Staphylococcus aureus abscess would be associated with areas of liquefaction filled with neutrophils, not granulomas.`,`Thromboembolism with infarction might be associated with hemorrhage and some acute inflammation but would not lead to granuloma formation.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The presence of granulomatous inflammation with caseous necrosis in an upper lung lobe of a patient is highly characteristic of secondary tuberculosis. All of the other proposed answers produce different patterns of tissue reaction.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 44-year-old man, a nonsmoker, has experienced a 3-kg weight loss over the past 3 months. He recently developed a low-grade fever and cough with mucoid sputum production, and after 1 week he noticed blood-streaked sputum. On physical examination, his temperature is 37.7&#176; C.    There are crackles in the left upper lobe on auscultation of the chest. Chest CT scan shows a 3-cm left upper lobe nodule with decreased attenuation centrally. Laboratory studies show hemoglobin, 14.5 g/dL (13.5–17.5 g/dL); platelet count, 211,400/mm<sup>3</sup> (150,000–400,000/mm<sup>3)</sup>; and WBC count, 9,890/mm<sup>3</sup> (4,500–11,000/mm<sup>3</sup>) with 40% segmented neutrophils, 2% bands, 40% lymphocytes, and 18% monocytes. Bronchoalveolar lavage specimen shows macrophages containing acid-fast bacilli. The survival of these bacilli in macrophages is most likely due to which of the following mechanisms?`,
        q2: ``,
        q3: [],
        option: [`Preventing fusion of phagocytic vacuoles with lysosomes`, `Neutralization of oxygen-derived free radicals `,`Inability of CD4+ Th2 cells to activate macrophages`,`Ability of the bacilli to grow in the absence of oxygen`,` Negative charge of the bacterial cell membranes`],
        optionFeedback: [`The clinical and laboratory findings are consistent with secondary pulmonary tuberculosis (TB). Active TB infection occurs due to inadequate killing of phagocytosed organisms within macrophages. This happens because the microbe blocks the formation of the phagolysosome by inhibiting signals that cause recruitment and assembly of proteins that mediate phagosome-lysosome fusion, allowing the bacterium to replicate unchecked within the vesicle. As a result, the bacteria are resistant to the killing mechanisms of macrophages, which require formation of phagolysosomes.   `,`Because the phagolysosome fails to form, free radicals cannot access the bacteria even if they are produced.`,`An effective host response requires the function of CD4+ Th1 cells which activate macrophages. `,`M. tuberculosis is an aerobe, and in fact may grow better in high oxygen environments like the upper lobe of the lung. `,`Negative charge has no effect on host defense against the tubercle bacilli. Components of M. tuberculosis cell wall may trigger innate immune responses, but these are inadequate to control the infection in the absence of an effective T-cell response. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The clinical and laboratory findings are consistent with secondary pulmonary tuberculosis (TB). Active TB infection occurs due to inadequate killing of phagocytosed organisms within macrophages. This happens because the microbe blocks the formation of the phagolysosome by inhibiting signals that cause recruitment and assembly of proteins that mediate phagosome-lysosome fusion, allowing the bacterium to replicate unchecked within the vesicle. As a result, the bacteria are resistant to the killing mechanisms of macrophages, which require formation of phagolysosomes `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A previously healthy, 20-year-old woman has had a low-grade fever for the past 2 weeks. On physical examination, her temperature is 37.7&#176; C; there are no other remarkable findings. The gross appearance of the lung shown in the figure is representative of her disease. Which of the following laboratory studies is most likely to report a positive result?`,
        q2: `<img src="../images/f010-q030-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Anticentromere antibody`, `HIV serologic test`,`Interferon-γ release assay`,`Rapid plasma reagin (RPR) test`,`Sweat chloride`],
        optionFeedback: [`Anticentromere antibody testing is used to diagnosis systemic sclerosis (scleroderma). `,`Nothing in the clinical scenario suggests that the patient is infected with HIV; furthermore, because HIV-infected individuals have poor cell-mediated immunity, M.    tuberculosis causes disseminated lesions in the lungs and elsewhere, not the localized lesions seen in this patient. `,`The clinical and pathologic findings are consistent with primary tuberculosis. The gross appearance of the lung shows a Ghon complex consisting of a subpleural lesion with enlarged hilar lymph nodes showing caseating necrosis. This is typical of primary tuberculosis. The interferon-γ release assay, performed by mixing patient blood cells with tubercle bacillus antigens and measuring interferon-γ production, is a sensitive assay for exposure to tuberculosis and is often used together with skin testing.  `,`The RPR test is used to diagnose syphilis for which the patient has no symptoms.`,`The sweat chloride test is used to diagnose cystic fibrosis for which the patient has no symptoms.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The clinical and pathologic findings are consistent with primary tuberculosis. The gross appearance of the lung shows a Ghon complex consisting of a subpleural lesion with enlarged hilar lymph nodes showing caseating necrosis. This is typical of primary tuberculosis. The interferon-γ release assay, performed by mixing patient blood cells with tubercle bacillus antigens and measuring interferon-γ production, is a sensitive assay for exposure to tuberculosis and is often used together with skin testing`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 46-year-old man has had fever, nonproductive cough, and weight loss for 2 months. On examination his temperature is 37.5&#176; C. A chest radiograph shows a miliary pattern of small nodules in all lung fields. Bronchoalveolar lavage is performed and microscopic examination of the fluid shows organisms averaging 50 microns in diameter with thick walls and filled with endospores. Which of the following infections is he most likely to have?`,
        q2: ``,
        q3: [],
        option: [` Blastomycosis`, `Coccidioidomycosis`,`Histoplasmosis`,`Mycobacteriosis`,` Nocardiosis`],
        optionFeedback: [`Blastomycosis can present as pulmonary infections, but typically only yeast forms are seen in tissues.`,`Coccidiomycosis is endemic in desert areas in the United States and Mexico and is highly infectious, even in those with normal immunity. Pulmonary infections typically show spherules, large structures filled with endospores, which are pathognomonic for coccidiomycosis.  `,`Histoplasmosis can present as pulmonary infections, but typically only yeast forms are seen in tissues. `,`Mycobacteria appear as small, beaded rods and are much smaller than fungal organisms. Their histologic detection requires acid fast stains.`,`Nocardia appear as small, beaded rods and are much smaller than fungal organisms. They are difficult to visualize without acid fast stains.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Coccidiomycosis is endemic in desert areas in the United States and Mexico and is highly infectious, even in those with normal immunity. Pulmonary infections typically show spherules, large structures filled with endospores, which are pathognomonic for coccidiomycosis. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 56-year-old man has had fever, night sweats, and a 3-kg weight loss over the past 4 months. In the past month, he has had episodes of hemoptysis. On physical examination there are upper lobe rales. The appearance of the lungs from a similar case is shown in the figure. Which of the following laboratory tests is most likely to provide a definitive diagnosis in this patient?`,
        q2: `<img src="../images/f010-q032-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Monocytosis in peripheral blood`, `CD4+ T cell count in bronchoalveolar lavage`,`CD4 + T cell count in peripheral blood`,`Detection of the causative agent by sputum culture`,`Positive skin test with microbial antigens`],
        optionFeedback: [`Peripheral blood monocytosis may be present but is nonspecific. `,`T-cell counts in bronchoalveolar lavage cannot distinguish between several infections that evoke cell mediated immunity.`,`T-cell counts in peripheral blood may be normal and are not diagnostically helpful in this setting. `,`The cough and fever along with extensive bilateral upper lobe caseating necrosis and cavitation are consistent with progressive secondary tuberculosis, which is most common in older adults with waning immunity or frank immunosuppression. Organisms are prevalent and usually detectable in sputum with acid-fast stains or more sensitive stains with certain fluorescent dyes. A positive molecular test for M. tuberculosis nucleic acid is considered sufficient for diagnosis even in the absence of a positive sputum smear and can be completed in 1-2 days. Culture is the gold standard for antibiotic-sensitivity testing.  `,`Because progressive TB usually occurs in individuals without normal immunity, skin testing is likely to produce a false negative result and is less predictive of active progressive TB than sputum testing. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The cough and fever along with extensive bilateral upper lobe caseating necrosis and cavitation are consistent with progressive secondary tuberculosis, which is most common in older adults with waning immunity or frank immunosuppression. Organisms are prevalent and usually detectable in sputum with acid-fast stains or more sensitive stains with certain fluorescent dyes. A positive molecular test for M. tuberculosis nucleic acid is considered sufficient for diagnosis even in the absence of a positive sputum smear and can be completed in 1-2 days. Culture is the gold standard for antibiotic-sensitivity testing.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 56-year-old man underwent allogeneic hematopoietic stem cell transplantation to treat acute myeloid leukemia. Two weeks after transplantation, he develops fever, nonproductive cough, dyspnea, pleuritic chest pain, and hemoptysis. A chest CT scan shows multiple bilateral 1- to 4-cm nodular densities. Bronchoalveolar lavage is performed, and microscopic examination of the fluid shows narrow, branching septate hyphae. A CBC shows hemoglobin, 11 g/dL (13.5–17.5 g/dL); hematocrit, 38.7% (41%–53%); WBC count, 800/mm<sup>3</sup>L (4,500–11,000/mm<sup>3</sup>), with 8% neutrophils; and platelet count, 40,100/mm<sup>3</sup> (150,000–400,000/mm<sup>3</sup>). He has most likely developed an infection with which of the following organisms?`,
        q2: ``,
        q3: [],
        option: [`Aspergillus fumigatus`, `Candida albicans`,`Cryptococcus neoformans`,`Mucor circinelloides `,`Moraxella catarrhalis `],
        optionFeedback: [`The patient is pancytopenic and severely neutropenic, a condition that leads to susceptibility to fungal and bacterial infections. Organisms with branching septate hyphae, seen in this patient, are consistent with Aspergillus infection, which often produces hemoptysis due to invasion of vessels.  `,`Candida is more likely to infect the oropharynx and gastrointestinal tract and is morphologically distinct from Aspergillus. It is seen as pseudohyphae and yeast forms.`,`Cryptococcus often infects the central nervous system (CNS) and is most common in the setting of severe T-cell immunodeficiency (e.g., in the setting of AIDS). Infectious organisms grow as yeast forms with thick periodic acid-Schiff (PAS)-positive cell walls. `,`Mucor most often infects the nasopharynx, often in the setting of poorly controlled diabetes. `,`Moraxella catarrhalis is a bacterium that mainly infects older adults and is a common cause of acute exacerbations of COPD.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The patient is pancytopenic and severely neutropenic, a condition that leads to susceptibility to fungal and bacterial infections. Organisms with branching septate hyphae, seen in this patient, are consistent with Aspergillus infection, which often produces hemoptysis due to invasion of vessels.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 47-year-old woman known to be HIV-positive has had a decreasing CD4+ lymphocyte count for the past year despite antiretroviral therapy. She has developed a fever with nonproductive cough over the past week. On auscultation of her chest, fine crackles are present in both lungs. A chest radiograph shows infiltrates in both lungs. A transbronchial biopsy is obtained and the microscopic appearance is shown in the figure. Which of the following organisms is most likely responsible for this woman’s pulmonary symptoms?`,
        q2: `<img src="../images/f010-q034-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Candida albicans`, `Cryptococcus neoformans`,`Cytomegalovirus`,`Klebsiella pneumoniae`,`Pneumocystis jiroveci`],
        optionFeedback: [`Candida is a fungus that most often presents with oropharyngeal (thrush) or esophageal infection.`,`Cryptococcus is a fungus that often presents with CNS involvement.`,`Individuals with HIV and a deficiency of CD4+ T cells are susceptible to a variety of opportunistic infections, including Candida, Cryptococcus, Pneumocystis and cytomegalovirus. Of these, the ones that are most likely to involve the lung are cytomegalovirus and Pneumocystis. The image shows the characteristic cytopathic features of cytomegalovirus infection: infected cells are enlarged and contain prominent intranuclear basophilic inclusions. `,`Klebsiella is a bacterium that produces a pneumonia that often is associated with copious production of mucoid sputum.`,`Pneumocystis is a fungus that causes pneumonia with pink-staining foamy intra-alveolar infiltrates in hematoxylin and eosin (H&amp;E)-stained sections. Diagnosis can be made on sputum specimens using molecular tests or by staining with specific antibodies or with certain special stains (e.g., Gomori methenamine silver) that highlight the organisms.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-Individuals with HIV and a deficiency of CD4+ T cells are susceptible to a variety of opportunistic infections, including Candida, Cryptococcus, Pneumocystis and cytomegalovirus. Of these, the ones that are most likely to involve the lung are cytomegalovirus and Pneumocystis. The image shows the characteristic cytopathic features of cytomegalovirus infection: infected cells are enlarged and contain prominent intranuclear basophilic inclusions. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A previously healthy 43-year-old woman has had malaise and an 8-kg weight loss over the past 3 years. She has had fever and a nonproductive cough with increasing dyspnea for the past 3 days. On physical examination, her temperature is 37.8&#176; C.    There is dullness to percussion over the lungs and diffuse crackles on auscultation. A chest radiograph shows extensive bilateral infiltrates. Bronchoalveolar lavage is done, and the fluid is stained with Gomori methenamine silver, with high-power microscopic appearance shown in the figure. Which of the following underlying conditions is most likely present in this woman?`,
        q2: `<img src="../images/f010-q035-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Centrilobular emphysema`, ` Diabetes `,`HIV infection`,`Sarcoidosis`,`Severe combined immunodeficiency`],
        optionFeedback: [`Centrilobular emphysema is not associated with T-cell immunodeficiency and does not lead to an increased risk of Pneumocystis infection.`,`Diabetes is not associated with T-cell immunodeficiency and does not lead to an increased risk of Pneumocystis infection.`,`The bronchoalveolar lavage contains round to cup-shaped organisms that are stained black with the silver stain. This appearance is characteristic of Pneumocystis jiroveci. Pneumocystis infection is confined to individuals with severe T-cell immunodeficiency; in this previously healthy adult woman, the most likely cause is unrecognized HIV infection.  `,`Sarcoidosis is not associated with T-cell immunodeficiency and does not lead to an increased risk of Pneumocystis infection.`,`Severe combined immunodeficiency could be associated with Pneumocystis infection, but typically presents early in life with recurrent infections.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The bronchoalveolar lavage contains round to cup-shaped organisms that are stained black with the silver stain. This appearance is characteristic of Pneumocystis jiroveci. Pneumocystis infection is confined to individuals with severe T-cell immunodeficiency; in this previously healthy adult woman, the most likely cause is unrecognized HIV infection. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 64-year-old man who is a chain-smoker has had a cough and a 5-kg weight loss over the past 3 months. Physical examination shows clubbing of the fingers. He is afebrile. A chest radiograph shows no hilar adenopathy, but there is cavitation within a 3-cm lesion near the right hilum. Laboratory studies show serum calcium of 12.3 mg/dL (8.4–10.2 mg/dL), and phosphorus of 2.4 mg/dL (3.0–4.5 mg/dL) Bronchoscopy shows a lesion nearly occluding the right main bronchus. Which of the following neoplasms is most likely to be present in this patient`,
        q2: ``,
        q3: [],
        option: [`Bronchial carcinoid`, `Metastatic renal cell carcinoma`,`Non-Hodgkin lymphoma`,`Small cell carcinoma`,`Squamous cell carcinoma`],
        optionFeedback: [`Bronchial carcinoids are usually well circumscribed, do not cavitate, and are not associated with hypercalcemia or clubbing. They may produce hormones that lead to carcinoid syndrome (e.g., flushing, diarrhea, bronchoconstriction) or other paraneoplastic phenomena. `,`Metastatic renal cell carcinoma would most often present as multiple nodules scattered in both lungs or a mass in peripheral lung fields rather than the hilum of the lung. `,`Non-Hodgkin lymphoma is more likely to present with lymphadenopathy, and usually is not associated with hypercalcemia or clubbing.`,`Small cell carcinoma is most often associated with paraneoplastic syndromes caused by production of adrenocorticotrophic hormone (ACTH) leading to Cushing syndrome; production of antidiuretic hormone (ADH), leading to the syndrome of inappropriate ADH production; or induction of autoantibodies that lead to neuromuscular dysfunction. It is aggressive and usually has spread to lymph nodes by the time of diagnosis.`,`A bronchial lesion associated with cavitation, clubbing of the fingers, and hypercalcemia is likely to be squamous cell carcinoma, which often produces parathyroid hormone-related protein (PTHrP) leading to paraneoplastic hypercalcemia.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-A bronchial lesion associated with cavitation, clubbing of the fingers, and hypercalcemia is likely to be squamous cell carcinoma, which often produces parathyroid hormone-related protein (PTHrP) leading to paraneoplastic hypercalcemia.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 55-year-old woman, a nonsmoker, has had a chronic, nonproductive cough for 6 months along with 8-kg weight loss. On physical examination there are no remarkable findings. Her chest radiograph shows a right peripheral subpleural mass. A fine-needle aspiration biopsy is performed, and she subsequently undergoes a right lower lobectomy. The microscopic examination of the lesion shows irregular glands invading the surrounding lung. Which of the following molecular test findings is likely to be most useful in deciding if her cancer may benefit from a tyrosine kinase inhibitor?`,
        q2: ``,
        q3: [],
        option: [`Amplification of FGFR1 gene`, `Inactivation of CDKN2A gene`,`Loss of both copies of TP53`,`Amplification of MYC gene`,`Rearrangement of ALK gene`],
        optionFeedback: [`FGFR1 amplifications are most commonly associated with squamous cell carcinoma. FGFR1 encodes a tyrosine kinase and inhibitors of FGFR1 are being studied in clinical trials, but are not yet in clinical use.`,`CDKN2A is a gene that encodes two tumor suppressors, ARF (a positive regulator of p53 function) and p16, a cyclin-dependent kinase inhibitor that acts as a brake on the cell cycle. Neither of these is affected by tyrosine kinase inhibitors.`,`TP53 is a tumor suppressor gene that encodes a transcription factor that drives the expression of genes that regulate cell cycle progression, DNA repair and apoptosis. Loss of p53 generally indicates a poor prognosis (regardless of tumor type) but is not currently targetable.`,`MYC is an oncogene that encodes a transcription factor regulating cellular metabolism. It is frequently activated by translocation, particularly in B-cell lymphomas. It is not currently targetable.`,`The microscopic description is that of adenocarcinoma, which may be associated with mutations or rearrangements involving several different genes encoding tyrosine kinases, including ALK. ALK rearrangements create a chimeric gene encoding a constitutively active ALK tyrosine kinase, and treatment of such cancers with ALK inhibitors often results in clinical benefit.   `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The microscopic description is that of adenocarcinoma, which may be associated with mutations or rearrangements involving several different genes encoding tyrosine kinases, including ALK. ALK rearrangements create a chimeric gene encoding a constitutively active ALK tyrosine kinase, and treatment of such cancers with ALK inhibitors often results in clinical benefit. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 60-year-old woman has had a chronic nonproductive cough for 4 months along with loss of appetite and a 6-kg weight loss. She does not smoke. On physical examination there are no remarkable findings. Her chest radiograph shows a right peripheral subpleural mass. A fine-needle aspiration biopsy is performed, and she subsequently undergoes a right lower lobectomy. She receives treatment with an inhibitor of epithelial growth factor receptor (EGFR) and remains symptom-free for the next 5 years. Which of the following neoplasms did she most likely have?`,
        q2: ``,
        q3: [],
        option: [`Adenocarcinoma`, `Bronchial carcinoid`,` Malignant mesothelioma`,`Small cell carcinoma`,`Squamous cell carcinoma`],
        optionFeedback: [`EGFR mutations that produce constitutive activation of the receptor’s tyrosine kinase activity are commonly associated with lung adenocarcinoma. Adenocarcinoma also is relatively common in female nonsmokers and frequently occurs as a peripheral lung nodule. `,`Bronchial carcinoid is a neuroendocrine tumor that is not associated with EGFR mutations. `,`Malignant mesothelioma presents with pleural disease rather than a lung mass and is not associated with EGFR mutations.`,`Small cell carcinoma usually presents near the hilum of the lung and is associated with TP53 and RB mutations and not with EGFR mutations.`,`Squamous cell carcinoma is associated with FGFR1 amplification rather than EGFR mutations.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-EGFR mutations that produce constitutive activation of the receptor’s tyrosine kinase activity are commonly associated with lung adenocarcinoma. Adenocarcinoma also is relatively common in female nonsmokers and frequently occurs as a peripheral lung nodule.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 61-year-old man with a long smoking history has developed truncal obesity, back pain, and skin that bruises easily over the past 5 months. On physical examination, he is afebrile, and his blood pressure is 160/95 mm Hg. A chest radiograph shows an ill-defined, 4-cm mass involving the left hilum of the lung. Cytologic examination of bronchial washings from bronchoscopy shows monomorphic tumor cells with high nuclear:cytoplasmic ratios that have the appearance of lymphocytes but are larger. The patient is told that, although his disease is apparently localized to one side of the chest cavity, surgical treatment is unlikely to be curative. He also is advised to stop smoking. Which of the following is the most likely diagnosis for this patient?`,
        q2: ``,
        q3: [],
        option: [`Adenocarcinoma`, ` Malignant mesothelioma`,`Non-Hodgkin lymphoma`,`Small cell carcinoma`,` Squamous cell carcinoma`],
        optionFeedback: [`Adenocarcinoma presents most commonly in the lung periphery and produces malignant glands, not small, uniform cells.`,`Malignant mesothelioma arises and preferentially involves the pleura and is composed of glandular elements and/or spindled cells.`,`Non-Hodgkin lymphoma may morphologically resemble small cell carcinoma but is composed of dyscohesive cells and is not related to smoking. It is not associated with ACTH secretion.`,`The patient has Cushing syndrome, a paraneoplastic syndrome. In this case, based on the reported appearance of the tumor cells, it is likely caused by production of ACTH by small cell carcinoma. Among lung carcinomas, small cell carcinoma is most likely to be associated with Cushing syndrome. Another clue is that surgical treatment is unlikely to be curative; among lung cancers, this is particularly true of small cell carcinoma.  `,`Squamous cell carcinoma may occur near the lung hilum but is composed of large cohesive cells that show keratinization, features not seen in small cell carcinoma. It is typically associated with secretion of parathyroid hormone-related peptide causing hypercalcemia.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The patient has Cushing syndrome, a paraneoplastic syndrome. In this case, based on the reported appearance of the tumor cells, it is likely caused by production of ACTH by small cell carcinoma. Among lung carcinomas, small cell carcinoma is most likely to be associated with Cushing syndrome. Another clue is that surgical treatment is unlikely to be curative; among lung cancers, this is particularly true of small cell carcinoma.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 59-year-old man who has smoked one pack of cigarettes per day for the past 43 years has developed a severe cough with hemoptysis over the past month. He has experienced a 10-kg weight loss over the past year. On physical examination, he is afebrile. Laboratory studies show a serum electrolyte pattern of SIADH (syndrome of inappropriate ADH secretion). Which of the following findings is most likely to be seen on a chest radiograph and biopsy?`,
        q2: ``,
        q3: [],
        option: [`Bilateral upper lobe cavitation with caseation`, ` Diaphragmatic pleural calcified plaques with spindle cell morphology`,`Invasive perihilar mass with small cell morphology`,`Subpleural nodule and hilar adenopathy with granulomas`,`A mass arising from the left main bronchus with cavitation with squamous cells`],
        optionFeedback: [`Bilateral upper lobe cavitation is a finding that is most often seen in secondary tuberculosis. TB is not associated with SIADH.`,`Diaphragmatic pleural calcified plaques are associated with asbestos exposure and do not cause SIADH.`,`In this patient with a long smoking history, weight loss, and hemoptysis, SIADH is likely to represent a paraneoplastic syndrome caused by small cell lung carcinoma. Small cell lung cancer often presents as an invasive perihilar mass.  `,`Subpleural nodule with hilar adenopathy could be indicative of adenocarcinoma with spread to hilar lymph nodes; alternatively, this could represent a Ghon complex (primary tuberculosis).`,`Left mainstem bronchus mass with cavitation would be a typical appearance for squamous cell carcinoma.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- In this patient with a long smoking history, weight loss, and hemoptysis, SIADH is likely to represent a paraneoplastic syndrome caused by small cell lung carcinoma. Small cell lung cancer often presents as an invasive perihilar mass.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 49-year-old man has had an increasing cough with hemoptysis for 2 weeks. He has never smoked and is in very good health. On physical examination, his temperature is 38.2&#176; C.    A chest radiograph shows an area of consolidation in the right upper lobe. His condition improves with antibiotic therapy; however, the cough and hemoptysis persist for 2 more weeks. Chest CT scan now shows right upper lung atelectasis. The rest of the lungs appear normal. Bronchoscopic examination shows a tan, well-circumscribed obstructive mass filling a right upper lobe bronchus. Which of the following neoplasms is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [` Adenocarcinoma`, `Carcinoid tumor`,`Hamartoma`,`Kaposi sarcoma`,`Malignant mesothelioma`],
        optionFeedback: [`Adenocarcinoma is more likely to be peripherally located and to have an infiltrative appearance.`,`The well-demarcated circumscribed appearance of the tumor and presentation as a submucosal mass with bronchial obstruction are typical of carcinoid tumor. Bronchial obstruction caused pneumonia in right upper lobe. `,`Lung hamartomas usually appear as “coin lesions” within periphery of the lung. They consist of nodules of connective tissue intersected by epithelial clefts. Cartilage is the most common connective tissue, but there may also be cellular fibrous tissue and fat. `,`Kaposi sarcoma of the lung is confined to the immunosuppressed and typically is infiltrative and multifocal.`,`Malignant mesothelioma produces pleural-based lesions that spread widely on pleural surfaces.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The well-demarcated circumscribed appearance of the tumor and presentation as a submucosal mass with bronchial obstruction are typical of carcinoid tumor. Bronchial obstruction caused pneumonia in right upper lobe. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 78-year-old man has had increasing dyspnea without cough or increased sputum production for the past 4 months. On physical examination, he is afebrile. Breath sounds are reduced in all lung fields. A chest CT scan shows a dense, pleural mass encasing most of the left lung. His condition deteriorates rapidly and he dies 6 months later. Appearance of the lung at autopsy is shown in the figure. Microscopic examination of a pleural biopsy specimen shows spindle and cuboidal cells that invade adipose tissue. Which of the following genes is most commonly mutated in this tumor?`,
        q2: `<img src="../images/f010-q043-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`PTEN`, `APC`,`NF1`,`BAP1`,`VHL`],
        optionFeedback: [`PTEN is a negative regulator of PI3K/AKT signaling that is often mutated in breast and endometrial cancers.`,`APC is a negative regulator of the Wnt pathway that is most often mutated in colon cancer.`,`NF1 is a negative regulator of Ras signaling that is often mutated in malignant peripheral nerve sheath tumor and at lower frequencies in many other forms of cancer. `,`A dense pleural mass encasing the lung with mixtures of cuboidal and spindle cells is diagnostic of malignant mesothelioma. The most commonly mutated tumor suppressor gene in this tumor is BAP1, a gene encoding a nuclear factor that regulates DNA repair and possibly gene expression.  `,`VHL is a negative regulator of the transcription factor HIF (hypoxia-inducible factor), which is normally responsible for mediating the cellular response to hypoxia. VHL is very commonly mutated in renal cell carcinoma.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-A dense pleural mass encasing the lung with mixtures of cuboidal and spindle cells is diagnostic of malignant mesothelioma. The most commonly mutated tumor suppressor gene in this tumor is BAP1, a gene encoding a nuclear factor that regulates DNA repair and possibly gene expression `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 48-year-old man visiting from southern China has had difficulty breathing through his nose and has experienced dull facial pain for the past 4 months. On physical examination, there is a mass filling the right nasal cavity. CT scan of the head shows a 5-cm mass in the nasopharynx on the right that erodes adjacent bone. The mass is excised, and microscopic examination shows that it is composed of large epithelial cells with indistinct borders and prominent nuclei. Mature lymphocytes are scattered throughout the undifferentiated neoplasm. Which of the following etiologic factors most likely played the greatest role in the development of this lesion?`,
        q2: ``,
        q3: [],
        option: [`Allergic rhinitis`, `ANCA-associated vasculitis`,`Epstein-Barr virus (EBV) infection`,`Sj&#246;gren syndrome`,` Smoking tobacco`],
        optionFeedback: [`Allergic rhinitis is not associated with an increased risk of cancer.`,`ANCA-associated vasculitis is not associated with an increased risk of cancer.`,`EBV infection is associated with nasopharyngeal carcinoma, particularly in children in some parts of Africa and in adults from southern China. It is a poorly differentiated cancer associated with a brisk host lymphocyte response.  `,`Sj&#246;gren syndrome is associated with inflammation and destruction of lacrimal and salivary glands and an increased risk of lymphoma, not carcinoma. `,`Smoking tobacco is associated with squamous cell carcinoma, often well differentiated. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- EBV infection is associated with nasopharyngeal carcinoma, particularly in children in some parts of Africa and in adults from southern China. It is a poorly differentiated cancer associated with a brisk host lymphocyte response`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 58-year-old man presents with several enlarged, firm right cervical lymph nodes. On physical examination, he is noted to have a right tonsillar mass, and microscopic examination shows a squamous cell carcinoma. Which of the following etiologic factors most likely played a role in the development of this lesion?`,
        q2: ``,
        q3: [],
        option: [`Epstein-Barr virus (EBV) infection`, `Human papillomavirus (HPV) infection`,`Repeated bouts of aspiration`,` Recurrent streptococcal infection.`,`Type I hypersensitivity`],
        optionFeedback: [`EBV is associated with nasopharyngeal carcinoma rather than squamous cell carcinoma. `,`Among primary sites in the head and neck region, squamous cell carcinoma arising in the tonsil is most likely to be associated with HPV, possibly because tonsillar crypt epithelium is particularly susceptible to infection by the virus. HPV is also associated with squamous cell carcinomas arising at other sites in the head and neck region such as the larynx, but smoking, chewing tobacco and alcohol use play a greater role in the etiology of cancer development at these sites.Incorrect answers:`,`Aspiration is not associated with laryngeal carcinoma or other forms of cancer.`,`Streptococcal infection is not associated with laryngeal carcinoma or other forms of cancer.`,`Type I hypersensitivity reactions are not associated with laryngeal carcinoma or other forms of cancer.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Among primary sites in the head and neck region, squamous cell carcinoma arising in the tonsil is most likely to be associated with HPV, possibly because tonsillar crypt epithelium is particularly susceptible to infection by the virus. HPV is also associated with squamous cell carcinomas arising at other sites in the head and neck region such as the larynx, but smoking, chewing tobacco and alcohol use play a greater role in the etiology of cancer development at these sites `,
        state: `notAnswered`,
        userAnswered: [],
    }
    

   ];






