var quiz = [
    {
        q: `A 25-year-old woman has noted breast secretions for the past month although she is not breastfeeding and has never been pregnant. Her last menstrual period was 5 months ago. Physical examination is unremarkable. MRI of the brain shows a 0.7-cm mass within the sella turcica. Which of the following additional clinical manifestations is she most likely to have?`,
        q2: ``,
        q3: [],
        option: [`Acromegaly`, `Cushing disease`, ` Hyperthyroidism`,`Infertility`,`Neurologic dysfunction`],
        optionFeedback: [`Acromegaly is caused by growth hormone-producing (somatotroph) adenomas. Growth hormone causes excessive growth of the bones and diabetes but not amenorrhea.`,`Cushing disease is caused by an adrenocorticotropin (ACTH)-producing (corticotroph) adenoma and presents with manifestations of excessive corticosteroid production including weight gain, striae, muscle weakness, hypertension and easy bruising.`,`Hyperthyroidism is caused by a TSH-producing (thyrotroph) adenoma and presents with signs and symptoms of hyperthyroidism such as fatigue, heart palpitations, frequent bowel movements and heat intolerance.`,`The clinical features and radiologic findings are diagnostic of a prolactin-secreting (lactotroph) anterior pituitary adenoma, the most common type of pituitary adenoma. Infertility in both men and women is a frequent complication of excess prolactin. `,`Neurologic dysfunction is most often seen with nonfunctioning pituitary adenomas, which are not diagnosed early (since they lack signs of hormone overproduction) and may grow to large size, causing mass effects. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The clinical features and radiologic findings are diagnostic of a prolactin-secreting (lactotroph) anterior pituitary adenoma, the most common type of pituitary adenoma. Infertility in both men and women is a frequent complication of excess prolactin. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 41-year-old woman notices that her gloves from the previous winter no longer fit her hands. Her facial features have become coarser in the past year, and her voice seems deeper. On physical examination, her blood pressure is 140/90 mmHg. Laboratory studies indicate a fasting blood glucose level of 138 mg/dL (70–110 mg/dL) and hemoglobin A1c level of 8.6% (&lt;6%). Which of the following additional test results is most likely to indicate the cause of her physical and laboratory findings?`,
        q2: ``,
        q3: [],
        option: [`Elevated serum cortisol despite high-dose dexamethasone dose`, `Inability of oral glucose load to suppress growth hormone levels`,`Hyperprolactinemia`,`Increased serum thyroid stimulating hormone (TSH) level`,`Increased urine catecholamine levels`],
        optionFeedback: [`Dexamethasone suppression tests measure the response of the adrenal glands to ACTH.  This patient does not show signs or symptoms of Cushing syndrome.`,`The physical findings suggest an excess of growth hormone and the laboratory evidence of diabetes is consistent with a growth hormone-producing (somatotroph) pituitary adenoma since growth hormone induces peripheral insulin resistance. In unaffected individuals, growth hormone production is suppressed by insulin produced in response to an oral glucose load (an example of feedback regulation), but adenomas are autonomous and do not respond to normal regulatory signals. `,`Excessive prolactin secretion is seen with prolactin-producing (lactotroph) adenoma, which presents with galactorrhea and amenorrhea in women and infertility in men and women.`,`Increased serum TSH is seen with TSH-producing (thyrotroph) adenoma, which presents with signs and symptoms of hyperthyroidism.`,`Increased urine catecholamines are seen with pheochromocytoma, a tumor of the adrenal medulla and other neuroendocrine glands.  Patients have hypertension; about two thirds of them have paroxysmal episodes of hypertension. They do not have diabetes.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale:- The physical findings suggest an excess of growth hormone and the laboratory evidence of diabetes is consistent with a growth hormone-producing (somatotroph) pituitary adenoma since growth hormone induces peripheral insulin resistance. In unaffected individuals, growth hormone production is suppressed by insulin produced in response to an oral glucose load (an example of feedback regulation), but adenomas are autonomous and do not respond to normal regulatory signals.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 21-year-old woman delivers a term infant after an uncomplicated pregnancy. The placenta cannot be delivered, however, and there is substantial hemorrhage, requiring transfusion of 10 U of packed RBCs. Over the next 3 months, she is unable to produce sufficient milk to breastfeed her infant, and she becomes increasingly fatigued. Laboratory studies show hyponatremia and hyperkalemia, normal serum calcium and phosphate, and normal blood sugar. Over the next 5 months, her menstrual cycles do not return. Which of the following laboratory findings is now most likely to be reported in this woman?`,
        q2: ``,
        q3: [],
        option: [`Decreased corticotropin-releasing hormone`, ` Decreased oxytocin`,`Failure of antidiuretic hormone release (ADH)`,`Decreased growth hormone `,`Increased corticotropin `],
        optionFeedback: [`Corticotropin-releasing hormone level will be normal because the hypothalamus is not affected.`,`Oxytocin will be unaffected because it is produced by the posterior pituitary.`,`ADH will be unaffected because it is produced by the posterior pituitary.`,`Ischemic necrosis of the pituitary (Sheehan syndrome) is a rare postpartum complication. During pregnancy, the anterior pituitary enlarges due to increased demand for prolactin but blood supply does not increase proportionately and the gland is susceptible to ischemia. Ischemic necrosis of the pituitary is most likely to occur in women who develop hypotension during delivery. The anterior pituitary is much more likely to be affected than posterior pituitary. This patient shows all the features of hypopituitarism: inability to breast feed due to lack of prolactin; loss of menstrual cycles due to deficiency of FSH and LH; hyponatremia and hyperkalemia due to adrenal insufficiency resulting from reduced ACTH production. In an adult, growth hormone deficiency may be manifested by central weight gain, dry skin and fatigue.`,`Corticotropin (ACTH) would be reduced, not increased, because it too is produced in the anterior pituitary.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Ischemic necrosis of the pituitary (Sheehan syndrome) is a rare postpartum complication. During pregnancy, the anterior pituitary enlarges due to increased demand for prolactin but blood supply does not increase proportionately and the gland is susceptible to ischemia. Ischemic necrosis of the pituitary is most likely to occur in women who develop hypotension during delivery. The anterior pituitary is much more likely to be affected than posterior pituitary. This patient shows all the features of hypopituitarism: inability to breast feed due to lack of prolactin; loss of menstrual cycles due to deficiency of FSH and LH; hyponatremia and hyperkalemia due to adrenal insufficiency resulting from reduced ACTH production. In an adult, growth hormone deficiency may be manifested by central weight gain, dry skin and fatigue. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 42-year-old man has had polyuria and polydipsia for the past 4 months. His medical history shows that he fell off a ladder and hit his head just before the onset of these problems. Physical examination is unremarkable. Laboratory findings include serum Na<sup>+</sup>, 155 mmol/L (136–145 mmol/L); K<sup>+</sup>, 3.9 mmol/L (3.5–5.0  mmol/L); Cl–, 111 mmol/L (95–105 mmol/L); and osmolality, 350 mOsm/mL (275–295 mOsm/mL). The urine specific gravity is 1.002 (1.005–1.030). This patient is most likely to have a deficiency of which of the following hormones?`,
        q2: ``,
        q3: [],
        option: [`Corticotropin`, `Thyrotropin `,`Oxytocin`,`Prolactin`,`Antidiuretic hormone (ADH)`],
        optionFeedback: [`Corticotropin deficiency would manifest as weight loss, anorexia, hypotension and progressive weakness, not symptoms and signs of diabetes insipidus.`,`Thyrotropin deficiency would manifest with signs and symptoms of hypothyroidism.`,`Oxytocin deficiency is seen in posterior pituitary or hypothalamic diseases; in women, it usually manifests with problems during childbirth and lactation whereas in men the effects are more subtle and may go unrecognized. `,`Prolactin deficiency would not manifest with signs and symptoms of diabetes insipidus.`,`The clinical history, increased serum Na+ and osmolality, and decreased urine specific gravity are diagnostic of diabetes insipidus, in which secretion of antidiuretic hormone (also called vasopressin) is reduced. The posterior pituitary may be damaged by head trauma, tumors, or surgical procedures involving the hypothalamus or pituitary. The result of ADH deficiency is inadequate resorption of water in the kidney, producing polyuria. The excessive renal water loss elevates the sodium concentration and osmolality in the blood, inducing thirst and frequent drinking of water (polydipsia).`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The clinical history, increased serum Na+ and osmolality, and decreased urine specific gravity are diagnostic of diabetes insipidus, in which secretion of antidiuretic hormone (also called vasopressin) is reduced. The posterior pituitary may be damaged by head trauma, tumors, or surgical procedures involving the hypothalamus or pituitary. The result of ADH deficiency is inadequate resorption of water in the kidney, producing polyuria. The excessive renal water loss elevates the sodium concentration and osmolality in the blood, inducing thirst and frequent drinking of water (polydipsia). `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 69-year-old man has become progressively obtunded over the past week. He has an 80 pack-year smoking history. On physical examination, he is afebrile and normotensive. A head CT scan shows no intracerebral hemorrhages. Laboratory findings include serum Na<sup>+</sup>, 115 mmol/L (136–145 mmol/L); K<sup>+</sup>, 4.2 mmol/L (3.5–5.0 mmol/L); Cl–, 85 mmol/L (95–105 mmol/L); bicarbonate, 23 mmol/L (22–28 mmol/L); serum glucose, 80 mg/dL (fasting, 70–110 mg/dL); blood urea nitrogen, 19 mg/dL (0.1–1.0 mg/dL); and creatinine, 1.7 mg/dL (0.6–1.2 mg/dL). Which of the following neoplasms is most likely to be present in this man?`,
        q2: ``,
        q3: [],
        option: [`Anterior pituitary adenoma`, `Adrenocortical carcinoma`,` Pheochromocytoma`,`Small cell lung carcinoma`,`Renal cell carcinoma`],
        optionFeedback: [`Anterior pituitary adenoma would not secrete ADH, which is a posterior pituitary hormone.`,`Adrenal tumors do not produce ADH.`,`Pheochromocytoma produces catecholamines, not ADH.`,`The clinical history of neurologic dysfunction and the laboratory finding of hyponatremia are suggestive of the syndrome of inappropriate ADH secretion. This is often seen in small cell lung cancer, when the tumor cells secrete the hormone (an example of a paraneoplastic syndrome). The history of smoking is consistent with lung cancer. `,`Paraneoplastic syndromes associated with excessive hormone secretion occur with renal cell carcinoma but are usually caused by inappropriate secretion of erythropoietin leading to polycythemia, not release of ADH leading to electrolyte abnormalities. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The clinical history of neurologic dysfunction and the laboratory finding of hyponatremia are suggestive of the syndrome of inappropriate ADH secretion. This is often seen in small cell lung cancer, when the tumor cells secrete the hormone (an example of a paraneoplastic syndrome). The history of smoking is consistent with lung cancer. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 47-year-old woman has had increasing fatigue with dyspnea and reduced exercise tolerance for the past year. She also complains of constipation. On examination she has nonpitting edema of the lower extremities. Laboratory studies show a serum TSH level of 10 mU/L (0.5–5.0 mU/L) and T<sub>4</sub> level of 2 &#181;g/dL (5–12 &#181;g/dL). She is most likely to have pathologic findings affecting which of the following cells?`,
        q2: ``,
        q3: [],
        option: [`Thyrotrophs `, `Hypothalamic cells`,`Somatotrophs `,`Thyroid C cells`,`Thyroid follicular cells `],
        optionFeedback: [`Thyrotrophs as a cause of hypothyroidism, perhaps in the setting of an anterior pituitary lesion, would show reduced TSH.    In a thyrotroph adenoma, the patient would have increased TSH.`,`Hypothalamic dysfunction as a cause of hypothyroidism would show reduced TSH.`,`Somatotroph abnormalities would not affect thyroid hormones.`,`Thyroid C cells are neuroendocrine cells that produce calcitonin, not thyroid hormone.`,`The clinical features suggest primary hypothyroidism, and the laboratory findings of reduced T<sub>4</sub> and increased TSH are diagnostic. Primary hypothyroidism may be caused by autoimmune thyroid disease (Hashimoto thyroiditis) or dietary iodine deficiency, or it may be iatrogenic (post-surgery for cancer). Whatever the underlying cause, the thyroid follicular cells are not functioning adequately. `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The clinical features suggest primary hypothyroidism, and the laboratory findings of reduced T<sub>4</sub> and increased TSH are diagnostic. Primary hypothyroidism may be caused by autoimmune thyroid disease (Hashimoto thyroiditis) or dietary iodine deficiency, or it may be iatrogenic (post-surgery for cancer). Whatever the underlying cause, the thyroid follicular cells are not functioning adequately. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 43-year-old woman has a 3-year history of increasing lethargy and weakness. She has cold intolerance and wears a sweater in the summer. One year ago, she had menorrhagia, but now she has oligomenorrhea. She has difficulty concentrating, and her memory is poor. She has chronic constipation. On physical examination, her temperature is 35.5&#176; C, pulse is 54 bpm, respirations are 13 breaths/min, and blood pressure is 110/70 mm Hg. Laboratory findings show hemoglobin, 13.8 g/dL (12.0–16.0 g/dL); hematocrit, 41.5% (36.0%–46.0%); glucose, 73 mg/dL (fasting, 70–110 mg/dL); and creatinine, 1.1 mg/dL (0.6–1.2 mg/dL). A representative microscopic image from another patient with the same disease is shown in the figure. Which of the following serologic test findings is most likely to be positive in this woman?`,
        q2: `<img src="../images/f016-q007-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Anticentromere antibody`, `Anti–double-stranded DNA antibody`,`Antimitochondrial antibody`,`Antithyrotroph antibody`,`Anti–thyroglobulin antibody`],
        optionFeedback: [`Anticentromere antibodies (one type of antinuclear autoantibody) are most often associated with limited systemic sclerosis.`,`Anti-dsDNA antibody is classic for systemic lupus erythematosus.`,`Antimitochondrial antibody is associated with primary sclerosing cholangitis.`,`The histologic features support an etiology of primary hypothyroidism (i.e., due to thyroid abnormality), not a lesion of thyrotrophs in the anterior pituitary.`,`The clinical history of lethargy, cold intolerance, and oligomenorrhea and the physical findings of low body temperature and low heart and respiratory rates are suggestive of hypothyroidism. The lymphoid follicles and large pink nodules of Hurthle cells seen microscopically are diagnostic for Hashimoto thyroiditis. (An episode of menorrhagia a year ago may indicate transient hyperthyroidism, which is often seen in these patients.) The disease is caused by T-cell autoimmunity to thyroid antigens/cells. Autoantibodies to thyroglobulin and thyroid peroxidase are found in most patients.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The clinical history of lethargy, cold intolerance, and oligomenorrhea and the physical findings of low body temperature and low heart and respiratory rates are suggestive of hypothyroidism. The lymphoid follicles and large pink nodules of Hurthle cells seen microscopically are diagnostic for Hashimoto thyroiditis. (An episode of menorrhagia a year ago may indicate transient hyperthyroidism, which is often seen in these patients.) The disease is caused by T-cell autoimmunity to thyroid antigens/cells. Autoantibodies to thyroglobulin and thyroid peroxidase are found in most patients.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 37-year-old woman has had difficulty swallowing and a feeling of fullness in the anterior neck for the past week. She is recovering from a mild upper respiratory tract infection 1 month ago. On physical examination, her temperature is 37.4&#176; C, pulse is 74 bpm, respirations are 16 breaths/min, and blood pressure is 122/80 mmHg. Her diffusely enlarged thyroid is painful to palpation. Laboratory studies show an increased serum T<sub>4</sub> level and a decreased TSH level. Two months later, her symptoms have resolved and her T<sub>4</sub> level is now normal. Which of the following conditions is most likely to have produced the patient’s laboratory and clinical findings?`,
        q2: ``,
        q3: [],
        option: [`Hashimoto thyroiditis`, `Medullary thyroid carcinoma`,`Subacute granulomatous thyroiditis`,`Toxic follicular adenoma`,`Toxic multinodular goiter`],
        optionFeedback: [`Hashimoto thyroiditis usually presents with painless swelling and hypothyroidism (although there may be transient hyperthyroidism early in the disease course). `,`Medullary carcinoma arises from calcitonin-producing C cells. It presents with local mass effects (compression of the trachea) but not abnormal thyroid function. `,`The clinical presentation of painful thyroid swelling following an upper respiratory tract infection with transient hyperthyroidism is classic for subacute granulomatous thyroiditis. Hyperthyroidism results from inflammatory damage to the follicles and release of thyroid hormone. The disease is usually self-limited. `,`Toxic adenoma is associated with evidence of hyperthyroidism that resolves only when the lesion is treated.`,`Toxic multinodular goiter is associated with evidence of hyperthyroidism that resolves only when the lesion is treated. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The clinical presentation of painful thyroid swelling following an upper respiratory tract infection with transient hyperthyroidism is classic for subacute granulomatous thyroiditis. Hyperthyroidism results from inflammatory damage to the follicles and release of thyroid hormone. The disease is usually self-limited.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 20-year-old woman and her identical twin sister both experience increasing diplopia. Their conditions develop within 3 years of each other. On physical examination, they have exophthalmos and weak extraocular muscle movement. The thyroid gland is diffusely enlarged but painless in both, and there is no lymphadenopathy in either woman. Which of the following serum laboratory findings is most likely to be reported in these two patients?`,
        q2: ``,
        q3: [],
        option: [`Decreased free thyroxine level`, `Decreased thyroid-stimulating hormone (TSH) level`,`High titer antithyroglobulin antibodies`,`Increased thyrotropin-releasing hormone (TRH) level`,`Decreased triiodothyronine level `],
        optionFeedback: [`Thyroxine (T<sub>4</sub>) levels are increased, not decreased, due to overproduction from the overstimulated thyroid follicular epithelial cells.`,`Exophthalmos and diffuse thyroid enlargement are typical for Graves disease, an autoimmune disease in which antibodies against the TSH receptor on thyroid follicular cells mimic the action of TSH and stimulate the cells to produce excessive amounts of thyroid hormones. TSH levels are reduced because the increased production of thyroid hormones (T<sub>4</sub> and T<sub>3</sub>) causes feedback inhibition of TSH.   The concordance rate of Graves disease in identical twins is 50%, suggesting a genetic component in the pathogenesis of this disease. `,`Antithyroglobulin antibodies are found in patients with Hashimoto thyroiditis. `,`Increased levels of TRH are seen in those with thyrotroph pituitary adenoma.`,`Triiodothyronine (T<sub>3</sub>) levels are increased, not decreased, because of overproduction from the overstimulated thyroid follicular epithelial cells.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Exophthalmos and diffuse thyroid enlargement are typical for Graves disease, an autoimmune disease in which antibodies against the TSH receptor on thyroid follicular cells mimic the action of TSH and stimulate the cells to produce excessive amounts of thyroid hormones. TSH levels are reduced because the increased production of thyroid hormones (T<sub>4</sub> and T<sub>3</sub>) causes feedback inhibition of TSH.  The concordance rate of Graves disease in identical twins is 50%, suggesting a genetic component in the pathogenesis of this disease. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 21-year-old woman has noted increasing fatigue and a 7-kg weight loss without dieting over the past 4 months. She also has increasing anxiety, nervousness, and diarrhea. Physical examination shows a diffusely enlarged thyroid gland. Her temperature is 37.5&#176; C, pulse is 103 bp, respirations are 28 breaths/min, and blood pressure is 140/75 mm Hg. A radionuclide scan of the thyroid shows a diffuse increase in uptake. The figure shows the representative microscopic appearance of the thyroid gland. Which of the following is most likely to be involved in the pathogenesis of this disease? `,
        q2: `<img src="../images/f016-q010-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Antibodies against thyroid stimulating hormone (TSH) receptor`, `Dietary deficiency of iodine`,`Irradiation of the neck`,` Maternal deficiency in T<sub>4</sub>`,`Mutation in the RET proto-oncogene `],
        optionFeedback: [`The clinical features are suggestive of hyperthyroidism (fatigue, weight loss, anxiety, rapid heart rate). The hyperplasia and infolding of follicular epithelium seen histologically are characteristic of Graves disease; diffuse uptake of radiolabeled iodine supports this diagnosis. The disease is caused by autoantibodies that bind to and stimulate the TSH receptor.`,`Iodine deficiency causes goiter, which is typically euthyroid.`,`Irradiation predisposes to papillary thyroid cancer.`,`Congenital thyroid hormone deficiency is rare and would present with hypothyroidism.`,`Mutations in RET are associated with papillary thyroid carcinoma, not Graves disease or other causes of hyperthyroidism. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The clinical features are suggestive of hyperthyroidism (fatigue, weight loss, anxiety, rapid heart rate). The hyperplasia and infolding of follicular epithelium seen histologically are characteristic of Graves disease; diffuse uptake of radiolabeled iodine supports this diagnosis. The disease is caused by autoantibodies that bind to and stimulate the TSH receptor.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 45-year-old woman from Nepal reports a feeling of fullness in her neck, but has no other concerns. The enlargement has been gradual and painless for more than 1 year. Physical examination confirms diffuse enlargement of the thyroid gland without any apparent masses or lymphadenopathy. Laboratory studies of thyroid function show a normal free T<sub>4</sub> level and a slightly increased thyroid stimulating hormone (TSH) level. Which of the following is the most likely cause of these findings?`,
        q2: ``,
        q3: [],
        option: [`Dietary deficiency of iodine`, `Thyrotroph adenoma of pituitary `,`Anti-TSH receptor antibodies`,`C-cell hyperplasia `,`Gain of function mutation in TSH receptor pathway`],
        optionFeedback: [`In endemic areas, such as the Himalayas, goiter (enlargement of the thyroid) is most often caused by dietary iodine deficiency, which leads to defective production of thyroid hormones, compensatory increase of TSH, and resulting proliferation of thyroid follicular epithelium until euthyroid state occurs. `,` A TSH-producing pituitary adenoma would cause greater increase in TSH and functional hyperthyroidism.`,`Anti-TSH receptor antibodies cause Graves disease which causes clinical hyperthyroidism.`,`Parafollicular C cells produce neuroendocrine hormones. They are the cells that give rise to medullary carcinoma. `,`Activating mutations in the TSH receptor pathway are associated with follicular adenoma, which produces a detectable thyroid mass. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- In endemic areas, such as the Himalayas, goiter (enlargement of the thyroid) is most often caused by dietary iodine deficiency, which leads to defective production of thyroid hormones, compensatory increase of TSH, and resulting proliferation of thyroid follicular epithelium until euthyroid state occurs. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 70-year-old man has had a gradually increasing neck mass for the past 2 years. Over the past 6 months, he has lost 3 kg weight, developed diarrhea and heat intolerance. On physical examination, his temperature is 37.3&#176; C, and pulse is 102 bpm. There is fullness to the anterior neck, with a 5 &#215; 10 cm irregular nodular mass on palpation. Laboratory studies show serum TSH of 0.2 mU/L (0.5–5.0 mU/L). A thyroid scintigraphic scan shows a 1.5-cm nodule with increased iodine uptake, and decreased uptake of the remaining enlarged thyroid. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Follicular adenoma`, `Graves disease`,`Hashimoto thyroiditis`,`Papillary carcinoma`,`Toxic multinodular goiter`],
        optionFeedback: [`Adenoma is usually a solitary mass in an otherwise unremarkable thyroid gland. Toxic adenomas produce thyroid hormone and are detected as “hot” nodules by scintigraphy.`,`Graves disease presents with hyperthyroidism. The gland is diffusely enlarged and not multinodular. There is a diffuse uptake of radiolabelled iodine.`,`Hashimoto thyroiditis causes hypothyroidism.`,`Papillary carcinoma presents with a mass that does not produce hormones and does not cause hyperthyroidism. `,`The irregularly enlarged thyroid is a multinodular goiter. The clinical findings (weight loss, heat intolerance, tachycardia, decreased TSH) indicate hyperthyroidism. The scan identifies an area of overproduction of thyroid hormone, confirming a toxic multinodular goiter. Iodine uptake is reduced in the rest of the gland because overproduction of thyroid hormones by the nodule inhibits TSH production.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The irregularly enlarged thyroid is a multinodular goiter. The clinical findings (weight loss, heat intolerance, tachycardia, decreased TSH) indicate hyperthyroidism. The scan identifies an area of overproduction of thyroid hormone, confirming a toxic multinodular goiter. Iodine uptake is reduced in the rest of the gland because overproduction of thyroid hormones by the nodule inhibits TSH production.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 30-year-old woman has a 6-month history of weight loss (3 kg), hand tremors, mild watery diarrhea, and heat intolerance. On physical examination, temperature is 37.3&#176; C; pulse, 103 bpm; respirations, 20 breaths/min; and blood pressure, 125/85 mm Hg. She has a 1-cm firm, painless nodule palpable on the left side of her neck. There is no lymphadenopathy. No other abnormal findings are noted. Laboratory findings include a total serum T<sub>4</sub> of 11.6 &#181;g/dL (5–12&#181;g/dL) with TSH of 0.2 mU/L (0.5–5.0 mU/L). A scintigraphic scan shows more uptake of radioactive iodine into the nodule than the surrounding thyroid. A partial thyroidectomy is performed, and microscopic examination of the excised nodule shows well-differentiated thyroid follicles without vascular or capsular invasion. Molecular analysis of this nodule is most likely to reveal which of the following genetic changes?`,
        q2: ``,
        q3: [],
        option: [`Fusion gene formed by PAX8 and PPARG genes`, `Gain of function mutation of TSH receptor gene`,` Mutational activation of RET tyrosine kinase receptor`,`Mutational activation of RAS gene`,`Activating mutations of BRAF gene `],
        optionFeedback: [`PAX8-PPARG gene fusions are seen in about half of follicular carcinomas which are usually nonfunctional. Follicular carcinomas show capsular and vascular invasion, absent in this case.`,`A solitary thyroid nodule associated with clinical and laboratory evidence of hyperthyroidism is typical of a functioning follicular adenoma which secretes thyroid hormones independent of TSH stimulation. These benign tumors are often caused by activating mutations in the TSH receptor gene. `,`RET mutations are seen in papillary thyroid carcinomas (also nonfunctional).`,`Activating mutations of RAS are found in many tumors, including follicular thyroid carcinoma.`,`Activating mutations of BRAF are found in many tumors, including papillary thyroid carcinoma.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- A solitary thyroid nodule associated with clinical and laboratory evidence of hyperthyroidism is typical of a functioning follicular adenoma which secretes thyroid hormones independent of TSH stimulation. These benign tumors are often caused by activating mutations in the TSH receptor gene.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 45-year-old man has a 4-month history of a lump on the left side of his neck. Physical examination reveals a nodule on the left lobe of the thyroid gland and an adjacent cervical lymph node that is enlarged and nontender. Laboratory studies are negative for serum thyroid autoantibodies and the T<sub>4</sub> and TSH levels are normal. A thyroidectomy is performed; the figure shows the microscopic appearance of the nodule. Which of the following etiologic factors is most likely to be involved in the pathogenesis of the thyroid nodule in this patient?`,
        q2: `<img src="../images/f016-q014-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Thyroid autoantibodies`, `Chronic dietary iodine deficiency`,`Pituitary adenoma`,`RET gene mutation`,`Viral infection`],
        optionFeedback: [`Autoimmunity is not associated with any epithelial thyroid tumor.`,`Iodine deficiency gives rise to uniform enlargement of the thyroid (goiter), but not a malignant tumor.`,`Pituitary adenomas are not associated with thyroid malignancy. Those that secrete TSH cause hyperthyroidism`,`A solitary thyroid nodule with enlarged cervical nodes suggests a thyroid cancer with metastases. The papillary architecture and clear nuclei are diagnostic for papillary carcinoma. These tumors are often associated with mutations of the RET tyrosine kinase. `,`Viral infection is associated with subacute granulomatous thyroiditis, but not thyroid tumors.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- A solitary thyroid nodule with enlarged cervical nodes suggests a thyroid cancer with metastases. The papillary architecture and clear nuclei are diagnostic for papillary carcinoma. These tumors are often associated with mutations of the RET tyrosine kinase. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 62-year-old woman has felt a 5-month history of a lump on the right side of her neck. On physical examination, she has no lymphadenopathy. A fine-needle aspiration biopsy is performed, followed by a thyroidectomy. A 3-cm solid mass within the right thyroid lobe has the microscopic appearance shown in the figure. Six months later, she presents with right thigh pain. A radiograph shows a fracture of the right femur in an area of lytic bone destruction. Further investigations will most likely reveal which of the following results?`,
        q2: `<img src="../images/f016-q015-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Elevated parathyroid hormone`, `A mass in sella turcica seen on CT scan`,`Uptake of radioiodine in the region of the fracture`,`Antibodies to TSH receptor in the serum`,`Elevated levels of serum calcitonin`],
        optionFeedback: [`Elevation in PTH levels are most commonly caused by a solitary functional adenoma  of the parathyroid glands that does not invade locally or cause vascular spread. Elevations in PTH can cause osteoporosis and microfractures.`,`TSH levels would be elevated in patients with thyrotroph pituitary adenomas, which would give rise to a mass in the sella turcica and cause hyperthyroidism. Follicular carcinomas are usually nonfunctional. `,`A thyroid mass with follicular architecture that is invading through the capsule is diagnostic of follicular carcinoma. Follicular carcinomas are much less likely than papillary carcinomas to spread to lymph nodes and much more likely to metastasize to distant sites through the bloodstream. The pain in the thigh is likely because of a bone metastasis. Since this is composed of functional thyroid follicular cells, it would take up iodine. `,`Antibodies to the TSH receptor on thyroid follicular cells are seen in Graves disease.`,`Calcitonin is produced by C cells. Elevated calcitonin in medullary carcinoma is derived from the neoplastic C cells. Microscopically, medullary carcinomas are composed of polygonal to spindle-shaped cells, which may form nests, trabeculae, and follicles. Amyloid deposits, derived from altered calcitonin molecules, are present in the adjacent stroma in many cases.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- A thyroid mass with follicular architecture that is invading through the capsule is diagnostic of follicular carcinoma. Follicular carcinomas are much less likely than papillary carcinomas to spread to lymph nodes and much more likely to metastasize to distant sites through the bloodstream. The pain in the thigh is likely because of a bone metastasis. Since this is composed of functional thyroid follicular cells, it would take up iodine. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 42-year-old woman has noted increasing fullness in her neck for the past 7 months. On physical examination, her thyroid gland is diffusely and asymmetrically enlarged and nodular. There is no lymphadenopathy. She undergoes thyroidectomy. Gross examination of the thyroid shows a multicentric thyroid neoplasm; microscopically, the neoplasm is composed of polygonal- to spindle-shaped cells forming nests and trabeculae. There is a prominent, pink hyaline stroma that stains positively with Congo red. Immunohistochemical staining for which of the following molecules will be most useful for diagnosis of this neoplasm?`,
        q2: ``,
        q3: [],
        option: [`Calcitonin`, `Serum amyloid associated protein (SAA)`,`Thyroglobulin`,`Thyrotropin`,`Parathyroid hormone`],
        optionFeedback: [`The histology is typical of medullary carcinoma, which makes up &lt;5% of cases of thyroid cancer and is derived from neuroendocrine cells in the thyroid, the calcitonin-producing parafollicular C cells. Tumors may be solitary or multiple, composed of nests of spindle-shaped or polygonal cells. The tumors frequently contain deposits of amyloid (the pink Congo Red-positive material) derived from the large amounts of calcitonin that are produced locally.`,`  SAA is an acute phase protein that is produced in inflammatory reactions and gives rise to amyloid (the secondary form, associated with chronic inflammatory diseases).`,`Thyroglobulin is produced by normal thyroid follicular epithelial cells and some follicular carcinomas.`,`Thyrotropin is produced by TSH-secreting cells in the anterior pituitary.`,`Parathyroid hormone is produced in the parathyroid glands, not the thyroid. Parathyroid hormone-related protein (PTHRP) can be ectopically produced by some carcinomas of the lung.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The histology is typical of medullary carcinoma, which makes up &lt;5% of cases of thyroid cancer and is derived from neuroendocrine cells in the thyroid, the calcitonin-producing parafollicular C cells. Tumors may be solitary or multiple, composed of nests of spindle-shaped or polygonal cells. The tumors frequently contain deposits of amyloid (the pink Congo Red-positive material) derived from the large amounts of calcitonin that are produced locally.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 40-year-old man experiences weakness and easy fatigability of 2 months’ duration. Physical examination yields no remarkable findings. Laboratory studies show serum calcium of 11.5 mg/dL (8.4–10.2 mg/dL), inorganic phosphorus of 2.1 mg/dL (3.0–4.5 mg/dL), and serum parathyroid hormone (PTH) of 858 pg/mL (230–630 pg/mL). Which of the following is the most likely cause of these findings?`,
        q2: ``,
        q3: [],
        option: [`Chronic renal failure`, `Medullary thyroid carcinoma`,`Parathyroid adenoma`,`Parathyroid carcinoma`,`Parathyroid hyperplasia`],
        optionFeedback: [`In chronic renal failure, there is retention of phosphate, which depresses serum calcium levels with a compensatory increase in parathyroid activity, causing secondary hyperparathyroidism. In such cases, there is hyperplasia of the parathyroid glands. Serum calcium levels are usually reduced or normal, phosphate levels are increased, and PTH is increased. Renal manifestations may dominate the clinical picture. `,`Medullary carcinoma of the thyroid is associated with increased production of calcitonin, which functions to reduce calcium levels by inhibiting osteoclast activity and renal absorption of calcium. However, hypocalcemia is not a notable feature of medullary carcinomas of thyroid.`,`Hypercalcemia with decreased phosphate and modestly elevated PTH are characteristic of primary hyperparathyroidism. In 85%–90% cases, the cause is parathyroid adenoma. Less frequently, it is caused by multiglandular parathyroid hyperplasia or parathyroid carcinoma.`,`Although parathyroid carcinoma can cause primary hyperparathyroidism, it is far less frequent than parathyroid adenoma (about 1%).  `,`Although parathyroid hyperplasia can cause primary hyperparathyroidism, it is far less frequent than parathyroid adenoma (about 5%–10%).  `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Hypercalcemia with decreased phosphate and modestly elevated PTH are characteristic of primary hyperparathyroidism. In 85%–90% cases, the cause is parathyroid adenoma. Less frequently, it is caused by multiglandular parathyroid hyperplasia or parathyroid carcinoma. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 63-year-old woman had frequent headaches for 1 month. Her daughter says that of late she is lethargic and depressed. Physical examination is unremarkable. Laboratory findings include serum calcium of 12.4 mg/dL (8.4–10.2 mg/dL), serum phosphorus of 1.9 mg/dL (3.0–4.5 mg/dL), and albumin of 4.2 g/dL (3.5–5.5 g/dL). A chest radiograph shows multiple lung masses and lytic lesions of the vertebral column. Which of the following conditions best accounts for these findings?`,
        q2: ``,
        q3: [],
        option: [`Chronic renal failure`, `Disseminated tuberculosis`,`Metastatic breast carcinoma`,`Parathyroid carcinoma`,`Vitamin D toxicity`],
        optionFeedback: [`In chronic renal failure, there is retention of phosphate, which depresses serum calcium levels with compensatory increase in parathyroid activity, causing secondary hyperparathyroidism. Serum calcium levels are usually reduced or normal, phosphate levels are increased, and PTH is increased. Renal manifestations may dominate the clinical picture.  `,`Tuberculosis can give rise to hypercalcemia by upregulating 1,25-dihydrocalciferol in activated macrophages, but this is rarely clinically significant.`,`Hypercalcemia associated with multiple lung and bone lesions is typical of metastatic cancer, the most common cause of hypercalcemia in adults. The most common metastatic cancers to bone are lung, prostate, thyroid, kidney and breast. Hypercalcemia results from secretion of PTH-related protein and osteoclast activity in the bone metastases. `,`Parathyroid carcinoma is rare and usually nonfunctional.`,`Vitamin D toxicity can cause hypercalcemia and bone pain in adults, but it is rare, and would not be associated with lung and bone metastases.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Hypercalcemia associated with multiple lung and bone lesions is typical of metastatic cancer, the most common cause of hypercalcemia in adults. The most common metastatic cancers to bone are lung, prostate, thyroid, kidney and breast. Hypercalcemia results from secretion of PTH-related protein and osteoclast activity in the bone metastases.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 47-year-old woman noticed a lump in her neck 1 week ago. On physical examination, there is a 2-cm nodule in the right lobe of the thyroid gland. A fine-needle aspiration biopsy is performed, and microscopic examination of the specimen shows cells consistent with a follicular neoplasm. She undergoes a subtotal thyroidectomy, in which the majority of the gland is excised, leaving only a small portion of thyroid tissue to preserve thyroid function. Which of the following is the most critical test that should be performed on this patient in the immediate postoperative period?`,
        q2: ``,
        q3: [],
        option: [`Antithyroglobulin antibody`, `Calcitonin`,`Radioiodine uptake `,`Parathyroid hormone`,`Thyroid stimulating hormone (TSH)`],
        optionFeedback: [`Antithyroglobulin antibody is found in Hashimoto thyroiditis.`,`Calcitonin is produced by medullary carcinoma of the thyroid.`,`Radioiodine uptake is used for preoperative diagnosis of thyroid diseases.`,`Surgical removal of the glands during thyroidectomy or other surgery is the most common cause of hypoparathyroidism. Since there is a real possibility that parathyroid glands may have been removed along with the thyroid, it is critical to monitor the patient’s parathyroid hormone levels postoperatively. `,`TSH levels change in diseases associated with hyperthyroidism or hypothyroidism.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Surgical removal of the glands during thyroidectomy or other surgery is the most common cause of hypoparathyroidism. Since there is a real possibility that parathyroid glands may have been removed along with the thyroid, it is critical to monitor the patient’s parathyroid hormone levels postoperatively. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 13-year-old girl collapses while playing basketball. On arrival at the Emergency Department, she is obtunded. On physical examination, she is hypotensive and tachycardic with deep, rapid, labored respirations. Laboratory studies show serum Na<sup>+</sup>, 151 mmol/L (136–145 mmol/L); K<sup>+</sup>, 4.6 mmol/L (3.5–5.0 mmol/L); Cl–, 98 mmol/L (95–105 mmol/L); CO<sub>2</sub>, 7 mmol/L (23–29 mmol/L); and glucose, 521 mg/dL (fasting, 70–110 mg/dL). Urinalysis shows 4+ glucosuria and 4+ ketonuria levels, but no protein, blood, or nitrite. Which of the following is the most likely mechanism underlying this disease?`,
        q2: ``,
        q3: [],
        option: [`Beta cell damage caused by T cells`, `Excessive production of ketones due to liver cell injury`,`Primary defect in glucagon secretion`,`Replacement of islets by amyloid`,`Defective secretion of cytokines from adipose tissue `],
        optionFeedback: [`This patient developed diabetic ketoacidosis, manifested by very high glucose, ketonuria and metabolic acidosis. This acute complication is most often seen with type 1 diabetes, which is caused by immune damage to islet beta cells. The patient’s age is consistent with the diagnosis.`,`Although ketones are produced in the liver from fatty acids, ketoacidosis is not a feature of hepatocyte injury and the high blood glucose would not be seen in ketoacidosis from any cause other than diabetes.`,`Defects in glucagon secretion are rare and do not cause severe diabetes.`,`Replacement of islets with amyloid is sometimes seen in long-standing type 2 diabetes, but these are older patients and they rarely develop ketoacidosis.`,`Cytokine production from adipose tissue may contribute to type 2 diabetes but not type 1 diabetes, which is most often complicated by ketoacidosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- This patient developed diabetic ketoacidosis, manifested by very high glucose, ketonuria and metabolic acidosis. This acute complication is most often seen with type 1 diabetes, which is caused by immune damage to islet beta cells. The patient’s age is consistent with the diagnosis.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A clinical study is conducted in patients diagnosed with either type 1 or type 2 diabetes. Persons with either type develop complications of accelerated and advanced atherosclerosis. All untreated patients have an elevated hemoglobin A1c. Which of the following features common to patients with both types of diabetes is most likely to be found by this study?`,
        q2: ``,
        q3: [],
        option: [`Association with certain MHC class II alleles`, `High concordance rate in monozygotic twins`,`Marked resistance to the action of insulin`,`Nonenzymatic glycation of proteins`,` Presence of islet cell antibodies`],
        optionFeedback: [`This is a feature of type 1, not type 2 diabetes.`,`This is a feature of type 2, not type 1 diabetes.`,`This is seen in type 2, but not type 1 diabetes.`,`The only abnormality common to both forms of diabetes is nonenzymatic glycation of proteins, measured clinically as elevated HbA1c. It is a consequence of hyperglycemia rather than its cause. Nonenzymatic glycation of proteins is the basis of several vascular complications.`,`This is a feature of type 1, not type 2 diabetes.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The only abnormality common to both forms of diabetes is nonenzymatic glycation of proteins, measured clinically as elevated HbA1c. It is a consequence of hyperglycemia rather than its cause. Nonenzymatic glycation of proteins is the basis of several vascular complications.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 50-year-old man with fasting blood glucose &gt;140 mg/dL (70–110 mg/dL) on two occasions is put on a restricted calorie diet and started on an oral hypoglycemic agent. Which of the following laboratory studies is most likely to afford the best method of monitoring disease control in this man?`,
        q2: ``,
        q3: [],
        option: [`Total cholesterol`, `Fasting plasma glucose`,`Glycated hemoglobin`,`Microalbuminuria`,`Retinal examinations`],
        optionFeedback: [`Cholesterol levels would not change with onset of diabetes and have no role in monitoring how well the disease is controlled.`,`Plasma glucose levels are affected by environmental changes, infections, and other conditions much more than HbA1c.`,`This patient has type 2 diabetes, which is best monitored by measuring levels of glycated hemoglobin (HbA1c). The degree of glycation is proportional to the level of blood glucose. Because RBCs have a life span of 120 days, the amount of HbA1c is a function of the blood glucose levels over the previous 120-day period and is a more accurate measure of long term glycemic control, than is blood glucose level which is transiently affected by numerous environmental factors including diet.`,`Albuminuria is an indicator of renal disease, which is a possible complication of advanced diabetes but not useful for monitoring the disease itself.`,`Neovascularization of the retina is a late complication of poorly controlled diabetes and is not an accurate measure of current disease control.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- This patient has type 2 diabetes, which is best monitored by measuring levels of glycated hemoglobin (HbA1c). The degree of glycation is proportional to the level of blood glucose. Because RBCs have a life span of 120 days, the amount of HbA1c is a function of the blood glucose levels over the previous 120-day period and is a more accurate measure of long term glycemic control, than is blood glucose level which is transiently affected by numerous environmental factors including diet.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 52-year-old man has been concerned about a gradual weight gain over the past 30 years. He is 174 cm (5 feet 7 inches) tall and weighs 91 kg (body mass index 30). He is taking no medications. On physical examination, he has decreased sensation to pinprick and light touch over the lower extremities. Laboratory studies show fasting blood glucose of 169 mg/dL (fasting, 70–110 mg/dL), creatinine of 1.9 mg/dL (0.6–1.2 mg/dL), total cholesterol of 220 mg/dL (&lt;200 mg/dL), and HDL cholesterol of 27 mg/dL (&gt;40 mg/dL). A chest radiograph shows mild cardiomegaly. Five years later, he has claudication in the lower extremities when he exercises. Based on these findings, which of the following complications is most likely to occur in this man?`,
        q2: ``,
        q3: [],
        option: [` Gangrene`, `Hypoglycemic coma`,`Ketoacidosis`,`Pancreatitis`,`Systemic amyloidosis`],
        optionFeedback: [`This patient has type 2 diabetes with evidence of hypertension (indicated by the cardiomegaly), and likely atherosclerosis (the high cholesterol and obesity being risk factors). He has peripheral neuropathy (sensory deficits) and vascular disease (claudication). A likely complication is gangrene secondary to vascular narrowing and loss of sensation. `,`Hypoglycemia can occur in patients who are taking insulin if they miss a meal or take too much insulin. This patient is not on insulin, so hypoglycemia is not likely. `,`Ketoacidosis is typically an acute complication of type 1 diabetes. This patient is overweight and the course of his disease is suggestive of type 2 diabetes.`,`Pancreatitis would cause acute abdominal pain and not the symptoms seen in this patient.`,`Deposition of amyloid can occur in the islets of type 2 diabetics; systemic amyloidosis is not associated with diabetes.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- This patient has type 2 diabetes with evidence of hypertension (indicated by the cardiomegaly), and likely atherosclerosis (the high cholesterol and obesity being risk factors). He has peripheral neuropathy (sensory deficits) and vascular disease (claudication). A likely complication is gangrene secondary to vascular narrowing and loss of sensation. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 45-year-old woman has had angina pectoris, polyuria, and polydipsia for the past 5 years. On physical examination, she has a body mass index of 32. Laboratory studies show her hemoglobin A1c is 10% (&#8804;6%). Urinalysis shows proteinuria, but no ketonuria. Which of the following is the most likely mechanism responsible for the clinical and pathologic features of her disease? `,
        q2: ``,
        q3: [],
        option: [`Chronic pancreatitis`, `Failure of self-tolerance to pancreatic beta cells`,`Impaired insulin signaling`,`Inheritance of disease-associated HLA class II genes`,`Insulitis `],
        optionFeedback: [`Although late in its course chronic pancreatitis can give rise to diabetes, it is usually associated with evidence of pancreatic enzyme deficiency (e.g., fat malabsorption).`,`This is typical of type 1 diabetes, not type 2 diabetes.`,`The clinical features (polyuria and polydipsia in an obese person) and laboratory findings (increased HbA1c) are classic for type 2 diabetes. The patient has likely developed vascular disease (angina) and kidney disease (proteinuria). An important pathogenic mechanism in type 2 diabetes is impaired insulin signaling causing insulin resistance of peripheral tissues.`,`This is typical of type 1 diabetes, not type 2 diabetes.`,`This is typical of type 1 diabetes, not type 2 diabetes.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The clinical features (polyuria and polydipsia in an obese person) and laboratory findings (increased HbA1c) are classic for type 2 diabetes. The patient has likely developed vascular disease (angina) and kidney disease (proteinuria). An important pathogenic mechanism in type 2 diabetes is impaired insulin signaling causing insulin resistance of peripheral tissues.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 50-year-old man has a 35-year history of diabetes. During this time, he has had hemoglobin A1c values between 7% and 10% (&#8804;6%). He now has difficulty attaining an erection and has loss of sensation in his legs. These neurologic changes are most likely to originate from which of the following mechanisms?`,
        q2: ``,
        q3: [],
        option: [`Cross-linking of extracellular matrix proteins`, `Abnormal transforming growth factor-β (TGF-β) signaling`,` Accelerated atherosclerosis of femoral arteries`,`Microaneurysms in CNS blood vessels`,`Toxic effects of intracellular hyperglycemia`],
        optionFeedback: [`Advanced glycation end-products (AGEs) are formed by glycosylation of plasma and tissue proteins, a process that is accelerated by hyperglycemia. AGEs bind to a receptor called RAGE that is expressed on inflammatory cells (macrophages and T cells), endothelium, and vascular smooth muscle cells. Binding of AGEs to RAGE leads to the production of cytokines and growth factors, generation of reactive oxygen species, increased procoagulant activity of endothelium, proliferation of smooth muscle cells, and synthesis of extracellular matrix. AGEs do not affect nerves.`,`Intracellular glucose is converted to diacylglycerol, which activates the enzyme protein kinase C. This enzyme stimulates several signaling pathways, leading to increased production of growth factors such as TGF-β (which stimulates production of extracellular matrix proteins). It does not cause nerve damage.`,`Accelerated atherosclerosis is a frequent complication of type 2 diabetes that can involve femoral arteries. This can lead to ischemia of the lower leg and gangrene. Reduced blood supply to the leg would not explain his neurologic symptoms. `,`Microaneurysms are seen in retinal vessels and contribute to the visual loss seen in advanced type 2 diabetes. They are not seen in vessels in the CNS and would not explain the patient’s symptoms. `,`Some tissues (e.g., nerve, lens, kidney, blood vessels) do not require insulin for glucose uptake, and, in the setting of hyperglycemia, intracellular glucose levels rise. Intracellular glucose is metabolized to sorbitol, in a reaction that depletes NADPH, a cofactor that is required for the regeneration of reduced glutathione (GSH), an important antioxidant. These cells therefore have increased susceptibility to damage caused by oxidative stress. `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Some tissues (e.g., nerve, lens, kidney, blood vessels) do not require insulin for glucose uptake, and, in the setting of hyperglycemia, intracellular glucose levels rise. Intracellular glucose is metabolized to sorbitol, in a reaction that depletes NADPH, a cofactor that is required for the regeneration of reduced glutathione (GSH), an important antioxidant. These cells therefore have increased susceptibility to damage caused by oxidative stress. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 39-year-old man has had headache, weakness, and a 5-kg weight gain over the past 3 months. He has experienced mental depression during the same period. On physical examination, his face is puffy. His temperature is 36.9&#176; C and blood pressure is 160/75 mm Hg. He has cutaneous striae over the lower abdomen and ecchymoses scattered over the extremities. A radiograph of the spine shows a compressed fracture of T11. Laboratory findings show fasting plasma glucose level of 200 mg/dL (fasting, 70–110 mg/dL), serum Na<sup>+</sup> of 150 mmol/L (136–145 mmol/L), and serum K<sup>+</sup> of 3.1 mmol/L (3.5–5.0 mmol/L). The plasma cortisol level is 38 &#181;g/dL at 8:00 am (5–23 &#181;g /dL) and 37 &#181;g/dL at 6:00 pm (&#8804;50% of 8:00 am level). Administration of low and high doses of dexamethasone fails to suppress the plasma cortisol level and excretion of urinary 17-hydroxycorticosteroids. The plasma ACTH level is 25 pg/mL (10–60 pg/mL) at 8:00 am. Which of the following lesions is most likely to be present in this man?`,
        q2: ``,
        q3: [],
        option: [`Pituitary corticotroph adenoma`, `Adrenal cortical adenoma`,` Pheochromocytoma`,`Small cell carcinoma of the lung`,`Thyroid medullary carcinoma`],
        optionFeedback: [`Plasma ACTH (corticotropin) would be elevated with an ACTH-producing pituitary adenoma.`,`The clinical manifestations characteristic of hypercortisolism (excessive production of corticosteroids) include weight gain, neurologic symptoms, abdominal striae, and osteoporosis (accounting for the patient’s vertebral fracture). The elevated plasma cortisol that is not suppressed by dexamethasone indicates an autonomous source of corticosteroids, either an adrenal cortical adenoma or an ectopic source of ACTH such as a lung cancer. The normal ACTH indicates that the lesion is likely an adrenal cortical adenoma. `,`Pheochromocytomas do not produce corticosteroids: they secrete catecholamines.`,`Lung cancers may produce ACTH as part of paraneoplastic syndromes, but if this were the case, plasma ACTH would be elevated.`,`Thyroid medullary carcinoma produces calcitonin, not corticosteroids. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical manifestations characteristic of hypercortisolism (excessive production of corticosteroids) include weight gain, neurologic symptoms, abdominal striae, and osteoporosis (accounting for the patient’s vertebral fracture). The elevated plasma cortisol that is not suppressed by dexamethasone indicates an autonomous source of corticosteroids, either an adrenal cortical adenoma or an ectopic source of ACTH such as a lung cancer. The normal ACTH indicates that the lesion is likely an adrenal cortical adenoma. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 28-year-old, otherwise healthy, man has had headaches for the past 2 weeks. Physical examination yields no remarkable findings except for a blood pressure of 174/116 mm Hg. An abdominal CT scan shows an enlarged right adrenal gland. A right adrenalectomy is performed to remove an adrenocortical adenoma. Blood pressure returns to normal after surgery. Which of the following laboratory findings was most likely seen in the patient’s pre-op blood work? `,
        q2: ``,
        q3: [],
        option: [`High serum glucose`, `High serum potassium`,`Low serum sodium`,`Low serum ACTH `,`Low serum renin`],
        optionFeedback: [`Hyperglycemia is not a feature of aldosterone-producing adrenal cortical adenomas.`,`The reduced renin leads to excessive excretion of K+ and reabsorption of Na+, so patients have hypokalemia and hypernatremia.`,`The reduced renin leads to excessive excretion of K+ and reabsorption of Na+, so patients have hypokalemia and hypernatremia.`,`ACTH levels would be suppressed by a corticosteroid-producing adrenal cortical adenoma; aldosterone does not have a feedback loop that lowers ACTH levels.`,`Acute onset of hypertension (as suggested by headaches, elevated blood pressure) in association with an adrenal adenoma indicates an aldosterone-producing tumor. This hormone inhibits the renin-angiotensin system and reduces plasma renin, leading to increased sodium resorption in renal tubules and hypertension.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Acute onset of hypertension (as suggested by headaches, elevated blood pressure) in association with an adrenal adenoma indicates an aldosterone-producing tumor. This hormone inhibits the renin-angiotensin system and reduces plasma renin, leading to increased sodium resorption in renal tubules and hypertension.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 5-year-boy has developed features that suggest puberty over the past 6 months. On physical examination, the boy has secondary sex characteristics, including pubic hair and enlargement of the penis. Which of the following laboratory abnormalities is most likely to be found in this patient?`,
        q2: ``,
        q3: [],
        option: [`Reduced serum ACTH`, `Elevated serum cortisol`,`Deficiency of 21-hydroxylase`,`Elevated urine catecholamines `,`Mutation in AIRE gene`],
        optionFeedback: [`Serum ACTH would be elevated.`,`Serum cortisol is low, hence the increased ACTH.`,`Premature virilization is the result of excessive androgens, most often caused by deficiency of 21-hydroxylase. This enzyme is involved in the production of glucocorticoids and mineralocorticoids. When these are low, the pituitary produces excess ACTH which cannot overcome the block in corticosteroid synthesis but stimulates androgen production.`,`Catecholamines are produced by pheochromocytoma, a tumor of the adrenal medulla.`,`AIRE gene mutations cause autoimmune polyendocrine (polyglandular) syndrome, which is manifested by immunologic destruction of the adrenal and other endocrine organs.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Premature virilization is the result of excessive androgens, most often caused by deficiency of 21-hydroxylase. This enzyme is involved in the production of glucocorticoids and mineralocorticoids. When these are low, the pituitary produces excess ACTH which cannot overcome the block in corticosteroid synthesis but stimulates androgen production.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 10-year-old, previously healthy, boy presents with severe headache and loss of consciousness. On examination, he is hypotensive and febrile with purpuric skin lesions. His peripheral blood smear shows schistocytes. Imaging studies show his adrenal glands are enlarged and there are extensive bilateral cortical hemorrhages. Which of the following mechanisms is the most likely cause of this condition?`,
        q2: ``,
        q3: [],
        option: [`Mutation in 21-hydroxylase gene`, `Autoimmune destruction of the adrenal glands`,`Pituitary thyrotroph adenoma`,`Infection with Neisseria meningitides`,`Metastases from a carcinoma of lung`],
        optionFeedback: [`21-hydroxylase mutations cause salt wasting and adrenogenital syndromes.`,`Autoimmune adrenalitis causes chronic adrenal cortical insufficiency (Addison disease), which is not associated with the acute symptoms in this child.`,`A pituitary thyrotroph adenoma would present with signs of hyperthyroidism such as diarrhea, weight loss and palpitations. `,`Hypotension with adrenal hemorrhages is diagnostic of Waterhouse-Friderichsen syndrome; when associated with disseminated bacterial infection, the most common cause is N. meningitides. In this setting, disseminated intravascular coagulation (DIC) leads to thrombocytopenia, resulting in the patient’s purpuric lesions. DIC and small thrombi also cause trauma to red cells in the narrowed microvasculature, leading to the lysis of red cells (microangiopathic hemolytic anemia) and the formation of schistocytes. `,`Adrenal metastases from lung cancer do occur, but not in a 10-year-old.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Hypotension with adrenal hemorrhages is diagnostic of Waterhouse-Friderichsen syndrome; when associated with disseminated bacterial infection, the most common cause is N. meningitides. In this setting, disseminated intravascular coagulation (DIC) leads to thrombocytopenia, resulting in the patient’s purpuric lesions. DIC and small thrombi also cause trauma to red cells in the narrowed microvasculature, leading to the lysis of red cells (microangiopathic hemolytic anemia) and the formation of schistocytes. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 29-year-old woman presents to the Emergency Department with acute right upper quadrant abdominal pain. Her medical history is significant for systemic lupus erythematosus treated for several years with corticosteroids for lupus nephritis. She undergoes an emergency appendectomy. On postoperative day 2, she becomes somnolent and develops severe nausea and vomiting. She then becomes hypotensive. Blood cultures are negative and laboratory studies show Na<sup>+</sup> of 128 mmol/L (136–145 mmol/L), K<sup>+</sup> of 4.9 mmol/L (3.5–5.0 mmol/L), Cl– of 89 mmol/L (95–105 mmol/L), CO2 of 19 mmol/L (23–29 mmol/L), glucose of 52 mg/dL (fasting, 70–110 mg/dL), and creatinine of 1.3 mg/dL (0.6–1.2 mg/dL). Which of the following morphologic findings in the adrenal gland cortex is most likely to be present in this patient?`,
        q2: ``,
        q3: [],
        option: [`Adenoma`, `Atrophy`,`Carcinoma`,`Caseating granulomas`,`Hemorrhagic necrosis`],
        optionFeedback: [`Nonfunctional unilateral adrenal tumors would not cause adrenocortical insufficiency because the other adrenal gland will be fully functional.`,`The clinical findings, along with hyponatremia and hyperkalemia, suggest acute adrenocortical insufficiency. The adrenal glands atrophy in patients given exogenous steroids because ACTH production is suppressed. If the steroid dose is not adjusted during stress, the result may be acute adrenocortical insufficiency. `,`Nonfunctional unilateral adrenal tumors would not cause adrenocortical insufficiency because the other adrenal gland will be fully functional.`,`Bilateral caseating granulomas of tuberculosis can cause chronic adrenal insufficiency, not acute adrenal insufficiency.`,`Hemorrhagic necrosis may cause acute adrenocortical insufficiency but would not be associated with steroid use. Waterhouse-Friderichsen syndrome is a cause for acute bilateral hemorrhagic necrosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical findings, along with hyponatremia and hyperkalemia, suggest acute adrenocortical insufficiency. The adrenal glands atrophy in patients given exogenous steroids because ACTH production is suppressed. If the steroid dose is not adjusted during stress, the result may be acute adrenocortical insufficiency. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 5-year-old boy has experienced increasing lethargy for the past 7 months. Physical examination shows hyperpigmentation of the skin. Vital signs include temperature of 36.9&#176; C, pulse of 70 bpm, respirations of 14/min, and blood pressure of 95/65 mmHg. Laboratory studies include a serum cortisol level of 3 &#181;g/mL at 8:00 am (5–23 &#181;g /dL) with a serum corticotropin (ACTH) level of 65 pg/mL (10–60 pg/mL). He also has an enlarged thyroid with a slight elevation in TSH levels. Which of the following is the most likely underlying mechanism in this disorder?`,
        q2: ``,
        q3: [],
        option: [`Mycobacterium tuberculosis infection `, `Failure to delete self-reactive T cells in the thymus`,`Destruction of anterior pituitary `,`Mutation in genes involved in synthesis of cortisol`,`Destruction by metastases to the adrenal glands `],
        optionFeedback: [`Adrenal tuberculosis can also cause chronic adrenocortical insufficiency (and is a frequent cause of Addison disease in lower income countries) but it would not be associated with hypothyroidism.`,`The clinical features and laboratory findings indicate chronic adrenocortical insufficiency. There is also mild hypothyroidism. This set of findings is diagnostic of autoimmune polyendocrine syndrome type 1 (APS-1), an inherited autoimmune disease caused by mutations in the AIRE gene. AIRE is a protein involved in expression of self antigens in the thymus and deletion of self-reactive T cells. This process is defective in APS-1 patients. `,`Destruction with loss of anterior pituitary hormones would likely cause deficiency of multiple hormones, including growth hormone, gonadotrophins, and prolactin.`,`Mutations of genes such as 21-hydroxylase usually present with salt-wasting and adrenogenital syndromes.`,`Adrenal metastases would not be associated with hypothyroidism and usually would present with clinical findings related to the tumor.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical features and laboratory findings indicate chronic adrenocortical insufficiency. There is also mild hypothyroidism. This set of findings is diagnostic of autoimmune polyendocrine syndrome type 1 (APS-1), an inherited autoimmune disease caused by mutations in the AIRE gene. AIRE is a protein involved in expression of self antigens in the thymus and deletion of self-reactive T cells. This process is defective in APS-1 patients.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 37-year-old woman states that, although most of the time she feels fine, she has had episodes of palpitations, tachycardia, tremor, and headache over the past 3 months. When her symptoms are worse, her blood pressure is measured in the range of 155/90 mm Hg. She collapses suddenly one day and is brought to the hospital, where her ventricular fibrillation is converted successfully to sinus rhythm. Physical examination is unremarkable. Which of the following laboratory findings is most likely to be reported in this patient?`,
        q2: ``,
        q3: [],
        option: [`Decreased plasma renin`, `Increased urinary cortisol`,`Decreased serum potassium level`,`Increased serum free T<sub>4</sub> level`,`Increased urinary free catecholamines`],
        optionFeedback: [`Plasma renin is decreased in cases of increased aldosterone production. This may cause hypertension with hypokalemia, but is not associated with the other clinical manifestations in this case such as paroxysms of hypertension`,`Urinary cortisol is increased in cases of hypercortisolism, which has a very different clinical presentation (e.g., striae, “buffalo hump,” weight gain).`,`Plasma renin is decreased in cases of increased aldosterone production. This may cause hypertension with hypokalemia, but not the other clinical manifestations in this case. `,`Serum T<sub>4</sub> is increased in hyperthyroidism, which may also be associated with increased sympathetic nervous system activity and cause tachycardia but not episodic hypertension.`,`The clinical findings suggest increased sympathetic nervous system activity and episodic hypertension. Of the possibilities listed, the most likely cause is increased production of catecholamines from a tumor of the adrenal medullary or paraganglion system (pheochromocytoma). `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The clinical findings suggest increased sympathetic nervous system activity and episodic hypertension. Of the possibilities listed, the most likely cause is increased production of catecholamines from a tumor of the adrenal medullary or paraganglion system (pheochromocytoma). `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 2-year-old boy is brought to the doctor because of an enlarged abdomen. On physical examination, there are no other abnormal findings except for slightly elevated blood pressure. An abdominal ultrasound scan shows a right retroperitoneal mass in the paravertebral region. Microscopic appearance of a CT-guided biopsy is shown in the figure. Which of the following features is a marker of poor prognosis?`,
        q2: `<img src="../images/f016-q033-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Age less than 18 months`, `Evidence of neuronal differentiation `,`MYCN amplification `,`Hyperdiploidy`,`Production of catecholamines`],
        optionFeedback: [`Age less than 18 months is associated with favorable prognosis in neuroblastoma.`,`Neuronal differentiation is associated with favorable prognosis in neuroblastoma.`,`The morphology shows a tumor of small, primitive-appearing cells with dark nuclei, sometimes arranged around fibrillary material, forming “pseudorosettes”; this is classic for neuroblastoma. Many of these tumors produce catecholamines, and detection of elevated levels of catecholamine metabolites in blood and urine is useful for diagnosis, but these hormones do not cause hypertension as often as in pheochromocytoma. MYCN amplification is seen in 25%–30% of these tumors and is associated with a worse prognosis. `,`Hyperdiploidy is associated with favorable prognosis in neuroblastoma.`,`The tumors often produce catecholamines, but this is not a prognostic factor.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The morphology shows a tumor of small, primitive-appearing cells with dark nuclei, sometimes arranged around fibrillary material, forming “pseudorosettes”; this is classic for neuroblastoma. Many of these tumors produce catecholamines, and detection of elevated levels of catecholamine metabolites in blood and urine is useful for diagnosis, but these hormones do not cause hypertension as often as in pheochromocytoma. MYCN amplification is seen in 25%–30% of these tumors and is associated with a worse prognosis. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 27-year-old man has a 3-month history of frequent headaches. Vital signs are significant for normal temperature and elevated blood pressure (140/85 mm Hg). Physical exam reveals an enlarged thyroid. Neurologic exam is normal and without visual defects. Laboratory studies show elevated serum calcitonin. A total thyroidectomy is performed, and on sectioning, the thyroid has multiple tumor nodules in both lobes. Microscopically, the thyroid nodules are composed of nests of neoplastic cells separated by amyloid-rich stroma. The endocrinologist recommends genetic testing of the patient’s family to determine risk for the development of similar tumors. Testing for a germline mutation of which of the following genes is most relevant?`,
        q2: ``,
        q3: [],
        option: [`MEN 1`, ` RET`,`AIRE`,`MYCN`,`CCND1 (encoding cyclin D1)`],
        optionFeedback: [`MEN-1 mutations cause multiple endocrine neoplasia syndrome type 1. Organs most commonly involved in this syndrome are the “three Ps”: parathyroid (hyperplasia and adenomas causing hyperparathyroidism), pancreas (including gastrin- and insulin-producing tumors, causing Zollinger-Ellison syndrome and hypoglycemia, respectively), and pituitary (most often a prolactin-secreting microadenoma).`,`Nests of tumor cells separated by stromal amyloid are characteristic of medullary carcinoma of the thyroid which is derived from parafollicular C cells that secrete calcitonin. Multifocal medullary carcinoma is a part of the multiple endocrine neoplasia syndrome type 2A (MEN-2A), which is caused by gain-of-function mutations in the RET tyrosine kinase and is characterized by medullary thyroid carcinoma, adrenal pheochromocytoma, and parathyroid hyperplasia. Hypertension in this case may be a manifestation of pheochromocytoma.`,`AIRE mutations are the cause of autoimmune polyendocrine syndrome (APS-1), which causes deficiency of multiple endocrine glands but not tumors.`,`MYCN amplification is seen as an acquired abnormality in neuroblastoma.`,`Acquired cyclin D mutations are found in certain lymphomas, breast cancers, and parathyroid adenomas, but do not occur in thyroid tumors.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Nests of tumor cells separated by stromal amyloid are characteristic of medullary carcinoma of the thyroid which is derived from parafollicular C cells that secrete calcitonin. Multifocal medullary carcinoma is a part of the multiple endocrine neoplasia syndrome type 2A (MEN-2A), which is caused by gain-of-function mutations in the RET tyrosine kinase and is characterized by medullary thyroid carcinoma, adrenal pheochromocytoma, and parathyroid hyperplasia. Hypertension in this case may be a manifestation of pheochromocytoma.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 26-year-old man developed sudden severe abdominal pain. On physical examination, he had marked abdominal tenderness and guarding. Laboratory studies showed serum glucose, 76 mg/dL (fasting, 70–110 mg/dL); calcium, 12.2 mg/dL (8.4–10.2 mg/dL); phosphorus, 2.6 mg/dL (3.0–4.5 mg/dL); creatinine, 1.1 mg/dL (0.6–1.2 mg/dL); and elevated serum parathyroid hormone level. During surgery, four enlarged parathyroid glands were found and excised, with reimplantation of one half of one gland and his serum calcium concentration returned to normal. Three years later, he had an episode of upper gastrointestinal hemorrhage. Endoscopy with biopsy revealed multiple benign gastric ulcerations. Abdominal MRI indicated several 1- to 2-cm mass lesions in the pancreas. At surgery, multiple tumors were found. Which of the following additional tumors is he most likely to develop?`,
        q2: ``,
        q3: [],
        option: [` Adrenal pheochromocytoma`, `Adrenal cortical adenoma`,`Pituitary adenoma`,`Pulmonary small cell carcinoma`,`Thyroid medullary carcinoma`],
        optionFeedback: [`Adrenal pheochromocytoma is associated with MEN-2B.`,`Adrenal adenoma is not a part of any of the MEN syndromes.`,`This patient has MEN-1 syndrome. Organs most commonly involved are the “three Ps”: parathyroids (hyperplasia and adenomas causing hyperparathyroidism), pancreas (including gastrin- and insulin-producing tumors, causing Zollinger-Ellison syndrome and hypoglycemia, respectively), and pituitary (most often a prolactin-secreting microadenoma).`,`Small cell carcinomas of the lung can produce hypercalcemia by secreting PTH-related protein but do not exhibit the other clinical features.`,`Medullary carcinoma of thyroid may be associated with MEN-2A or MEN-2B, but not MEN-1.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- This patient has MEN-1 syndrome. Organs most commonly involved are the “three Ps”: parathyroids (hyperplasia and adenomas causing hyperparathyroidism), pancreas (including gastrin- and insulin-producing tumors, causing Zollinger-Ellison syndrome and hypoglycemia, respectively), and pituitary (most often a prolactin-secreting microadenoma).`,
        state: `notAnswered`,
        userAnswered: [],
    }
    

   ];
