var quiz = [
    {
        q: `A 36-year-old woman has had increasing malaise for 3 weeks and urine output &lt;500 mL/day for the past 4 days. On examination, she has a blood pressure 170/112 mm Hg and peripheral edema. Urinalysis shows 1+ protein and 3+ blood, and no glucose or ketones. Urine microscopic examination shows red cells (RBCs) and RBC casts. The blood urea nitrogen is 39 mg/dL (7–18 mg/dL), the creatinine is 4.3 mg/dL (0.6–1.2 mg/dL), and antinuclear antibodies (ANA) are positive. The serum complement C1q, C3, and C4 are decreased. A renal biopsy is performed, and immunofluorescence microscopy shows the pattern of staining with antibody to C3 seen in the figure. Which of the following mechanisms is most likely the cause of her renal disease?`,
        q2: `<img src="../images/f011-q001-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Deposition of antiphospholipid antibodies on the basement membrane`, `Deposition of antistreptococcal antibodies that cross-react with glomerular basement membrane (GBM)`, `Deposition of complexes comprised of DNA and anti-DNA antibodies `,`Deposition of complexes comprised of histones and antihistone antibodies `,`Deposition of antibodies that cross-react with alveolar basement membrane`],
        optionFeedback: [`Antiphospholipid antibodies are also produced in systemic lupus erythematosus and cause coagulation abnormalities but they do not deposit in the glomerulus. `,`Antistreptococcal antibodies bind to streptococcal antigens deposited in the GBM or form circulating immune complexes that deposit in the glomerulus (post-streptococcal glomerulonephritis). While some antistreptococcal antibodies cross-react with myocardial antigens, causing rheumatic fever, there are no known antistreptococcal antibodies that cross react with GBM antigens `,`The staining pattern is granular, characteristic of the deposition of immune complexes. The clinical history and laboratory findings are strongly suggestive of lupus nephritis (renal disease associated with systemic lupus erythematosus). The most common autoantibodies in these patients are anti-DNA antibodies. `,`In systemic lupus erythematosus (SLE), autoantibodies against numerous nucleoproteins are more common than those that react with histones. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The staining pattern is granular, characteristic of the deposition of immune complexes. The clinical history and laboratory findings are strongly suggestive of lupus nephritis (renal disease associated with systemic lupus erythematosus). The most common autoantibodies in these patients are anti-DNA antibodies. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 7-year-old boy is recovering from impetigo. Physical examination shows five honey-colored crusts on his face. The crusts are removed, and a culture of the lesions grows Streptococcus pyogenes.  He is treated with antibiotics. One week later, he develops malaise with nausea and a slight fever and passes dark brown urine with RBC casts. Laboratory studies show a serum anti–streptolysin O titer of 1:1024. Which of the following is the most likely outcome of his renal disease?`,
        q2: ``,
        q3: [],
        option: [`Chronic renal failure`, `Complete recovery`,`Acute renal failure`,`Rheumatic heart disease`,`Streptococcal urinary tract infection`],
        optionFeedback: [`Chronic renal failure would present with progressive loss of kidney function and not evidence of acute inflammation or injury. It is a rare outcome of this disease in children as opposed to adults, one third of whom develop chronic renal disease.`,`The kidney disease is characteristic of an acute nephritic syndrome (microscopic hematuria and systemic manifestations of acute inflammation). The streptococcal infection preceding the renal disease and the presence of antistreptococcal antibody are consistent with acute poststreptococcal glomerulonephritis. More than 95% of affected children recover completely in weeks to months. A small minority of children (perhaps fewer than 1%) do not improve, become severely oliguric, and develop a rapidly progressive form of glomerulonephritis. `,`The characteristic feature of acute renal failure is sudden loss of renal function manifested by increased serum creatinine and, often, oliguria. It is a rare outcome in children with this disorder.`,`Rheumatic heart disease is also a sequela of streptococcal infection, but it affects the heart and not the kidneys. The streptococci that cause rheumatic fever are of different subtypes than those that cause renal disease. In addition, prompt antibiotic therapy usually prevents the development of rheumatic heart disease (although not glomerulonephritis).`,``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale:-  The kidney disease is characteristic of an acute nephritic syndrome (microscopic hematuria and systemic manifestations of acute inflammation). The streptococcal infection preceding the renal disease and the presence of antistreptococcal antibody are consistent with acute poststreptococcal glomerulonephritis. More than 95% of affected children recover completely in weeks to months. A small minority of children (perhaps fewer than 1%) do not improve, become severely oliguric, and develop a rapidly progressive form of glomerulonephritis. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 45-year-old man has experienced increasing malaise, nausea, and reduced urine output for the past 3 days. On physical examination, he is afebrile and normotensive. Laboratory findings show a serum creatinine level of 7.5 mg/dL (0.6–1.2 mg/dL). Urinalysis shows hematuria, but no pyuria or glucosuria. A renal biopsy is done; the light microscopic picture is shown in the figure. Which of the following additional laboratory studies is most likely to be useful for classification and treatment of this disease?`,
        q2: `<img src="../images/f011-q004-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Antinuclear antibody titer`, `Antiglomerular basement membrane antibody`,`HIV-1 RNA copy level`,`Quantitative serum immunoglobulins`,`Rheumatoid factor`],
        optionFeedback: [`Antinuclear antibodies are seen in lupus and other autoimmune diseases. Lupus nephritis does not present as crescentic glomerulonephritis with acute renal failure. `,`The acute presentation of oliguria and renal failure, and the histologic appearance of crescentic glomerulonephritis, are characteristic of rapidly progressive glomerulonephritis (RPGN). This clinical syndrome has numerous possible underlying causes, the most common of which is Goodpasture syndrome, which is associated with the deposition of anti-GBM antibody in the glomerulus in a linear immunofluorescence pattern. `,`Immune-complex glomerulonephritis is a rare complication of HIV disease. It does not usually present as crescentic glomerulonephritis.  HIV disease is typically associated with focal sclerosing glomerulosclerosis  `,`Measurements of total serum immunoglobulin would not be helpful for the diagnosis.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The acute presentation of oliguria and renal failure, and the histologic appearance of crescentic glomerulonephritis, are characteristic of rapidly progressive glomerulonephritis (RPGN). This clinical syndrome has numerous possible underlying causes, the most common of which is Goodpasture syndrome, which is associated with the deposition of anti-GBM antibody in the glomerulus in a linear immunofluorescence pattern.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 21-year-old previously healthy man has noticed blood in his urine for the past 2 days. He reports no dysuria, frequency, or hesitancy of urination. On physical examination, there are no abnormal findings. Laboratory findings show a blood urea nitrogen level of 39 mg/dL (7–18 mg/dL) and creatinine level of 4.1 mg/dL (0.6–1.2 mg/dL). A renal biopsy specimen is obtained; the immunofluorescence pattern of staining with antibody against human IgG is shown in the figure. Which of the following therapeutic measures is most likely to be beneficial in this case?`,
        q2: `<img src="../images/f011-q005-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Plasma exchange `,`Antibiotic administration`,`Anti-tumor necrosis factor (TNF) infusion`,`Hepatitis B vaccine`,`HIV antibody infusion`],
        optionFeedback: [`The acute onset of hematuria and evidence of renal failure suggests nephritis, and the immunofluorescence staining pattern is indicative of deposition of anti-GBM antibody. This individual most likely has a form of rapidly progressive glomerulonephritis (RPGN). In severe cases, removal of the antibody from the blood by plasmapheresis is required to alleviate the acute renal failure. Chronic immunosuppression will be needed to suppress autoantibody production. `,`The lesion is not caused by an infection and is not diagnostic of acute postinfectious glomerulonephritis (GN), which is characterized by immune complex deposition in a granular immunofluorescence pattern. Antibiotics would not help even in postinfectious GN because the infection would have already resolved, and the renal lesions are not caused by ongoing infection. `,`Anti-TNF therapy is helpful for rheumatoid arthritis, inflammatory bowel disease, and other autoimmune diseases in which T cell–mediated inflammation is prominent. `,`Hepatitis vaccine is preventive, not therapeutic. Renal involvement is not common in hepatitis; when it occurs, it is caused by deposition of immune complexes in a granular pattern. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The acute onset of hematuria and evidence of renal failure suggests nephritis, and the immunofluorescence staining pattern is indicative of deposition of anti-GBM antibody. This individual most likely has a form of rapidly progressive glomerulonephritis (RPGN). In severe cases, removal of the antibody from the blood by plasmapheresis is required to alleviate the acute renal failure. Chronic immunosuppression will be needed to suppress autoantibody production.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 44-year-old woman has developed a fever, nonproductive cough, and decreased urine output over the past 3 days. On physical examination, her temperature is 37.7&#176; C and blood pressure is 145/95 mm Hg. She has had chronic sinusitis. On auscultation, crackles are heard over all lung fields. A chest radiograph shows bilateral patchy infiltrates and nodules. The serum creatinine level is 4.1 mg/dL (0.6–1.2 mg/dL), and the blood urea nitrogen level is 43 mg/dL (7–18 mg/dL). The results of serologic testing are negative for ANA, but positive for PR3-ANCA (c-ANCA). A renal biopsy specimen shows glomerular crescents and damage to small arteries. The result of immunofluorescence staining with anti-IgG and anti-C3 antibodies is negative. Which of the following additional microscopic findings is most likely to be seen in this biopsy?`,
        q2: ``,
        q3: [],
        option: [`Focal segmental glomerulosclerosis (FSGS) `,` Glomerular basement membrane (GBM) thickening`,`Hyperplastic arteriolosclerosis`,`Infiltration by T cells`,`Necrotizing granulomatous vasculitis`],
        optionFeedback: [`FSGS typically presents with nephrotic syndrome and shows focal and segmental glomerular sclerosis, not crescents. `,`GBM thickening is a nonspecific finding associated with several diseases, all of which present with the nephrotic syndrome.`,`Hyperplastic arteriolosclerosis is seen in malignant hypertension.`,`T-cell infiltrates are common in tubulointerstitial nephritis but are not common in vasculitis-associated RPGN.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Acute onset of renal failure suggests nephritis. The renal biopsy shows crescentic glomerulonephritis (GN), a classical histologic manifestation of rapidly progressive GN (RPGN). One of the causes of RPGN is vasculitis; the finding of small arterial damage supports this diagnosis. The involvement of the lungs and sinuses is consistent with a systemic necrotizing granulomatous vasculitis referred to as polyangiitis with granulomatosis (previously called Wegener disease), which often involves the kidneys.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 48-year-old man has had increased swelling in the extremities for 2 months. Physical examination showed generalized edema. A 24-hour urine collection yielded 4.1 g (&lt;150 mg/24 h) of protein. Laboratory studies now show serum creatinine level of 4.5 mg/dL (0.6-1.2 mg/dL) and blood urea nitrogen level of 44 mg/dL (7-18 mg/dL). A renal biopsy was done, and microscopic examination showed diffuse thickening of the basement membrane. Immunofluorescence staining with antibody to the C3 component of complement was positive in a granular pattern in the glomerular capillary loops. He did not respond to a course of corticosteroid therapy. Which of the following immunologic mechanisms is most likely responsible for the glomerular changes observed in the biopsy specimen?`,
        q2: ``,
        q3: [],
        option: [`Formation of antibodies against basement membrane collagen`,`Formation of antibodies against streptococci that cross-react with the basement membrane`,`Development cytotoxic T cells directed against renal antigens`,`Deposition of immune complexes on the basement membrane`,`Release of prostaglandins by inflammatory cells`],
        optionFeedback: [`Anti-glomerular basement membrane antibody is deposited in a linear pattern and patients develop rapidly progressive glomerulonephritis.`,`Antistreptococcal antibodies form immune complexes that may be deposited in glomeruli. Antibodies that cross-react with streptococci are usually reactive with myocardial antigens and are the cause of rheumatic fever. `,`There are no known examples of renal disease caused by cytotoxic T lymphocytes (CTLs) reacting against renal antigens.`,`The immunofluorescence staining pattern is diagnostic of immune complex deposition, with subsequent activation of complement at the sites of deposition. The clinical presentation is of the nephrotic syndrome (proteinuria) accompanied by the development of mild renal failure. This presentation and lack of therapeutic response to steroids are characteristic of membranous nephropathy.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The immunofluorescence staining pattern is diagnostic of immune complex deposition, with subsequent activation of complement at the sites of deposition. The clinical presentation is of the nephrotic syndrome (proteinuria) accompanied by the development of mild renal failure. This presentation and lack of therapeutic response to steroids are characteristic of membranous nephropathy.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 7-year-old boy has become less active over the past 10 days. On physical examination, he has facial puffiness. Urinalysis shows no blood, glucose, or ketones, and microscopic examination shows no casts or crystals. The serum creatinine level is normal. A 24-hour urine collection yields 3.8 g of protein (&lt;150 mg/24 h), primarily of low molecular weight. He improves after corticosteroid therapy. He has more episodes of proteinuria over the next 4 years, which respond to corticosteroid therapy. A renal biopsy is performed. Which of the following is the most likely alteration in the glomeruli by light microscopy?`,
        q2: ``,
        q3: [],
        option: [`Diffuse basement membrane thickening`,` No abnormality`,`Diffuse increase in cellularity`,`Focal sclerosis `,`Hyalinization`],
        optionFeedback: [`Diffuse basement thickening is caused by the deposition of immune complexes in the glomerular basement membrane, and is characteristic of membranous nephropathy. This disease also causes the nephrotic syndrome, but it is more common in adults and much less responsive to steroid therapy. `,`The clinical presentation is of the nephrotic syndrome. In children, the most common cause is minimal change disease, which is characterized by normal glomerular histology (as the name of the disease implies). This disease responds well to steroid therapy. The “selective” proteinuria (preferential loss of small proteins) distinguishes this disease from most other causes of the nephrotic syndrome, in which larger proteins are also often lost. `,`Diffuse glomerular hypercellularity is a reflection of inflammation and proliferation of intrinsic glomerular cells. It is most often seen in postinfectious glomerulonephritis and lupus nephritis, both caused by extensive immune complex deposition in the glomerulus. `,`Focal sclerosis is seen in focal segmental glomerulosclerosis, which also causes nephrotic syndrome but is more common in adults, is more severe and in some cases leads to renal failure. The glomerular histology shows focal sclerosis involving portions of some, but not all glomeruli.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical presentation is of the nephrotic syndrome. In children, the most common cause is minimal change disease, which is characterized by normal glomerular histology (as the name of the disease implies). This disease responds well to steroid therapy. The “selective” proteinuria (preferential loss of small proteins) distinguishes this disease from most other causes of the nephrotic syndrome, in which larger proteins are also often lost. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 44-year-old man with increasing malaise for the past month now has noticed increasing swelling in the hands and legs. On physical examination, there is generalized edema. Urinalysis shows 4+ proteinuria and no blood, glucose, or ketones. Microscopic examination of the urine shows no casts or RBCs and 2 WBCs per high-power field. The 24-hour urine protein level is 4.2 g (&lt;150 mg/24 h). A renal biopsy specimen is obtained, and immunofluorescence staining with antibody to the C3 component of complement produces the pattern shown in the figure. Which of the following is the most likely mechanism of proteinuria?`,
        q2: `<img src="../images/f011-q009-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Injury by anti-glomerular basement membrane (GBM) antibodies`,`HIV infection`,`Injury by immune complexes`,`Mutations affecting type IV (basement membrane) collagen`,`Autoantibodies against complement protein 3`],
        optionFeedback: [`Anti-GBM antibodies typically cause rapidly progressive glomerulonephritis characterized by hematuria and some proteinuria, usually not large enough to cause nephrotic syndrome. Anti-GBM antibodies are deposited along the GBM giving rise to a linear pattern of staining.`,`The history is not typical for HIV, and HIV-associated renal involvement usually presents as FSGS.  `,`The clinical presentation (generalized edema caused by loss of protein in the urine) is typical for nephrotic syndrome, and the granular staining pattern of C3 deposition is diagnostic for membranous nephropathy. Immune complexes deposited in the glomeruli disrupt glomerular permeability by damaging podocytes and the GBM.  `,`Mutations affecting basement membrane collagen are the cause of hereditary nephritis (Alport syndrome), which typically presents with hematuria and does not show immune complex deposition.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The clinical presentation (generalized edema caused by loss of protein in the urine) is typical for nephrotic syndrome, and the granular staining pattern of C3 deposition is diagnostic for membranous nephropathy. Immune complexes deposited in the glomeruli disrupt glomerular permeability by damaging podocytes and the GBM.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 6-year-old girl has become increasingly lethargic over the past 2 weeks. On examination she has puffiness around the eyes. Her temperature is 36.9&#176; C, and blood pressure is 100/60 mm Hg. Laboratory findings show serum creatinine, 0.7 mg/dL (0.6-1.2 mg/dL); blood urea nitrogen, 12 mg/dL(7-18 mg/dL); and cholesterol, 217 mg/dL (&lt;170 mg/dL). Urinalysis shows 4+ proteinuria, lipiduria, and no blood or glucose. The 24-hour urine protein level is 3.8 g (&lt;150 mg/24 h). The child’s condition improves after glucocorticoid therapy. Which of the following findings by electron microscopy is most likely to characterize this disease process?`,
        q2: ``,
        q3: [],
        option: [`Diffusely thickened basement membrane`,`Effacement of podocyte foot processes`,`Increased mesangial matrix`,` Reduplication of glomerular basement membrane (GBM)`,`Subepithelial electron-dense humps`],
        optionFeedback: [`Diffuse basement membrane thickening is seen in membranous nephropathy, which is a more frequent cause of nephrotic syndrome in adults and does not usually respond to steroids. `,`In a child with steroid-responsive nephrotic syndrome, the likely diagnosis is minimal change disease. The only electron microscopic abnormality in these cases is effacement of podocyte foot processes, a change that is often seen in association with proteinuria caused by glomerular permeability abnormalities. `,`Increased mesangial matrix is typical of diabetic nephropathy, in which matrix material is deposited in the mesangium and glomerular capillary walls, and membranoproliferative glomerulonephritis, which is associated with immune complex deposition. Both may present with nephrotic syndrome, usually in adults. `,`“Reduplication” or splitting of the GBM is seen in membranoproliferative glomerulonephritis. It is caused by mesangial cells and matrix material inserting into the capillary wall. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- In a child with steroid-responsive nephrotic syndrome, the likely diagnosis is minimal change disease. The only electron microscopic abnormality in these cases is effacement of podocyte foot processes, a change that is often seen in association with proteinuria caused by glomerular permeability abnormalities.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 25-year-old man has experienced increasing malaise for the past 2 weeks. On physical examination, he has periorbital edema. Urine examination shows 3+ proteinuria, but no hematuria or glucosuria. The serum creatinine level is 2.3 mg/dL (0.6-1.2 mg/dL). He receives a course of corticosteroid therapy but does not improve. A renal biopsy is performed. Microscopic examination shows that approximately 50% of the glomeruli are affected by the lesion shown in the figure. Which of the following laboratory tests will most likely be abnormal in this case?`,
        q2: `<img src="../images/f011-q011-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Anti-dsDNA antibody titer`,`Serum complement 3 (C3) level`,`HbA1c level`,`Serologic test for HIV`,`Antistreptolysin O titer`],
        optionFeedback: [`Anti-dsDNA antibody is diagnostic of systemic lupus erythematosus.`,`Serum C3 is reduced in immune-complex diseases, such as systemic lupus erythematosus and poststreptococcal glomerulonephritis.`,`HbA1c is used to diagnose diabetes. One of the presentations of diabetic nephropathy is also nephrotic syndrome, but the histologic picture is completely different and is characterized by hyaline arteriolosclerosis, diffuse thickening of the basement membrane, diffuse mesangial sclerosis and nodular glomerulosclerosis (Kimmelstiel-Wilson disease).`,`The clinical presentation is of the nephrotic syndrome (proteinuria and edema), and the biopsy shows the classical features of focal segmental glomerulosclerosis (FSGS). Focal refers to involvement of only a fraction of glomeruli and segmental to involvement of only a portion of the glomerulus. Although this disease is usually primary (idiopathic), it may be associated with HIV infection. Of the choices provided, HIV has the strongest association with FSGS.  `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The clinical presentation is of the nephrotic syndrome (proteinuria and edema), and the biopsy shows the classical features of focal segmental glomerulosclerosis (FSGS). Focal refers to involvement of only a fraction of glomeruli and segmental to involvement of only a portion of the glomerulus. Although this disease is usually primary (idiopathic), it may be associated with HIV infection. Of the choices provided, HIV has the strongest association with FSGS.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 38-year-old woman has been feeling lethargic for 4 months. On physical examination, she is afebrile, and her blood pressure is 140/90 mm Hg. Laboratory findings show the serum creatinine level is 5.8 mg/dL (0.6-1.2 mg/dL). Antinuclear antibody (ANA) tests are negative. Urinalysis shows 2+ blood and 1+ protein. A renal biopsy is performed; microscopic examination shows hypercellular glomeruli and prominent ribbon-like deposits along the lamina densa of the glomerular basement membrane. Which of the following antibodies is most likely to be present in the serum of this patient?`,
        q2: ``,
        q3: [],
        option: [`C3 nephritic factor (autoantibody against C3 convertase)`,`Antibodies against hepatitis B core (HBc) antigen`,`Anti-HIV antibodies`,`Monoclonal IgG antibodies`,`Antiphospholipid antibodies`],
        optionFeedback: [`The clinical picture is that of a mixed nephritic-nephrotic syndrome (increased serum creatinine and proteinuria). The glomerular histology is characteristic of dense deposit disease, one of the C3 glomerulopathies. In these diseases, there is uncontrolled activation of the complement system, most often caused by an autoantibody that stabilizes C3 convertase. Inherited mutations in complement regulatory proteins may result in the same abnormalities. `,`Renal involvement associated with viral hepatitis is uncommon; when it does occur, it usually presents as an immune complex disease.`,`HIV-associated renal disease usually presents as FSGS`,`Monoclonal IgG antibodies are seen in myeloma. Myeloma is associated with tubulointerstitial disease with protein casts (composed of the light chains of immunoglobulins) in tubules and an associated interstitial inflammation. Glomerular involvement may be seen in the form of amyloid deposition, which does not produce inflammation or hypercellular glomeruli. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The clinical picture is that of a mixed nephritic-nephrotic syndrome (increased serum creatinine and proteinuria). The glomerular histology is characteristic of dense deposit disease, one of the C3 glomerulopathies. In these diseases, there is uncontrolled activation of the complement system, most often caused by an autoantibody that stabilizes C3 convertase. Inherited mutations in complement regulatory proteins may result in the same abnormalities. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 25-year-old man has a 5-year history of gluten sensitivity. Four days after a mild upper respiratory infection, he begins passing dark red-brown urine. The dark urine persists for the next 3 days and then becomes clear and yellow, only to become red-brown again 1 month later. There are no remarkable findings on physical examination. Urinalysis shows 3+ hematuria; 1+ proteinuria; and no glucose or ketones. Microscopic examination of the urine shows RBCs, but no WBCs, casts, or crystals. A 24-hour urine protein level is 200 mg (&lt;150 mg/24 h). A renal biopsy is most likely to show which of the following alterations in the glomeruli?`,
        q2: ``,
        q3: [],
        option: [`Diffuse cellular proliferation and basement membrane thickening`,`Granular staining of the basement membrane by anti-IgG antibodies`,`Mesangial IgA staining by immunofluorescence`,`Subepithelial electron-dense deposits`,`Focal hyalinization within individual glomeruli`],
        optionFeedback: [`Glomerular hypercellularity along with GBM thickening is seen in immune-complex diseases, typically lupus nephritis, and some other forms of immune-complex glomerulonephritis. In this and other immune complex diseases, the antibody is most often IgG, and never IgA.    `,`Granular staining of the GBM indicating deposition of IgG (and C3) is diagnostic of immune-complex diseases. `,`Recurrent hematuria is a characteristic feature of IgA nephropathy, in which complexes of IgA and anti-IgA are deposited in the mesangium. There is often an association with celiac disease (gluten sensitivity). `,`Subepithelial deposits indicate immune complexes. This location of deposits is most often seen in poststreptococcal glomerulonephritis. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Recurrent hematuria is a characteristic feature of IgA nephropathy, in which complexes of IgA and anti-IgA are deposited in the mesangium. There is often an association with celiac disease (gluten sensitivity). `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `One week after a mild flu-like illness, a 9-year-old boy has an episode of hematuria that subsides within 2 days. One month later, he tells his parents that his urine is red again. On physical examination, there are no significant findings. Urinalysis shows 1+ proteinuria; 1+ hematuria; and no ketones, glucose, or urobilinogen. The blood urea nitrogen level is 36 mg/dL (7-18 mg/dL), and the creatinine level is 3.2 mg/dL (0.6-1.2 mg/dL). Which of the following abnormalities is most likely to initiate this disease?`,
        q2: ``,
        q3: [],
        option: [`Autoantibodies against C3 convertase`,`Abnormal glycosylation of IgA`,`Escherichia coli –mediated injury of capillary endothelium`,`Immune complex-mediated podocyte injury`,`Deficiency of ADAMTS13 protease`],
        optionFeedback: [`Anti-C3 convertase antibodies are seen in C3 glomerulopathy, which presents with the nephrotic syndrome or a mixed nephrotic-nephritic clinical pattern, most often progressing to renal failure. `,`The appearance of recurrent microscopic hematuria and mild renal failure following upper respiratory infection is suggestive of IgA nephropathy. The glomeruli would contain mesangial deposits composed of IgA and IgG autoantibody against IgA.   The postulated mechanism is abnormal glycosylation of IgA, causing the altered IgA to be recognized as foreign and eliciting an IgG autoantibody response. `,`Endothelial damage by bacterial toxins is the postulated mechanism of one form of thrombotic microangiopathy, hemolytic uremic syndrome (HUS). These are more severe diseases in which patients present with sudden onset of renal failure, hematuria, bleeding problems, and hemolytic anemia. The morphologic picture is dominated by thrombi in glomerular capillaries and small vessels. `,`Immune complex–mediated podocyte injury results in the nephrotic syndrome, which is not this patient’s presentation.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The appearance of recurrent microscopic hematuria and mild renal failure following upper respiratory infection is suggestive of IgA nephropathy. The glomeruli would contain mesangial deposits composed of IgA and IgG autoantibody against IgA.   The postulated mechanism is abnormal glycosylation of IgA, causing the altered IgA to be recognized as foreign and eliciting an IgG autoantibody response. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 15-year-old boy has been passing dark-colored urine for the past month. On physical examination, he has bilateral sensorineural hearing loss and corneal erosions. Urinalysis shows 1+ hematuria, 1+ proteinuria, and no ketones, glucose, or leukocytes. The serum creatinine level is 2.5 mg/dL (0.6-1.2 mg/dL), and the blood urea nitrogen level is 24 mg/dL (7-18 mg/dL). By electron microscopy, the glomerular basement membrane (GBM) shows areas of attenuation, with splitting and lamination of lamina densa in other thickened areas. Which of the following is the most likely underlying cause of this disease?`,
        q2: ``,
        q3: [],
        option: [` Mutation in a gene encoding type IV collagen`,`Increased synthesis of abnormal IgA`,`Mutations affecting primary cilia of renal tubular epithelium`,`Acquired deficiency of ADAMTS13 metalloprotease`,`Vesicoureteral reflux`],
        optionFeedback: [`Microscopic hematuria associated with hearing loss is typical of hereditary nephritis (Alport syndrome). The electron microscopic appearance of the glomeruli is diagnostic, and is caused by an inherited structural abnormality in basement membrane collagen (type IV collagen). `,`An IgA abnormality is the cause of IgA nephropathy, which also presents with microscopic hematuria but without hearing loss or the characteristic GBM structural abnormalities.`,`Ciliary abnormalities are the cause of cystic diseases of the kidney, which do not show GBM defects.`,`Deficiency of this protease is the cause of thrombotic thrombocytopenic purpura (TTP), in which microscopic thrombi are seen in glomerular capillaries and small vessels.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Microscopic hematuria associated with hearing loss is typical of hereditary nephritis (Alport syndrome). The electron microscopic appearance of the glomeruli is diagnostic, and is caused by an inherited structural abnormality in basement membrane collagen (type IV collagen).  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An autopsy study is performed involving persons with gross pathologic findings of bilaterally small kidneys (&lt;100 g) that have a coarsely granular surface appearance. Microscopic examination shows sclerotic glomeruli, a fibrotic interstitium, tubular atrophy, arterial thickening, and scattered lymphocytic infiltrates. Which of the following clinical findings was most likely reported in these patients’ medical histories?`,
        q2: ``,
        q3: [],
        option: [`Hemoptysis`,`Hypertension`,`Lens dislocation`,`Pharyngitis`,`Skin rash`],
        optionFeedback: [`Hemoptysis may occur in patients who have anti-GBM antibodies that cross-react with basement membrane of pulmonary alveoli (Goodpasture syndrome). The renal injury is acute, and the clinical course is rapidly progressive. The kidney does not show fibrosis. `,`The histology is characteristic of “benign” nephrosclerosis, a disease associated with long-standing hypertension. The renal changes are caused by narrowing of small arteries and arterioles, leading to ischemic damage of the glomeruli and tubules and interstitial scarring (fibrosis). `,`Lens dislocation is a manifestation of a genetic disease of connective tissues, Marfan syndrome, which is associated with aortic, cardiac and skeletal abnormalities but not renal disease.`,`Pharyngitis is a sign of infection (e.g., with streptococci) and may be an antecedent of acute poststreptococcal glomerulonephritis, which presents with nephritis and glomerular lesions caused by immune complex deposition.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The histology is characteristic of “benign” nephrosclerosis, a disease associated with long-standing hypertension. The renal changes are caused by narrowing of small arteries and arterioles, leading to ischemic damage of the glomeruli and tubules and interstitial scarring (fibrosis). `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 33-year-old woman has had fever and increasing fatigue for the past 2 months. Over the past year, she has noticed soreness of her muscles and joints and has had a 4-kg weight loss. On physical examination, she has pain on deep inspiration, and a friction rub is heard on auscultation of the chest. Laboratory findings show fasting serum glucose 73mg/dL (70-110 mg/dL), total protein, 5.2 g/dL (6.0-7.8 g/dL); albumin, 2.9 g/dL (3.5-5.5 g/dL); and creatinine, 2.4 mg/dL (0.6-1.2 mg/dL). Serum complement levels are decreased. CBC shows hemoglobin of 9.7 g/dL (12.0-16.0 g/dL), platelet count of 85,000/mm<sup>3</sup> (150,000-400,000/mm<sup>3</sup>) and WBC count of 3,560/mm<sup>3 </sup>(4,500-11,000/mm<sup>3</sup>). A renal biopsy specimen shows diffuse proliferative glomerulonephritis with extensive granular immune deposits of IgG and C3 in capillary loops and mesangium. After treatment with immunosuppressive therapy consisting of prednisone and cyclophosphamide, her condition improves. Which of the following serologic studies is most likely to be positive in this patient?`,
        q2: ``,
        q3: [],
        option: [`Anticentromere antibody`,`Anti–DNA topoisomerase I antibody`,`Anti–double-stranded DNA antibody`,`Antiglomerular basement membrane antibody`,` Antihistone antibody`],
        optionFeedback: [`Antibodies reactive with centromeres are more common in systemic sclerosis.`,`Antibodies reactive with DNA topoisomerase are more common in systemic sclerosis.`,`This presentation of a systemic illness with arthritis and pleuritis is characteristic of systemic lupus erythematosus (SLE). Laboratory findings that support this diagnosis include reduced serum albumin (caused by proteinuria), increased creatinine (mild renal failure), reduced C3 (complement consumption), and pancytopenia (possibly caused in part by antibody-mediated destruction of blood cells). The renal biopsy shows the features of the most common and severe form of lupus nephritis. The most characteristic serologic finding in SLE is the presence of antibodies against double-stranded DNA.    `,`Anti-GBM antibody is seen in cases of glomerulonephritis  (GN) with linear antibody deposition; the most common clinical presentation is rapidly progressive GN (crescentic GN).`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- This presentation of a systemic illness with arthritis and pleuritis is characteristic of systemic lupus erythematosus (SLE). Laboratory findings that support this diagnosis include reduced serum albumin (caused by proteinuria), increased creatinine (mild renal failure), reduced C3 (complement consumption), and pancytopenia (possibly caused in part by antibody-mediated destruction of blood cells). The renal biopsy shows the features of the most common and severe form of lupus nephritis. The most characteristic serologic finding in SLE is the presence of antibodies against double-stranded DNA.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 63-year-old man is in stable condition after an acute myocardial infarction, which produced a 3-hour period of hypotension before paramedical personnel arrived. Over the next week, the blood urea nitrogen level increases to 48 mg/dL (7-18 mg/dL), the serum creatinine level increases to 5 mg/dL (0.6-1.2 mg/dL), and the urine output decreases. He undergoes hemodialysis for the next 2 weeks and then develops marked polyuria, with urine output of 2 to 3 L/day. His renal function gradually returns to normal. Which one of the following morphologic alterations is most likely to have contributed to this clinical picture?`,
        q2: ``,
        q3: [],
        option: [`Necrosis of glomeruli`,` Necrosis of tubular epithelium`,`Renal papillary necrosis`,`Atherosclerosis of renal arteries`,`Renal infarcts`],
        optionFeedback: [`Necrosis of glomeruli is seen in some primary glomerular diseases (FSGS, sometimes in crescentic glomerulonephritis ) but is not a consequence of hypotension because glomeruli are much less sensitive to hypoxia than are tubules. `,`Acute renal failure developing after a hypotensive episode is classic for the clinical syndrome of acute kidney injury (which pathologists call acute tubular injury). The typical lesion in severe cases is ischemic necrosis of tubules (which is why this disorder was previously called acute tubular necrosis). `,`Papillary necrosis is associated with severe acute pyelonephritis, especially in diabetics.`,`Atherosclerosis is associated with hypertension. It may be present in this case because the myocardial infarct is a result of coronary atherosclerosis. But renal atherosclerosis by itself does not cause acute oliguric renal failure. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Acute renal failure developing after a hypotensive episode is classic for the clinical syndrome of acute kidney injury (which pathologists call acute tubular injury). The typical lesion in severe cases is ischemic necrosis of tubules (which is why this disorder was previously called acute tubular necrosis). `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 19-year-old woman has had a fever and chills accompanied by right flank pain for the past 3 days. She has had two similar episodes during the past year. On physical examination, her temperature is 38.3&#176;C, her blood pressure is 152/94 mm Hg, and there is right costovertebral angle tenderness. Laboratory findings show a fasting serum glucose level of 77 mg/dL (70-110 mg/dL) and creatinine level of 1 mg/dL (0.6-1.2 mg/dL). Urinalysis shows no protein, RBCs, glucose, or ketones, but numerous WBCs are noted. Which of the following is the most useful test for diagnosis?`,
        q2: ``,
        q3: [],
        option: [` Antinuclear antibody`,` Plasma renin`,`Renal biopsy`,`Urine culture`,`Abdominal CT scan`],
        optionFeedback: [`Antinuclear antibody is detected in systemic lupus erythematosus, which would present with nephrotic syndrome or nephritis and would not show leukocytes in the urine.`,`Plasma renin is used to determine if hypertension has a renal cause.`,`Renal biopsy is performed in cases when the diagnosis cannot be made by less invasive tests. It is most often done in nephrotic or nephritic syndrome caused by glomerular lesions.`,`Fever and chills indicate systemic inflammation, and flank pain suggests a process involving the kidneys. Presence of leukocytes in the urine is diagnostic of pyelonephritis. Urine culture would be done to identify the causative organism (usually a coliform bacterial species) in order to initiate appropriate antibiotic therapy. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-Fever and chills indicate systemic inflammation, and flank pain suggests a process involving the kidneys. Presence of leukocytes in the urine is diagnostic of pyelonephritis. Urine culture would be done to identify the causative organism (usually a coliform bacterial species) in order to initiate appropriate antibiotic therapy.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 51-year-old woman has a 1-week history of dysuria and urinary frequency. On physical examination, her temperature is 38&#176;C, and she has pain on palpation over the left costovertebral angle. Laboratory findings show fasting glucose, 177 mg/dL (70-110 mg/dL); hemoglobin A<sub>1c</sub>, 9.8% (&lt; 6%); hemoglobin, 13.1 g/dL (12.0-15.2 gm/dL); platelet count, 232,200/mm<sup>3</sup> (150,000-400,000/mm<sup>3</sup>); and WBC count, 11,320/mm<sup>3</sup> (4,500-11,000/mm<sup>3</sup>). Urinalysis shows 2+ glucosuria; and no RBCs, protein, or ketones. Microscopic examination of the urine shows numerous WBCs, and a urine culture is positive for Escherichia coli.  Which of the following complications is most likely to develop in this patient?`,
        q2: ``,
        q3: [],
        option: [`Acute tubular necrosis`,`Crescentic glomerulonephritis`,`Hydronephrosis`,`Necrotizing papillitis`,`Renal calculi`],
        optionFeedback: [`Acute tubular injury usually results from hypotension or exposure to some toxins and is not typical of acute pyelonephritis in a diabetic.`,`Crescentic glomerulonephritis  is the histologic appearance of rapidly progressive glomerulonephritis, which presents with evidence of nephritic syndrome.`,`Hydronephrosis is caused by urinary tract obstruction and is usually detected radiologically.`,`The elevated hemoglobin A<sub>1c</sub> establishes the diagnosis of diabetes. Urinary symptoms and flank pain suggest acute pyelonephritis, which is confirmed by the finding of white cells in the urine and the positive urine culture. A serious complication in diabetics with pyelonephritis is papillary necrosis which can lead to acute renal failure; diabetic microvascular abnormalities predispose to this lesion. Passage of necrotic fragments of papillae can cause symptoms resembling the passage of renal calculi. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The elevated hemoglobin A<sub>1c</sub> establishes the diagnosis of diabetes. Urinary symptoms and flank pain suggest acute pyelonephritis, which is confirmed by the finding of white cells in the urine and the positive urine culture. A serious complication in diabetics with pyelonephritis is papillary necrosis which can lead to acute renal failure; diabetic microvascular abnormalities predispose to this lesion. Passage of necrotic fragments of papillae can cause symptoms resembling the passage of renal calculi.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 30-year-old woman has had increasing malaise with nocturia and polyuria for the past year. She has had a high fever for the past 3 days. On physical examination, her blood pressure is 170/95 mm Hg. Urinalysis shows 1+ proteinuria and numerous white blood cells. A renal ultrasound scan shows an enlarged right kidney with pelvic and calyceal enlargement and cortical thinning; the left kidney appears normal. A right-sided nephrectomy is performed, and grossly there are large irregular scars with underlying blunted calyces. Microscopic examination shows inflammatory infiltrates extending from the medulla to the cortex, with tubular destruction and extensive interstitial fibrosis. Lymphocytes, plasma cells, and neutrophils are abundant. Which of the following underlying conditions is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Polycystic kidney disease`,` Essential hypertension`,`Systemic lupus erythematosus`,` Vesicoureteral reflux`,`Drug-induced tubulointerstitial nephritis`],
        optionFeedback: [`Polycystic kidney disease presents with hematuria, hypertension, and progressive renal failure, not evidence of infection. Grossly, the kidneys are often massively enlarged and the parenchyma is almost entirely replaced by cysts. `,`In hypertension, there is interstitial fibrosis and loss of tubules, but this is caused by ischemia not chronic infection, so inflammatory infiltrates are not prominent and there are no white cells in the urine. `,`The main renal complication of systemic lupus erythematosus is glomerular disease; interstitial fibrosis and tubular atrophy are uncommon. `,`The history of frequent urination and fever suggests a urinary tract infection. The presence of white cells in the urine is diagnostic for pyelonephritis and the ultrasound image is consistent with a chronic lesion (loss of renal parenchyma). The histology of the nephrectomy specimen is diagnostic of chronic pyelonephritis. Vesicoureteral reflux is a major predisposing condition because it allows the retrograde passage of bacteria from the lower urinary tract to the kidneys. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The history of frequent urination and fever suggests a urinary tract infection. The presence of white cells in the urine is diagnostic for pyelonephritis and the ultrasound image is consistent with a chronic lesion (loss of renal parenchyma). The histology of the nephrectomy specimen is diagnostic of chronic pyelonephritis. Vesicoureteral reflux is a major predisposing condition because it allows the retrograde passage of bacteria from the lower urinary tract to the kidneys.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 29-year-old woman has had a fever and sore throat for the past 3 days. On physical examination, her temperature is 38&#176;C. The pharynx is erythematous and there is a yellowish tonsillar exudate. She is treated with ampicillin and recovers fully in 7 days. Two weeks later, she develops fever and a rash, and notices a slight decrease in urinary output. Her temperature is 37.7&#176;C, and there is a diffuse erythematous rash on the trunk and extremities. Urinalysis shows 1+ proteinuria, 1+ hematuria, and no glucose or ketones. Microscopic examination of the urine shows RBCs and WBCs, including eosinophils, but no casts or crystals. Which of the following is the most likely cause of her disease?`,
        q2: ``,
        q3: [],
        option: [`Deposition of immune complexes with streptococcal antigens`,`Formation of antibodies against glomerular basement membrane`,`Hematogenous dissemination of septic emboli`,`Hypersensitivity reaction to ampicillin`,`Renal tubular cell necrosis caused by bacterial toxins`],
        optionFeedback: [`Poststreptococcal glomerulonephritis involves glomeruli and causes hematuria, hypertension and variable proteinuria. WBCs in the urine are uncommon. A skin rash may be seen as part of acute streptococcal infection, but it is usually not present by the time renal symptoms appear. `,`Anti-glomerular basement membrane antibodies also cause nephritis (proteinuria, hematuria, renal failure); WBCs in the urine are uncommon.`,`Systemic emboli may lodge in the kidneys and cause renal infarction, which is manifested by hematuria. If the emboli are infected (as may occur in bacterial endocarditis) they may produce abscesses. There is no association with skin rash. `,`The onset of mild hematuria and proteinuria associated with skin rash following administration of ampicillin (and several other drugs) is strongly suggestive of a drug reaction, causing tubulointerstitial nephritis. (Skin rash is a frequent manifestation of drug hypersensitivity.) The presence of WBCs, especially eosinophils, in the urine supports this diagnosis. The confirmatory test is removal of the offending agent, which should lead to complete resolution. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The onset of mild hematuria and proteinuria associated with skin rash following administration of ampicillin (and several other drugs) is strongly suggestive of a drug reaction, causing tubulointerstitial nephritis. (Skin rash is a frequent manifestation of drug hypersensitivity.) The presence of WBCs, especially eosinophils, in the urine supports this diagnosis. The confirmatory test is removal of the offending agent, which should lead to complete resolution.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 72-year-old man with chronic arthritis has taken more than 3 g of analgesics per day, including phenacetin, aspirin, and acetaminophen, for the past 20 years. He now has slowly increasing malaise, nausea, and diminished mentation over a period of several months. On physical examination, his blood pressure is 156/92 mm Hg. Laboratory findings show blood urea nitrogen level of 68 mg/dL (7-18 mg/dL) and creatinine level of 7.1 mg/dL (0.6-1.2 mg/dL). Which of the following renal diseases is he most likely to develop?`,
        q2: ``,
        q3: [],
        option: [` Acute tubular injury`,` Chronic glomerulonephritis`,`Hydronephrosis`,`Renal cell carcinoma`,`Renal papillary necrosis`],
        optionFeedback: [`Acute tubular injury usually presents with sudden onset of renal failure with oliguria. `,`Chronic glomerulonephritis is a long-standing disorder with progressive loss of renal function and often hypertension but no history of prolonged analgesic use.`,`Hydronephrosis is enlargement of the calyces caused by urinary tract obstruction. It is identified radiologically. The clinical features reflect the primary disease that is causing obstruction. `,`Renal cell carcinoma presents with hematuria and a unilateral renal mass, or signs and symptoms attributable to spread of the tumor.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Chronic use of analgesics (especially phenacetin) is associated with a renal disease called analgesic nephropathy. Patients present with progressive renal failure, often associated with hypertension, as here. The constitutional symptoms are likely related to renal failure. Papillary necrosis is a common pathologic manifestation of analgesic nephropathy. The disease stabilizes or improves if analgesics are discontinued.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 63-year-old man has noted increasing back pain for 7 months. He has had three respiratory tract infections with Streptococcus pneumoniae  during the past year. On examination, he has pitting edema to his thighs. Laboratory studies show total serum protein, 9.6/dL (6.0-7.8 g/dL); albumin, 2.5 g/dL (3.5-5.5 g/dL); creatinine, 3 mg/dL (0.6-1.2 mg/dL); blood urea nitrogen, 28 mg/dL (7-18 mg/dL); and fasting glucose, 79 mg/dL (70-110 mg/dL). Urinalysis shows proteinuria of 4 g/24 h (&lt;150 mg/24 h), but no glucosuria or hematuria. Abdominal CT scan shows enlarged kidneys without cysts or masses; multiple well-circumscribed lytic lesions are noted in the vertebral column. A renal biopsy specimen stained with H&amp;E shows deposits of amorphous pink material within glomeruli, interstitium, and small arteries. Which of the following diseases is he most likely to have?`,
        q2: ``,
        q3: [],
        option: [`Analgesic nephropathy`,`ANCA-associated granulomatous vasculitis`,`Type 2 diabetes `,`Membranous nephropathy`,`Multiple myeloma`],
        optionFeedback: [`Analgesic nephropathy presents with tubulointerstitial nephritis with papillary necrosis.`,` ANCA- associated granulomatous vasculitis presents with acute onset of renal failure with fibrinoid necrosis of renal blood vessels.`,`Diabetic nephropathy also presents with nephrotic syndrome and glomerular hyaline deposits, but no deposits in the interstitium or vessels. Patients also show clinical and laboratory evidence of diabetes. `,`Membranous nephropathy is an immune complex glomerulonephritis that causes the nephrotic syndrome; there are no deposits in the interstitium or vessels. `,``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The back pain, bone lesions, and immunosuppressed state evidenced by recurrent infections are consistent with the diagnosis of myeloma, a tumor of plasma cells. Patients with myeloma may develop amyloidosis, which causes the nephrotic syndrome; the deposits of amorphous pink material are characteristic of amyloid and can be confirmed with a Congo red stain. Nephrotic syndrome is caused by glomerular deposits of amyloid that distort the microanatomy of the glomerulus and lead to “spilling” of protein into the urinary space.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 45-year-old man has had headaches, nausea, and vomiting that have worsened over the past 5 days. He has started “seeing spots” before his eyes and experienced periods of mental confusion. On physical examination, his blood pressure is 270/150 mm Hg. Urinalysis shows 1+ proteinuria, 2+ hematuria, and no glucose, ketones, or leukocytes. The blood urea nitrogen and creatinine levels are elevated. He dies 2 weeks later from a cerebral bleed. Which of the following histologic findings is most likely to be seen in this patient’s kidneys at autopsy?`,
        q2: ``,
        q3: [],
        option: [`Glomerular crescents`,` Fibrinoid necrosis of arterioles`,`Mesangial IgA deposition`,`Nodular glomerulosclerosis`,`Acute tubular necrosis`],
        optionFeedback: [`Glomerular crescents are seen in RPGN, which presents with nephritis, usually with proteinuria. Severe hypertension is not present. `,`The clinical picture is typical of malignant hypertension with renal involvement. The main lesions in the kidneys involve blood vessels and take the form of fibrinoid necrosis and hyperplastic arteriolosclerosis, which lead to severe narrowing of arterioles.`,`Mesangial IgA deposits comprised of IgA and anti-IgA antibodies  are diagnostic of IgA nephropathy, which presents with recurrent hematuria.`,`Nodular glomerulosclerosis is seen in diabetic nephropathy.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical picture is typical of malignant hypertension with renal involvement. The main lesions in the kidneys involve blood vessels and take the form of fibrinoid necrosis and hyperplastic arteriolosclerosis, which lead to severe narrowing of arterioles.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 5-year-old girl develops cramping abdominal pain and diarrhea 4 days after eating a hamburger, chili, and ice cream at a home barbecue. The next day, she has decreased urine output. On physical examination, there are petechial hemorrhages in the skin. Laboratory findings show a serum creatinine level of 2.2 mg/dL (0.6-1.2 mg/dL) and blood urea nitrogen level of 20 mg/dL (7-18 mg/dL). CBC shows hemoglobin, 10.8 g/dL (10.5-13.5 g/dL); hematocrit, 32.4% (33-40%); platelet count, 64,300/mm<sup>3</sup> (150,000-400,000/mm<sup>3</sup>) and WBC count, 6,480/mm<sup>3</sup> (3,800-14,000/mm<sup>3</sup>). The peripheral blood smear shows schistocytes, and the serum <small>D</small>-dimer level is elevated. Urinalysis shows 2+ hematuria; and no protein or glucose. A renal biopsy specimen shows small thrombi within glomerular capillary loops. This clinical picture develops most commonly after infection with which of the following organisms?`,
        q2: ``,
        q3: [],
        option: [` Candida albicans `,`Clostridium difficile `,` Escherichia coli `,`Proteus mirabilis `,`Staphylococcus aureus `],
        optionFeedback: [`Candida  is a fungus that causes mucocutaneous lesions and, in immunosuppressed individuals, systemic infection. It is not associated with glomerular lesions or hemolytic anemia. `,`C. difficile  causes pseudomembranous colitis in patients treated with antibiotics that deplete the normal intestinal flora.`,`The clinical presentation is diagnostic of hemolytic uremic syndrome (HUS). This is a form of thrombotic microangiopathy caused by Shiga-like toxin produced by E. coli . The pathogenesis involves widespread damage to the endothelium caused by the toxin. This triggers the formation of microvascular thrombi, consumption of platelets (causing thrombocytopenia), and microangiopathic hemolytic anemia (caused by fragmentation of RBCs as they traverse microvasculature narrowed by thrombi). The <small>D</small>-dimer is a fibrin breakdown product; its elevation indicates disseminated coagulation. Renal failure results from injury to glomeruli. Other forms of thrombotic microangiopathy include thrombotic thrombocytopenic purpura (TTP) and atypical HUS caused by excessive activation of complement.`,`Proteus  is a frequent cause of urinary tract infection but is not associated with disseminated coagulation, hemolytic anemia, or vascular thrombi.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The clinical presentation is diagnostic of hemolytic uremic syndrome (HUS). This is a form of thrombotic microangiopathy caused by Shiga-like toxin produced by E. coli . The pathogenesis involves widespread damage to the endothelium caused by the toxin. This triggers the formation of microvascular thrombi, consumption of platelets (causing thrombocytopenia), and microangiopathic hemolytic anemia (caused by fragmentation of RBCs as they traverse microvasculature narrowed by thrombi). The <small>D</small>-dimer is a fibrin breakdown product; its elevation indicates disseminated coagulation. Renal failure results from injury to glomeruli. Other forms of thrombotic microangiopathy include thrombotic thrombocytopenic purpura (TTP) and atypical HUS caused by excessive activation of complement.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 55-year-old man has had back pain and dark-colored urine for the past month. On physical examination, there is tenderness over the right costovertebral angle. Urinalysis shows a pH of 6 (4.5-8.0); specific gravity, 1.015 (1.002-1.030); 2+ hematuria; and no protein, glucose, or ketones. Microscopic examination of the urine shows numerous RBCs, a few WBCs, and no casts or crystals. The figure shows the representative gross appearance of the renal lesion. Which of the following driver mutations is most likely to be found in this lesion?`,
        q2: `<img src="../images/f011-q027-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Inactivation of VHL , with overexpression of VEGF`,`Inactivation of WT1 , with overexpression of genes involved in renal differentiation`,`Inactivation of APC , with overexpression of beta-catenin`,`Inactivation of RB  with loss of G<sub>1</sub>-S control`,`Inactivation of PTEN , with activation of PI3K/AKT tyrosine kinases `],
        optionFeedback: [`The history of flank pain and hematuria is suspicious for renal cell carcinoma, and the morphology is characteristic (yellowish tumor because of lipid-filled cells, often with areas of hemorrhage and vascular invasion). A frequent genetic lesion in this tumor is deletion or inactivation of the VHL  gene. The VHL protein is a ubiquitin ligase that is responsible for degradation of many proteins, including the transcription factor HIF-1α. Increased levels of HIF-1α lead to overproduction of growth factors, including VEGF, which promotes angiogenesis and tumor growth.`,`Inactivation of the WT1  gene is associated with Wilms tumor, a tumor associated with abnormal differentiation of the renal blastema because of reduced, not over, expression of genes associated with differentiation. The tumor presumably develops because of over-proliferation of primordial cells. `,`Inactivation of APC  is associated with carcinoma of the colon.`,`Mutational inactivation of RB  occurs in retinoblastomas and osteogenic sarcomas. High-risk HPVs also cause functional inactivation of RB .`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The history of flank pain and hematuria is suspicious for renal cell carcinoma, and the morphology is characteristic (yellowish tumor because of lipid-filled cells, often with areas of hemorrhage and vascular invasion). A frequent genetic lesion in this tumor is deletion or inactivation of the VHL  gene. The VHL protein is a ubiquitin ligase that is responsible for degradation of many proteins, including the transcription factor HIF-1α. Increased levels of HIF-1α lead to overproduction of growth factors, including VEGF, which promotes angiogenesis and tumor growth.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `Members of a family with a history of renal cancers undergo ultrasound screening. Two adults are found to have multifocal and bilateral renal mass lesions. Biopsies are obtained, and microscopic examination shows a papillary pattern. A mutation involving which of the following genes is most likely to be found in this family?`,
        q2: ``,
        q3: [],
        option: [`MET `,` PKD1 `,`RAS `,`NF1 `,`WT1 `],
        optionFeedback: [`Elevated serum potassium is not a paraneoplastic syndrome. Hypercalcemia, however, can be seen due to overproduction of parathyroid hormone-related protein (PTHrP).`,`The clinical and pathologic findings are classic for the clear cell variant of renal cell carcinoma. Some of these tumors produce erythropoietin, which can cause erythrocytosis or polycythemia. `,`Cushing syndrome is a paraneoplastic syndrome associated with small cell carcinoma of lung. It is caused by tumor cell production of an ACTH-like substance; this is not associated with renal cell carcinomas.`,`There is no evidence that the cells of renal cell carcinoma can produce hepcidin, which, if elevated, would be expected to produce the “anemia of chronic inflammation”.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Familial papillary renal cell carcinomas are most often associated with activation of the MET   gene, which encodes a receptor for hepatocyte growth factor. Increased responses to this growth factor are thought to lead to tumorigenesis. This tumor tends to be multifocal and bilateral.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 4-year-old girl has a 1-month history of abdominal pain. On physical examination, she is febrile, and palpation of the abdomen shows a mass on the right side. Laboratory studies show hematuria without proteinuria. Abdominal CT scan shows a 12-cm, circumscribed, solid mass in the right kidney. A right-sided nephrectomy is performed; the gross appearance of the mass is shown in the figure. Microscopic examination shows poorly formed tubules and glomeruli. Which of the following additional conditions is most likely to be associated with this renal mass?`,
        q2: `<img src="../images/f011-q030-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [` Polycythemia`,` Gonadal dysgenesis`,`Hypertension `,`Adrenogenital syndrome`,` Medullary carcinoma of thyroid`],
        optionFeedback: [`Familial papillary renal cell carcinomas are most often associated with activation of the MET   gene, which encodes a receptor for hepatocyte growth factor. Increased responses to this growth factor are thought to lead to tumorigenesis. This tumor tends to be multifocal and bilateral. `,`PKD1  mutations are associated with polycystic kidney disease.`,`RAS  mutations are associated with many cancer types, but not commonly renal cell cancer.`,`NF-1  mutations are associated with neurofibromatosis`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-This childhood renal tumor is characteristic of Wilms tumor. The tumor is associated with mutations in the WT1  gene. Germline mutations of WT1  cause a number of familial clinical syndromes, some of which (specifically, the Denys-Drash syndrome) are associated with gonadal dysgenesis (male pseudohermaphroditism).  `,
        state: `notAnswered`,
        userAnswered: [],
    },

 {
        q: `A 60-year-old man has a 6-month history of a feeling of fullness in his abdomen and a 5-kg weight loss. He has a 50 pack-year smoking history. Physical examination is normal. Urinalysis shows 3+ hematuria, but no protein, glucose, or leukocytes. Abdominal CT scan shows an 11-cm mass in the upper pole of the right kidney. A right-sided nephrectomy is performed, and gross examination reveals that the mass has invaded the renal vein. Microscopic examination of the mass shows cells with abundant clear cytoplasm. Elevated blood level of which of the following is most likely to be found in this patient?`,
        q2: ``,
        q3: [],
        option: [` Potassium`,` Erythropoietin`,`Adrenocorticotrophic hormone (ACTH)`,`Hepcidin`,` Thromboplastins`],
        optionFeedback: [`Polycythemia may be associated with renal cell carcinoma.`,`This childhood renal tumor is characteristic of Wilms tumor. The tumor is associated with mutations in the WT1  gene. Germline mutations of WT1  cause a number of familial clinical syndromes, some of which (specifically, the Denys-Drash syndrome) are associated with gonadal dysgenesis (male pseudohermaphroditism). `,`Neuroblastomas produce catecholamines and may cause hypertension.`,`Adrenogenital syndrome occurs with certain tumors of the adrenal glands.`,``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The clinical and pathologic findings are classic for the clear cell variant of renal cell carcinoma. Some of these tumors produce erythropoietin, which can cause erythrocytosis or polycythemia.`,
        state: `notAnswered`,
        userAnswered: [],
    }


   ];
