var quiz = [
    {
        q: `A 41-year-old man had an influenza-like illness for 1 week, followed 4 days later by rapidly progressive, ascending motor weakness requiring mechanical ventilation. On physical examination, he is now afebrile and has 3/5 motor strength in his extremities. A lumbar puncture yields clear, colorless cerebrospinal fluid under normal pressure. This fluid has a slightly elevated protein concentration, but a normal glucose level, and a cell count with only a few mononuclear cells. Despite supportive therapy he dies due to respiratory failure. At autopsy, lymphocytic infiltrates and segmental demyelination were seen in peripheral nerves. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Amyotrophic lateral sclerosis (ALS)`, `Guillain-Barr&#233; syndrome`, `Multiple sclerosis (MS)`,`Varicella-zoster virus infection`,`Vitamin B<sub>12</sub> (cobalamin) deficiency`],
       optionFeedback: [`ALS is a chronic progressive neurodegenerative disease that affects upper and lower motor neurons in the cerebral cortex and spinal cord respectively. It does not have an acute onset as in this patient and is usually not associated with an infectious prodrome. `,`Acute ascending paralysis following a viral or other illness is typical of Guillain-Barr&#233; syndrome, a demyelinating disease affecting motor neurons. It is believed to be an autoimmune disease triggered by an infection (or vaccination). It is thought that microbe-specific T cells and antibodies cross react with antigens in myelin. Mononuclear cell infiltrates in the nerve roots and proximal nerve segments are characteristic. `,`MS is a chronic demyelinating disease of the central nervous system. Sporadic episodes of muscle weakness are common, but not acute ascending paralysis. `,`Varicella reactivation causes shingles, a painful inflammatory disease not associated with ascending paralysis`,`Vitamin B<sub>12</sub> deficiency causes subacute combined degeneration of the spinal cord, a disorder in which both sensory and motor abnormalities develop over weeks. hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Acute ascending paralysis following a viral or other illness is typical of Guillain-Barr&#233; syndrome, a demyelinating disease affecting motor neurons. It is believed to be an autoimmune disease triggered by an infection (or vaccination). It is thought that microbe-specific T cells and antibodies cross react with antigens in myelin. Mononuclear cell infiltrates in the nerve roots and proximal nerve segments are characteristic.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 93-year-old woman has noted frequent outbreaks of painful lesions on the skin of her right chest for the past year. On physical examination, there is a vesicular eruption in a 1 &#215; 8 cm area over the right seventh rib. She is treated with acyclovir, and partial resolution of the skin lesions occurs, but the pain persists for the next 3 months. Which of the following is the most likely cause for her findings?`,
        q2: ``,
        q3: [],
        option: [`Aging`, `Diabetes`,`Multiple sclerosis (MS)`,`Somatoform pain disorder`,`Varicella-zoster virus infection`],
       optionFeedback: [`Aging alone would not cause a skin rash or vesicular eruption.`,`Diabetes alone would not cause a skin rash or vesicular eruption.`,`MS is a chronic demyelinating disease of the central nervous system; it is not associated with cutaneous lesions.`,`Somatoform pain disorder presents with pain that usually cannot be explained by a known underlying medical condition.`,` Painful vesicular eruptions in the region of a peripheral nerve distribution are typical of shingles, a disease caused by reactivation of latent varicella-zoster infection (often in hemangioblastomas.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale:- Painful vesicular eruptions in the region of a peripheral nerve distribution are typical of shingles, a disease caused by reactivation of latent varicella-zoster infection (often in elderly and immunocompromised individuals).   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 55-year-old obese man has a 2-month history of a nonhealing foot ulcer. Physical examination reveals a 2-cm, shallow ulceration of the left medial malleolus. There is symmetric decreased sensation in the distal regions of the lower extremities. Past medical history is significant for multiple urinary tract infections. Laboratory testing is most likely to reveal elevated serum levels of which of the following?`,
        q2: ``,
        q3: [],
        option: [`HbA1c`, `LDL cholesterol`,`β2 microglobulin`,`Cardiac troponin`,`Creatine kinase`],
       optionFeedback: [`A chronic nonhealing ulcer with evidence of peripheral neuropathy (sensory defects) and recurrent infections is strongly suggestive of diabetes. Diabetic neuropathy may be mixed sensory motor and also involves the autonomic nervous system, leading to difficulty in bladder emptying and recurrent urinary tract infections. Elevated HbA1c is `,`LDL cholesterol is elevated in patients with atherosclerotic vascular disease, which may accompany diabetes but does not itself cause peripheral neuropathy or increased susceptibility to infection.`,`Elevated β2-microglobulin, a component of HLA molecules, is associated with dialysis-associated amyloidosis. This is now rarely seen due to changes in dialysis membranes that have resulted in better clearance of β2-microglobulin.`,`Cardiac troponin is increased in myocardial infarction due to release from necrotic myocardial cells.`,`Creatine kinase, a muscle enzyme, is elevated in muscle injury from any cause and following myocardial infarction.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- A chronic nonhealing ulcer with evidence of peripheral neuropathy (sensory defects) and recurrent infections is strongly suggestive of diabetes. Diabetic neuropathy may be mixed sensory motor and also involves the autonomic nervous system, leading to difficulty in bladder emptying and recurrent urinary tract infections. Elevated HbA1c is an indicator of hyperglycemia.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 58-year-old man has a 1-month history of worsening double vision and eyelid drooping, particularly toward the end of the day. He also has had difficulty chewing his food at dinner. On physical examination, he has 5/5 motor strength in his extremities that decreases to 4/5 strength with repetitive movement. There is no pain on palpation and no decrease in joint mobility. Which of the following therapeutic agents is most likely to improve this patient’s symptoms?`,
        q2: ``,
        q3: [],
        option: [`Cholinesterase inhibitors`, `Corticosteroids`,`Insulin`,`Vitamin B`,`Antibiotics `],
       optionFeedback: [`Progressive weakness affecting multiple muscle groups, especially the eyelids and extraocular muscles that worsens following exercise is characteristic of the autoimmune disease myasthenia gravis. In this disease, autoantibodies against acetylcholine receptors inhibit neurotransmission and destroy the receptors. Maximizing the amount of acetylcholine available by inhibiting the enzyme that degrades it relieves symptoms but does `,`Corticosteroids inhibit inflammation but are unlikely to be beneficial in this purely antibody-mediated disease.`,`Insulin is useful in some diabetic patients but has no role in this patient’s treatment.`,`Vitamin B<sub>12</sub> would help in subacute combined degeneration of the spinal cord, a disorder in which both sensory and motor abnormalities develop over weeks.`,`Antibiotics would not be used unless there was some sign of infection.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Progressive weakness affecting multiple muscle groups, especially the eyelids and extraocular muscles that worsens following exercise is characteristic of the autoimmune disease myasthenia gravis. In this disease, autoantibodies against acetylcholine receptors inhibit neurotransmission and destroy the receptors. Maximizing the amount of acetylcholine available by inhibiting the enzyme that degrades it relieves symptoms but does not cure the disease.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 42-year-old man has a 2-year history of increasing progressive muscle weakness in both arms and legs and dysarthria and difficulty swallowing. He is now wheelchair-bound. Physical examination shows 3/5 motor strength in all extremities. He has no muscle pain on palpation, no deformities or loss of joint mobility, and no tremor. There is no sensory loss. Family history is significant for a similar condition in first-degree relatives. A biopsy specimen of the quadriceps muscle shows atrophy of the myofibers but no inflammation. Molecular testing reveals a mutation affecting the gene encoding superoxide dismutase. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Amyotrophic lateral sclerosis`, `Becker muscular dystrophy`,`Guillain-Barr&#233; syndrome`,`Myasthenia gravis`,`Lambert-Eaton syndrome`],
       optionFeedback: [`A motor neuron disease causing muscle atrophy and with a possible family history is suspicious for amyotrophic lateral sclerosis. Motor neurons in the spinal cord, brain stem, and cerebral cortex may be affected. SOD1 mutations are present in ~20% of familial cases (`,`Becker muscular dystrophy presents with progressive muscle weakness and often cardiac involvement. It is caused by mutations in the dystrophin gene. `,`Guillain-Barr&#233; syndrome is a demyelinating peripheral neuropathy that is typically immune mediated. It has an acute onset and causes ascending paralysis. There is no increased risk in first-degree relatives and mutations of SOD1 are not seen in this disease.`,`Myasthenia gravis is an autoimmune disease caused by autoantibodies against the acetylcholine receptor. There is no increased risk in first-degree relatives and mutations of SOD1 are not seen in this disease.`,`Lambert-Eaton syndrome is caused by antibodies against calcium channel proteins in the neuromuscular junction. It is often a paraneoplastic syndrome, especially with small cell lung cancer (a tumor of neuroendocrine cells) and is not familial. hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- A motor neuron disease causing muscle atrophy and with a possible family history is suspicious for amyotrophic lateral sclerosis. Motor neurons in the spinal cord, brain stem, and cerebral cortex may be affected. SOD1 mutations are present in ~20% of familial cases (most cases are sporadic). `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 42-year-old woman has had an increasing number of subcutaneous nodules developing over the past 20 years. On physical examination the nodules range from 0.5 to 1.5 cm in size and are firm and nontender. She also has multiple light brown spots on her skin. She presents with a 1-month history of pain in her posterior left thigh. MRI shows an 8-cm mass. A mutation in the gene encoding which of the following proteins is most likely to be present in this woman`,
        q2: ``,
        q3: [],
        option: [` RAS`, `Merlin`,`E-cadherin`,`Dystrophin`,`Neurofibromin `],
       optionFeedback: [`RAS mutations are seen in many tumors but not in neurofibromatosis.`,`Mutations in the gene that encodes merlin, NF2, cause neurofibromatosis type 2, which presents with multiple tumors (schwannomas, meningiomas, and others), but not neurofibromas.`,`E-cadherin mutations are seen in many tumors but not in neurofibromatosis.`,`Dystrophin mutations cause muscular dystrophy and are not associated with cutaneous findings or soft tissue masses.`,`Multiple subcutaneous nodules (neurofibromas) with caf&#233;-au-lait spots on the skin are characteristic of neurofibromatosis type 1 (formerly called von Recklinghausen disease). The disease is caused by loss of function mutations in NF1, a tumor suppressor that encodes neurofibromin, a RAS- GTPase; its loss results in unrestrained activation of RAS. The thigh mass with pain is likely a malignant peripheral nerve sheath tumor, a rare sarcoma that has an increased incidence in patients hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Multiple subcutaneous nodules (neurofibromas) with caf&#233;-au-lait spots on the skin are characteristic of neurofibromatosis type 1 (formerly called von Recklinghausen disease). The disease is caused by loss of function mutations in NF1, a tumor suppressor that encodes neurofibromin, a RAS- GTPase; its loss results in unrestrained activation of RAS. The thigh mass with pain is likely a malignant peripheral nerve sheath tumor, a rare sarcoma that has an increased incidence in patients with type 1 neurofibromatosis. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `An autopsy is requested for a 75-year-old man who died in the ICU after 3 days in a coma following a cerebrovascular accident (stroke) involving the right middle cerebral artery (MCA), confirmed by CT scan. Clinical history is significant for multiple transient attacks of CNS ischemia during the previous 2 years. Microscopic examination of sections in the ischemic area reveals a population of cells with intensely eosinophilic cytoplasm. Which of the following cell types do these eosinophilic cells most likely represent?`,
        q2: ``,
        q3: [],
        option: [` Neurons`, `Astrocytes`,`Ependymal cells`,`Microglia`,`Oligodendroglia`],
       optionFeedback: [`Ischemic injury, as in this case, causes typical changes in neurons, including cell shrinking, nuclear pyknosis, and intense eosinophilia of the cytoplasm (hence the name “red neurons”). Because neurons are the most oxygen-dependent cells in the CNS, they are the first to `,`Astrocytes are responsible for repair and scarring (gliosis).  They do not typically show eosinophilic changes in the setting of acute ischemia.`,`Ependymal cells line ventricles and canals and may be injured in some viral infections, but do not typically show eosinophilic changes in the setting of acute ischemia.`,`Microglia are tissue-resident macrophages, which eliminate dead cells but they do not show eosinophilic changes following acute ischemia.`,`Oligodendrocytes synthesize myelin; they do not show eosinophilic  changes following acute ischemia.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Ischemic injury, as in this case, causes typical changes in neurons, including cell shrinking, nuclear pyknosis, and intense eosinophilia of the cytoplasm (hence the name “red neurons”). Because neurons are the most oxygen-dependent cells in the CNS, they are the first to be damaged by ischemia.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 49-year-old woman has a 2-day history of a severe headache. On physical examination, she is afebrile and normotensive. Funduscopic examination shows papilledema in the right eye. One day later, she has right pupillary dilation and impaired ocular movement. She then becomes obtunded. Which of the following lesions best explains these findings?`,
        q2: ``,
        q3: [],
        option: [`Chronic subdural hematoma`, `Temporal lobe herniation`,`Noncommunicating hydrocephalus`,`Hydrocephalus ex vacuo`,`Ruptured middle cerebral berry aneurysm`],
       optionFeedback: [`Chronic subdural hematoma develops following trauma and is insidious in onset and progresses slowly.`,`Papilledema indicates increased intracranial pressure. Dilated pupils and obtunded state are consistent with a transtentorial temporal lobe herniation secondary to increased intracranial pressure. Pupillary dilation is due to compression of the third cranial nerve, and coma results from compression of the midbrain. `,`Noncommunicating hydrocephalus is a localized expansion of one of the ventricles, usually secondary to an obstruction. The presentation is usually subtle, and reflects the primary disease. `,`Hydrocephalus ex vacuo is a compensatory increase in the volume of the ventricle secondary to loss of brain parenchyma from any cause (e.g., infarct). It is of no clinical consequence. `,`A ruptured aneurysm causes subarachnoid hemorrhage and presents with sudden severe headache, often followed by rapid loss of consciousness. hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Papilledema indicates increased intracranial pressure. Dilated pupils and obtunded state are consistent with a transtentorial temporal lobe herniation secondary to increased intracranial pressure. Pupillary dilation is due to compression of the third cranial nerve, and coma results from compression of the midbrain. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 21-year-old woman hits her head during a mountain biking accident and loses consciousness for 5 minutes. On examination, her deep tendon reflexes are diminished. A head CT scan 6 hours later shows no abnormalities. She recovers over the next week, with no neurologic deficits, but cannot remember this event. Which of the following underlying conditions is the most likely explanation for her symptoms?`,
        q2: ``,
        q3: [],
        option: [`Arteriolosclerosis`, `Concussion`,`Hydrocephalus`,`Post-traumatic dementia`,`Diffuse axonal injury `],
       optionFeedback: [`Arteriolosclerosis is narrowing of small vessels and would not be associated with trauma or the acute findings described.`,`Transient loss of consciousness and absent reflexes following brain trauma are characteristic of concussion. Recovery with persisting amnesia is also typical.`,`Hydrocephalus is a slowly developing increase in CSF volume.`,`Post-traumatic dementia is a neurodegenerative disorder caused by repeated brain trauma (now called chronic traumatic encephalopathy).`,`Diffuse axonal injury affects the deep white matter and occurs in the setting of trauma, particularly when there is movement of one area of the brain relative to another (e.g., angular acceleration). Morphologically, it is characterized by widespread, often asymmetric axonal swellings that appear within hours of the injury and may persist for much longer.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Transient loss of consciousness and absent reflexes following brain trauma are characteristic of concussion. Recovery with persisting amnesia is also typical.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `An 83-year-old woman slips in the bathtub in her home and falls backward, striking her head. At the Emergency Department, examination shows a 3-cm reddish, slightly swollen area over the occiput. She is arousable but somnolent. Physical exam reveals no motor or sensory deficits or papilledema. CT scan of the head would most likely reveal acute hemorrhage in which of the following locations?`,
        q2: ``,
        q3: [],
        option: [` Basal ganglia`, `Cerebral ventricle`,`Epidural space`,`Inferior frontal lobe`,`Occipital lobes`],
       optionFeedback: [`Basal ganglia would not be affected by this type of fall.`,`Cerebral ventricles would not be affected by this type of fall.`,`The epidural space would not be affected by this type of fall.`,`This is classic contrecoup injury, in which the moving head strikes an object and the force is transmitted to the opposite side of the head. A fall backwards is most likely to injure inferior frontal lobes. A blow to a stationary head is more likely to produce coup injury at the site of the blow. `,`Occipital lobes would not be affected by this type of fall.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- This is classic contrecoup injury, in which the moving head strikes an object and the force is transmitted to the opposite side of the head. A fall backwards is most likely to injure inferior frontal lobes. A blow to a stationary head is more likely to produce coup injury at the site of the blow.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 19-year-old skateboarder flew off a jump and hit a tree. He was not wearing a helmet or other protective gear. He was initially unconscious, but recovered after a short period. He wanted to try another run, but his friends called for help. On the way to the Emergency Department, he became comatose. Physical examination now shows left papilledema. Skull radiographs show a linear fracture of the left temporoparietal region. This clinical picture is most consistent with which of the following lesions?`,
        q2: ``,
        q3: [],
        option: [` Acute leptomeningitis`, `Contusion of frontal lobes`,`Middle meningeal artery laceration`,`Ruptured berry aneurysm`,`Tearing of cerebral bridging veins `],
       optionFeedback: [`Acute meningitis develops more slowly with signs of inflammation (e.g., headache, neck rigidity), not associated with trauma or skull fracture.`,`Contusions are small areas of hemorrhage with tissue injury, which may be associated with temporary loss of consciousness (concussion).`,`A complication of traumatic skull fracture is an epidural hemorrhage secondary to laceration of a meningeal artery. A lucid interval followed by rapid neurological deterioration is typical of this type of trauma. Papilledema indicates increased intracranial pressure.`,`A ruptured aneurysm causes subarachnoid hemorrhage and presents with sudden severe headache, often followed by rapid loss of consciousness.`,`Tearing of bridging veins leads to subdural hematoma; the symptoms evolve more slowly and often consist of headache and confusion. It is more common in elderly patients due to brain atrophy and consequent stretching of the bridging veins.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- A complication of traumatic skull fracture is an epidural hemorrhage secondary to laceration of a meningeal artery. A lucid interval followed by rapid neurological deterioration is typical of this type of trauma. Papilledema indicates increased intracranial pressure. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `An 80-year-old nursing home resident is admitted to the hospital due to the recent onset of fluctuating levels of consciousness with headache and confusion. On physical examination, she is arousable, but disoriented and irritable. Vital signs include temperature of 36.9&#176; C and blood pressure of 130/85 mm Hg. There is papilledema of the right eye. CT scan of the head shows a collection of blood in the subdural space on the right. Which of the following vascular lesions most likely produced these findings?`,
        q2: ``,
        q3: [],
        option: [`Bleeding from an arteriovenous malformation (AVM)`, `Laceration of the middle meningeal artery`,`Rupture of a saccular aneurysm`,` Tearing of the cerebral bridging veins`,`Thrombosis of the middle cerebral artery `],
       optionFeedback: [`Bleeding from an AVM results in an intracerebral or subarachnoid hemorrhage, not a subdural hemorrhage.`,`Laceration of a meningeal artery causes an epidural hemorrhage.`,`Rupture of an aneurysm causes a subarachnoid hemorrhage.`,`The gradual development of symptoms and evidence of increased intracranial pressure (papilledema) are characteristic of a subdural hemorrhage. Subdural hemorrhage is caused by tearing of bridging veins and is usually secondary to trauma. In elderly patients, even minimal trauma can cause stretching and tearing of bridging veins because of brain atrophy.`,`Thrombosis of the middle cerebral artery causes cerebral infraction, which could be hemorrhagic but the blood does not get into the subdural space.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The gradual development of symptoms and evidence of increased intracranial pressure (papilledema) are characteristic of a subdural hemorrhage. Subdural hemorrhage is caused by tearing of bridging veins and is usually secondary to trauma. In elderly patients, even minimal trauma can cause stretching and tearing of bridging veins because of brain atrophy.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 68-year-old woman with a history of atrial fibrillation suddenly loses consciousness and collapses. When she becomes arousable, she is unable to move her left arm and has difficulty speaking. On physical examination, her temperature is 37&#176; C, pulse is 81 bpm, respirations are 18 breaths/min, and blood pressure is 135/85 mm Hg. Despite optimal medical therapy, she does not regain consciousness and the family elects to withdraw care. The figure shows the representative gross appearance of her brain at autopsy. The development of such a lesion most likely resulted from which of the following conditions?`,
        q2: `<img src="../images/f017-q013-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Arteriovenous malformation (AVM)`, `Embolic arterial occlusion`,`Metastatic carcinoma`,` Organizing subdural hematoma`,`Cerebral amyloid angiopathy `],
       optionFeedback: [`An AVM can rupture and cause intracerebral hemorrhage but not infarcts.`,`A focal hemorrhagic infarct (area of necrosis with multiple small hemorrhages in a particular arterial distribution) is most often caused by an embolus. Atrial fibrillation predisposes to the formation of mural thrombi in the atrium, a likely source of the embolus in this case. Speech difficulty and paralysis of the left arm are typical of infarcts affecting the right cerebral hemisphere.`,`Metastatic carcinoma would usually be a more circumscribed lesion and would not present with the symptoms in this case. Such lesions are often multifocal.`,`The depicted lesion is intracerebral, not subdural.`,`Cerebral amyloid angiopathy is characterized by amyloid deposits in cerebral arteries. The deposits weaken the vessel wall and may lead to multiple lobar hemorrhages in the cerebral cortex.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- A focal hemorrhagic infarct (area of necrosis with multiple small hemorrhages in a particular arterial distribution) is most often caused by an embolus. Atrial fibrillation predisposes to the formation of mural thrombi in the atrium, a likely source of the embolus in this case. Speech difficulty and paralysis of the left arm are typical of infarcts affecting the right cerebral hemisphere.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 79-year-old man with metabolic syndrome has a 3-month history of multiple episodes of sudden dysarthria, a feeling of weakness in his right hand, and dizziness. These episodes usually last less than 1 hour, and then he feels fine. Today, he lost consciousness and fell to the floor. On regaining consciousness 4 minutes later, he was unable to move his right arm. Which of the following underlying lesions is most likely to be found in his brain?`,
        q2: ``,
        q3: [],
        option: [`Arteriovenous malformation (AVM)`, `Cerebral atherosclerosis`,` Frontal lobe tumor`,`Meningoencephalitis`,`Subdural hematoma `],
       optionFeedback: [`AVM manifests usually with sudden intracerebral or subarachnoid hemorrhage, with more severe and acute symptoms.`,`The multiple episodes of weakness and dizziness are typical of transient ischemic attacks (TIAs), most often the result of cerebral atherosclerosis and transient vascular obstructions by plaques or associated thrombi. The last episode may indicate a cerebral infarct (stroke). Metabolic syndrome predisposes to atherosclerosis. `,`A frontal lobe tumor would present more insidiously and not with TIAs or stroke.`,`Meningoencephalitis (usually acute) shows signs of inflammation (e.g., headache, neck rigidity), and not prior TIAs.`,`Subdural hematoma is usually the result of trauma and also does not cause TIAs.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The multiple episodes of weakness and dizziness are typical of transient ischemic attacks (TIAs), most often the result of cerebral atherosclerosis and transient vascular obstructions by plaques or associated thrombi. The last episode may indicate a cerebral infarct (stroke). Metabolic syndrome predisposes to atherosclerosis. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 59-year-old woman had sudden loss of consciousness 4 months ago. On physical examination, she now has left hemiplegia. CT imaging shows a large, cystic space in the right parietal region. MR angiography shows occlusion of a peripheral cerebral artery branch at the gray-white junction near the lesion. Which of the following underlying disease processes is this woman most likely to have?`,
        q2: ``,
        q3: [],
        option: [`AIDS with a low CD4+ T-lymphocyte count`, `Chronic alcoholism `,`Chronic renal failure with hypertension`,`Colonic adenocarcinoma with migratory thrombophlebitis`,`Ischemic heart disease with left ventricular mural thrombus`],
       optionFeedback: [`AIDS causes a slowly progressive encephalopathy but without infarction or vascular occlusion.`,`Stroke is not a complication of alcoholism. `,`Hypertension most often causes cerebral bleeds, which may be associated with lacunar infarcts.`,`Malignant neoplasms can be associated with hypercoagulability and thrombosis but this is far less common than cardiac disease as a cause of stroke.`,`A remote cerebral infarct represented by the cystic lesion is present. Hemiplegia caused by occlusion of a cerebral artery is characteristic of a cerebral embolus. From the choices given, the most likely cause is heart disease with a myocardial infarct and an overlying left ventricular mural thrombus, which would be the hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- A remote cerebral infarct represented by the cystic lesion is present. Hemiplegia caused by occlusion of a cerebral artery is characteristic of a cerebral embolus. From the choices given, the most likely cause is heart disease with a myocardial infarct and an overlying left ventricular mural thrombus, which would be the source of the embolus. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 55-year-old man suddenly loses consciousness while driving at slow speed  and comes to a stop without a collision. Paramedics arrive but are unable to arouse him. On physical examination, there is bilateral papilledema. He has no spontaneous movements. The figure shows the gross appearance of the brain at autopsy. Which of the following underlying conditions is most likely to have caused this lesion?`,
        q2: `<img src="../images/f017-q016-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Vitamin B<sub>1</sub> deficiency`, `Saccular aneurysms`,`Multiple sclerosis (MS)`,`Systemic hypertension`,` Thromboembolism `],
       optionFeedback: [`Vitamin B<sub>1</sub> (thiamine) deficiency causes an encephalopathy that may present with confusion and ataxia but does not cause the sudden loss of consciousness seen with cerebral hemorrhage.`,`Rupture of saccular aneurysms causes subarachnoid hemorrhage.`,`MS is a chronic demyelinating disease that may present with episodes of relapsing and remitting paralysis, but not an acute event as in this case.`,`The clinical picture (sudden loss of consciousness, increased intracranial pressure manifested by papilledema) is characteristic of an intracerebral hemorrhage, and the brain shows a large bleed in the cerebral hemisphere. The leading underlying cause of nontraumatic cerebral hemorrhage is hypertension. `,`Thromboembolism can give rise to cerebral infarcts and present with acute loss of consciousness. There may be hemorrhage in the infarcts but not the massive hemorrhage seen here. Increased intracerebral pressure (seen here as papilledema) is uncommon.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The clinical picture (sudden loss of consciousness, increased intracranial pressure manifested by papilledema) is characteristic of an intracerebral hemorrhage, and the brain shows a large bleed in the cerebral hemisphere. The leading underlying cause of nontraumatic cerebral hemorrhage is hypertension.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `An 86-year-old man has become progressively unable to live independently for the past 10 years and now requires assistance with activities of daily living. On physical examination, he has no motor or sensory deficits. He cannot give the current date or state where he is. Six months later, he develops pneumonia and dies of respiratory failure. At autopsy, histologic examination of the brain shows numerous neocortical neuritic plaques and neurofibrillary tangles. Which of the following mechanisms is most likely responsible for his disease?`,
        q2: ``,
        q3: [],
        option: [`Aggregation of Aβ peptide`, `Conformational change in the prion protein (PrP)`,`Dopamine deficiency`,`Expansion of polyglutamine repeats`,` Mutations in the gene that encodes tau`],
       optionFeedback: [`The clinical history is suggestive of Alzheimer disease and the pathologic findings are diagnostic. Deposits of aggregated Aβ peptides are believed to be one of the underlying pathogenic `,`Prion disease is a neurodegenerative disease that typically presents with rapidly progressing dementia; it does not show neuritic plaques.`,`Dopamine deficiency is implicated in Parkinson disease, which is a movement disorder. It is not associated with plaques and tangles.`,`Expansions of polyglutamine repeats are the postulated cause of Huntington disease, a more rapidly progressive form of ataxia and dementia. Morphologic features include atrophy of the putamen and caudate nucleus.`,`Mutations in tau are a likely cause of frontotemporal dementia, which is dominated by behavioral and language difficulties.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The clinical history is suggestive of Alzheimer disease and the pathologic findings are diagnostic. Deposits of aggregated Aβ peptides are believed to be one of the underlying pathogenic mechanisms in the disease.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 50-year-old woman develops a sudden, severe headache and is taken to the Emergency Department. On examination, she has nuchal rigidity. Her blood pressure is 115/83 mm Hg. A lumbar puncture is done; the CSF shows numerous RBCs, no neutrophils, a few mononuclear cells, and a normal glucose level. The Gram stain result is negative. CT imaging shows subarachnoid hemorrhage at the base of the brain. Which of the following vascular events has most likely occurred in this woman?`,
        q2: ``,
        q3: [],
        option: [` Bleeding from cerebral amyloid angiopathy`, `Hematoma formation from arteriolosclerosis`,`Middle cerebral artery thromboembolism`,`Rupture of an intracranial berry aneurysm`,`Tear of subdural bridging veins `],
       optionFeedback: [`Cerebral amyloid angiopathy is characterized by amyloid deposits in cerebral arteries. The deposits weaken the vessel wall and may lead to multiple lobar hemorrhages in the cerebral cortex.`,`Arteriolosclerosis does not give rise to bleeds unless there is another factor such as hypertension involved.`,`Middle cerebral artery thromboembolism can give rise to a hemorrhagic infarct but the blood does not go to subarachnoid space.`,`Sudden headache and red cells in the CSF are diagnostic of subarachnoid hemorrhage, which is most often caused by a ruptured saccular aneurysm in the circle of Willis (berry aneurysm).`,`Tear of subdural bridging veins gives rise to subdural hematomas, not subarachnoid hemorrhages.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Sudden headache and red cells in the CSF are diagnostic of subarachnoid hemorrhage, which is most often caused by a ruptured saccular aneurysm in the circle of Willis (berry aneurysm).`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 45-year-old previously healthy man has developed headaches over the past month. There are no remarkable findings on physical examination. A cerebral MR angiogram shows a 7-mm saccular aneurysm at the trifurcation of the right middle cerebral artery. Which of the following is the most likely complication from this lesion?`,
        q2: ``,
        q3: [],
        option: [`Cerebellar tonsillar herniation`, `Hydrocephalus`,`Epidural hematoma`,`Subarachnoid hemorrhage`,`Subdural hematoma`],
       optionFeedback: [`Subarachnoid hemorrhages do not cause tonsillar herniation, which leads to acute loss of breathing and respiration and may be fatal.`,`Hydrocephalus is gradual accumulation of CSF in the ventricles. It is not associated with cerebral aneurysm. `,`Epidural hemorrhage is usually due to trauma causing tearing of the middle meningeal artery. Patients may have a lucid interval followed by acute neurologic deterioration. `,`A 7-mm aneurysm is at high risk for rupture into the subarachnoid space. In most cases this is an acute event marked by sudden onset of severe headache. A headache of one month’s duration could not have been due to rupture of the aneurysm but from another incidental, unrelated cause.`,`Subdural hematoma is also usually the result of brain trauma, causing tearing of bridging veins. hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- A 7-mm aneurysm is at high risk for rupture into the subarachnoid space. In most cases this is an acute event marked by sudden onset of severe headache. A headache of one month’s duration could not have been due to rupture of the aneurysm but from another incidental, unrelated cause.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 25-year-old man presents with a 5-month history of headaches. During the last two weeks, he has had 4 generalized seizures. On physical examination, he has no papilledema or movement disorder. CT scan of the head shows a 2-cm mass in the right frontal lobe. A stereotactic biopsy specimen of this lesion shows only gliosis and evidence of recent and remote hemorrhage. The mass is removed, and histologic examination shows a conglomerate of various-sized tortuous vessels surrounded by gliosis. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Ruptured saccular aneurysm`, `Arteriovenous malformation`,`Multiple sclerosis plaque`,`Organizing abscess`,`Prior head trauma`],
       optionFeedback: [`A ruptured saccular (berry) aneurysm causes subarachnoid hemorrhage, usually presenting with sudden headache and without seizures.`,`A hemorrhagic lesion with tortuous vessels is a characteristic finding for an arteriovenous malformation. Slow bleeds from these malformations cause headaches and seizures.`,`An MS plaque is a focus of demyelination with macrophages and other immune cells. It is not vascular or hemorrhagic. `,`An abscess would be walled off with gliosis and usually contains inflammatory cells and necrotic debris. `,`Prior head trauma may cause contusions, which over time form areas of gliosis with macrophages. They do not contain tortuous blood vessels.  hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- A hemorrhagic lesion with tortuous vessels is a characteristic finding for an arteriovenous malformation. Slow bleeds from these malformations cause headaches and seizures.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 19-year-old male college student with no prior medical history has a sore throat followed a day later by sudden onset of a severe headache. Physical examination shows mild pharyngitis and nuchal rigidity. His skin shows petechial hemorrhages. His temperature is 38.8&#176; C, pulse is 98 bpm, respirations are 26 breaths/min, and blood pressure is 95/45 mm Hg. The figure shows a representative gross appearance of the brain of someone with the same disorder. Which of the following infectious organisms is most likely to have produced his disease?`,
        q2: `<img src="../images/f017-q021-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Cryptococcus neoformans`, `Mycobacterium tuberculosis`,`Neisseria meningitidis`,`Poliovirus`,`Herpes simplex virus-1`],
       optionFeedback: [`Cryptococcus infection is most often seen in immunosuppressed individuals and presents with evidence of meningitis and encephalitis.`,`Tuberculous meningitis is a chronic infection, usually without the systemic signs of acute inflammation; the exudate is thick and gelatinous mostly, on the base of the brain.`,`A pyogenic exudate is evident within the leptomeninges on the surface of the brain. This is typical of acute meningitis caused by Neisseria meningitides. Patients present typically with headache, neck stiffness, and systemic signs of inflammation. Pharyngitis may precede the neurologic symptoms. `,`In the CNS, poliovirus infects motor neuron cells in the spinal cord and causes flaccid paralysis. Purulent meningitis is not seen.`,`Herpes simplex virus causes a destructive encephalitis most often affecting the temporal lobes.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- A pyogenic exudate is evident within the leptomeninges on the surface of the brain. This is typical of acute meningitis caused by Neisseria meningitides. Patients present typically with headache, neck stiffness, and systemic signs of inflammation. Pharyngitis may precede the neurologic symptoms.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 44-year-old woman who is an intravenous drug user is admitted to the hospital with increasing headache and high fever for the past 24 hours. On physical examination, her temperature is 38.4&#176; C, pulse is 85 bpm, respirations are 18/min, and blood pressure is 125/85 mm Hg. CT scan of the head shows no mass lesion or midline shift. A lumbar puncture is performed. The CSF shows 70,000 neutrophils/mm<sup>3</sup>, an increased protein concentration, and a decreased glucose level. Which of the following infectious agents is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Herpes simplex virus`, `JC virus`,`Mycobacterium tuberculosis`,`Streptococcus pneumoniae `,`Toxoplasma gondii`],
       optionFeedback: [`Herpes simplex virus causes a destructive encephalitis most often affecting the temporal lobes.`,`JC virus causes a slowly progressive neurologic disease and progressive multifocal leukoencephalopathy with extensive white matter destruction, usually in immunocompromised patients.`,`Tuberculous meningitis is a chronic infection usually without the systemic signs of acute inflammation and few if any neutrophils in the CSF.`,`Headache and fever raise the suspicion of bacterial meningitis. In bacterial infections, the CSF shows increased pressure, increased protein, decreased glucose, and abundant neutrophils. By contrast, in viral infections, there may be an early neutrophilic pleocytosis that rapidly converts to a lymphocytosis; the protein concentration is elevated, but the glucose is normal and the pressure is normal or only slightly elevated.`,`Toxoplasmosis is a parenchymal infection most often in immunosuppressed individuals; it forms multiple abscesses.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Headache and fever raise the suspicion of bacterial meningitis. In bacterial infections, the CSF shows increased pressure, increased protein, decreased glucose, and abundant neutrophils. By contrast, in viral infections, there may be an early neutrophilic pleocytosis that rapidly converts to a lymphocytosis; the protein concentration is elevated, but the glucose is normal and the pressure is normal or only slightly elevated.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 43-year-old woman has a 2-week history of headache and fever following a severe respiratory tract infection. Past history is notable for a diagnosis of bronchiectasis. On physical examination, her temperature is 38.3&#176; C. There is no papilledema. She has no loss of sensation or motor function, but she has homonymous hemianopsia (loss of half of the visual field on the same side in both eyes). CT scan of the head shows a sharply demarcated, 3-cm, ring-enhancing lesion in the right occipital region. Laboratory analysis of the CSF from a lumbar puncture shows numerous neutrophils, increased protein, and normal glucose levels. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Cerebral abscess`, `Glioblastoma`,`Metastatic carcinoma`,`Multiple sclerosis`,`Herpes encephalitis `],
       optionFeedback: [`Localized visual loss and a single mass suggest a focal lesion. Brain abscesses are discrete lesions with central necrosis surrounded by granulation and fibrous tissue, usually caused by bacterial infection. Predisposing conditions include bacterial endocarditis, congenital heart disease with right-to-left shunt, and lung infections, particularly those that are associated with bronchiectasis. The lungs are the likely source of `,`Glioblastoma does appear as a ring-enhancing lesion on MRI, but it does not present with signs of infection and the CSF does not show neutrophils.`,`Metastatic carcinoma is a focal lesion with localizing signs, but it does not present with signs of infection and the CSF does not show neutrophils.`,`Multiple sclerosis is a relapsing and remitting demyelinating disease that does not present with ring-enhancing lesions or signs of infection and the CSF does not show neutrophils.`,`Herpes encephalitis presents with evidence of parenchymal loss, often in the temporal lobes and is not a focal lesion; the CSF may contain mononuclear cells but not neutrophils.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Localized visual loss and a single mass suggest a focal lesion. Brain abscesses are discrete lesions with central necrosis surrounded by granulation and fibrous tissue, usually caused by bacterial infection. Predisposing conditions include bacterial endocarditis, congenital heart disease with right-to-left shunt, and lung infections, particularly those that are associated with bronchiectasis. The lungs are the likely source of bacteria in this case. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 4-year-old girl residing near Cape Town, South Africa, has a 1-week history of worsening headache and irritability and presents with nausea, vomiting, and diminished responsiveness to verbal commands. On examination, she has a temperature of 37.2&#176; C.   A tremor is observed in her extremities and she has lateral gaze paralysis. Examination of the CSF from a lumbar puncture shows 100 leukocytes/mm<sup>3</sup>of which 75% are mononuclear; glucose is decreased and protein is markedly elevated. CT imaging with contrast shows basilar meningeal thickening and a focal 2-cm mass involving the right cerebellar hemisphere. Which of the following infectious agents is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Coxsackie virus B`, `Haemophilus influenzae`,`Mycobacterium tuberculosis`,`Treponema pallidum`,`Taenia solium`],
       optionFeedback: [`In viral infection, mononuclear cells are present in the CSF but protein is not high; also, there is no mass.`,`H. influenzae can cause pyogenic meningitis with high protein, low sugar, and neutrophils in CSF.`,`Generalized and neurologic symptoms suggest an infection. The CSF findings of low sugar, high protein with mononuclear cells are characteristic of tuberculous meningitis. TB produces a thick gelatinous exudate at the base of the brain that can entrap and compress cranial nerves, most commonly the abducens nerve, resulting in lateral gaze paralysis. The solitary mass is likely a tuberculoma. This child lives in an area where tuberculosis is endemic. `,`T. pallidum, the causative agent of syphilis, produces chronic infections that may present with meningitis, parenchymal lesions, or sensory nerve abnormalities.`,`T. solium causes cysticercosis, which may produce cystic lesions that can cause seizures.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Generalized and neurologic symptoms suggest an infection. The CSF findings of low sugar, high protein with mononuclear cells are characteristic of tuberculous meningitis. TB produces a thick gelatinous exudate at the base of the brain that can entrap and compress cranial nerves, most commonly the abducens nerve, resulting in lateral gaze paralysis. The solitary mass is likely a tuberculoma. This child lives in an area where tuberculosis is endemic. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 26-year-old woman with no significant past medical history has headaches for 4 weeks along with increasing malaise. Physical examination is unremarkable. CT scan and MRI of the head show no abnormalities. A lumbar puncture yields clear, colorless CSF with a normal opening pressure. Laboratory analysis of the CSF shows a normal glucose concentration and a minimally increased protein level. Several lymphocytes are present, but there are no neutrophils. A Gram stain and India ink preparation of the CSF are negative. Her condition gradually improves over the next 6 months. Serum serologic tests are most likely to show an elevated titer of antibodies to which of the following infectious agents?`,
        q2: ``,
        q3: [],
        option: [`Cryptococcus neoformans`, `Enterovirus `,`Rabies virus`,`Neisseria meningitidis`,`Toxoplasma gondii`],
       optionFeedback: [`Cryptococcus causes an indolent or more fulminant meningitis or meningoencephalitis, often in immunosuppressed individuals. The CSF usually has elevated protein, and fungal yeast forms can be detected with special stains.`,`Persistent malaise and headache are suggestive of meningitis; the CSF picture is characteristic of viral (“aseptic”) meningitis. In almost 80% of cases, the cause is an enterovirus infection. The disease is often self-limited.`,`Rabies causes severe encephalitis with extreme CNS sensitivity to touch and other stimuli.`,`N. meningitidis causes an acute meningitis with signs of acute infection and markedly elevated protein, low glucose, and neutrophils in the CSF (a dramatic contrast to viral meningitis, which explains why the latter is called “aseptic”).`,`Cerebral toxoplasmosis develops in immunosuppressed individuals or newborns (who acquire the infection during birth); in newborns, it presents with chorioretinitis, hydrocephalus, and intracranial calcifications. In adults, it causes multiple abscesses.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Persistent malaise and headache are suggestive of meningitis; the CSF picture is characteristic of viral (“aseptic”) meningitis. In almost 80% of cases, the cause is an enterovirus infection. The disease is often self-limited.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 25-year-old, previously healthy woman has acute onset confusion and disorientation followed by a generalized tonic-clonic seizure. On admission to the hospital, she is afebrile, and her blood pressure is 110/65 mm Hg. No papilledema is observed. Serum and urine drug screening results are negative. CT scan of the head shows a 3-cm recent hemorrhage in the left temporal lobe. A lumbar puncture is done, and the CSF shows only a few mononuclear cells and normal glucose and protein levels. Infection with which of the following organisms is the most likely cause of her disease?`,
        q2: ``,
        q3: [],
        option: [`Taenia solium`, `Cytomegalovirus (CMV)`,` Herpes simplex virus`,`Eastern equine encephalitis virus`,`Neisseria meningitidis `],
       optionFeedback: [`T. solium causes cysticercosis, which may produce cystic lesions that may cause seizures, but not hemorrhagic temporal lobe lesions.`,`In adults, CMV usually infects immunosuppressed individuals and causes subacute encephalitis with periventricular lesions.`,`Acute neurologic symptoms with hemorrhagic and necrotic temporal lobe lesions are most consistent with herpes encephalitis. The CSF is typically unremarkable. `,`Equine encephalitis virus, an arbovirus, is prevalent in endemic areas. Infection causes generalized and focal neurologic signs, but usually not lesions limited to the temporal lobe.`,`N. meningitidis causes acute bacterial (“pyogenic”) meningitis, with signs of acute infection and markedly elevated protein and neutrophils in the CNS.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Acute neurologic symptoms with hemorrhagic and necrotic temporal lobe lesions are most consistent with herpes encephalitis. The CSF is typically unremarkable. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 33-year-old woman whose two previous pregnancies resulted in normal term infants, gives birth at 34 weeks’ gestation to a stillborn fetus. On examination, the fetus is observed to be hydropic. Autopsy of the fetus shows that the brain has extensive periventricular necrosis with focal calcifications. Which of the following congenital infections is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Cytomegalovirus`, `Group B Streptococcus`,`Herpes simplex virus`,`HIV`,`Listeria monocytogenes`],
       optionFeedback: [`Intrauterine infection with periventricular lesions, calcifications, and microcephaly are characteristic of CMV.  Cytomegalovirus is one of the so-called “TORCH” congenital infections that can affect the fetus in utero: toxoplasmosis, other (syphilis, parvovirus B19, varicella zoster), rubella, cytomegalovirus and herpes. Clinical and pathologic manifestations include fever, encephalitis, chorioretinitis, hepatosplenomegaly, pneumonitis, myocarditis, hemolytic anemia, and vesicular or hemorrhagic skin lesions. Infections occurring early in gestation may also cause chronic sequelae in the child, including growth retardation and intellectual disability, cataracts, congenital cardiac `,`S. pneumoniae causes acute bacterial (pyogenic) meningitis in children and adults, with characteristic CSF changes mentioned earlier. It is not associated with periventricular calcifications. `,`Herpes encephalitis is not an intrauterine infection, and it causes acute neurologic symptoms with hemorrhagic and necrotic temporal lobe lesions.`,`HIV encephalitis usually occurs in older individuals infected with the virus and presents with subtler neurologic signs.`,`L. monocytogenes is an uncommon cause of congenital infection. Neonates may present with meningoencephalitis, with CSF changes typical of pyogenic meningitis.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Intrauterine infection with periventricular lesions, calcifications, and microcephaly are characteristic of CMV.    Cytomegalovirus is one of the so-called “TORCH” congenital infections that can affect the fetus in utero: toxoplasmosis, other (syphilis, parvovirus B19, varicella zoster), rubella, cytomegalovirus and herpes. Clinical and pathologic manifestations include fever, encephalitis, chorioretinitis, hepatosplenomegaly, pneumonitis, myocarditis, hemolytic anemia, and vesicular or hemorrhagic skin lesions. Infections occurring early in gestation may also cause chronic sequelae in the child, including growth retardation and intellectual disability, cataracts, congenital cardiac anomalies, and bone defects.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 52-year-old woman with leukemia undergoes chemotherapy. Two months later, she develops neurologic deficits with ataxia, motor weakness in the right arm, difficulty swallowing, and sensory changes in the left leg. MRI of the brain shows irregular areas of demyelination in white matter of the cerebral hemispheres and the cerebellum. A stereotaxic biopsy specimen shows perivascular chronic inflammation, marked gliosis, and intranuclear inclusions within oligodendroglia. Which of the following viruses most likely caused these findings?`,
        q2: ``,
        q3: [],
        option: [`Cytomegalovirus (CMV)`, `Herpes simplex virus (HSV)`,`JC virus`,` Rabies virus`,` West Nile virus`],
       optionFeedback: [`CMV usually infects adults if they are immunosuppressed and causes subacute encephalitis with periventricular lesions, not demyelination.`,`HSV causes acute neurologic symptoms with hemorrhagic and necrotic temporal lobe lesions.`,`Generalized progressive neurologic symptoms with multiple foci of demyelination in an immunosuppressed individual is characteristic of progressive multifocal leukoencephalopathy, an infection caused by JC virus, a type of polyoma virus. The virus infects and damages oligodendrocytes, accounting for the widespread demyelination. `,`Rabies causes a severe encephalitis with extreme CNS sensitivity to touch and other stimuli.`,`West Nile virus, an arbovirus, is prevalent in endemic areas. Infection causes generalized and focal neurologic signs, not demyelination.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Generalized progressive neurologic symptoms with multiple foci of demyelination in an immunosuppressed individual is characteristic of progressive multifocal leukoencephalopathy, an infection caused by JC virus, a type of polyoma virus. The virus infects and damages oligodendrocytes, accounting for the widespread demyelination. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 38-year-old man with chronic renal failure received a kidney transplant. While being treated with cyclosporine, azathioprine, and high doses of corticosteroids, he began to experience headaches and became lethargic. On physical examination, he now has a fever and nuchal rigidity. A lumbar puncture is performed, and the opening pressure is increased. A CSF cell count shows increased lymphocytes. Despite supportive therapy, his condition deteriorates and he dies. A low power section of the whole brain is illustrated in the figure. Microscopically, mucoid-encapsulated yeasts can be seen within the lesions. Which of the following organisms is most likely infecting this man?`,
        q2: `<img src="../images/f017-q029-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Entamoeba histolytica`, `Blastomyces dermatitidis`,`Listeria monocytogenes`,`Cryptococcus neoformans`,`Plasmodium falciparum  `],
       optionFeedback: [`Ameba causes liver abscess but rarely spreads to the CNS; when it does, it causes focal abscesses.`,`Blastomyces causes a pulmonary infection that rarely affects the CNS; when it does, it can cause meningitis or abscesses.`,`Listeria can cause pyogenic meningitis with characteristic CSF findings. It does not cause soap bubble lesions.`,`The clinical picture indicates meningitis, which is unlikely to be bacterial because of the CSF findings. The histology is characteristic of Cryptococcus, which produces “soap bubble” lesions in Virchow-Robin spaces as the fungal organisms spread along vessels in these spaces and proliferate. The CSF usually has elevated protein, and fungal yeast forms can be detected with special stains. The infection usually occurs in immunosuppressed individuals.`,`Cerebral malaria is usually related to obstruction of small blood vessels, and does not cause lesions like those seen in this case. hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The clinical picture indicates meningitis, which is unlikely to be bacterial because of the CSF findings. The histology is characteristic of Cryptococcus, which produces “soap bubble” lesions in Virchow-Robin spaces as the fungal organisms spread along vessels in these spaces and proliferate. The CSF usually has elevated protein, and fungal yeast forms can be detected with special stains. The infection usually occurs in immunosuppressed individuals.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 27-year-old woman had an episode of weakness 3 months ago, which she attributed to job stress and fatigue. The neurologic examination shows mild residual weakness, with 4/5 motor strength in the right lower extremity. Laboratory examination of the CSF from a lumbar puncture shows increased IgG levels with prominent oligoclonal bands. MRI of the brain shows small, scattered, 0.5-cm areas consistent with demyelination, most of which are located in periventricular white matter. Which of the following complications is she most likely to develop?`,
        q2: ``,
        q3: [],
        option: [`Non-Hodgkin lymphoma`, ` Progressive dementia`,`Visual impairment`,`Seizure disorder`,`Tremor at rest`],
       optionFeedback: [`Primary CNS lymphoma (often seen in immunosuppressed individuals) can present with a variety of focal and generalized neurologic symptoms, but not demyelination.`,`Progressive dementia presents with memory and cognitive defects, not evidence of demyelination.`,`Episodic weakness with areas of demyelination is characteristic of multiple sclerosis. The CSF finding of oligoclonal IgG bands is typical. Patients often develop episodes of unilateral visual impairment due to involvement of the optic nerve (optic neuritis). `,`Seizure disorder (epilepsy) presents with seizures, not demyelination.`,`Tremor at rest is most often caused by Parkinson disease, not demyelination.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Episodic weakness with areas of demyelination is characteristic of multiple sclerosis. The CSF finding of oligoclonal IgG bands is typical. Patients often develop episodes of unilateral visual impairment due to involvement of the optic nerve (optic neuritis). `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 28-year-old man presents for a physical examination at a new job. His past medical history is significant for (1) paresthesia of his left arm and difficulty walking 3 years ago which subsequently resolved; (2) blurred vision in his left eye for the past year; and (3) difficulty writing with his right hand during the last 6 months. On physical examination, there is decreased visual acuity on the left, no papilledema, and no retinal lesions, decreased motor strength and decreased sensation in the right hand and forearm. MRI of the brain shows focal areas of increased signal intensity in periventricular white matter and in the left optic nerve. Which of the following is the most likely mechanism of this disease?`,
        q2: ``,
        q3: [],
        option: [`Inherited disorder of myelin synthesis`, `Autoimmune reaction against myelin`,`Viral meningoencephalitis`,`Misfolding of PrP<sup>c</sup>`,`Schwann cell dysfunction`],
       optionFeedback: [`Inherited disorders of myelin synthesis (leukodystrophies) present with progressive loss of neurologic function, usually starting at a young age, with diffuse and symmetric changes on MRI.`,`Episodic weakness and visual impairment are typical of multiple sclerosis (MS), caused by an autoimmune reaction against myelin proteins. The MRI findings are consistent with periventricular demyelination. Symptoms are distinct in time and space (waxing and waning).`,`Viral meningoencephalitis usually causes perivascular and parenchymal chronic inflammation. Different viruses infect different cells in the brain, producing distinct clinical manifestations. `,`Misfolding of prion proteins causes prion disease, such as Creutzfeldt-Jakob disease, a rapidly progressive form of dementia.`,`The demyelination in MS is due to an autoimmune attack on myelin and not on dysfunction of Schwann cells.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Episodic weakness and visual impairment are typical of multiple sclerosis (MS), caused by an autoimmune reaction against myelin proteins. The MRI findings are consistent with periventricular demyelination. Symptoms are distinct in time and space (waxing and waning).`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 74-year-old woman sustains blunt head trauma in a motor vehicle accident. On admission to the hospital, she is conscious but disoriented. CT scan of the head shows a right temporal bone fracture and mild cerebral edema. Her blood alcohol level is 0.24 % (&lt;0.08%). Two days later, laboratory studies show serum Na<sup>+</sup>, 115 mmol/L (136–145 mEq/L); K<sup>+</sup>, 3.9 mmol/L (3.5–5.0 mEq/L); Cl&#8722;, 82 mmol/L (95–105 mEq/L); CO<sub>2</sub>, 23 mmol/L (23–29 mmol/L); glucose, 73 mg/dL (fasting, 70–110 mg/dL); and creatinine, 1 mg/dL (0.6–1.2 mg/dL). The hyponatremia is corrected over the next 2 hours with intravenous fluid and electrolyte therapy. She then rapidly becomes confused and exhibits limb weakness. No papilledema is seen on funduscopic examination. An MRI shows loss of myelin in the region of the pons. Which of the following complications has most likely occurred in this woman?`,
        q2: ``,
        q3: [],
        option: [`Osmotic demyelination syndrome`, `Cerebellar tonsillar herniation`,` Intraventricular hemorrhage`,`Subacute combined degeneration of the cord`,` Wernicke-Korsakoff syndrome`],
       optionFeedback: [`Rapid correction of hyponatremia can cause osmotic demyelination in the basis pontis `,`Cerebellar herniation would be associated with papilledema.`,`Intraventricular hemorrhage would not result from hyponatremia.`,`Subacute combined degeneration of the cord results from deficiency of vitamin B<sub>12</sub>.`,`Wernicke-Korsakoff syndrome is an uncommon complication of chronic alcoholism.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Rapid correction of hyponatremia can cause osmotic demyelination in the basis pontis (central pontine myelinolysis). `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 68-year-old woman with a 7-year history of progressive dementia dies of bronchopneumonia. At autopsy, there is cerebral atrophy in a predominantly frontal and parietal lobe distribution. Microscopic examination of the brain shows numerous neuritic plaques in the hippocampus, amygdala, and neocortex. Neurofibrillary tangles in the hippocampus contain tau protein. Which of the following mechanisms is the most important factor in the development of her disease?`,
        q2: ``,
        q3: [],
        option: [`Expansion of glutamine-encoding CAG repeats`, `Inheritance of HLA-DR3/DR4 alleles`,`Increased tandem repeats in the FMR1 gene`,`Mutation of a prion protein gene`,`Self-aggregation of Aβ peptide`],
       optionFeedback: [`Expansion of glutamine-encoding trinucleotide repeats is seen in Huntington disease and other neurodegenerative diseases.`,`Association with particular HLA alleles is often seen in autoimmune diseases. HLA-DR3/DR4 associations are seen in type 1 diabetes.`,`Tandem repeats in the FMR1 gene cause the fragile X syndrome, the second most common genetic cause of intellectual disability (after Down syndrome).`,`Prion mutations cause prion disease, such as Creutzfeldt-Jakob disease, a rapidly progressive form of dementia.`,`Progressive dementia with plaques and tangles is characteristic of Alzheimer disease, in which aggregated Aβ peptides play hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Progressive dementia with plaques and tangles is characteristic of Alzheimer disease, in which aggregated Aβ peptides play a central pathogenic role.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 60-year-old man had increasing irritability over 3 years. He wandered about his neighborhood, complaining to the neighbors about everything. He had no memory loss and was able to find his way home. More recently, he developed aphasia. On physical examination, there were no motor or sensory deficits and no gait disturbances or tremor. MRI of the brain showed bilateral marked temporal and frontal lobe gyral atrophy. He died of pneumonia 1 year later. At autopsy, the frontal cortex microscopically shows extensive neuronal loss, and some remaining neurons show intracytoplasmic inclusions that stain immunohistochemically for tau protein. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [` Alzheimer disease`, ` Huntington disease`,`Frontotemporal lobe degeneration`,`Parkinson disease`,`Prion disease`],
       optionFeedback: [`Alzheimer disease presents with memory loss and progressive dementia, and the cerebral cortex is globally atrophic, not limited to the frontotemporal lobes. Microscopic examination reveals prominent plaques and neurofibrillary tangles.`,`Huntington disease presents with movement disorder caused by atrophy of the caudate and putamen.`,`Behavioral and language problems without memory loss are typical of frontotemporal lobar degeneration (FTLD, clinically known as frontotemporal dementia). Involvement of frontal and temporal lobes and the presence of tau inclusions are characteristic. `,`Parkinson disease is a movement disorder characterized by tremors and rigidity caused by loss of neurons in the substantia nigra and globus pallidus.`,`Prion disease is a rapidly progressive form of dementia.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Behavioral and language problems without memory loss are typical of frontotemporal lobar degeneration (FTLD, clinically known as frontotemporal dementia). Involvement of frontal and temporal lobes and the presence of tau inclusions are characteristic. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 55-year-old man has had increasing difficulty with initiation of voluntary movements and increasing inability to perform activities of daily living for 1 year. On physical examination, he has tremors at rest and rigidity of the limbs. The right side of the figure shows the gross appearance of the midbrain of this patient; on the left is a section through normal midbrain. Pathologic effects of this disease are most likely related to which of the following inclusions in the nucleus?`,
        q2: `<img src="../images/f017-q035-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [` Huntingtin`, `Frataxin`,` α-Synuclein`,`Tau`,`Aβ amyloid`],
       optionFeedback: [`Trinucleotide repeat expansions in the gene encoding huntingtin cause Huntington disease, a movement disorder with repetitive jerky movements. No inclusions are seen in the disease. `,`Mutations in the gene that encode frataxin, usually trinucleotide repeat expansions, are the cause of Friedrich ataxia, which usually presents with gait difficulty (ataxia) early in life. Lesions are mostly in the cerebellum and spinal cord (hence the name spinocerebellar ataxias for this group of disorders), but no inclusions are seen.`,`Movement disorder (tremors and rigidity) with loss of neurons in the substantia nigra (seen as pallor in the brain section) are diagnostic of Parkinson disease. Inclusions of α-synuclein, forming Lewy bodies, are implicated in the pathogenesis of this disease. `,`Tau aggregates are associated with frontotemporal lobar degeneration (FTLD) and Alzheimer disease, but inclusions are not present.`,`Aβ aggregates form amyloid within neuritic plaques in Alzheimer disease; they do not form intranuclear inclusions.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Movement disorder (tremors and rigidity) with loss of neurons in the substantia nigra (seen as pallor in the brain section) are diagnostic of Parkinson disease. Inclusions of α-synuclein, forming Lewy bodies, are implicated in the pathogenesis of this disease. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 47-year-old woman has a 1-year history of difficulty performing activities of daily living. She is emotionally labile and often cries. On physical examination, she has involuntary, jerky movements of her extremities. Cranial nerves are intact. She has no motor weakness and no sensory deficits. Her memory is normal. Family history is relevant for the deaths of her father and brother 5 years after experiencing the same symptoms. Which of the following genetic abnormalities is most likely to be present in this woman?`,
        q2: ``,
        q3: [],
        option: [`Mutant prion protein`, `Mutation in superoxide dismutase-1 (SOD1) gene`,`Trisomy 21`,`Expansion of glutamine-encoding CAG repeats`,`Mutation in presenilin genes`],
       optionFeedback: [`Mutant prion protein causes prion disease, a rapidly progressive form of dementia.`,`Mutations in the SOD gene are associated with familial forms of amyotrophic lateral sclerosis (ALS), which affects motor neurons in the spinal cord and brain stem and presents with progressive weakness.`,`Trisomy 21 causes Down syndrome and is associated with Alzheimer disease, not Huntington disease.`,`The family history suggests an autosomal dominant disease and the patient’s jerky (“choreiform”) movements are characteristic of Huntington disease, which is caused by expansion of CAG repeats in the huntingtin (HTT) gene. `,`Mutations in presenilin are associated with an early-onset form of Alzheimer disease.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The family history suggests an autosomal dominant disease and the patient’s jerky (“choreiform”) movements are characteristic of Huntington disease, which is caused by expansion of CAG repeats in the huntingtin (HTT) gene. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 36-year-old, previously healthy man now has progressive, symmetric muscular weakness. A year ago, he noted weakness in the area of the head and neck, which caused difficulty with speech, eye movements, and swallowing. In the past year, the weakness in the upper and lower extremities has increased, and he can no longer stand, walk, or feed himself. Injury to which of the following cells is the most likely cause of the patient’s symptoms?`,
        q2: ``,
        q3: [],
        option: [` Ependymal cell`, `Lower motor neuron`,`Microglial cell`,`Oligodendrocyte`,`Substantia nigra neuron`],
       optionFeedback: [`There are no known diseases with selective destruction of these cell types.`,`Progressive symmetric muscle weakness is typical of amyotrophic lateral sclerosis, a disease in which lower motor neurons in the spinal cord (and brain stem) are destroyed, as well as upper motor neurons in the cortex. `,`There are no known diseases with selective destruction of these cell types.`,`JC virus selectively infects oligodendrocytes and is the etiologic agent of progressive multifocal leukoencephalopathy (PML), a disease that occurs almost exclusively in immunosuppressed adults.`,`Substantia nigra neurons are lost in Parkinson disease.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Progressive symmetric muscle weakness is typical of amyotrophic lateral sclerosis, a disease in which lower motor neurons in the spinal cord (and brain stem) are destroyed, as well as upper motor neurons in the cortex.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 70-year-old man who had remained healthy most of his life began to have subtle memory loss 6 months ago that became progressively worse. Because he could no longer take care of himself, he was admitted to a nursing home. The physician who examined him found no other symptoms or signs of neurologic diseases. His muscle strength was preserved and he did not have any jerky movements or rigidity. He died within 4 weeks of admission with terminal pneumonia. At autopsy, the brain appeared grossly normal. Histologically, there was extensive neuron loss and spongiform transformation of the cerebral cortex and deep gray matter structures due to presence of multiple small vacuoles in the surviving neurons. Which of the following mechanisms is the most likely cause of this disease?`,
        q2: ``,
        q3: [],
        option: [`Mutation in presenilin genes`, ` Misfolding of prion proteins `,`Aggregation of hyperphosphorylated tau`,`Loss of dopamine–producing neurons`,`Polyglutamine expansion of frataxin`],
       optionFeedback: [`Mutations in presenilin are associated with an early-onset form of Alzheimer disease, a slowly progressive disorder.`,`Rapidly progressive neurodegenerative disease beginning with memory loss is suspicious for a prion disease, and the picture of spongiform encephalopathy (due to loss of brain cells) is diagnostic of Creutzfeldt-Jakob disease, which is caused by misfolding of prion protein (PrP). Normal prion proteins (PrP<sup>C</sup>) are membrane proteins found in all cells and are particularly abundant in neurons. At some very low rate that can be increased by mutation, PrP<sup>C</sup> can undergo conversion to a protease-resistant, misfolded pathogenic conformation called PrP<sup>SC</sup>. When PrP<sup>SC</sup> interacts with PrP<sup>C</sup>, it converts the normal protein into PrP<sup>SC</sup>, thus propagating itself like an infectious agent. It is not known why normal PrP<sup>C</sup> undergoes the initial conformational change.`,`Aggregates of hyperphosphorylated tau are associated with some forms of frontotemporal lobar degeneration and Alzheimer disease.`,`Loss of dopamine-producing neurons in the substantia nigra causes Parkinson disease.`,`Mutations in the gene encoding frataxin, usually trinucleotide repeat expansions, are the cause of Friedrich ataxia, which usually presents with gait difficulty (ataxia) early in life. Lesions are mostly in the cerebellum and spinal cord (hence the name spinocerebellar ataxias for this group of disorders), but no inclusions are seen.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Rapidly progressive neurodegenerative disease beginning with memory loss is suspicious for a prion disease, and the picture of spongiform encephalopathy (due to loss of brain cells) is diagnostic of Creutzfeldt-Jakob disease, which is caused by misfolding of prion protein (PrP). Normal prion proteins (PrP<sup>C</sup>) are membrane proteins found in all cells and are particularly abundant in neurons. At some very low rate that can be increased by mutation, PrP<sup>C</sup> can undergo conversion to a protease-resistant, misfolded pathogenic conformation called PrP<sup>SC</sup>. When PrP<sup>SC</sup> interacts with PrP<sup>C</sup>, it converts the normal protein into PrP<sup>SC</sup>, thus propagating itself like an infectious agent. It is not known why normal PrP<sup>C</sup> undergoes the initial conformational change.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 55-year-old man has a 2-month history of chronic headaches. He presents at the Emergency Department following a generalized tonic-clonic seizure. Physical examination reveals left-sided weakness. An MRI of his brain shows a large, irregular, 6-cm mass in the right cerebral hemisphere that extends across the corpus callosum. Histologic examination of a stereotaxic biopsy of the mass reveals pleomorphic cells positive for glial fibrillary acidic protein (GFAP). Molecular analysis shows IDH1 mutations but no 1p/19q deletions. Which of the following neoplasms is he most likely to have?`,
        q2: ``,
        q3: [],
        option: [`Diffuse large B-cell lymphoma`, ` Anaplastic astrocytoma`,`Hemangioblastoma`,`Medulloblastoma`,`Pilocytic astrocytoma`],
       optionFeedback: [`Diffuse large B-cell lymphomas are typically not pleomorphic and do not harbor IDH mutations.  `,`The clinical presentation is typical for a brain tumor, and IDH mutation identifies it as a type of astrocytoma or oligodendroglioma. Oligodendrogliomas show variable expression of GFAP whereas most astrocytomas are GFAP positive. 1p/19q co-deletions are more common in oligodendrogliomas. Histologically, oligodendrogliomas have round nuclei and perinuclear halos, a “fried egg” appearance resembling normal oligodendrocytes.`,`Hemangioblastomas are associated with von Hippel-Lindau disease and are most common in the cerebellum and retina. They do not harbor IDH mutations.`,`Medulloblastoma most commonly arises in the midline of the cerebellum in pediatric patients, but may occur laterally in adults. Like astrocytoma, medulloblastoma is GFAP positive; however, these tumors do not harbor IDH mutations.`,`Pilocytic astrocytomas most commonly arise in the cerebellum of children and young adults. Pilocytic astrocytoma has a relatively benign behavior and, like astrocytoma, is GFAP positive; however, it does not harbor IDH mutations.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical presentation is typical for a brain tumor, and IDH mutation identifies it as a type of astrocytoma or oligodendroglioma. Oligodendrogliomas show variable expression of GFAP whereas most astrocytomas are GFAP positive. 1p/19q co-deletions are more common in oligodendrogliomas. Histologically, oligodendrogliomas have round nuclei and perinuclear halos, a “fried egg” appearance resembling normal oligodendrocytes.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 10-year-old boy has had persistent headaches for the past 3 months. He is afebrile and displays an ataxic gait. CT scan of the head shows a 4-cm cystic mass in the right cerebellar hemisphere. The CSF protein concentration is elevated but the glucose level is normal. Neurosurgery is performed, and the mass is removed and sectioned. On gross examination, the mass is a cyst filled with gelatinous material. The cyst has a thin wall and a 1-cm mural nodule. Microscopically, the mass is composed of cells that stain positive for glial fibrillary acidic protein (GFAP) and have long, hair like processes. BRAF mutations are present, but no IDH mutation is identified. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Pilocytic astrocytoma`, `Ependymoma`,`Hemangioblastoma`,`Medulloblastoma`,`Meningioma `],
       optionFeedback: [`A slow-growing cystic cerebellar astrocytic (GFAP+) tumor with a mural nodule in a child is diagnostic of pilocytic astrocytoma. These tumors sometimes have mutations in BRAF but not in `,`Ependymoma is not derived from astrocytes and, therefore, is GFAP negative. They typically occur adjacent to ventricles.`,`Hemangioblastoma typically arises in the cerebellum (often as part of the von Hippel-Lindau syndrome), but is a GFAP-negative, highly vascular tumor. It lacks BRAF mutations.`,`Medulloblastoma is also a cerebellar tumor of children, composed of small blue cells having hyperchromatic nuclei and scant cytoplasm on H&amp;E stain.`,`Meningioma occurs on the external surface attached to the dura. Meningioma rarely occurs in children and is GFAP negative.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- A slow-growing cystic cerebellar astrocytic (GFAP+) tumor with a mural nodule in a child is diagnostic of pilocytic astrocytoma. These tumors sometimes have mutations in BRAF but not in IDH. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 40-year-old man has a 6-month history of headaches and had a seizure 1 day ago. Physical examination is unremarkable. MRI of the brain shows a solitary, circumscribed 3-cm mass in the right parietal lobe. The mass has small cysts and areas of calcification and hemorrhage. Neurosurgery is performed, and the mass is removed. Microscopically, the mass consists of sheets of cells with “fried egg” appearance. The patient receives adjuvant radiation and chemotherapy, and there is no recurrence. Which of the following molecular markers is most likely to be found in the cells of this mass?`,
        q2: ``,
        q3: [],
        option: [`BRAF mutation`, `CD20 expression`,`WNT pathway activation`,`EGFR amplification`,`1p and 19q co-deletions`],
       optionFeedback: [`Among brain tumors, BRAF mutation is most often seen in pilocytic astrocytoma.`,`CD20 is a B-cell marker expressed in non-Hodgkin lymphoma.`,`WNT pathway activation is seen in medulloblastoma.`,`EGFR amplification is seen in glioblastoma.`,`This cystic hemorrhagic tumor composed of cells with perinuclear halos, responsible for the “fried-egg” appearance, is an oligodendroglioma. Co-deletion of large segments of chromosomes 1p hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- This cystic hemorrhagic tumor composed of cells with perinuclear halos, responsible for the “fried-egg” appearance, is an oligodendroglioma. Co-deletion of large segments of chromosomes 1p and 19q is characteristic. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 46-year-old woman has had increasing weakness and loss of sensation in the lower extremities for the past 5 months. She has been unable to walk without assistance for the past week. On physical examination, there is 4/5 motor strength in the right lower extremity and 3/5 motor strength in the left lower extremity. There is bilateral loss of sensation to light touch from the lateral mid-thigh distally. MRI of the spine shows a 1 &#215; 4 cm lesion in the spinal cord. The mass is removed. Microscopically, the tumor is composed of cuboidal cells forming rosettes. Which of the following lesions was most likely present in this patient?`,
        q2: ``,
        q3: [],
        option: [`Choroid plexus papilloma`, `Ependymoma`,`Meningioma`,`Neurofibroma`,`Pilocytic astrocytoma`],
       optionFeedback: [`Choroid plexus papillomas resemble normal choroid plexus histologically, with cells showing microvilli and scattered cilia. The symptoms are related to increased CSF pressure (e.g., headache), not peripheral nerve abnormalities.`,`Ependymoma arises from the ependymal cells lining the ventricular system, and is most often found adjacent to these channels. In the first two decades of life, ependymoma most commonly arises near the fourth ventricle, while in adults it mainly occurs in the spinal cord. Tumor cells may form rosettes or canals that resemble the embryonic ependymal canal. The histologic appearance of this spinal cord tumor is diagnostic of ependymoma. The motor and sensory abnormalities are due to compression of nerve roots by the tumor.`,`Meningioma usually arises from the arachnoid and the vast majority is intracranial.`,`Neurofibroma is a peripheral nerve tumor; ependymomas may be associated with the neurofibromatosis, type 2.`,`Pilocytic astrocytoma is a slow-growing cystic cerebellar astrocytic tumor in a child or young adult.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Ependymoma arises from the ependymal cells lining the ventricular system, and is most often found adjacent to these channels. In the first two decades of life, ependymoma most commonly arises near the fourth ventricle, while in adults it mainly occurs in the spinal cord. Tumor cells may form rosettes or canals that resemble the embryonic ependymal canal. The histologic appearance of this spinal cord tumor is diagnostic of ependymoma. The motor and sensory abnormalities are due to compression of nerve roots by the tumor.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 45-year-old woman has a 5-month history of right-sided unilateral headaches. Physical examination is unremarkable. CT scan of the brain reveals a parasagittal dural mass that compresses the underlying brain. A representative gross appearance of the lesion is shown in the figure. The mass is surgically removed and microscopic examination shows elongated cells with pale, oblong nuclei and pink cytoplasm with occasional psammoma bodies. Cytogenetic analysis shows 22q- with loss of NF2 gene. Which of the following is the most likely diagnosis?`,
        q2: `<img src="../images/f017-q044-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Astrocytoma`, `Ependymoma`,`Meningioma`,`Metastasis`,`Tuberculoma`],
       optionFeedback: [`Astrocytoma is a parenchymal tumor usually arising in the cerebral hemispheres. The cells show mild atypia. Psammoma bodies are not common.`,`Ependymoma is a ventricular tumor characterized by cuboidal cells forming rosettes.`,`Meningioma arises from meningothelial cells of the arachnoid and appears as if attached to the overlying dura. The described histology is characteristic. Loss of NF2 is seen in about half of solitary meningiomas.`,`Metastatic tumor would reflect the histology of the original tumor, and is often multiple.`,`Focal tuberculous lesions are large enough to produce a mass effect and usually show granulomatous inflammation but no tumor cells.hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Meningioma arises from meningothelial cells of the arachnoid and appears as if attached to the overlying dura. The described histology is characteristic. Loss of NF2 is seen in about half of solitary meningiomas.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 41-year-old woman has a 4-month history of gradual hearing loss. On physical examination, she has decreased hearing on the left. A head MRI shows a sharply circumscribed, 4-cm mass adjacent to the left pons that extends toward the left inferior cerebellar hemisphere. A smaller 1-cm lesion is in a similar location on the right. Family screening reveals a similarly affected 38-year-old sibling. An inherited mutation involving which of the following genes is most likely to be present in this patient?`,
        q2: ``,
        q3: [],
        option: [`NF2`, ` TP53`,`PTCH1`,`TSC1`,`VHL`],
       optionFeedback: [`The patient has bilateral tumors located in the cerebellopontine angle arising from the eighth cranial nerve (causing impaired hearing). These tumors are schwannomas (also called acoustic neuromas); bilateral tumors are seen in the context of neurofibromatosis 2 which is due to a germline mutation in the NF2 gene. NF2 encodes merlin, a cytoskeletal protein that functions as a tumor suppressor by E-cadherin–mediated contact inhibition.`,`TP53 mutations give rise to the Li-Fraumeni syndrome, which is associated with multiple tumors, including medulloblastoma.`,`PTCH1 mutations give rise to nevoid basal cell carcinoma (Gorlin) syndrome and medulloblastomas.`,`TSCI mutations are associated with cortical hamartomas in the setting of tuberous sclerosis, an autosomal dominant disease characterized by hamartomas and benign tumors in the CNS (cortical tubers and subependymal nodules) and throughout the body (e.g., renal angiomyolipomas, retinal glial hamartomas, cardiac rhabdomyomas). Two genes have been linked to tuberous sclerosis: TSC1 and TSC2, which encode hamartin and tuberin, respectively.`,`VHL mutations give rise to renal cell cancers and cerebellar hemangioblastomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The patient has bilateral tumors located in the cerebellopontine angle arising from the eighth cranial nerve (causing impaired hearing). These tumors are schwannomas (also called acoustic neuromas); bilateral tumors are seen in the context of neurofibromatosis 2 which is due to a germline mutation in the NF2 gene. NF2 encodes merlin, a cytoskeletal protein that functions as a tumor suppressor by facilitating E-cadherin–mediated contact inhibition.`,
        state: `notAnswered`,
        userAnswered: [],
    }
    

   ];
