var quiz = [
    {
        q: `A 24-year-old woman gives birth to a term infant after an uncomplicated pregnancy. Three days after birth, the infant vomits all oral feedings. On physical examination, the abdomen is distended and tender, and bowel sounds are reduced. An abdominal ultrasound scan shows marked colonic dilation above a narrow segment in the distal sigmoid region. A biopsy specimen from the narrowed region shows an absence of ganglion cells in the muscle wall and submucosa. Which of the following conditions is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Colonic atresia`, `Hirschsprung disease`, `Intussusception`,` Necrotizing enterocolitis`,` Volvulus`],
        optionFeedback: [`Colonic atresia is very rare. It may also present with obstruction, but the biopsy would not show an absence of ganglion cells.`,`<!--Answers:-->Colonic obstruction in a newborn indicates a congenital disease. The absence of ganglion cells in the wall of the colon is diagnostic for Hirschsprung disease. `,`Intussusception is telescoping of the bowel through a distal portion, sometimes caused by a tumor or traction on an enlarged mesenteric lymph node, but usually without an identifiable cause.`,`Necrotizing enterocolitis is a bacterial infection that presents with bloody diarrhea. It is a complication of prematurity and typically involves terminal ileum, cecum, and right colon; it does not present with obstruction.`,`Volvulus (twisting of the intestine) also presents later in life and may be diagnosed by ultrasound or radiologically. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Colonic obstruction in a newborn indicates a congenital disease. The absence of ganglion cells in the wall of the colon is diagnostic for Hirschsprung disease.    `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 22-year-old woman has had multiple episodes of aspiration of food associated with difficulty swallowing during the past year. On auscultation of her chest, crackles are heard at the base of the right lung. A barium swallow shows marked esophageal dilation above the level of the lower esophageal sphincter. A biopsy specimen from the lower esophagus is most likely to show which of the following lesions?`,
        q2: ``,
        q3: [],
        option: [`Absence of myenteric ganglia`, `Barrett esophagus`,`Esophageal atresia`,`Esophageal carcinoma`,` Systemic sclerosis`],
        optionFeedback: [`<!--Answers:-->Achalasia is characterized by the triad of incomplete lower esophageal sphincter (LES) relaxation, increased LES tone, and esophageal aperistalsis. It causes functional obstruction of the esophagus. Primary achalasia is due to ganglion cell degeneration from unknown causes. Secondary achalasia may arise in the setting of Chagas disease following Trypanosoma cruzi-mediated destruction of ganglion cells.`,` Barrett esophagus is a complication of chronic gastroesophageal reflux disease (GERD) and is characterized by metaplasia of the normal squamous esophageal epithelium to columnar epithelium, typically with goblet cells. It is a risk factor for esophageal carcinoma.`,`Esophageal atresia is a rare congenital anomaly that presents with signs of obstruction shortly after birth.`,`Esophageal carcinomas are uncommon in young individuals and present with dysphagia.`,`In systemic sclerosis, there is fibrosis of the esophageal wall and associated dysphagia. Esophageal dilation is not a feature of this disease.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale:- Achalasia is characterized by the triad of incomplete lower esophageal sphincter (LES) relaxation, increased LES tone, and esophageal aperistalsis. It causes functional obstruction of the esophagus. Primary achalasia is due to ganglion cell degeneration from unknown causes. Secondary achalasia may arise in the setting of Chagas disease following Trypanosoma cruzi-mediated destruction of ganglion cells. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 51-year-old man has sudden onset of massive emesis of bright red blood. On physical examination, his temperature is 36.9° C, pulse is 103 beats/min, respirations are 23 breaths/min, and blood pressure is 85/50 mm Hg. His spleen tip is palpable. Laboratory studies show a hematocrit of 21% (41%–53%). The serologic test result for HBsAg is positive. He has had no prior episodes of hematemesis. The hematemesis is most likely to be a consequence of which of the following?`,
        q2: ``,
        q3: [],
        option: [`Barrett esophagus`, `Candida albicans infection`,`Esophageal varices`,`Reflux esophagitis`,`Squamous cell carcinoma`],
        optionFeedback: [`Barrett esophagus is an epithelial lesion of the esophagus that predisposes to carcinoma. It does not cause bleeding. `,`C. albicans causes superficial inflammation with ulcers in the oral cavity and esophagus. It may cause pain but does not present with sudden bleeding. `,`<!--Answers:-->The low hematocrit and hematemesis indicate significant blood loss, and the positive test for HBsAg indicates liver disease. The palpable spleen supports the diagnosis of portal hypertension secondary to cirrhosis. One of the complications of portal hypertension is esophageal varices, which can lead to gradual blood loss as well as severe acute bleeding (hematemesis). `,`Reflux esophagitis presents with heartburn and not sudden massive blood loss. `,`Squamous cell carcinoma of the esophagus causes difficulty in swallowing and may ulcerate, with some blood loss, but rarely massive sudden hematemesis. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The low hematocrit and hematemesis indicate significant blood loss, and the positive test for HBsAg indicates liver disease. The palpable spleen supports the diagnosis of portal hypertension secondary to cirrhosis. One of the complications of portal hypertension is esophageal varices, which can lead to gradual blood loss as well as severe acute bleeding (hematemesis). `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 55-year-old man has had increasing difficulty swallowing during the past 6 months. There are no significant findings on physical examination. Upper gastrointestinal endoscopy shows a 3 cm area of erythematous mucosa at the gastroesophageal junction. A biopsy specimen from the lower esophagus shows metaplasia of the squamous epithelium to columnar epithelium with some mucin-filled goblet cells. Which of the following complications is most likely to occur as a consequence of this patient’s condition?`,
        q2: ``,
        q3: [],
        option: [`Achalasia`, `Adenocarcinoma`,` Diverticulum formation`,` Lacerations`,`Squamous cell carcinoma`],
        optionFeedback: [`Achalasia is a developmental defect that leads to loss of the myenteric plexus in the esophagus, impairing peristalsis and swallowing.`,`<!--Answers:-->Squamous to columnar epithelial metaplasia in the lower esophagus is diagnostic of Barrett esophagus. The greatest risk with this lesion is the development of adenocarcinoma in the area of metaplasia. `,`Diverticula are most commonly seen in the colon and rectum. They are not associated with columnar metaplasia of the epithelium.`,`Esophageal lacerations are caused by trauma associated with severe vomiting or retching.`,`Squamous cell carcinoma occurs in the esophagus, but it is not a tumor that occurs in areas of Barrett esophagus. It typically affects the mid portion of the esophagus and is associated with alcohol use, smoking and HPV infection.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Squamous to columnar epithelial metaplasia in the lower esophagus is diagnostic of Barrett esophagus. The greatest risk with this lesion is the development of adenocarcinoma in the area of metaplasia.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 68-year-old man has a 25-year history of heartburn and substernal pain after meals. For the past year, he has had increased pain and difficulty swallowing liquids and solids. On physical examination, there are no remarkable findings. Upper gastrointestinal endoscopy shows an ulcerated lower esophageal mass that nearly occludes the lumen of the esophagus. A biopsy specimen of this mass is most likely to show which of the following neoplasms?`,
        q2: ``,
        q3: [],
        option: [`Adenocarcinoma`, `Neuroendocrine tumor`,` Gastrointestinal stromal tumor`,`Non-Hodgkin lymphoma`,`Squamous cell carcinoma`],
        optionFeedback: [`<!--Answers:-->Long-standing esophageal reflux, as in this patient, is associated with Barrett esophagus and subsequent development of adenocarcinoma in the metaplastic epithelium.`,`Neuroendocrine tumors are usually seen in the intestines, less often in the stomach, and rarely in the esophagus. These tumors sometimes present clinically with signs related to production of various hormones, including catecholamines. `,`Gastrointestinal stromal tumors are quite rare in the esophagus; more than half occur in the wall of the stomach.`,`Extranodal B-cell lymphoma frequently arises in the stomach or the small bowel, but esophageal lymphoma is rare. `,`Squamous cell carcinoma is associated with alcohol use, smoking and HPV infection, but usually not with esophageal reflux. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Long-standing esophageal reflux, as in this patient, is associated with Barrett esophagus and subsequent development of adenocarcinoma in the metaplastic epithelium.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 73-year-old man with a history of chronic alcoholism has had increasing difficulty swallowing and has noticed a 3-kg weight loss over the past 2 months. On physical examination, there are no remarkable findings. Upper gastrointestinal endoscopy shows a 3-cm, ulcerated mass in the midesophagus that partially occludes the esophageal lumen. Which of the following is most likely to be seen on microscopic evaluation of this mass?`,
        q2: ``,
        q3: [],
        option: [`Adenocarcinoma`, `Esophagitis with numerous eosinophils`,`Dilated vascular channels`,`Columnar metaplasia`,`Squamous cell carcinoma`],
        optionFeedback: [`Adenocarcinoma of the esophagus is usually seen in areas of Barrett esophagus, which is associated with a history of reflux. Tumors are typically centered in the lower third of the esophagus, not in the midesophagus as this one is.`,`Esophagitis with numerous eosinophils (eosinophilic esophagitis) is an allergic disease often associated with asthma. It does not present with an obstructive mass. `,`Dilated vascular channels in the wall of the esophagus are varices, most often seen in patients with portal hypertension secondary to cirrhosis. These vessels may present with bleeding but not an obstructive mass. `,`Columnar metaplasia is diagnostic of Barrett esophagus. It develops secondary to reflux and may be a precursor of adenocarcinoma. The metaplasia is associated with symptoms of reflux but not an obstructive mass.`,`<!--Answers:-->Esophageal obstruction (manifested by difficulty in swallowing) and weight loss in a person with a history of chronic alcohol use is suspicious for squamous cell carcinoma of the esophagus. This diagnosis can be confirmed by upper GI endoscopy and histologic examination of the biopsy. `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Esophageal obstruction (manifested by difficulty in swallowing) and weight loss in a person with a history of chronic alcohol use is suspicious for squamous cell carcinoma of the esophagus. This diagnosis can be confirmed by upper GI endoscopy and histologic examination of the biopsy.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 72-year-old man has been taking nonsteroidal antiinflammatory drugs (NSAIDs) for the past two years because of chronic degenerative arthritis of the hips and knees. Over the past 2 weeks, he has had epigastric pain with nausea and vomiting and an episode of hematemesis. On physical examination, there are no remarkable findings. A gastric biopsy specimen shows shallow ulcerations with neutrophils. Which of the following is the most likely mechanism of the gastric lesions?`,
        q2: ``,
        q3: [],
        option: [`Reduced prostaglandin production`, `Infection with H. pylori`,`Increased bicarbonate secretion `,`Increased mucosal blood flow `,`Stimulation of vagus nerve`],
        optionFeedback: [`<!--Answers:-->Prostaglandins produced in the gastric epithelium promote numerous protective mechanisms, including suppression of acid secretion, increased production of mucins, and increased blood flow and epithelial restitution after injury. NSAIDs inhibit prostaglandin production, which suppresses inflammation systemically (prostaglandins are important mediators of inflammation). Individuals treated chronically with NSAIDs develop gastritis with acute ulcers because of the loss of mucosal defenses. `,`H. pylori infection is a cause of gastritis and ulcers but is unrelated to NSAID use.`,`Bicarbonate counteracts the effects of gastric acid and is thus also protective of the gastric mucosa. NSAIDs inhibit, rather than increase, bicarbonate production.`,`Prostaglandins promote mucosal blood flow, so their inhibition by NSAIDs results in reduced blood flow.`,`Vagal nerve stimulation is implicated as a causative factor in gastric “stress ulcers” associated with intracranial injury.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Prostaglandins produced in the gastric epithelium promote numerous protective mechanisms, including suppression of acid secretion, increased production of mucins, and increased blood flow and epithelial restitution after injury. NSAIDs inhibit prostaglandin production, which suppresses inflammation systemically (prostaglandins are important mediators of inflammation). Individuals treated chronically with NSAIDs develop gastritis with acute ulcers because of the loss of mucosal defenses.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 51-year-old woman has been feeling increasingly tired for the past 7 months. There are no remarkable findings on physical examination. Laboratory studies include hemoglobin, 9.5 g/dL (12.0–16.0 g/dL); hematocrit, 29.1% (36%–46%); mean corpuscular volume (MCV), 124 µm<sup>3</sup> (80–100 μm<sup>3</sup>); platelet count, 168,000/mm<sup>3</sup> (150,000–400,000/mm<sup>3</sup>) and WBC count, 4,350/mm<sup>3</sup> (4,500–11,000/mm<sup>3</sup>). Hypersegmented polymorphonuclear leukocytes (PMNs) are found on a peripheral blood smear. The serum gastrin is markedly increased. Antibodies directed against which of the following are most likely to be found in this patient?`,
        q2: ``,
        q3: [],
        option: [`Gastric parietal cells `, `Gliadin`,`Helicobacter pylori`,`Gastric antral cells`,`Tropheryma whipplei `],
        optionFeedback: [`<!--Answers:-->The clinical presentation (insidious onset of fatigue, anemia, hypersegmented PMNs and increased MCV are characteristic of megaloblastic anemias caused by deficiency of vitamin B<sub>12</sub> or folic acid. Folate deficiency is usually of nutritional origin, whereas B<sub>12</sub> deficiency may be caused by gastric disease that results in diminished intrinsic factor production or ileal disease that prevents uptake of B<sub>12</sub> intrinsic factor complexes. The increased gastrin production suggests that the stomach is involved by a disorder that is decreasing acid secretion. Collectively, these features indicate destruction of gastric parietal epithelial cells, which are the major producers of intrinsic factor (required for absorption of vitamin B<sub>12</sub>, which is essential for hematopoiesis) and gastric acid. The cause of this parietal damage is most often an autoimmune response. Autoantibodies are produced against the epithelial cells, but these may be secondary to a T-cell mediated attack on parietal cells, which is believed to be the source of the tissue damage. `,`Antibodies against gliadin (a component of gluten from wheat and other grains) are seen in celiac disease.`,`Antibodies against  H.   pylori may be seen in infected patients but do not cause lesions. This infection is associated with gastritis and peptic ulcer disease. Chronic bleeding from peptic ulcers may cause iron deficiency anemia, but not megaloblastic anemia. `,`Gastric antral cells are the site of injury in H. pylori gastritis and peptic ulcer disease, but not the targets of antibody-mediated injury. `,`T. whipplei is the cause of Whipple disease, an intestinal bacterial infection associated with malabsorption and systemic manifestations such as arthritis and cardiac abnormalities. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The clinical presentation (insidious onset of fatigue, anemia, hypersegmented PMNs and increased MCV are characteristic of megaloblastic anemias caused by deficiency of vitamin B<sub>12</sub> or folic acid. Folate deficiency is usually of nutritional origin, whereas B<sub>12</sub> deficiency may be caused by gastric disease that results in diminished intrinsic factor production or ileal disease that prevents uptake of B<sub>12</sub> intrinsic factor complexes. The increased gastrin production suggests that the stomach is involved by a disorder that is decreasing acid secretion. Collectively, these features indicate destruction of gastric parietal epithelial cells, which are the major producers of intrinsic factor (required for absorption of vitamin B<sub>12</sub>, which is essential for hematopoiesis) and gastric acid. The cause of this parietal damage is most often an autoimmune response. Autoantibodies are produced against the epithelial cells, but these may be secondary to a T-cell mediated attack on parietal cells, which is believed to be the source of the tissue damage.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 59-year-old man has had nausea and vomiting for 5 months. He has experienced no hematemesis. On physical examination, there is no abdominal tenderness, and bowel sounds are present. Upper gastrointestinal endoscopy shows erythematous areas of mucosa with thickened rugal folds in the gastric antrum. The microscopic appearance of a gastric biopsy specimen stained with a Steiner silver stain is shown in the figure. Which of the following factors is most likely responsible for this gastric mucosal pathology?`,
        q2: `<img src="../images/f012-q010-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Injury to gastric parietal cells`, `Infection with H. pylori`,`Production of heat-stable enterotoxin`,`Increase in gastric pH`,`Achlorhydria `],
        optionFeedback: [`Injury to parietal cells, as in autoimmune gastritis, would lead to reduced acid secretion.`,`<!--Answers:-->The clinical history and endoscopic appearance suggest chronic gastritis. The silver stain demonstrates the presence of bacteria with the appearance of H. pylori. This infection is associated with inflammation in the antral region. When intense, inflammatory infiltrates may create thickened rugal folds `,`Heat-stable enterotoxins are produced by enteropathogenic E. coli, which causes enterocolitis and diarrhea but not gastritis.`,`H. pylori-induced gastritis is associated with normal or decreased pH.   `,`Loss of acid-secreting parietal cells and resultant achlorhydria is a feature of autoimmune gastritis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical history and endoscopic appearance suggest chronic gastritis. The silver stain demonstrates the presence of bacteria with the appearance of H. pylori. This infection is associated with inflammation in the antral region. When intense, inflammatory infiltrates may create thickened rugal folds`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 47-year-old woman with a lengthy history of heartburn and dyspepsia experiences sudden onset of abdominal pain. On physical examination, she has severe mid-epigastric pain with guarding. Bowel sounds are reduced. An abdominal plain film radiograph shows free air under the left diaphragm. She is immediately taken to surgery, and a perforated duodenal ulcer is repaired. Infection with which of the following organisms is most likely to have produced these findings?`,
        q2: ``,
        q3: [],
        option: [`Campylobacter jejuni`, `Giardia lamblia`,`Helicobacter pylori`,`Shigella flexneri`,`Yersinia enterocolitica`],
        optionFeedback: [`Campylobacter jejuni infection causes enterocolitis but not gastritis or peptic ulcer disease.`,`Giardia is a flagellated protozoan parasite that also causes enterocolitis.`,`<!--Answers:-->Perforated duodenal ulcer in a patient with a history suggesting chronic gastritis is most often associated with H. pylori infection. `,`Shigella flexneri infection causes enterocolitis but not gastritis or peptic ulcer disease.`,`Yersinia enterocolitica infection causes enterocolitis but not gastritis or peptic ulcer disease.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Perforated duodenal ulcer in a patient with a history suggesting chronic gastritis is most often associated with H. pylori infection.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 35-year-old man has had epigastric pain for more than 1 year. The pain tends to occur 2 to 3 hours after a meal and is relieved if he takes antacids or eats more food. He has noticed a 4-kg weight gain in the past year. He does not smoke and drinks 1 glass of wine daily. The result of a urea breath test is positive, and a gastric biopsy specimen contains urease. He begins a 2-week course of antibiotics, but on day 4, he feels better and discontinues treatment. Three weeks later, the epigastric pain recurs. If he does not seek further treatment, he is at greatest risk for which one of the following complications?`,
        q2: ``,
        q3: [],
        option: [`Carcinoid syndrome`,`Fat malabsorption`,`Gastric carcinoma`,` Migratory thrombophlebitis`,` Vitamin B<sub>12</sub> deficiency `],
        optionFeedback: [`Carcinoid syndrome is the clinical manifestation of a carcinoid tumor (now called neuroendocrine neoplasm), which is not related to H. pylori infection.`,`Fat malabsorption results from chronic pancreatitis and intestinal disorders such as celiac disease and Crohn disease, but not gastritis.`,`<!--Answers:-->The history of epigastric pain suggests gastritis and the positive urea breath test and urease activity are diagnostic of H. pylori infection. Chronic infection predisposes to the development of gastric adenocarcinoma and extranodal marginal zone lymphoma (also known as mucosa-associated lymphoid tumor, or MALToma).`,`Migratory thrombophlebitis is associated with pancreatic carcinoma and other, usually mucin secreting, adenocarcinomas of the GI tract.`,`Vitamin B<sub>12</sub> deficiency is the result of autoimmune damage to gastric parietal cells and is the cause of pernicious anemia. It is not associated with H. pylori gastritis. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-  The history of epigastric pain suggests gastritis and the positive urea breath test and urease activity are diagnostic of H. pylori infection. Chronic infection predisposes to the development of gastric adenocarcinoma and extranodal marginal zone lymphoma (also known as mucosa-associated lymphoid tumor, or MALToma). `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 49-year-old woman has a history of peptic ulcer disease for which she has been treated with proton pump inhibitors. She presents now with nausea and abdominal discomfort after meals. On physical examination, there are no abnormal findings. Upper endoscopy is performed, and there are three ovoid nodules in the fundus and antrum, ranging from 1.0 to 2.0 cm in size. They have rounded smooth surfaces. Biopsies are taken and on microscopic examination there are irregular, cystically dilated, and elongated foveolar glands. Which of the following lesions does she most likely have?`,
        q2: ``,
        q3: [],
        option: [`Acute gastritis`,`Chronic H.   pylori gastritis`,`Fundic gland polyps`,`Gastric lymphoma`,`Gastric carcinoma`],
        optionFeedback: [`Acute gastritis is a mucosal inflammatory process associated with presence of neutrophils among epithelial cells or within mucosal glands. The surface epithelium is intact but there is foveolar cell hyperplasia. Acute gastritis is caused by disruption of protective mechanisms of gastric mucosa as may occur with ingestion of NSAIDs and in uremic patients.`,`Although this patient may have H. pylori gastritis associated with peptic ulcer disease, polyps are not typically seen in this setting, which is more commonly associated with loss of rugal folds when inflammation is severe.`,`<!--Answers:-->Fundic gland polyps are caused by chronic use of proton pump inhibitors, which inhibit production of gastric acid, leading to a compensatory increase in secretion of gastrin, which stimulates proliferation of oxyntic gland cells, the epithelial cells found in the gastric fundus. `,`Gastric lymphoma is also associated with H. pylori infection, but it usually presents as a tumor infiltrating the mucosa, not polypoid masses.`,`Gastric carcinoma is another lesion associated with chronic H. pylori infection. It presents as ulcerating masses and malignant glands infiltrating the stomach wall. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Fundic gland polyps are caused by chronic use of proton pump inhibitors, which inhibit production of gastric acid, leading to a compensatory increase in secretion of gastrin, which stimulates proliferation of oxyntic gland cells, the epithelial cells found in the gastric fundus.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 53-year-old woman has had nausea, vomiting, and mid-epigastric pain for 5 months. On physical examination, there are no significant findings. An abdominal CT scan shows gastric outlet obstruction. Upper gastrointestinal endoscopy shows an ulcerated 2 × 4 cm bulky mass in the antrum at the pylorus. A urease test is positive. Which of the following neoplasms is most likely to be seen in a biopsy specimen of this mass?`,
        q2: ``,
        q3: [],
        option: [`Adenocarcinoma`, `Leiomyosarcoma`,`Neuroendocrine carcinoma`,`Gastrointestinal stromal tumor (GIST)`,`Squamous cell carcinoma`],
        optionFeedback: [`<!--Answers:-->An obstructive mass associated with H. pylori infection (as indicated by the urease test) is typical of gastric adenocarcinoma. The diagnosis must be confirmed by biopsy. `,`This tumor is not associated with H. pylori infection, and typically does not present as obstructive masses in the antrum of the stomach.`,`This tumor is not associated with H. pylori infection. Endocrine cell hyperplasia may arise in the setting of autoimmune gastritis; rarely, this may progress to form small, multicentric, low-grade neuroendocrine (carcinoid) tumors that are not obstructive masses in the antrum of the stomach.`,`This tumor is not associated with  H. pylori infection, and typically does not present as obstructive masses in the antrum of the stomach. Histologically, GIST are composed of spindled to epithelioid cells.`,`Squamous cell carcinoma occurs in the esophagus and not in the stomach.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- An obstructive mass associated with H. pylori infection (as indicated by the urease test) is typical of gastric adenocarcinoma. The diagnosis must be confirmed by biopsy. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 67-year-old woman has experienced severe nausea, vomiting, early satiety, and a 9-kg weight loss over the past 4 months. On physical examination, she has muscle wasting. Upper gastrointestinal endoscopy shows that the entire gastric mucosa is eroded and rugal folds are lost. An abdominal CT scan shows that the stomach is small and shrunken. A biopsy shows sheets of mucin-filled cells infiltrating the gastric wall. Which of the following molecular alterations is most likely to be found in this lesion?`,
        q2: ``,
        q3: [],
        option: [`Loss of function mutation of the gene encoding E-cadherin`, `Loss of function mutation of the gene encoding beta-catenin`,`Activating mutations of the KIT gene`,`Activating mutations of the BCL6 gene`,`Activating mutations of the BRAF gene `],
        optionFeedback: [`<!--Answers:-->The clinical history is suggestive of a GI cancer, and the endoscopy and histology (sheets of mucin-filled cells infiltrating the gastric wall) are diagnostic for diffuse infiltrative gastric adenocarcinoma (formerly known as linitis plastica). This tumor is consistently associated with loss of expression of the adhesion molecule E-cadherin, which is due to acquired mutations in about half of sporadic cases and epigenetic downregulation in the remaining half. The loss of cellular adhesion enables the tumor to infiltrate tissues as single malignant cells. `,`Beta-catenin is mutated in the intestinal form of gastric adenocarcinoma. This protein is part of the Wnt signaling pathway, which is consistently hyperactive in this type of gastric tumor.`,`KIT encodes a tyrosine kinase; mutations in the gene leading to overactivity of the kinase are found in gastrointestinal stromal tumor and mast cell disease.`,`BCL6 is mutated in diffuse large cell B cell lymphoma.`,`Activating mutations of BRAF are found in numerous tumors, including melanoma and colon cancer, but not gastric cancers.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The clinical history is suggestive of a GI cancer, and the endoscopy and histology (sheets of mucin-filled cells infiltrating the gastric wall) are diagnostic for diffuse infiltrative gastric adenocarcinoma (formerly known as linitis plastica). This tumor is consistently associated with loss of expression of the adhesion molecule E-cadherin, which is due to acquired mutations in about half of sporadic cases and epigenetic downregulation in the remaining half. The loss of cellular adhesion enables the tumor to infiltrate tissues as single malignant cells. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 52-year-old man has had a 4-kg weight loss and nausea for the past 6 months. He has no vomiting or diarrhea. On physical examination, there are no remarkable findings. Upper gastrointestinal endoscopy shows a 6-cm area of irregular, pale fundic mucosa with loss of the rugal folds. A biopsy specimen shows a monomorphous infiltrate of lymphoid cells. Helicobacter pylori organisms are identified in mucus overlying adjacent mucosa. He receives antibiotic therapy for H. pylori, and a repeat biopsy specimen shows resolution of the infiltrate. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Autoimmune gastritis`,`Chronic gastritis`,`Diffuse large B-cell lymphoma`,` Gastrointestinal stromal tumor`,`Extranodal marginal zone lymphoma.`],
        optionFeedback: [`Autoimmune gastritis is not associated with H. pylori infection and does not present as a focal lesion with lymphoid infiltrates.`,`Chronic gastritis may be caused by H. pylori infection. It usually presents with epigastric discomfort and not a focal infiltrate of lymphoid cells. The inflammatory infiltrate seen in chronic gastritis is a mixed population of neutrophils, lymphocytes and macrophages, not a monomorphous population of lymphocytes.`,`Diffuse large B cell lymphoma is an aggressive neoplasm that may arise in the stomach. These tumors are not associated with H. pylori infection.`,`Gastrointestinal stromal tumor (GIST) is a mesenchymal tumor arising in the musculature of the gastric wall, not the mucosa. It is not associated with H. pylori infection. `,`<!--Answers:-->Patients with H. pylori infection develop lymphomas that typically arise from marginal zone B cells. These extranodal marginal zone lymphoma are also known as mucosa-associated lymphoid tumor, or MALToma. The continued growth of this tumor is dependent on the infection, suggesting that the host response to the bacteria is involved in initiation and maintenance of the tumor.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Patients with H. pylori infection develop lymphomas that typically arise from marginal zone B cells. These extranodal marginal zone lymphoma are also known as mucosa-associated lymphoid tumor, or MALToma. The continued growth of this tumor is dependent on the infection, suggesting that the host response to the bacteria is involved in initiation and maintenance of the tumor.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 61-year-old man with increasing fatigue, early satiety, and nausea for 5 months vomited dark granular material yesterday. Endoscopy reveals a large ulcerated mass in the gastric fundus. Biopsies are taken and microscopically the mass is composed of spindle cells that are positive for KIT with immunohistochemical staining. Mitoses are frequent. Gastrectomy is performed, and a 10-cm circumscribed mass is seen to arise from the gastric wall. Which of the following therapies is most likely to be a useful adjunct in treatment of his disease?`,
        q2: ``,
        q3: [],
        option: [`Broad spectrum antibiotics`, `Retinoic acid`,`Antibodies to epidermal growth factor receptor (EGFR)`,`Tyrosine kinase inhibitors`,`Corticosteroids`],
        optionFeedback: [`Antibiotics would not be helpful for this tumor. They may be beneficial for H. pylori-associated extranodal marginal zone lymphoma of the stomach.`,`Retinoic acid is used as differentiation therapy for one type of leukemia but would not have an effect on this tumor.`,`Anti-EGFR antibodies are efficacious in tumors associated with EGFR mutation or overexpression (some lung and breast cancers). The EGF receptor also is a tyrosine kinase, but it is not involved in GIST. `,`<!--Answers:-->The history is that of a gastric tumor; endoscopic biopsy is diagnostic for gastrointestinal stromal tumor (GIST), a tumor of mesenchymal cells that is strongly associated with mutations in the receptor tyrosine kinase KIT and, less commonly, PDGFRA (platelet-derived growth factor receptor α). KIT is a receptor for stem cell factor (also known as KIT ligand). The mutation results in constitutive signaling, leading to unregulated proliferation, and is responsive to tyrosine kinase inhibitor therapy. `,`Corticosteroids are antiinflammatory drugs that would not be beneficial for this or any other solid tumor. They are used to treat many lymphoid malignancies.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The history is that of a gastric tumor; endoscopic biopsy is diagnostic for gastrointestinal stromal tumor (GIST), a tumor of mesenchymal cells that is strongly associated with mutations in the receptor tyrosine kinase KIT and, less commonly, PDGFRA (platelet-derived growth factor receptor α). KIT is a receptor for stem cell factor (also known as KIT ligand). The mutation results in constitutive signaling, leading to unregulated proliferation, and is responsive to tyrosine kinase inhibitor therapy. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An 11-month-old, previously healthy infant has not produced stool for 1 day. The mother notices that the infant’s abdomen is distended. On physical examination, the infant’s abdomen is very tender, and bowel sounds are nearly absent. An abdominal plain film radiograph shows no free air, but there are distended loops of small bowel with air-fluid levels. Which of the following is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Duodenal atresia`, `Hirschsprung disease`,`Intussusception`,`Meckel diverticulum`,`Pyloric stenosis`],
        optionFeedback: [`Duodenal obstruction due to atresia is rare. It would present at birth and would not cause distal intestinal obstruction.`,`Hirschsprung disease presents with intestinal obstruction at birth.`,`<!--Answers:-->Failure to produce stool, abdominal distention, and absent bowel sounds are diagnostic of intestinal obstruction. The radiological findings confirm the diagnosis. Of the numerous causes of intestinal obstruction, the most common in previously healthy children under the age of 2 is intussusception. Its cause is usually unknown. `,`Meckel diverticulum is a usually asymptomatic outpouching of the wall of the ileum. When ectopic gastric mucosa is present, patients may present with symptoms of peptic ulcer disease.`,`Pyloric stenosis may be a consequence of chronic inflammation or a rare congenital lesion. It would cause gastric obstruction, not distal intestinal obstruction. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Failure to produce stool, abdominal distention, and absent bowel sounds are diagnostic of intestinal obstruction. The radiological findings confirm the diagnosis. Of the numerous causes of intestinal obstruction, the most common in previously healthy children under the age of 2 is intussusception. Its cause is usually unknown. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 40-year-old man has repeated bouts of mild to moderate abdominal pain, often precipitated by alcohol consumption. He had increasingly voluminous, bulky, foul-smelling stools and a 7-kg weight loss for the past year. There is no history of hematemesis or melena. He has some bloating, but no abdominal tenderness. On physical examination, there are no palpable abdominal masses, and bowel sounds are present. Which of the following is most likely to be present on examination of his stool?`,
        q2: ``,
        q3: [],
        option: [`Entamoeba histolytica trophozoites`, `Giardia lamblia cysts`,`Increased stool fat`,`Occult blood`,`Vibrio cholerae organisms`],
        optionFeedback: [`Ameba infects the intestines and causes enterocolitis that presents with dysentery (bloody stools).`,`Giardia can cause diarrhea and malabsorption, but typically not fat malabsorption.`,`<!--Answers:-->The clinical presentation indicates a form of malabsorption, and the characteristics of the stool are typical of fat malabsorption. The repeated bouts of pain are suggestive of chronic pancreatitis, which is a common cause of malabsorption. `,`Occult blood is a sign of malignancy of the gastrointestinal tract or peptic ulcer disease. `,`Vibrio cholerae causes cholera, which presents with watery diarrhea due to electrolyte and fluid loss from the intestinal epithelium. It does not manifest as fat malabsorption. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The clinical presentation indicates a form of malabsorption, and the characteristics of the stool are typical of fat malabsorption. The repeated bouts of pain are suggestive of chronic pancreatitis, which is a common cause of malabsorption. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 20-year-old woman has a 6-month history of bulky foul-smelling diarrhea associated with flatulence. She has experienced a 4-kg weight loss. She has no fever, nausea, vomiting, or abdominal pain. On physical examination, there are no significant findings. A stool sample is negative for occult blood, ova, and parasites, and a stool culture yields no pathogens. An upper gastrointestinal endoscopy is performed and a biopsy specimen from the upper part of the small bowel shows severe diffuse blunting of villi and abundant intraepithelial lymphocytes. Which of the following serologic tests is most likely to be positive in this patient?`,
        q2: ``,
        q3: [],
        option: [`Anticentromere antibody`, `Anti–DNA topoisomerase I antibody`,`Antimitochondrial antibody`,`Antinuclear antibody`,`Antitransglutaminase antibody`],
        optionFeedback: [`Anticentromere antibodies are most often seen in systemic sclerosis.`,`Anti-DNA topoisomerase antibodies are most often seen in systemic sclerosis.`,`Antimitochondrial antibodies are seen in primary biliary cholangitis.`,`Antinuclear antibody is seen in lupus and other autoimmune diseases. `,`<!--Answers:-->The clinical presentation suggests a malabsorption syndrome. The histologic findings are suggestive of celiac disease. This could be proven by withdrawing and then challenging with gluten-containing food. Patients with the disease frequently make antibodies (often IgA) against tissue transglutaminase. The role of these antibodies in the pathogenesis of celiac disease is unclear; transglutaminase may be involved in chemical modification of gliadin, the major gluten-containing protein in wheat and other grains, and the modified protein may elicit damaging immune responses in some individuals. `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The clinical presentation suggests a malabsorption syndrome. The histologic findings are suggestive of celiac disease. This could be proven by withdrawing and then challenging with gluten-containing food. Patients with the disease frequently make antibodies (often IgA) against tissue transglutaminase. The role of these antibodies in the pathogenesis of celiac disease is unclear; transglutaminase may be involved in chemical modification of gliadin, the major gluten-containing protein in wheat and other grains, and the modified protein may elicit damaging immune responses in some individuals.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 40-year-old man has episodic abdominal bloating, flatulence, and explosive diarrhea. These symptoms appear to be related to the milkshakes that he loves to consume. On physical examination, there are no remarkable findings. Laboratory studies show no increase in stool fat and no occult blood, ova, or parasites in the stool. A routine stool culture yields no pathogens. When he does not consume milkshakes or ice cream sodas, he is not symptomatic. Which of the following conditions best accounts for these findings?`,
        q2: ``,
        q3: [],
        option: [`Autoimmune gastritis`, `Celiac disease`,`Cholelithiasis`,`Cystic fibrosis`,`Disaccharidase deficiency`],
        optionFeedback: [`Autoimmune gastritis causes deficiency of gastric acid and intrinsic factor due to damage to gastric parietal cells and presents with anemia and other features reflecting deficiency of vitamin B<sub>12</sub> (intrinsic factor is required for absorption of this vitamin). `,`Celiac disease is caused by sensitivity to gluten and presents with diarrhea and malabsorption.`,`Cholelithiasis (gallstones) presents with pain and manifestations of biliary obstruction (jaundice).`,`Cystic fibrosis is an inherited multisystem disease in which the major manifestations are diarrhea and malabsorption (secondary to deficiency in pancreatic enzymes) and pulmonary infections that may lead to bronchiectasis (secondary to airway plugging by thick mucus). The affected gene, called cystic fibrosis transmembrane conductance regulator (CFTR), encodes a chloride channel.`,`<!--Answers:-->The clinical features are typical of lactose intolerance, which is most often caused by deficiency of disaccharidase, the enzyme that breaks down milk lactose. The deficiency may be congenital or acquired, usually following intestinal infection. `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The clinical features are typical of lactose intolerance, which is most often caused by deficiency of disaccharidase, the enzyme that breaks down milk lactose. The deficiency may be congenital or acquired, usually following intestinal infection.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 26-year-old man who has been vacationing in Thailand for one week, had fever, headache, and muscle pains for a day followed by watery diarrhea of 5 to 10 stools per day for 4 days. On physical examination there is diffuse abdominal pain. Microscopic examination of the stool shows numerous leukocytes and Gram-negative curved rods. The diarrhea subsides, but 2 weeks later he has increasing weakness in his legs. Which of the following organisms is most likely to produce his disease?`,
        q2: ``,
        q3: [],
        option: [`Vibrio cholerae`, `Campylobacter jejuni`,`Clostridium perfringens`,`Giardia lamblia`,`Salmonella typhi`],
        optionFeedback: [`Cholera presents with watery diarrhea and could have been the cause of this patient’s symptoms, but it is not associated with neurologic complications.`,`<!--Answers:-->Campylobacter is a common cause of traveler’s diarrhea. It is a Gram-negative bacillus. The leg weakness raises the possibility of Guillain-Barre syndrome, paralysis caused by immune injury to peripheral nerves. The immune injury may be due to cross-reaction of antibodies against Campylobacter lipopolysaccharide with gangliosides in nerves. This is an example of molecular mimicry. `,`C. perfringens is a Gram-positive bacillus that can cause antibiotic-associated diarrhea (less often than C.   difficile). It typically causes gas gangrene. `,`Giardia can cause diarrhea and malabsorption but is typically not associated with travel and does not cause neurologic complications.`,`S. typhi causes typhoid fever, which presents with acute enterocolitis and systemic manifestations of infection and inflammation.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Campylobacter is a common cause of traveler’s diarrhea. It is a Gram-negative bacillus. The leg weakness raises the possibility of Guillain-Barre syndrome, paralysis caused by immune injury to peripheral nerves. The immune injury may be due to cross-reaction of antibodies against Campylobacter lipopolysaccharide with gangliosides in nerves. This is an example of molecular mimicry. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 65-year-old woman is being treated in the hospital for pneumonia complicated by septicemia. She has required multiple antibiotics and was intubated and mechanically ventilated earlier in the course. On day 20 of hospitalization, she has abdominal distention. Bowel sounds are absent, and an abdominal radiograph shows dilated loops of small bowel suggestive of ileus. Laboratory studies show leukocytosis and hypoalbuminemia. At laparotomy, a portion of distal ileum and cecum is resected. The mucosal surface is covered by an irregular sheath of necrotic debris with enmeshed inflammatory cells. Which of the following is the most likely causative agent of these clinical and pathologic features?`,
        q2: ``,
        q3: [],
        option: [`Tropheryma whipplei`, `Norovirus`,`Clostridium botulinum`,`Clostridium difficile`,`Entamoeba histolytica`],
        optionFeedback: [`Tropheryma whipplei causes Whipple disease, which usually presents with diarrhea, weight loss secondary to malabsorption, and arthralgia (the cause of which is unknown).`,` Norovirus infection is responsible for almost half the outbreaks of gastroenteritis worldwide and is a frequent cause of sporadic gastroenteritis in developed countries. The infection is usually self-limited. Local outbreaks are usually related to contaminated food or water, but person-to-person transmission underlies most sporadic cases.`,`C. botulinum is the Clostridium that causes botulism, not enterocolitis.`,`<!--Answers:-->Enterocolitis developing after treatment with multiple or broad-spectrum antibiotics is most often pseudomembranous colitis caused by C. difficile. The necrotic debris covering the epithelium is known as a pseudomembrane and is responsible for the name of this lesion. `,`Ameba causes enterocolitis that presents with dysentery (bloody stools); it is not associated with antibiotic use. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Enterocolitis developing after treatment with multiple or broad-spectrum antibiotics is most often pseudomembranous colitis caused by C. difficile. The necrotic debris covering the epithelium is known as a pseudomembrane and is responsible for the name of this lesion.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `Over a holiday weekend, more than 100 adults at a resort hotel develop a diarrheal illness marked by voluminous, watery stools more than 10 times per day. They also report headache, abdominal cramping pain, and myalgias. On physical examination they have manifestations of dehydration and mild fever. Laboratory studies of stool samples show no increase in leukocytes or fat and no RBCs. Their illness lasts just 1 to 3 days and resolves with no sequelae. Which of the following infectious agents is the most likely cause for their illness?`,
        q2: ``,
        q3: [],
        option: [`Cytomegalovirus (CMV)`,`Clostridium botulinum`,`Norovirus`,`Staphylococcus aureus`,`Vibrio cholerae`],
        optionFeedback: [`CMV is a sporadic systemic infection usually in immunosuppressed individuals. It is not associated with outbreaks of gastroenteritis. `,`C. botulinum is the Clostridium that causes botulism, not enterocolitis.`,`<!--Answers:-->Norovirus is a frequent cause of outbreaks of gastroenteritis. The infection is usually self-limited. The absence of leukocytes and major systemic symptoms is consistent with a viral and not bacterial infection. `,`S. aureus causes abscesses in the skin and organs such as the lungs, not outbreaks of gastroenteritis.`,`V. cholerae causes cholera, which presents with watery diarrhea. It may be associated with epidemics in situations of overcrowding and water contamination. In the event of cholera infection, fecal leukocytes would be seen.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Norovirus is a frequent cause of outbreaks of gastroenteritis. The infection is usually self-limited. The absence of leukocytes and major systemic symptoms is consistent with a viral and not bacterial infection. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A study of children living in rural Malawi in Africa reveals a high prevalence of iron deficiency anemia. Stool samples are positive for occult blood. Pruritus of the skin of their feet as well as cough is an additional finding in many of these children. Which of the following parasitic infestations is the most likely cause for these findings?`,
        q2: ``,
        q3: [],
        option: [`Ancylostoma duodenale`,`Ascaris lumbricoides`,`Entamoeba histolytica`,`Giardia lamblia`,`Strongyloides stercoralis`],
        optionFeedback: [`<!--Answers:-->Necator americanus and Ancylostoma duodenale are hookworms that initiate infection by larval penetration through the skin. They develop in the lungs and are swallowed and complete their maturation in the duodenum. Here the adult worms attach to the mucosa, suck blood, and reproduce. Because of the chronic blood loss, hookworm infections are a leading cause of iron deficiency anemia in developing countries. `,`Ascaris lumbricoides is a nematode that infects individuals by fecal-oral transmission of the parasite’s eggs. In the intestine, the eggs hatch to release larvae, which penetrate the mucosa and migrate first to the liver, creating hepatic abscesses, and then to the lungs, where they cause pneumonia. There is no loss of blood.`,`Entamoeba histolytica causes amebic dysentery presenting with painful bloody diarrhea. Anemia is not the dominant feature.`,`Giardia lamblia, a flagellated protozoan, is the most common pathogenic parasite in humans. Infection is acquired by ingestion of cysts in contaminated food or water. Trophozoites are released in the acidic environment of the stomach and damage intestinal microvilli, causing apoptosis of epithelial cells. The infection may lead to acute or chronic malabsorptive diarrhea, but it is typically non-bloody. `,`Strongyloides stercoralis larvae live in fecally contaminated soil and can penetrate the skin. From here, they migrate to the lungs, are swallowed from the trachea, and mature into adult worms in the intestine. The eggs hatch in the intestine and release larvae that continue a cycle of autoinfection. The usual clinical presentation is intermittent gastrointestinal, pulmonary, or cutaneous symptoms that may continue for many years. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Necator americanus and Ancylostoma duodenale are hookworms that initiate infection by larval penetration through the skin. They develop in the lungs and are swallowed and complete their maturation in the duodenum. Here the adult worms attach to the mucosa, suck blood, and reproduce. Because of the chronic blood loss, hookworm infections are a leading cause of iron deficiency anemia in developing countries. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 31-year-old woman had increasingly severe diarrhea 1 week after returning from a trip to Central America. Gross examination of the stools showed mucus and streaks of blood. The diarrheal illness subsided within 4 weeks, but now she has become febrile and has pain in the right upper quadrant of the abdomen. An abdominal ultrasound scan shows a 10-cm, irregular, partly cystic mass in the right hepatic lobe. Which of the following infectious organisms is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Clostridium difficile`, `Cryptosporidium parvum`,`Giardia lamblia`,`Entamoeba histolytica`,`Strongyloides stercoralis`],
        optionFeedback: [`C. difficile causes pseudomembranous colitis, which usually develops after broad-spectrum antibiotic treatment.`,`Cryptosporidium causes chronic diarrhea and may cause severe disease in immunosuppressed individuals.`,`Giardia can cause diarrhea and malabsorption but is typically not associated with travel.`,`<!--Answers:-->A gastrointestinal illness apparently acquired in Central America should raise the suspicion of amebiasis. The disease presents with dysentery (bloody diarrhea) and the infection can spread to the liver, causing amebic abscess. The clinical and ultrasound features in this case are diagnostic of a liver abscess. Liver involvement is not a feature of any of the other infections. `,`Strongyloides is a helminthic parasite that can cause chronic diarrhea.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- A gastrointestinal illness apparently acquired in Central America should raise the suspicion of amebiasis. The disease presents with dysentery (bloody diarrhea) and the infection can spread to the liver, causing amebic abscess. The clinical and ultrasound features in this case are diagnostic of a liver abscess. Liver involvement is not a feature of any of the other infections.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 27-year-old man has a history of chronic intermittent abdominal pain, fever and diarrhea for the past 3 years which he had ascribed to indigestion. He has also noted 5Kg of weight loss in the past 6 months. He now presents with sudden onset of marked abdominal pain. On physical examination, his abdomen is diffusely tender and distended and bowel sounds are absent. He undergoes surgery and a segment of terminal ileum along with cecum with a firm, erythematous serosal surface, is removed. The gross appearance of the resected specimen is shown in the figure here. Which of the following complications occur most commonly in patients with this disease process?`,       
        q2: `<img src="../images/f012-q028-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Chronic cholecystitis`,`Enterocutaneous fistula`,`Intussusception`,`Liver abscess`,`Mesenteric artery thrombosis `],
        optionFeedback: [`Chronic cholecystitis is not a typical complication of Crohn disease.`,`<!--Answers:-->The clinical presentation is that of “acute abdomen,” which may be caused by ischemic infarction or perforation of the intestine (not visible in the figure). The resected specimen shows a section of the terminal ileum with thickened walls, mucosal edema and redness, due to underlying inflammation. The adjacent cecum and proximal ileum show no gross abnormalities. This appearance is consistent with Crohn disease. The involved intestine often shows full-wall thickness inflammation and ulcers that can form fistulas to the skin. `,`Intussusception, in which a segment of bowel telescopes into a distal segment causing acute obstruction, is not a typical complication of Crohn disease.`,`Liver abscess is not a typical complication of Crohn disease.`,`Mesenteric artery thrombosis, which causes ischemic necrosis of a segment of bowel, is not a typical complication of Crohn disease. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical presentation is that of “acute abdomen,” which may be caused by ischemic infarction or perforation of the intestine (not visible in the figure). The resected specimen shows a section of the terminal ileum with thickened walls, mucosal edema and redness, due to underlying inflammation. The adjacent cecum and proximal ileum show no gross abnormalities. This appearance is consistent with Crohn disease. The involved intestine often shows full-wall thickness inflammation and ulcers that can form fistulas to the skin. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 49-year-old woman has had abdominal cramps and diarrhea for the past month. She has a history of similar episodes of self-limited pain and diarrhea, which have occurred multiple times during the past 20 years. Each episode lasts about 2 weeks and resolves without treatment. Findings on physical examination are unremarkable, but a stool sample is positive for occult blood. Laboratory studies show no ova or parasites in the stool. Colonoscopy shows diffuse and uninterrupted mucosal inflammation and superficial ulceration extending from the rectum to the ascending colon. Colonic biopsy shows acute inflammation limited to the mucosa and submucosa. She is at greatest risk for developing which of the following complications?`,
        q2: ``,
        q3: [],
        option: [`Adenocarcinoma`,`Diverticulitis`,`Fat malabsorption`,`Perirectal fistula formation`,`Pseudomembranous colitis`],
        optionFeedback: [`<!--Answers:-->The clinical features suggest inflammatory bowel disease. The endoscopic and biopsy findings of diffuse superficial inflammation and ulceration, without any skip areas, are diagnostic for ulcerative colitis. Patients with this disease are at high risk for developing colonic adenocarcinoma. `,`Diverticulitis is an occasional complication of diverticulosis but is not associated with ulcerative colitis.`,`Fat malabsorption is seen in numerous diseases, such as celiac disease and chronic pancreatitis, but is usually not associated with diffuse mucosal inflammation.`,`Fistulas are occasional complications of Crohn disease but ulcerative colitis involves the superficial mucosa and not the wall of the intestine, so it does not produce fistulas.`,`Pseudomembranous colitis is caused by C. difficile infection and is most often seen in patients treated with broad-spectrum antibiotics. The prominent pathologic feature is a “pseudomembrane” of necrotic debris on a superficially inflamed mucosa.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The clinical features suggest inflammatory bowel disease. The endoscopic and biopsy findings of diffuse superficial inflammation and ulceration, without any skip areas, are diagnostic for ulcerative colitis. Patients with this disease are at high risk for developing colonic adenocarcinoma. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 30-year-old woman has experienced intermittent bouts of lower abdominal pain and low-volume diarrhea for the past 2 years. On colonoscopy there is friable mucosa from the rectum to the ascending colon. Biopsies are taken and on microscopic examination show acute and chronic mucosal inflammation with focal erosion. Her stool is negative for ova, parasites, and bacterial pathogens. Which of the following ongoing testing procedures is most useful for long-term follow-up of this woman?`,
        q2: ``,
        q3: [],
        option: [`Abdominal CT scanning`,`Biopsy screening for dysplasia`,`Genetic mutational analysis for NOD2`,`Molecular testing for C. difficile toxins in stools`,`Stool cultures for microbiota`],
        optionFeedback: [`Abdominal CT scan would not reveal dysplasia or early adenocarcinoma.`,`<!--Answers:-->Diffuse involvement of the colon seen by colonoscopy and superficial mucosal inflammation with ulceration as seen in the biopsy are diagnostic of ulcerative colitis. Since these patients are at high risk for development of adenocarcinoma of the colon, frequent screening (and sometimes total colectomy) is recommended. `,`NOD2 gene polymorphisms are associated with a proportion of Crohn disease cases, not with ulcerative colitis.`,`C. difficile causes pseudomembranous colitis, most often seen in patients treated with broad-spectrum antibiotics. The prominent pathologic feature is a “pseudomembrane” of necrotic debris on a superficially inflamed mucosa.`,`Stool cultures for microbes are done as part of the initial diagnostic workup for colitis, but these patients are not unusually susceptible to infectious enterocolitis so these cultures would not be used for follow-up screening. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Diffuse involvement of the colon seen by colonoscopy and superficial mucosal inflammation with ulceration as seen in the biopsy are diagnostic of ulcerative colitis. Since these patients are at high risk for development of adenocarcinoma of the colon, frequent screening (and sometimes total colectomy) is recommended. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 26-year-old man has a 3-week history of intermittent cramping abdominal pain and low-volume diarrhea. A stool sample is positive for occult blood. The symptoms subside within 1 week. Six months later, the abdominal pain recurs with perianal pain. On physical examination, there is now a perirectal fistula. Colonoscopy shows many areas of mucosal edema and ulceration and intervening areas that appear normal. Microscopic examination of a biopsy specimen from an ulcerated area shows a patchy acute and chronic inflammatory infiltrate, crypt abscesses, and noncaseating granulomas. Which of the following genetic changes is most likely to be associated with this disease?`,
        q2: ``,
        q3: [],
        option: [` Mutation in APC gene`,`Polymorphism of NOD2 gene`,`HLA-DQ2 genotype`,`Mutation of mismatch repair genes`,`Microsatellite instability `],
        optionFeedback: [`Mutations in the APC gene are associated with familial adenomatous polyposis and colon adenocarcinoma, not Crohn disease.`,`<!--Answers:-->The clinical history suggests an inflammatory bowel disease. The presence of a fistula, the colonoscopic appearance of “skip” lesions, and the morphologic findings (especially crypt abscesses and granulomas) are diagnostic of Crohn disease. A subset of these patients has polymorphisms in the NOD2 gene. Although the presence of two mutant NOD2 alleles significantly increases the risk of developing the disease, identification of mutations is not of diagnostic or prognostic value, so genetic testing is not recommended. NOD2 is a cytosolic sensor of microbes, and triggers host reactions that combat microbes (a mechanism of innate immunity). It is postulated that the disease-associated polymorphisms encode a version of NOD2 that is not fully functional, allowing commensal bacteria to penetrate the intestinal wall and induce chronic inflammation. `,`HLA associations are seen with many autoimmune diseases, and HLA-DQ2 is associated with celiac disease, but Crohn disease and ulcerative colitis are not associated with any HLA allele.`,`Mutations in mismatch repair genes, which are often manifested as microsatellite instability, are associated with some forms of colonic adenoma and adenocarcinoma. The hereditary form of this disease is hereditary nonpolyposis colorectal carcinoma (HNPCC).`,`Microsatellite instability is associated with mutations in mismatch repair genes and predisposition to  colonic adenoma and adenocarcinoma. The hereditary form of this disease is hereditary nonpolyposis colorectal carcinoma (HNPCC). `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical history suggests an inflammatory bowel disease. The presence of a fistula, the colonoscopic appearance of “skip” lesions, and the morphologic findings (especially crypt abscesses and granulomas) are diagnostic of Crohn disease. A subset of these patients has polymorphisms in the NOD2 gene. Although the presence of two mutant NOD2 alleles significantly increases the risk of developing the disease, identification of mutations is not of diagnostic or prognostic value, so genetic testing is not recommended. NOD2 is a cytosolic sensor of microbes, and triggers host reactions that combat microbes (a mechanism of innate immunity). It is postulated that the disease-associated polymorphisms encode a version of NOD2 that is not fully functional, allowing commensal bacteria to penetrate the intestinal wall and induce chronic inflammation. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 53-year-old woman undergoes a routine checkup. The only abnormal finding is a stool specimen that contains occult blood. Colonoscopy shows a solitary, rounded lesion at the splenic flexure. It is removed and its histologic appearance is shown in the figure. Which of the following features of such lesions carry the highest risk of malignancy?`,
        q2: `<img src="../images/f012-q033-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Location in the sigmoid colon`,`Size &gt;4cm`,`Tubular architecture`,`Presence of a stalk`,`Presence of mucus-secreting cells`],
        optionFeedback: [`This is a common location of adenomas and does not have prognostic value.`,`<!--Answers:-->The lesion is a colonic adenoma (adenomatous polyp). Although all colonic adenomas carry a risk of malignant transformation, size is the greatest predictor of this risk; cancers almost never arise in adenomas &lt;1 cm in diameter but do so in almost 40% of lesions &gt;4 cm. `,`Tubular, tubulovillous, or villous architecture of adenomas does not have prognostic value.`,`Adenomas may be stalked or sessile but these features do not have prognostic value.`,`Mucus-secreting cells indicate differentiation but this is not a risk factor.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The lesion is a colonic adenoma (adenomatous polyp). Although all colonic adenomas carry a risk of malignant transformation, size is the greatest predictor of this risk; cancers almost never arise in adenomas &lt;1 cm in diameter but do so in almost 40% of lesions &gt;4 cm. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 19-year-old man is advised to see his physician because genetic screening has detected a disease in other family members. On physical examination, a stool sample is positive for occult blood. A colonoscopy is performed, followed by a colectomy. On gross examination the mucosal surface of the colectomy specimen shows scores of lesions that are microscopically similar to the ones shown in the figure. Molecular analysis of this patient’s normal fibroblasts is most likely to show a mutation in which of the following genes?`,
        q2: `<img src="../images/f012-q034-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [` APC`,`MLH1`,`KRAS`,`NOD2`,`TP53`],
        optionFeedback: [`<!--Answers:-->The histologic image shows three colonic adenomas. The clinical presentation and presence of large numbers of colonic adenomas are diagnostic for familial adenomatous polyposis (FAP). This disease is caused by mutations in the APC gene. APC is a negative regulator of Wnt signaling, and thus of β-catenin activity. The disease is familial in ~75% of cases, as in this patient who has a family history of the disease. Patients inherit one mutant APC  allele (present in all cells of the body); adenomas develop when the second allele is mutated or lost in colonic epithelium.`,`MLH1 encodes a protein involved in DNA repair. Mutations in this gene cause a different syndrome of colonic polyps, called hereditary nonpolyposis colorectal carcinoma (HNPCC). Adenomas and adenocarcinomas in patients with HNPCC tend to occur on the right side of colon.`,`Mutations in KRAS are associated with progression of adenomas to adenocarcinomas of the colon. They are also associated with other cancers. Since they are not inherited in the germ line, fibroblasts from FAP patients do not have a mutant KRAS allele.`,`Polymorphisms of the NOD2 gene are associated with Crohn disease. `,`Mutations in TP53 are associated with progression of adenomas to adenocarcinomas of the colon. They are also associated with other cancers. Since TP53 mutations are not inherited in the germ line, fibroblasts from FAP patients do not have a mutant TP53 allele.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The histologic image shows three colonic adenomas. The clinical presentation and presence of large numbers of colonic adenomas are diagnostic for familial adenomatous polyposis (FAP). This disease is caused by mutations in the APC gene. APC is a negative regulator of Wnt signaling, and thus of β-catenin activity. The disease is familial in ~75% of cases, as in this patient who has a family history of the disease. Patients inherit one mutant APC  allele (present in all cells of the body); adenomas develop when the second allele is mutated or lost in colonic epithelium.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 33-year-old man has a routine health maintenance examination. A stool sample is positive for occult blood. On colonoscopy, a 6-cm ulcerated mass is seen projecting into the cecum. There are three smaller, sessile lesions 1 to 3 cm in size. The microscopic appearance of the ulcerated lesion is shown in the figure. The smaller lesions are reported as sessile serrated adenomas. Which of the following molecular events is thought to be most critical in the development of such lesions?`,
        q2: `<img src="../images/f012-q035-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Amplification of ERBB2 (commonly known as HER2) gene`,`Defective DNA mismatch repair gene`,`Germline transmission of a defective APC gene`,`Inactivating mutation of the E-cadherin gene`,`Activating mutation of the beta-catenin gene`],
        optionFeedback: [`ERBB2 encodes a receptor for epidermal growth factor. It is frequently amplified in cancers of the breast. `,`<!--Answers:-->The clinical presentation and histologic appearance indicate a colonic adenocarcinoma developing in an adenoma. The pathway of cancer development from sessile serrated adenomas is associated with mutations in one of several DNA mismatch repair genes. `,`Mutations in the APC gene are associated with familial adenomatous polyposis and a different pathway of colonic adenocarcinoma.`,`E-cadherin mutations are seen in the hereditary form of diffuse gastric cancer and in about 50% of sporadic diffuse gastric cancers.`,`β-catenin mutations are seen in colon adenocarcinomas that develop from adenomatous polyps but that have unmutated APC, suggesting that abnormalities in β-catenin are the critical downstream event in cancer development by this pathway. Since APC and β-catenin are in the same pathway, mutations are mutually exclusive.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical presentation and histologic appearance indicate a colonic adenocarcinoma developing in an adenoma. The pathway of cancer development from sessile serrated adenomas is associated with mutations in one of several DNA mismatch repair genes. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 73-year-old man has noted a change in bowel habits for the past year. Defecation is more difficult and the caliber of stools has decreased. On physical exam, there are no abnormal findings. Laboratory tests show hypochromic microcytic anemia. Colonoscopy is performed for the first time in this man, followed by colonic resection with the gross appearance shown in the figure. Which of the following preexisting conditions confers the highest risk of developing similar lesions?`,
        q2: `<img src="../images/f012-q036-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Hypersensitivity to gluten`,`Diverticulitis`,`Crohn disease`,`Portal hypertension`,`Infection with HPV-16`],
        optionFeedback: [`Hypersensitivity to gluten causes celiac disease.`,`Diverticulitis has no associated cancer risk.`,`<!--Answers:-->A change in bowel habits along with hypochromic microcytic anemia in an older person should arouse the suspicion of colon cancer. Since carcinomas located in the sigmoid colon tend to be annular, they affect the caliber of stools. Microscopic examination confirms the diagnosis of colonic adenocarcinoma. Of the conditions listed, the only one that has a high risk of developing colon cancer is Crohn disease. In inflammatory bowel disease, risk of cancer is associated with colonic involvement; therefore, Crohn disease that spares the colon (e.g., ileal disease) does not increase risk. `,`Portal hypertension is most often caused by cirrhosis of the liver.`,`HPV infection is associated with cancers of the cervix and oropharynx, not colon.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- A change in bowel habits along with hypochromic microcytic anemia in an older person should arouse the suspicion of colon cancer. Since carcinomas located in the sigmoid colon tend to be annular, they affect the caliber of stools. Microscopic examination confirms the diagnosis of colonic adenocarcinoma. Of the conditions listed, the only one that has a high risk of developing colon cancer is Crohn disease. In inflammatory bowel disease, risk of cancer is associated with colonic involvement; therefore, Crohn disease that spares the colon (e.g., ileal disease) does not increase risk.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 49-year-old man has used chewing tobacco and snuff for many years. On physical examination a white plaque is seen on the hard palate. It cannot be removed by scraping. A biopsy is performed, and microscopic examination of the lesion shows a thickened squamous mucosa. Four years later, a biopsy specimen of a similar lesion shows carcinoma in situ. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Aphthous ulcer`,`Lichen planus`,`Leukoplakia`,`Pyogenic granuloma`,`Xerostomia`],
        optionFeedback: [`Aphthous ulcers are painful inflammatory lesions of unknown etiology involving the oral mucosa.`,`Lichen planus is a skin disease that may involve the oral cavity. Histologically, it is characterized by a dense, “band-like” lymphocytic infiltrate at the interface between the mucosa and the submucosal tissue.`,`<!--Answers:-->A white adherent plaque in the oral cavity is called leukoplakia. It begins as a benign lesion that is often associated with tobacco use and can progress to cancer. `,`Pyogenic granuloma is a vascular lesion of the oral mucosa usually found in children, young adults, and pregnant women.`,`Xerostomia (dry mouth) is a symptom often associated with lesions affecting the salivary glands and ducts.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- A white adherent plaque in the oral cavity is called leukoplakia. It begins as a benign lesion that is often associated with tobacco use and can progress to cancer. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 54-year-old man, a nonsmoker, has a nonhealing ulceration at the base of his tongue on the right side for 2 months. On examination this lesion is 1 cm in diameter with irregular borders. Biopsy of the lesion is performed and microscopic examination shows infiltrating squamous cell carcinoma. Which of the following infectious agents is most likely to be associated with this lesion?`,
        q2: ``,
        q3: [],
        option: [`Candida albicans`,`Herpes simplex virus (HSV)`,`Human papillomavirus (HPV)`,`HIV`,` Group A streptococcus`],
        optionFeedback: [`C. albicans is a fungus that causes oral thrush and is not associated with any cancer.`,`HSV causes inflammatory lesions, not cancer.`,`<!--Answers:-->Cancers of the oropharynx (and cervix) are often associated with infection with high-risk serotypes of HPV.  `,`HIV causes AIDS, which may predispose to some cancers, but HIV is not itself carcinogenic.`,`Streptococci are frequent causes of acute pharyngitis but not associated with any cancer.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Cancers of the oropharynx (and cervix) are often associated with infection with high-risk serotypes of HPV. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 65-year-old woman has noticed a slowly enlarging nodule on her face for the past 3 years. On physical examination, a 3-cm, nontender, mobile, discrete mass is palpable on the left side of the face, anterior to the ear and just superior to the mandible. The mass is completely excised, and histologic examination shows ductal epithelial cells in a myxoid stroma containing islands of cartilage-like (chondroid) tissue and bone. This patient is most likely to have which of the following neoplasms?`,
        q2: ``,
        q3: [],
        option: [`Mucoepidermoid carcinoma`,`Pleomorphic adenoma`,`Pyogenic granuloma`,`Squamous cell carcinoma`,`Warthin tumor`],
        optionFeedback: [`Mucoepidermoid carcinoma is the most common malignant tumor of the salivary glands. It is composed of a mixture of squamous, mucus-secreting, and intermediate cells.`,`<!--Answers:-->The histologic appearance is diagnostic of pleomorphic adenoma, a benign lesion that is so named because it contains a mixture of epithelial and mesenchymal (often resembling cartilage) components. They sometimes recur after excision and can progress to cancer.`,` Pyogenic granuloma is a vascular lesion of unknown etiology found on the gums of children, young adults, and pregnant women. The lesions consist of proliferating small blood vessels, similar to those in granulation tissue, which may create an alarming red appearance. The lesions may regress or become fibrotic. `,`Squamous cell carcinoma does not arise in salivary glands and is microscopically quite distinct from the tumor this patient has.`,` Warthin tumor is a benign neoplasm that is the second most common salivary gland tumor. It arises almost exclusively in the parotid gland. The tumors are encapsulated and are composed of cystic spaces lined by a double layer of neoplastic epithelial cells resting on a dense lymphoid stroma sometimes bearing germinal centers. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The histologic appearance is diagnostic of pleomorphic adenoma, a benign lesion that is so named because it contains a mixture of epithelial and mesenchymal (often resembling cartilage) components. They sometimes recur after excision and can progress to cancer.`,
        state: `notAnswered`,
        userAnswered: [],
    }
    
     ];






