var quiz = [
    {
        q: `A 45-year-old woman who works while standing for long periods notices at the end of her 8-hour shift that her lower legs and feet are swollen, although there was no swelling at the beginning of the day. There is no pain or erythema associated with this swelling. She is otherwise healthy and takes no medications; laboratory testing reveals normal liver and renal function. Which of the following mechanisms best explains this phenomenon?`,
        q2: ``,
        q3: [],
        option: [`Excessive free water intake`, ` Hypoalbuminemia`, `Increased hydrostatic pressure`,`Lymphatic obstruction`,`Secondary aldosteronism`],
          optionFeedback: [`Excessive free water intake is unlikely to produce edema in an individual with normal renal and cardiac function. `,
          `Hypoalbuminemia is unlikely in the absence of liver disease or nephrotic syndrome. `,`  Standing in one place without moving may result in edema because of increased hydrostatic pressure secondary to the lack of the “milking” action of muscular contractions, which help to increase blood return from the lower legs when upright.  `,`Lymphatic obstruction is most common following some sort of injury, for which there is no history. `,`Secondary aldosteronism is associated with reduced renal perfusion which stimulates the <a href="https://www.merckmanuals.com/professional/endocrine-and-metabolic-disorders/adrenal-disorders/primary-aldosteronism#v982814">renin-angiotensin axis</a> and results in hypersecretion of aldosterone. The most common causes are heart failure, cirrhosis with ascites and nephrotic syndrome.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-Standing in one place without moving may result in edema because of increased hydrostatic pressure secondary to the lack of the “milking” action of muscular contractions, which help to increase blood return from the lower legs when upright.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 56-year-old woman diagnosed with cancer in her left breast underwent a mastectomy with axillary lymph node dissection. Postoperatively, she develops marked swelling of the left arm due to the axillary lymph node dissection that has persisted for 6 months. Now on physical examination, her temperature is 36.9° C.  Her left arm is not tender or erythematous, and it is not painful with movement or to touch, but it is enlarged and has a doughy consistency. Which of the following is the most likely mechanism for these findings?`,
        q2: ``,
        q3: [],
        option: [`Cellulitis`, ` Congestive heart failure`,`Decreased plasma osmotic pressure`,`Lymphedema`,` Phlebothrombosis`],
         optionFeedback: [`Cellulitis is associated with pain, erythema, and often systemic symptoms such as fever. `,`Congestive heart failure, depending on the chamber, may present with pulmonary edema or peripheral edema, generally bilateral and worse in dependent tissues (e.g., the legs). `,`Decreased plasma osmotic pressure presents with symmetric peripheral edema and (if a complication of liver failure) ascites.`,`   This is a classic setting for development of lymphedema due to damage to the lymphatic channels draining the arm during the surgical procedure.  `,`Phlebothrombosis is unusual in an arm (where venous stasis is uncommon) and often is associated with pain.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale:- This is a classic setting for development of lymphedema due to damage to the lymphatic channels draining the arm during the surgical procedure  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 94-year-old woman has a one-month history of dyspnea and worsening cough with frothy sputum production. She is afebrile. A chest radiograph shows pulmonary infiltrates, suggestive of edema, and increased heart size compared to a previous radiograph. Which of the following is the most likely mechanism for development of her pulmonary infiltrates?`,
        q2: ``,
        q3: [],
        option: [` Decreased sodium intake`, `Hypoalbuminemia`,`Increased hydrostatic pressure`,` Inflammation`,`Pulmonary arterial obstruction`],
         optionFeedback: [`Decreased sodium intake may be associated with a contraction of blood volume and lower blood pressure and would not cause pulmonary edema. `,`Hypoalbuminemia is typically associated with peripheral edema, not pulmonary edema. `,`   The likely cause in this instance is left-sided heart failure with increase in pulmonary venous pressure, which often presents with pulmonary edema and related symptoms.  `,`Inflammation is unlikely in this context since she has no symptoms of inflammation (e.g., fever). `,`Pulmonary arterial obstruction typically occurs with pulmonary thromboemboli (arising from a deep vein thrombosis), which may cause pulmonary infarction, particularly when pulmonary arterial circulation is compromised by left heart failure.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The likely cause in this instance is left-sided heart failure with increase in pulmonary venous pressure, which often presents with pulmonary edema and related symptoms.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 58-year-old man with pulmonary emphysema has lower leg swelling with pitting edema to the knees and prominent jugular venous distention to the level of the mandible. His serum levels of aspartate aminotransferase (AST) and alanine aminotransferase (ALT) are moderately increased. The representative gross appearance of his liver is shown in the figure. Which of the following underlying conditions is most likely to be present in this man?`,
        q2: `<img src="../images/f003-q004-9780323640251.png`,
        q3: [],
        option: [`Chronic renal failure`, ` Common bile duct obstruction`,` Congestive heart failure`,` Portal vein thrombosis`,`Thrombocytosis`],
         optionFeedback: [`Chronic renal failure may present with peripheral edema but is not likely to be associated with liver damage and jugular venous distention. `,`Common bile duct obstruction would typically present with jaundice and an elevated alkaline phosphatase level, not AST and ALT; furthermore, it is not associated with edema. `,`    Congestive heart failure, specifically right-sided heart failure (perhaps due to longstanding left-sided failure) explains all of the observed symptoms. Jugular venous distention occurs when central venous pressure increases due to the inability of the right ventricle to empty properly. This also accounts for the patient’s dependent edema. The liver shows chronic passive congestion affecting predominantly the area around the central veins, producing the so-called “nutmeg” liver.  `,`Portal vein thrombosis might present with ascites and symptoms related to intestinal ischemia but would not be associated with peripheral edema and jugular venous distention. `,`Thrombocytosis may present with thrombosis at various sites (including the portal vein in diseases such as polycythemia vera) but is not typically associated with any of the findings seen in this patient.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Congestive heart failure, specifically right-sided heart failure (perhaps due to longstanding left-sided failure) explains all of the observed symptoms. Jugular venous distention occurs when central venous pressure increases due to the inability of the right ventricle to empty properly. This also accounts for the patient’s dependent edema. The liver shows chronic passive congestion affecting predominantly the area around the central veins, producing the so-called “nutmeg” liver.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A superficial puncture wound from a needle stick injury leads to a small amount of bleeding in a healthy person. Seconds after this injury occurs, the bleeding stops. Which of the following is most likely the principal mechanism to immediately stop the blood loss from this injury?`,
        q2: ``,
        q3: [],
        option: [` Fibrin polymerization`, `Neutrophil chemotaxis`,`Platelet aggregation`,`Protein C activation`,`Vasoconstriction`],
         optionFeedback: [`Fibrin polymerization is part of secondary hemostasis induced by the activation of thrombin through the coagulation cascade. `,`Neutrophil chemotaxis has little role in hemostasis. `,`Platelet aggregation is part of primary hemostasis, in which a platelet plug rapidly forms at a site of vascular injury. This response takes time to develop and occurs after the initial vasoconstriction.`,`Protein C activation occurs when thrombin binds to thrombomodulin expressed on the surface of intact endothelial cells. Activated protein C acts to inhibit coagulation by cleavage of prothrombogenic factors such as activated Factor V.`,`    Acute injury to vessel walls induces the release of factors such as norepinephrine, which stimulates smooth muscle cells to contract, stanching bleeding. This response is short-lived and bleeding will resume unless other hemostatic mechanisms are initiated.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Acute injury to vessel walls induces the release of factors such as norepinephrine, which stimulates smooth muscle cells to contract, stanching bleeding. This response is short-lived and bleeding will resume unless other hemostatic mechanisms are initiated.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 15-year-old girl incurs a superficial 0.5 cm laceration to the sole of her foot after stepping on a piece of broken glass. The cut stops bleeding within 5 minutes after application of local pressure. Which of the following substances released by endothelium is most likely to counteract platelet aggregation near this site of injury?`,
        q2: ``,
        q3: [],
        option: [`Glycoprotein IIb/IIIa`, ` Prostacyclin`,`Tissue-type plasminogen activator`,` Thrombomodulin`,`Thromboxane A2`],
         optionFeedback: [`Glycoprotein IIb/IIIa is a platelet fibrinogen receptor and, when activated, augments platelet aggregation. `,` Prostacyclin is a direct inhibitor of platelet aggregation.  `,`Tissue-type plasminogen activator is secreted by endothelium in response to thrombin, but is involved in activation of plasmin, which breaks down fibrin; it does not affect platelet aggregation.`,`Thrombomodulin binds to thrombin to form a complex that inactivates prothrombogenic factors such as activated Factor V through protein C/protein S complexes; it does not influence platelet activation. `,`Thromboxane A2 is a potent activator of platelet aggregation that is synthesized by platelets themselves.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Prostacyclin is a direct inhibitor of platelet aggregation.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 26-year-old woman has a history of frequent nosebleeds and increased menstrual blood flow. On physical examination, petechiae and purpura are present on the skin of her extremities. Laboratory studies show near normal partial thromboplastin time (PTT), prothrombin time (PT), and platelet count, but decreased von Willebrand factor activity. This patient most likely has a derangement in which of the following steps in hemostasis?`,
        q2: ``,
        q3: [],
        option: [`Fibrin polymerization`, `Platelet adhesion`,`Platelet aggregation`,`Thrombin generation`,`Vasoconstriction`],
         optionFeedback: [`Fibrin polymerization is not affected by deficiencies of von Willebrand factor. `,` Platelet adhesion depends on normal von Willebrand factor (vWF) function. vWF acts as a bridge between platelet surface glycoprotein GpIb and subendothelial collagen.  `,`Platelet aggregation is prompted by a variety of factors, such as thromboxane A2, and does not depend on von Willebrand factor.`,`Thrombin generation depends on upstream factors in the coagulation cascade. `,`Vasoconstriction is not affected by von Willebrand factor.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Platelet adhesion depends on normal von Willebrand factor (vWF) function. vWF acts as a bridge between platelet surface glycoprotein GpIb and subendothelial collagen.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 59-year-old woman with a history of diabetes had a myocardial infarction three months ago. Her BMI is 35. She is now taking a low dose of aspirin to reduce the risk for recurrent arterial thrombosis. On which of the following steps in hemostasis does aspirin have its greatest effect?`,
        q2: ``,
        q3: [],
        option: [`Adhesion of platelets to collagen`, `Aggregation of platelets`,` Production of tissue factor`,`Synthesis of von Willebrand factor`,`Synthesis of antithrombin III`],
         optionFeedback: [`Adhesion of platelets to collagen requires von Willebrand factor and platelet receptor Gp1a, which are unaffected by aspirin. `,`   Aspirin is an irreversible inhibitor of cyclooxygenase, which is required to synthesize thromboxane A2, a potent activator of platelet aggregation.  `,`Although it is conceivable that aspirin might lower tissue factor production through its anti-inflammatory effects, this is not a primary effect of the drug.`,`Synthesis of von Willebrand factor is unaffected by aspirin. `,`Synthesis of antithrombin III is unaffected by aspirin.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Aspirin is an irreversible inhibitor of cyclooxygenase, which is required to synthesize thromboxane A2, a potent activator of platelet aggregation.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 12-year-old boy has a 10-year history of multiple soft tissue hemorrhages and acute upper airway obstruction from hematoma formation in the neck. On physical examination, he has decreased range of motion of the large joints, particularly the knees and ankles. He has no petechiae or purpura of the skin. Laboratory studies show normal prothrombin time, elevated partial thromboplastin time (PTT), normal platelet count, and markedly decreased Factor VIII activity. Which of the following mechanisms best describes the underlying basis of his disease?`,
        q2: ``,
        q3: [],
        option: [`Decrease in production of thrombin`, `Antiphospholipid antibodies`,`Failure of platelet aggregation`,`Failure of fibrin polymerization`,`Inability to neutralize antithrombin III`],
         optionFeedback: [`    The boy’s bleeding pattern is consistent with hemophilia, which may be caused by a deficiency of factor VIII (hemophilia A) or factor IX (hemophilia B). Factor VIII and factor IX from a complex that is a critical component of the coagulation cascade, being essential for normal generation of thrombin in response to vascular injury in vivo.  `,`Antiphospholipid antibodies are sometimes associated with an elevated PTT, but in vivo may cause clotting rather than a bleeding tendency (antiphospholipid antibody syndrome). `,`Failure of platelet aggregation is typically associated with superficial bleeding in the form of petechiae and ecchymoses.`,`Failure of fibrin polymerization is a rare cause of bleeding associated with inherited or acquired abnormal fibrinogen molecules or (more commonly) consumption of drugs that inhibit fibrin polymerization (for which there is no history here). `,`Inability to neutralize antithrombin III (overactivity of antithrombin III) is not a cause of clinical bleeding.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The boy’s bleeding pattern is consistent with hemophilia, which may be caused by a deficiency of factor VIII (hemophilia A) or factor IX (hemophilia B). Factor VIII and factor IX from a complex that is a critical component of the coagulation cascade, being essential for normal generation of thrombin in response to vascular injury in vivo.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 66-year-old woman has sudden onset of chest pain that radiates to her neck and left arm. On examination 30 minutes later, she is diaphoretic and hypotensive. Her serum troponin I level is elevated. Coronary angiography shows complete occlusion of the left anterior descending artery. Which of the following drugs is most likely to be administered emergently as thrombolytic therapy for this woman?`,
        q2: ``,
        q3: [],
        option: [` Antithrombin`, `Low-molecular–weight heparin`,` Nitric oxide`,`Tissue plasminogen activator(t-PA)`,`Vitamin K`],
         optionFeedback: [`Antithrombin would do little to break up a clot that already has formed. `,`Low-molecular–weight heparin might prevent clot propagation but would not break down a clot that has already formed. `,`Nitric oxide is a vasodilator and could improve blood flow to a part of the heart supplied by a narrowed vessel, but would not open up a vessel that is completely occluded.`,` Coronary artery obstruction may be reversed with agents such as t-PA that stimulate the activity of plasmin to break down fibrin. The other strategy is placing a stent to open up the obstruction.  `,`Vitamin K is required for synthesis of a variety of dicarboxylated factors, including coagulation factors II, VII, IX, and X, as well as proteins C and S, but has no role in this setting. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-Coronary artery obstruction may be reversed with agents such as t-PA that stimulate the activity of plasmin to break down fibrin. The other strategy is placing a stent to open up the obstruction.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 60-year-old woman with a history of diabetes has a 5-hour history of left-sided chest pain radiating to the arm. Serial measurements of serum troponin I levels show an elevated level 24 hours after the onset of pain. Coronary angiography shows occlusion of the left anterior descending artery. Which of the following mechanisms is the most likely cause of thrombosis in this patient?`,
        q2: ``,
        q3: [],
        option: [`Antiphospholipid antibody`, ` Damage to endothelium`,` Decreased antithrombin III level`,`Mutations in Factor V gene`,` Stasis of blood flow`],
         optionFeedback: [`Antiphospholipid antibody may promote thrombosis in veins and arteries, but is not a common cause of coronary artery thrombosis. `,`    Damage to the endothelium in atherosclerotic lesions is the most common cause of coronary artery thrombosis. Diabetes is associated with a markedly increased risk of atherosclerosis.  `,`Decreased antithrombin III level is associated with venous thrombosis, not coronary artery thrombosis.`,`Mutations in the Factor V gene are associated with venous thrombosis, not coronary artery thrombosis. `,`Stasis of blood flow is associated with venous thrombosis, not coronary artery thrombosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Damage to the endothelium in atherosclerotic lesions is the most common cause of coronary artery thrombosis. Diabetes is associated with a markedly increased risk of atherosclerosis.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 31-year-old man of northern European descent has had multiple episodes of deep venous thrombosis during the past 10 years and one episode of pulmonary thromboembolism during the past year. Laboratory tests show that his prothrombin time (PT), partial thromboplastin time (PTT), platelet count, and platelet function studies all are normal. Which of the following risk factors is the most likely cause of his coagulopathy?`,
        q2: ``,
        q3: [],
        option: [`Antithrombin III deficiency`, ` Factor V mutation`,` Hyperhomocysteinemia`,`Mutation in protein C`,` Occult malignancy`],
         optionFeedback: [`Antithrombin III deficiency is much less common than Factor V Leiden, but can also result in thrombophilia. `,` Factor V mutation is one of the most common forms of thrombophilia, particularly in those of northern European origin, in whom it is present in about 5%–6% of the population. The mutation results in resistance to cleavage and inactivation of Factor V by activated protein C, and therefore in a gain of function of Factor V. The risk is highest in those who are homozygous for this variant.  `,`Hyperhomocysteinemia is rare and its association with thrombosis is unclear, although it may do so via endothelial injury.`,`Mutation in protein C may also predispose to thrombosis, but it is rare. `,`Occult malignancy is exceedingly unlikely, given the long history of thrombophilia.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Factor V mutation is one of the most common forms of thrombophilia, particularly in those of northern European origin, in whom it is present in about 5%–6% of the population. The mutation results in resistance to cleavage and inactivation of Factor V by activated protein C, and therefore in a gain of function of Factor V.  The risk is highest in those who are homozygous for this variant.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 23-year-old woman has a 24-hour history of altered consciousness and slurred speech. A head computed tomography scan shows a right temporal infarction. Cerebral angiography shows a distal right middle cerebral arterial occlusion. Three years ago, she also had an episode of pulmonary embolism. A pregnancy 18 months ago ended in miscarriage. Laboratory studies show a positive serologic test for syphilis, normal prothrombin time (PT), elevated partial thromboplastin time (PTT), and normal platelet count. Which of the following is the most likely cause of these findings?`,
        q2: ``,
        q3: [],
        option: [`Antiphospholipid antibody`, `Disseminated intravascular coagulation`,`Factor V mutation`,`Hypercholesterolemia `,`von Willebrand disease`],
         optionFeedback: [`    Antiphospholipid antibody fits all of the observed findings. These antibodies bind phospholipids and certain proteins and through mechanisms that are not yet fully explained increase the risk of arterial and venous clotting in vivo. Antiphosopholipid antibodies also frequently provide a false-positive serologic test for syphilis because the antigen in the standard assay for syphilis is embedded in cardiolipin.  `,`Disseminated intravascular coagulation usually presents acutely and is not associated with pulmonary embolism or the observed serologic abnormalities. `,`Factor V mutation is associated with deep venous thrombosis, not stroke, and cannot explain the observed serologic abnormalities.`,`Hypercholesterolemia is not associated with pulmonary embolism and cannot explain the observed serologic abnormalities. `,`von Willebrand disease is associated with bleeding, is an unusual association with stroke, is not associated with pulmonary embolism, and cannot explain the observed serologic abnormalities.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Antiphospholipid antibody fits all of the observed findings. These antibodies bind phospholipids and certain proteins and through mechanisms that are not yet fully explained increase the risk of arterial and venous clotting in vivo. Antiphosopholipid antibodies also frequently provide a false-positive serologic test for syphilis because the antigen in the standard assay for syphilis is embedded in cardiolipin`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 71-year-old man with a history of diabetes died of an acute myocardial infarction. At autopsy, the aorta, opened longitudinally, appeared as shown in the figure. Which of the following complications associated with this aortic disease would most likely have been present during his life?`,
        q2: `<img src="../images/f003-q014-9780323640251r.png"/>`,
        q3: [],
        option: [`Edema of the left leg`, ` Gangrene of the foot`,` Pulmonary thromboembolism`,`Hepatic infarction`,`Thrombocytopenia`],
         optionFeedback: [`Edema of the left leg is most likely to be caused by venous obstruction, such as by a deep venous thrombosis. `,`   The image shows extensive atherosclerosis. Gangrene of the foot might occur due to atherosclerotic disease in more distal vessels or in thromboembolic obstruction of distal vessels.  `,`Arterial atherosclerotic disease is not a source for pulmonary thromboemboli.`,`Hepatic infarction occurs rarely due to the liver’s dual blood supply and would be a very unusual complication of atherosclerotic disease. `,`Although platelets contribute to the formation of a thrombus, in focal thrombosis (e.g., as part of mural thrombi overlying an atherosclerotic vessel) not enough platelets are consumed to cause thrombocytopenia. Thrombocytopenia occurs with disseminated intravascular coagulation and other systemic consumptive coagulopathies such as thrombotic thrombocytopenia purpura and hemolytic uremic syndrome.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The image shows extensive atherosclerosis. Gangrene of the foot might occur due to atherosclerotic  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 55-year-old woman has a one-week history of discomfort and swelling of her left leg following major abdominal surgery. On physical examination, the leg slightly resists flexion and is tender to palpation. A Doppler sonogram shows thrombosis of deep leg veins. Which of the following is the most likely underlying factor that has led to her condition?`,
        q2: ``,
        q3: [],
        option: [` Lactic acidosis`, ` Venous stasis`,`Endothelial signaling through Toll-like receptors`,` Nitric oxide release by macrophages`,`Turbulent blood flow`],
         optionFeedback: [`Lactic acidosis is usually associated with severe illness and tissue hypoperfusion, which are not evident here. `,`The described clinical scenario is a classic situation in which prolonged immobility causes venous stasis and leads to deep vein thrombosis, likely because activated clotting factors (which would normally be washed away and removed from the circulation by the liver) accumulate in areas of stasis.`,`Endothelial signaling through Toll-like receptors may produce endothelial activation, a state that is prothrombotic, but if generalized would be more likely to be associated with intravascular coagulation than formation of a thrombus in a deep vein.`,`Nitric oxide release by macrophages might produce vasodilation, which is antithrombotic. `,`Turbulent blood flow is another factor that can lead to endothelial activation, but this is most likely to occur in high-pressure arterial vessels.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The described clinical scenario is a classic situation in which prolonged immobility causes venous stasis and leads to deep vein thrombosis, likely because activated clotting factors (which would normally be washed away and removed from the circulation by the liver) accumulate in areas of stasis.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 70-year-old man was hospitalized three weeks ago for a cerebral infarction. He is now ambulating for the first time. Within minutes of returning to his hospital room, he has sudden onset of dyspnea with diaphoresis. He cannot be resuscitated. The gross appearance of the hilum of the left lung at autopsy is shown in the figure. Which of the following risk factors most likely contributed to this finding?`,
        q2: `<img src="../images/f003-q017-9780323640251.png"/>`,
        q3: [],
        option: [`Antiphospholipid antibody`, ` Bronchopneumonia`,`Factor V mutation`,`Venous stasis`,`Pulmonary hypertension`],
         optionFeedback: [`Antiphospholipid antibody can be associated with venous or arterial thrombosis, but it is an unusual cause of fatal pulmonary embolism. `,`Local inflammation from pneumonia may cause thrombosis of small vessels in the affected part of the lung. `,`Factor V mutation could be contributory, but most of those affected present at younger ages than this patient.`,`   The figure shows a large embolus at the bifurcation of the pulmonary artery, causing death due to acute right heart failure. Venous stasis is the leading cause of fatal pulmonary embolism following an illness that results in immobility, as in this instance.  `,`Pulmonary hypertension can lead to vascular changes, including arterial wall hypertrophy and hyperplasia and microthrombi, but is not a cause of pulmonary thromboembolism. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The figure shows a large embolus at the bifurcation of the pulmonary artery, causing death due to acute right heart failure. Venous stasis is the leading cause of fatal pulmonary embolism following an illness that results in immobility, as in this instance.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 32-year-old man is involved in a vehicular accident and sustains fractures of the right femur and tibia and the left humerus. The fractures are repaired surgically. He is in stable condition for two days, but then suddenly becomes severely dyspneic. Which of the following complications from his injuries is the most likely cause of his sudden respiratory difficulty?`,
        q2: ``,
        q3: [],
        option: [`Cardiac rupture`, `Fat embolism`,`Pulmonary edema`,`Pulmonary infection`,`Bleeding into the pleural space`],
         optionFeedback: [`Cardiac rupture is most commonly a complication of recent myocardial infarction, for which there is no evidence. When caused by severe chest trauma, it would occur at the time of the injury.. `,` Fat embolism is a likely cause in this setting following trauma to multiple bones.  `,`Pulmonary edema is most commonly caused by heart failure, for which there is no evidence.`,`Pulmonary infection would not be expected to present with sudden onset of severe dyspnea. `,`Bleeding into the pleural space would be an unlikely cause of dyspnea in this setting except as an immediate complication of acute injury.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Fat embolism is a likely cause in this setting following trauma to multiple bones.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 22-year-old woman with an uncomplicated pregnancy develops sudden dyspnea with cyanosis and hypotension intrapartum during routine vaginal delivery of a term infant. She has a generalized seizure and becomes comatose. Her condition does not improve over the next two days. Which of the following findings is most likely to be present in her peripheral pulmonary arteries?`,
        q2: ``,
        q3: [],
        option: [`Aggregates of platelets`, ` Amniotic fluid`,`Fat globules`,`Gas bubbles`,`Thromboemboli`],
         optionFeedback: [`Aggregates of platelets may cause symptoms related to vessel obstruction, most often in hemolytic uremic syndrome, thrombotic thrombocytopenia purpura, and heparin-induced thrombocytopenia, but none of these is an acute complication of childbirth. `,` Amniotic fluid embolism is a rare but severe and frequently fatal complication of childbirth.  `,`Fat globules can cause similar symptoms if they reach the vasculature, but this typically occurs following trauma to bones.`,`Gas bubbles in blood vessels may occur in decompression sickness or may enter the circulation as a complication of instrumentation (e.g., laparoscopic surgery) that inadvertently introduces gas. `,`Thromboemboli arise in the setting of deep vein thrombosis of leg veins. In this case, amniotic fluid emboli are far more likely. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Amniotic fluid embolism is a rare but severe and frequently fatal complication of childbirth `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 31-year-old man is on a scuba diving trip and descends to a depth of 50 m in the Blue Hole off the coast of Belize. After 30 minutes, his equipment malfunctions and he quickly returns to the surface. Within five minutes, he develops difficulty breathing, with dyspnea and substernal chest pain, followed by a severe headache and vertigo. An hour later, he develops severe, painful myalgias and arthralgias. These symptoms abate within 24 hours. Which of the following most likely occluded his arterioles at the time of the event?`,
        q2: ``,
        q3: [],
        option: [`Fat globules`, ` Fibrin clots`,`Gas bubbles`,`Platelet thrombi`,`Ruptured atheromatous plaque`],
         optionFeedback: [`Fat globules (fat emboli) in the blood are a complication of physical trauma. `,`Fibrin clots may be a complication of disseminated intravascular coagulation (DIC), which is not associated with rapid decompression. `,`  This story is classic for “the bends” (decompression sickness), in which rapid ascent from pressurized depths causes inhaled nitrogen gas to come out of solution and form bubbles in vessels and other sites such as joints.  `,`Platelet thrombi are not associated with rapid decompression.`,`Ruptured atheromatous plaque is not a complication of decompression.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- This story is classic for “the bends” (decompression sickness), in which rapid ascent from pressurized depths causes inhaled nitrogen gas to come out of solution and form bubbles in vessels and other sites such as joints`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 53-year-old man with congestive heart failure develops pulmonary <i>Streptococcus pneumoniae</i> infection after a bout of influenza. After recuperating for 2 weeks, he notes pleuritic chest pain. The pain is caused by the development of the lesion shown in the figure. Which of the following events has most likely occurred in this man?`,
        q2: `<img src="../images/f003-q021-9780323640251.png"/>`,
        q3: [],
        option: [`Acute pulmonary venous congestion`, `Chronic pulmonary venous congestion`,`Pulmonary edema`,`Pulmonary infarction and hemorrhage`,` Pulmonary venous thrombosis`],
         optionFeedback: [`Acute pulmonary venous congestion would produce a diffusely red lung, not a focal area as seen in this image. `,`Chronic pulmonary venous congestion might produce a diffusely brownish lung due to recurrent small hemorrhages and deposition of hemosiderin. `,`Pulmonary edema would be associated with heavy, wet lungs, but not focal lesions.`,`  The presence of a “red” infarct is consistent with a pulmonary embolism, which produced infarction and subsequent hemorrhage in this patient in whom oxygenation was compromised by another superimposed process (congestive heart failure, pneumonia). Infacts are uncommon in the normal lung due to its dual circulation.  `,`Pulmonary venous thrombosis is very rare and may produce changes associated with pulmonary hypertension, rather than pulmonary infarction.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The presence of a “red” infarct is consistent with a pulmonary embolism, which produced infarction and subsequent hemorrhage in this patient in whom oxygenation was compromised by another superimposed process (congestive heart failure, pneumonia). Infacts are uncommon in the normal lung due to its dual circulation`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An 80-year-old woman with a 1-week history of dysuria presents with a 1-day history of fever. On examination, her temperature is 37.9° C, pulse 103 bpm, and blood pressure 80/40 mm Hg. She has right flank pain. A urinalysis shows numerous WBCs. Her plasma lactate is increased. Urine and blood cultures grow <i>Escherichia coli.</i> This clinical condition is most likely initiated by which of the following processes?`,
        q2: ``,
        q3: [],
        option: [` Activation of innate immune cells and endothelium by microbial products`, `Anaerobic glycolysis resulting in lactic acidosis`,` Disseminated intravascular coagulation resulting in widespread hypoxia`,`Triggering of mast cells resulting in release of vasoactive amines`,`Bilateral hemorrhage of adrenal glands resulting in adrenal insufficiency`],
         optionFeedback: [`    The patient has symptoms consistent with sepsis (septic shock) and systemic inflammatory response syndrome (SIRS), which is caused by systemic activation of the innate immune system, in this instance by microbial products.  `,`Anaerobic glycolysis resulting in lactic acidosis is a result, not a cause, of sepsis. `,`Disseminated intravascular coagulation resulting in widespread hypoxia is a result, not a cause, of sepsis.`,`Triggering of mast cells resulting in release of vasoactive amines is the underlying cause of anaphylactic shock, not systemic inflammatory response syndrome. `,`Bilateral hemorrhage of adrenal glands resulting in adrenal insufficiency (Waterhouse-Friderichsen syndrome) may be a complication of sepsis and systemic inflammatory response syndrome, not a cause. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The patient has symptoms consistent with sepsis (septic shock) and systemic inflammatory response syndrome (SIRS), which is caused by systemic activation of the innate immune system, in this instance by microbial products `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 63-year-old woman has had a fever and felt faint for the past 2 days. On physical examination, her temperature is 38.4° C, pulse is 101 bpm, respirations are 17 breaths per min, and blood pressure is 85/40 mm Hg. She has marked peripheral vasodilation. The serum lactic acid level is 6.8 mg/dL.    Which of the following laboratory findings is most likely related to the cause of her clinical condition?`,
        q2: ``,
        q3: [],
        option: [` Blood culture positive for <i>Pseudomonas aeruginosa </i>`, `Reduced serum C3`,` Elevated serum troponin I`,`Increased blood urea nitrogen`,`Reduced Po<sub>2</sub> on blood gas measurement`],
         optionFeedback: [`    Her symptoms are consistent with septic shock caused by infection with <i>Pseudomoanas aeruginosa</i>. `,`Reduced serum C3 is seen in disorders in which there is increased activation of complement, particularly disorders in which immune complexes form, such as systemic lupus erythematosus. `,`Elevated serum troponin I may be seen in disorders associated with injury to the heart.`,`Increased blood urea nitrogen is associated with renal failure, a potential complication of systemic inflammatory response syndrome. `,`Reduced Po<sub>2</sub> on blood gas measurement may be the result of many disorders, including acute respiratory distress syndrome, one of the complications of systemic inflammatory response syndrome.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Her symptoms are consistent with septic shock caused by infection with <i>Pseudomoanas aeruginosa</i>. `,
        state: `notAnswered`,
        userAnswered: [],
    }
    

   ];






