var quiz = [
    {
        q: `Several children between the ages of 3 and 6 years have been admitted to a local hospital with recent onset ataxia, nausea and vomiting and convulsions. All have previously exhibited delayed psychosocial development and have lived in the same community. On physical examination, the children have diffuse abdominal pain. Head CT scans show marked cerebral edema. Laboratory studies show microcytic anemia. Toxic exposure to which of the following substances is the most likely cause for this illness?`,
        q2: ``,
        q3: [],
        option: [`Ethylene glycol`, `Kerosene`, `Lead`,` Methanol`,`Mercury`],
        optionFeedback: [`Ethylene glycol, found in antifreeze, is sometimes the culprit in suicides and accidental pediatric poisonings (attributable to its sweet taste). Onset of symptoms is acute (unlike lead poisoning, which usually develops over time) and manifests as vomiting, abdominal pain, renal failure, diminished sensorium, headaches, and seizures.`,`Kerosene poisoning tends to manifest with fever, dyspnea, and often aspiration pneumonitis.`,`Lead poisoning is a well-established cause of microcytic anemia, abdominal “colic,” psychomotor delay, and (when severe) encephalopathy in children, who are particularly prone to poisoning in homes with lead paint. `,`Methanol poisoning presents with diminished sensorium, vomiting, metabolic acidosis, renal failure, and diminished vision, sometimes leading to blindness and death.`,`Mercury poisoning has many manifestations including muscle weakness, poor coordination, peripheral neuropathy, skin changes, and altered CNS function. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Lead poisoning is a well-established cause of microcytic anemia, abdominal “colic,” psychomotor delay, and (when severe) encephalopathy in children, who are particularly prone to poisoning in homes with lead paint. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 36-year-old man is the owner of a radiator repair shop, where he cleans, cuts, polishes, and welds metals. Over 6 months, he develops worsening malaise with headache and abdominal pains and finds that he frequently drops his tools. Complete blood count indicates microcytic anemia. Peripheral blood smear reveals basophilic stippling of RBCs. Which of the following findings would most likely be seen on physical examination?`,
        q2: ``,
        q3: [],
        option: [`Splenomegaly`, `Peripheral neuropathy`,`Ecchymosis`,`Dermatitis`,` Pathologic fractures`],
        optionFeedback: [`Splenomegaly occurs in certain hemolytic anemias such as hereditary spherocytosis; it is not a common finding in environmental poisonings or exposures.`,`The findings are characteristic of lead poisoning in an adult, in whom characteristic features include microcytic anemia, basophilic stippling, and peripheral neuropathy. `,`Ecchymosis might be evidence of a bleeding disorder. Exposure to rat poison (warfarin) is a potential environmental cause, but warfarin poisoning is not associated with basophilic stippling or microcytic anemia.`,`Dermatitis (rash) may be seen with a wide variety of environmental exposures, but is not a typical complication of lead poisoning.`,`Pathologic fractures occur when bone is weakened (e.g., osteoporosis, benign and malignant neoplasms). Although 80%–85% of absorbed lead is taken up by the bones and teeth, where it binds with phosphates, it does not cause pathologic fractures but, instead, areas of hyperdensity that can be appreciated on plain radiography.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale:-  The findings are characteristic of lead poisoning in an adult, in whom characteristic features include microcytic anemia, basophilic stippling, and peripheral neuropathy.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An increasing incidence of cerebral palsy, deafness, blindness, and intellectual disability is noted in young children in a coastal fishing community where a chemical plant began discharging its wastewater into the local bay 5 years earlier. In utero exposure to which of the following compounds is most likely responsible for the childrenâ€™s illness?`,
        q2: ``,
        q3: [],
        option: [`Arsenic`, `Cadmium`,`Methyl mercury`,`Lead`,`Dioxin`],
        optionFeedback: [`Arsenic poisoning usually occurs due to groundwater contamination or intentional poisoning. Acute poisoning is often associated with abdominal pain, diarrhea, and vomiting, while chronic poisoning often leads to skin changes, particularly darkening of the skin and hyperkeratosis, and is associated with an elevated risk of squamous cell carcinoma.`,`Cadmium poisoning usually occurs as the result of an industrial exposure, which may occur through water contamination or by inhalation during operations involving the use of cadmium paints or the smelting of metals. It is also present in many foods (e.g., cereals, organ meats, root crops, cocoa) which may be a significant source, depending on dietary habits, Acute exposure may cause flu-like symptoms and liver and renal damage, the latter leading to hypophosphatemia, osteomalacia, and hyperuricemia.`,`The symptoms are compatible with Minamata disease, caused by exposure of the developing fetus to methyl mercury, which readily passes from the mother to the fetal circulation via the placenta. Organic mercury becomes concentrated at the top of the food chain, and fish such as tuna and other predators are therefore likely to have particularly high levels of contamination.`,`Lead can be associated with neurologic changes and acute encephalopathy, but not typically cerebral palsy. It is most commonly ingested in contaminated water and lead paint.`,`Dioxin and related compounds such as polychlorinated biphenyl (PCB) are byproducts of industrial processes that if ingested in large amounts cause chloracne, a disfiguring, acne-like skin eruption.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The symptoms are compatible with Minamata disease, caused by exposure of the developing fetus to methyl mercury, which readily passes from the mother to the fetal circulation via the placenta. Organic mercury becomes concentrated at the top of the food chain, and fish such as tuna and other predators are therefore likely to have particularly high levels of contamination.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 61-year-old woman living in an industrial area with very poor air quality has a 7-month history of worsening cough and 1 week earlier had an episode of hemoptysis. She has an 80 pack-year smoking history. A chest radiograph shows a 7-cm infiltrative, perihilar mass in the right lung. Exposure to which of the following airborne agents is most likely to be associated with these findings?`,
        q2: ``,
        q3: [],
        option: [`Carbon monoxide`, `Nicotine`,`Sulfur dioxide`,` Ozone`,`Polycyclic aromatic hydrocarbons`],
        optionFeedback: [`Carbon monoxide may cause cardiovascular effects by decreasing the oxygen carrying capacity of the blood, but is not carcinogenic.`,`Nicotine is a CNS stimulant with addictive properties and has cardiovascular effects through nicotinic receptors, but is not carcinogenic.`,`Sulfur dioxide is an irritant in air pollution that can cause upper and lower airway symptoms and exacerbate COPD, but is not carcinogenic.`,`Ozone is an irritant in air pollution that can cause upper and lower airway symptoms and exacerbate COPD, but is not carcinogenic.`,`The clinical history and imaging studies support a diagnosis of lung cancer and the perihilar location is suggestive of small cell carcinoma and squamous cell carcinoma, two malignancies that are strongly associated with cigarette smoking. Polycyclic aromatic hydrocarbons are found in the tar fraction of cigarette smoke and are metabolized by the cytochrome P450 system to reactive molecules (e.g., epoxides) that are mutagenic and contribute to lung cancer development in smokers.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The clinical history and imaging studies support a diagnosis of lung cancer and the perihilar location is suggestive of small cell carcinoma and squamous cell carcinoma, two malignancies that are strongly associated with cigarette smoking. Polycyclic aromatic hydrocarbons are found in the tar fraction of cigarette smoke and are metabolized by the cytochrome P450 system to reactive molecules (e.g., epoxides) that are mutagenic and contribute to lung cancer development in smokers.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `While attending a party, a 19-year-old man drinks 2 L of mixed alcoholic beverages (50% ethanol by volume) over a 30-minute period. Prior to this episode, he only drank 1 to 2 drinks each month. He does not use illicit drugs, but has been taking acetaminophen for headaches. Which of the following complications is most likely to prove lethal within the first 12 hours?`,
        q2: ``,
        q3: [],
        option: [`Acute pancreatitis`, `Depressed brainstem reflexes`,`Acute liver failure`,`Variceal bleeding`,`Wernicke disease`],
        optionFeedback: [`Acute pancreatitis may occur after binge drinking, but is unlikely to be rapidly fatal.`,`Alcohol depresses neuronal function, and in large amounts can inhibit brainstem reflexes that control respiration, leading to respiratory failure, coma, and death.`,`Acute liver failure can be seen in acetaminophen overdose, but typically evolves slowly over several days with nausea, vomiting, diarrhea, and jaundice. Chronic alcoholics are more susceptible to acetaminophen toxicity since alcohol induces cytochrome P450 which increases production of toxic acetaminophen metabolites.`,`Variceal bleeding is a feature of chronic alcohol abuse in the setting of cirrhosis and portal hypertension, not acute toxicity.`,`Wernicke encephalopathy is a feature of chronic alcohol abuse complicated by thiamine deficiency.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Alcohol depresses neuronal function, and in large amounts can inhibit brainstem reflexes that control respiration, leading to respiratory failure, coma, and death.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 35-year-old man is admitted with recent onset hematemesis. Physical examination reveals hypotension, splenomegaly, and ascites. Endoscopy shows tortuous vessels and esophageal bleeding. Despite volume resuscitation and emergency surgery, the patient died. Excessive consumption of which of the following was the most likely cause of the gross findings?`,
        q2: ``,
        q3: [],
        option: [`Cocaine`, `Heroin`,`Alcohol`,`Nicotine`,`Aspirin`],
        optionFeedback: [`Cocaine abuse is associated with cardiovascular and CNS changes. `,`Heroin abuse is associated with infectious complications when used parenterally, including hepatitis B and C which, over time, could result in cirrhosis. However, heroin does not directly cause liver damage.`,`The dilated, tortuous veins are consistent with esophageal varices, most often caused by portal hypertension secondary to cirrhosis. These vessels are prone to rupture which can result in life-threatening hematemesis. Among the possible answers, only chronic alcohol abuse is commonly associated with cirrhosis. `,`Nicotine addiction is associated with complications of smoking, principally pulmonary and cardiac disease, not liver disease.`,`Aspirin overdose is associated with metabolic acidosis and cardiovascular collapse, whereas routine use is associated with a mild bleeding tendency. There is no association with cirrhosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The dilated, tortuous veins are consistent with esophageal varices, most often caused by portal hypertension secondary to cirrhosis. These vessels are prone to rupture which can result in life-threatening hematemesis. Among the possible answers, only chronic alcohol abuse is commonly associated with cirrhosis. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 39-year-old woman has been using low-dose estrogen–containing oral contraceptives intermittently for the past 20 years. She has smoked one pack of cigarettes per day for the past 18 years. She is G2, P2, and gave birth to two term live-born infants of low birth weight, without anomalies. Physical examination is unremarkable. Her BMI is 24 (high normal) and her total cholesterol is 300 mg/dL (&lt;200 mg/dL). She is at increased risk for developing which of the following conditions?`,
        q2: ``,
        q3: [],
        option: [` Breast carcinoma`, `Cholecystitis`,` Endometrial carcinoma`,`Myocardial infarction`,` Ovarian carcinoma`],
        optionFeedback: [`Estrogen exposure is mainly associated with an increased risk of breast cancer in post-menopausal women.`,`She may also be at increased risk for gallstones, but this is more likely in individuals who are obese, which she is not.`,`Endometrial carcinoma is most commonly associated with sustained estrogen exposure, which can be seen in patients with obesity, estrogen-secreting tumors (e.g., ovarian granulosa cell tumors), and polycystic ovary syndrome.`,`Smoking and hypercholesterolemia are important risk factors for myocardial infarction. Oral contraceptives do not increase the risk of coronary artery disease in women younger than 30 years or in older women who are nonsmokers, but the risk is approximately double in women older than 35 years who smoke. `,`Ovarian carcinoma risk appears to be somewhat decreased by use of oral contraceptives, and risk of this cancer is highest in post-menopausal women.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Smoking and hypercholesterolemia are important risk factors for myocardial infarction. Oral contraceptives do not increase the risk of coronary artery disease in women younger than 30 years or in older women who are nonsmokers, but the risk is approximately double in women older than 35 years who smoke. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 22-year-old football player collapses during practice due to cardiac arrest and cannot be resuscitated. The medical examiner investigating this sudden death finds mild coronary atherosclerosis, histologic evidence of hypertension in the renal blood vessels, and patchy myocyte dropout and interstitial myocardial fibrosis at autopsy. Use of which of the following substances by this man most likely led to these findings?`,
        q2: ``,
        q3: [],
        option: [`Fentanyl`, `Cocaine`,`Ethanol`,`Heroin`,`Marijuana`],
        optionFeedback: [`Opiates like fentanyl are mainly associated with death due to respiratory depression.`,`Cocaine use, even on single occasion, can lead to fatal cardiac arrhythmias due to its inhibitory effect on neurotransmitter uptake. At adrenergic nerve endings, it blocks the reuptake of both epinephrine and norepinephrine while stimulating the presynaptic release of norepinephrine. These neurotransmitters accumulate in synapses, causing hyperstimulation which results in tachycardia, hypertension, and peripheral vasoconstriction. “Excitotoxicity” may lead to necrosis of single myocytes and focal myocardial fibrosis.`,`Ethanol abuse mainly presents with altered sensorium and is not associated with sudden cardiac death.`,`Opiates like heroin are mainly associated with death due to respiratory depression.`,`Marijuana use mainly presents with altered sensorium and is not associated with sudden death of any cause.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Cocaine use, even on single occasion, can lead to fatal cardiac arrhythmias due to its inhibitory effect on neurotransmitter uptake. At adrenergic nerve endings, it blocks the reuptake of both epinephrine and norepinephrine while stimulating the presynaptic release of norepinephrine. These neurotransmitters accumulate in synapses, causing hyperstimulation which results in tachycardia, hypertension, and peripheral vasoconstriction. “Excitotoxicity” may lead to necrosis of single myocytes and focal myocardial fibrosis. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 26-year-old woman with a 6-month history of depression accompanied by active suicidal ideation ingests 35 g of acetaminophen. She quickly experiences nausea and vomiting. Within 1 day, she becomes progressively obtunded. On physical examination, her temperature is 36.9° C, pulse is 75 bpm, respirations are 15 breaths/min, and blood pressure is 100/65 mm Hg. Treatment with which of the following is most appropriate to conserve liver function?`,
        q2: ``,
        q3: [],
        option: [` N-acetylcysteine (NAC)`, `High-dose steroids`,`Insulin`,`Packed red blood cells`,`Ursodeoxycholic acid`],
        optionFeedback: [`Acetaminophen is metabolized in the liver by the cytochrome P-450 system to a highly reactive intermediate that is normally detoxified by conjugation with glutathione. Excess doses deplete glutathione and result in acute hepatocyte injury and necrosis, producing liver failure and (often) death. NAC is a precursor of glutathione and helps to replenish glutathione stores, limiting hepatocyte damage.`,`High-dose steroids have a role in the treatment of inflammatory, immunologic (e.g., autoimmune hepatitis), and allergic disorders, but not in the treatment of acetaminophen overdose. `,`Insulin is used to treat patients with diabetes. It does not have a role in the treatment of acetaminophen overdose.`,`Packed red blood cells are useful in cases of hemorrhage, as can be seen with ruptured esophageal varices or trauma.`,`Ursodeoxycholic acid slows progression of early stage primary biliary cholangitis by an unknown mechanism. It has no role in the treatment of acetaminophen toxicity. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Acetaminophen is metabolized in the liver by the cytochrome P-450 system to a highly reactive intermediate that is normally detoxified by conjugation with glutathione. Excess doses deplete glutathione and result in acute hepatocyte injury and necrosis, producing liver failure and (often) death. NAC is a precursor of glutathione and helps to replenish glutathione stores, limiting hepatocyte damage.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 27-year-old, previously healthy man collapses at a party where there is illicit drug use. In the ambulance, defibrillation is necessary to establish a normal cardiac rhythm. On physical examination, his temperature is 40° C; respirations, 30 breaths/min; heart rate, 110 bpm; and blood pressure, 175/90 mm Hg. He has dilated pupils and a perforated nasal septum. While in the hospital he has a seizure. Which of the following is the most likely effect of the drug consumed by this individual?`,
        q2: ``,
        q3: [],
        option: [` Depression of respiratory centers in the brainstem`, `Blockade of serotonin uptake in the brainstem`,` Inhibition of epinephrine reuptake at synaptic junctions`,` Direct stimulation of membrane receptors in neurons`,`Increased production of dopamine in the brain`],
        optionFeedback: [`Depression of respiratory centers in the brainstem is characterized by 8–12 breaths/minute (not the brisk respiratory rate seen in the patient) and is a feature of opiate use.`,`Blockade of serotonin uptake in the brainstem is a feature of hallucinogens such as lysergic acid diethylamide (LSD).`,`The perforated septum, hyperpyrexia, tachycardia, and seizures are consistent with chronic cocaine use by snorting. At adrenergic nerve endings, cocaine blocks the reuptake of both epinephrine and norepinephrine while also stimulating the presynaptic release of norepinephrine. The resulting accumulation of these neurotransmitters in synapses cause “hyperstimulation” that produces tachycardia and arterial vasoconstriction. This mismatch of “supply and demand” may cause cardiac ischemia, which together with hyperstimulation may provoke serious and sometimes fatal arrhythmias. In the CNS, cocaine blocks dopamine reuptake; the most common CNS findings are hyperpyrexia (due to effects on pathways that control body temperature) and seizures (due to hyperstimulation).`,`Direct stimulation of membrane receptors in neurons underlies the effects of cannabinoids in marijuana.`,`Increased production of dopamine in the brain is not a feature of cocaine which acts by blocking reuptake, thereby flooding synapses with dopamine.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The perforated septum, hyperpyrexia, tachycardia, and seizures are consistent with chronic cocaine use by snorting. At adrenergic nerve endings, cocaine blocks the reuptake of both epinephrine and norepinephrine while also stimulating the presynaptic release of norepinephrine. The resulting accumulation of these neurotransmitters in synapses cause “hyperstimulation” that produces tachycardia and arterial vasoconstriction. This mismatch of “supply and demand” may cause cardiac ischemia, which together with hyperstimulation may provoke serious and sometimes fatal arrhythmias. In the CNS, cocaine blocks dopamine reuptake; the most common CNS findings are hyperpyrexia (due to effects on pathways that control body temperature) and seizures (due to hyperstimulation).`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 20-year-old man is brought to the hospital Emergency Department by a friend who found him unconscious in his apartment after trying to contact him for 3 days. On arrival, the patient is in a state of respiratory depression. He experiences convulsions for 2 minutes, followed by cardiac arrest. Advanced cardiac life support measures are instituted, and he is stabilized and intubated. On physical examination, there are needle tracks in the left antecubital fossa and miosis. Echocardiography reveals tricuspid incompetence and the presence of vegetations. His temperature is 39.2° C.  Use of which of the following substances by this man most likely produced these findings?`,
        q2: ``,
        q3: [],
        option: [`Cocaine`, `Ethanol`,`Tetrahydrocannabinoid (THC)`,` Heroin`,` Amphetamine`],
        optionFeedback: [`Cocaine is usually taken by snorting or smoking and kills through cardiovascular dysfunction, not respiratory arrest.`,`Ethanol kills most commonly through respiratory depression but is not associated with endocarditis or the other findings in this case.`,`Tetrahydrocannabinoid (the principle psychoactive ingredient in marijuana) is not associated with sudden death or any of the other features in this case.`,`Intravenous drug use is consistent with the skin tracks, respiratory arrest, miosis, and apparent right-sided endocarditis. Heroin is an opiate that causes respiratory depression.`,`Amphetamines, due to similar mechanism of action, tend to be associated with complications similar to those seen with cocaine abuse.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Intravenous drug use is consistent with the skin tracks, respiratory arrest, miosis, and apparent right-sided endocarditis. Heroin is an opiate that causes respiratory depression.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 56-year-old man with a 60 pack-year history of smoking has been diagnosed with a squamous cell carcinoma of the larynx. He receives local radiation therapy to treat the carcinoma. One year later, endoscopy shows no gross evidence of residual carcinoma. Which of the following adverse effects is most likely to be present in this patient as a result of this radiotherapy?`,
        q2: ``,
        q3: [],
        option: [`Azoospermia`, `Cerebral atrophy`,`Colonic ulceration`,`Marrow aplasia`,`Salivary gland fibrosis`],
        optionFeedback: [`Azoospermia results only with radiation given directly to the testes or whole body.`,`If given to the CNS, radiation can produce a late brain injury consisting of demyelinization and white matter necrosis. `,`Colonic ulceration is associated with abdominal radiation, not localized head and neck radiation.`,`Marrow aplasia should not be a complication of involved field radiation to the larynx; it occurs with whole body radiation.`,`Therapeutic doses of radiation can cause acute vascular injury resulting in tissue damage due to ischemia, and over time, scarring and fibrosis of tissues included in the irradiated field.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Therapeutic doses of radiation can cause acute vascular injury resulting in tissue damage due to ischemia, and over time, scarring and fibrosis of tissues included in the irradiated field.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `The firemen who initially responded to fight the fires from the Chernobyl nuclear reactor accident were exposed to high radiation levels, some exceeding 50 Sv (5000 cGy). Within hours, many reported nausea and vomiting, confusion and seizures. Acute damage to which of the following tissues most likely led to this finding?`,
        q2: ``,
        q3: [],
        option: [`Bone marrow`, `Cerebrum`,`Heart`,`Lungs`,`Small intestine`],
        optionFeedback: [`Because formed peripheral blood elements persist for days to weeks, bone marrow aplasia will not produce symptoms in the first hours after radiation exposure. `,`High doses of radiation can cause acute brain swelling (edema), which may prove fatal. `,`Heart damage from radiation typically takes the form of late vascular changes and ischemic changes (years after exposure).`,`Lung damage takes the form of radiation pneumonitis, which most commonly appears 1–3 months after radiation exposure.`,`Acute small intestinal damage stems from killing of rapidly dividing intestinal epithelial cells, leading to sloughing of the epithelial lining, bloody diarrhea, and pain. It usually appears after several days, too late to explain the symptoms in these victims of a nuclear accident.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- High doses of radiation can cause acute brain swelling (edema), which may prove fatal. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 3-year-old boy has a 6-month history of multiple respiratory infections. On physical examination, the child appears chronically ill, listless, and underdeveloped. He is 50% of ideal body weight and has marked muscle wasting of the extremities. Laboratory findings include hemoglobin, 9.4 g/dL (12.0–16.0 g/dL); hematocrit, 27.9% (41%–53%); mean corpuscular volume (MCV), 75 µm<sup>3</sup> (80–100 µm<sup>3</sup>); platelet count, 182,000/mm<sup>3</sup> (150,000–400,000/mm<sup>3</sup>); WBC count, 6,730/mm<sup>3</sup> (4,500–11,000 mm<sup>3</sup>); serum albumin, 4.1 g/dL (normal 3.5–5.5 g/dL); and total protein, 6.8 g/dL (6.0–7.8 g/dL). Which of the following conditions is most likely to explain these findings?`,
        q2: ``,
        q3: [],
        option: [`Bulimia`, `Folate deficiency`,`Kwashiorkor`,`Lead poisoning`,` Marasmus`],
        optionFeedback: [`Bulimia is a condition of induced regurgitation, often associated with binge/purge eating behavior. Those affected are not malnourished but may have features related to frequent vomiting, such as electrolyte imbalances and aspiration of gastric contents.`,`Folate deficiency, if severe, leads to megaloblastic anemia, which is not associated in its initial phases with profound weight loss and leads to macrocytic anemia, not microcytic anemia.`,`Kwashiorkor is a form of malnutrition caused by deficiency of protein in the diet, not calorie deficiency. Individuals are typically edematous due to hypoalbuminemia.`,`Lead poisoning is associated with microcytic anemia but does not cause profound weight loss.`,`This child is markedly underweight and thin and shows muscle loss, all features of marasmus, which is caused by malnutrition due to inadequate calorie intake. Unlike kwashiorkor, serum albumin level remains near normal.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- This child is markedly underweight and thin and shows muscle loss, all features of marasmus, which is caused by malnutrition due to inadequate calorie intake. Unlike kwashiorkor, serum albumin level remains near normal.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 5-year-old boy has had recurrent upper respiratory infections for the past 2 months. He is at the 55th percentile for height and the 38th percentile for weight. Physical examination shows generalized edema, ascites, muscle wasting, and areas of desquamation of skin over the trunk and extremities. Laboratory studies are most likely to show which of the following findings?`,
        q2: ``,
        q3: [],
        option: [`Thrombocytopenia`, `Hypoalbuminemia`,`Hypocalcemia`,`Hyperglycemia`,`Megaloblastic anemia`],
        optionFeedback: [`Thrombocytopenia, if severe, would present with petechial bleeding.`,`The findings (skin desquamation, muscle wasting, preservation of weight, edema) are all consistent with kwashiorkor, a form of protein deficiency malnutrition. The edema stems from low blood protein levels.`,`Hypocalcemia, if severe, would present with tetany, and is not a common feature of malnutrition.`,`Hyperglycemia is most commonly seen in diabetes and is not a feature of malnutrition.`,`Megaloblastic anemia may be seen with diets deficient in folate but is associated with cytopenias and mucosal abnormalities; it does not explain the patient’s edema, ascites, muscle wasting or other findings.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The findings (skin desquamation, muscle wasting, preservation of weight, edema) are all consistent with kwashiorkor, a form of protein deficiency malnutrition. The edema stems from low blood protein levels.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `An epidemiologic study in an impoverished community finds increased numbers of pediatric respiratory tract infections due to multiple organisms. Most of the children have a history of pneumonitis. The study documents increased rates of blindness, urinary tract calculi, and generalized papular dermatosis in these children as they reach adulthood. These children are most likely to have a deficiency of which of the following vitamins?`,
        q2: ``,
        q3: [],
        option: [`Vitamin A`, `Vitamin B`,`Vitamin E`,`Vitamin D`,`Vitamin K`],
        optionFeedback: [`Vitamin A has an important role in regulating the proper differentiation of epithelial cells. When deficient, abnormal keratinization of the cornea may lead to blindness, whereas similar changes in the respiratory tract may disrupt the mucociliary clearance of organisms, leading to increased rates of infection. The dermatosis also is a manifestation of perturbed epithelial differentiation, and renal and bladder stones arise secondary to squamous metaplasia of the urinary tract. `,`Vitamin B<sub>1</sub> (thiamine) deficiency is associated with high output heart failure (beriberi), peripheral neuropathy, and Wernicke encephalopathy. `,`Vitamin E deficiency is associated with skeletal muscle abnormalities, ataxia, and vision loss.`,`Vitamin D deficiency is associated with rickets in children and osteomalacia in adults due to its central role in calcium and phosphate metabolism. Vitamin D deficiency may also increase susceptibility to certain infectious agents.`,`Vitamin K deficiency presents with a bleeding diathesis: vitamin K is necessary for the synthesis of coagulation factors II, VII, IX, and X, as well as other calcium-binding factors that regulate blood clotting. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Vitamin A has an important role in regulating the proper differentiation of epithelial cells. When deficient, abnormal keratinization of the cornea may lead to blindness, whereas similar changes in the respiratory tract may disrupt the mucociliary clearance of organisms, leading to increased rates of infection. The dermatosis also is a manifestation of perturbed epithelial differentiation, and renal and bladder stones arise secondary to squamous metaplasia of the urinary tract. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 3-year-old boy presents to the pediatrician when his mother notices that he has difficulty walking and is short for his age. Physical examination reveals the findings in the figure. Ophthalmologic exam is normal and there are no petechiae or areas of purpura on the skin. Which of the following is the most direct cause of the observed skeletal abnormalities? <img src="../images/f019-q018-9780323640251.png" alt="icon"/>`,
        q2: ``,
        q3: [],
        option: [`Reduced synthesis of osteoid `, `Overgrowth of epiphyseal cartilage`,` Metastatic calcification`,`Reduced intestinal absorption of calcium`,` Keratomalacia`],
        optionFeedback: [`Osteoid production is unaffected by vitamin D deficiency; however, the resulting osteoid is not effectively mineralized and accumulates beneath the growth plate (metaphysis).`,`The bowing of the legs in this patient is characteristic of rickets caused by vitamin D deficiency, which leads to inadequate ossification of growing cartilage within the epiphyseal plates. This abnormality in turn leads to cartilage overgrowth and softening of the bones, which bend under physical stress.`,`Metastatic calcification is a feature of disorders associated with hypercalcemia, such as vitamin D toxicity or hyperparathyroidism.`,`Reduced absorption of calcium in the gut may be a complication of certain diets, drugs, and vitamin D deficiency. However, the alterations in calcium metabolism that ultimately lead to the bone defect in rickets involve not only decreased calcium uptake, but also inadequate uptake of phosphate and low serum phosphate levels, which may be the most important factor in inadequate bone mineralization.`,`Keratomalacia (keratinization of the cornea) is a feature of vitamin A deficiency and would be unlikely in a patient with a normal ophthalmologic exam.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The bowing of the legs in this patient is characteristic of rickets caused by vitamin D deficiency, which leads to inadequate ossification of growing cartilage within the epiphyseal plates. This abnormality in turn leads to cartilage overgrowth and softening of the bones, which bend under physical stress. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 75-year-old woman presents to the Emergency Department with a 2-week history of right leg pain. The patient lives alone and eats sparingly because of her low fixed retirement income. On physical examination, the patient is noted to be thin and somewhat debilitated. There is marked tenderness to palpation over the lateral aspect of the right shin, a poorly healed cut on the right hand, and a diffuse petechial skin rash that appears centered on hair follicles. A radiograph shows a right tibial subperiosteal hematoma. Laboratory studies show a hemoglobin level of 11.3 g/dL (12.0–16.0 g/dL). A deficiency of which of the following nutrients is most likely to explain these findings?`,
        q2: ``,
        q3: [],
        option: [`Ascorbic acid`, `Folate `,`Thiamine `,`Riboflavin `,` Vitamin K`],
        optionFeedback: [`The findings are consistent with scurvy, a deficiency of dietary vitamin C (ascorbic acid). Vitamin C is required for collagen crosslinking, and its deficiency leads to poor wound healing and vascular fragility. Humans do not synthesize ascorbic acid endogenously, and the vitamin must be obtained from the diet. It is present in milk and some animal products (liver, fish) and is abundant in a variety of fruits and vegetables. Debilitated patients, patients on restrictive (“fad”) diets and those with limited access to healthy foods are particularly susceptible to scurvy. `,`Folate deficiency typically presents with megaloblastic anemia and symptoms related to cytopenia.`,`Thiamine deficiency is marked by high output heart failure (beriberi), peripheral neuropathy, and Wernicke encephalopathy.`,`Riboflavin deficiency is associated with cheilosis, glossitis, seborrheic dermatitis, and corneal abnormalities.`,`Vitamin K deficiency presents with bleeding due to the requirement for vitamin K for the synthesis of coagulation factors II, VII, IX, and X, as well as other calcium binding factors that regulate blood clotting.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The findings are consistent with scurvy, a deficiency of dietary vitamin C (ascorbic acid). Vitamin C is required for collagen crosslinking, and its deficiency leads to poor wound healing and vascular fragility. Humans do not synthesize ascorbic acid endogenously, and the vitamin must be obtained from the diet. It is present in milk and some animal products (liver, fish) and is abundant in a variety of fruits and vegetables. Debilitated patients, patients on restrictive (“fad”) diets and those with limited access to healthy foods are particularly susceptible to scurvy. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 55-year-old woman has a 1-year history of worsening memory and difficulty with tasks of daily living. She has had watery diarrhea for the past 3 months. Physical examination shows red, scaling skin in sun-exposed areas. Deep tendon reflexes are normal, and sensation is intact. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Beriberi`, ` Cheilosis`,`Hypothyroidism`,`Marasmus`,`Pellagra`],
        optionFeedback: [`Beriberi is a form of high output cardiac failure caused by thiamine (vitamin B<sub>1</sub>) deficiency.`,`Cheilosis (angular stomatitis) is a feature of riboflavin (vitamin B<sub>2</sub>) deficiency, but can also be seen with other vitamin deficiencies, including niacin deficiency. It is not a specific disease.`,`Hypothyroidism may present with many alterations, including skin changes (myxedema), fatigue (due to decreased cardiac output), and constipation.`,`Marasmus is a wasting condition caused by inadequate caloric intake (starvation).`,`Pellagra, caused by niacin (vitamin B<sub>3</sub>) deficiency, is characterized by diarrhea, dermatitis, and dementia, all features seen in this case. `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Pellagra, caused by niacin (vitamin B<sub>3</sub>) deficiency, is characterized by diarrhea, dermatitis, and dementia, all features seen in this case. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 52-year-old woman with a long history of ethanol abuse has had congestive heart failure for the past year and presents with a 1-month history of increasing confusion, disorientation, and difficulty ambulating. Physical examination shows nystagmus, ataxia of gait, and decreased sensation in the lower extremities. Laboratory studies show hemoglobin, 13.1 g/dL (12.0–16.0 g/dL); hematocrit, 39.3% (36.0–46%); mean corpuscular volume (MCV), 90 µm<sup>3</sup> (80–100 µm<sup>3</sup>); platelet count, 269,300/mm<sup>3</sup> (150,000–400,000/mm<sup>3</sup>); and WBC count 7,120/mm<sup>3</sup> (4,500–11,000 mm<sup>3</sup>). A long-term dietary deficiency of which of the following nutrients is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Folate`, `Niacin`,`Pyridoxine`,`Riboflavin`,` Thiamine`],
        optionFeedback: [`Folate deficiency typically presents with megaloblastic anemia and symptoms related to cytopenias.`,`Niacin deficiency is characterized by diarrhea, dermatitis, and dementia.`,`Pyridoxine deficiency may present with seborrheic dermatitis, glossitis, stomatitis, and neuropathies. `,`Riboflavin deficiency is associated with cheilosis, glossitis, seborrheic dermatitis, and corneal abnormalities.`,`Thiamine deficiency is marked by high output heart failure (beriberi), peripheral neuropathy, and Wernicke encephalopathy, all of which may be present in this case.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Thiamine deficiency is marked by high output heart failure (beriberi), peripheral neuropathy, and Wernicke encephalopathy, all of which may be present in this case.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 55-year-old woman has been steadily gaining weight for the past 30 years. She underwent a cholecystectomy for cholelithiasis 5 years ago. She does not smoke. She is 164 cm (5 ft 4 in) tall and weighs 126 kg (BMI 47). On physical examination, she has decreased range of motion with pain on movement of the knees. Laboratory studies show a blood glucose level of 176 mg/dL (fasting, 70–110 mg/dL). This patient is at greatest risk of developing which of the following neoplasms?`,
        q2: ``,
        q3: [],
        option: [` Liposarcoma`, `Endometrial carcinoma`,`Hepatocellular carcinoma`,`Pulmonary squamous cell carcinoma`,`Carcinoma of the cervix`],
        optionFeedback: [`Liposarcoma has no known risk factors, outside of rare individuals who inherit mutations in the TP53 tumor suppressor gene (Li-Fraumeni syndrome). `,`Because of her obesity, this woman is exposed to higher levels of endogenous estrogen since androgens produced by the adrenal glands and ovaries are converted to estrogen by adipocytes, a reaction catalyzed by the enzyme aromatase. Sustained stimulation of the growth of uterine glands by estrogen is an important risk factor for endometrial carcinoma. `,`The major risk factors for hepatocellular carcinoma are chronic infection with hepatitis B or C, as well as other causes of chronic liver injury.`,`Pulmonary squamous cell carcinoma risk is mainly associated with smoking tobacco.`,`Carcinoma of the cervix risk is mainly associated with chronic infection by high-risk human papillomaviruses, not increased estrogen exposure.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Because of her obesity, this woman is exposed to higher levels of endogenous estrogen since androgens produced by the adrenal glands and ovaries are converted to estrogen by adipocytes, a reaction catalyzed by the enzyme aromatase. Sustained stimulation of the growth of uterine glands by estrogen is an important risk factor for endometrial carcinoma. `,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `A 45-year-old female presents to a nutritionist for dietary advice. Her BMI is 35 and she has a consistently high caloric intake because she lacks a feeling of satiety when eating. She is most likely to have diminished responsiveness to which of the following molecules?`,
        q2: ``,
        q3: [],
        option: [`Ghrelin`, `Glucagon`,`Neuropeptide Y`,`Adiponectin`,`Leptin`],
        optionFeedback: [`Ghrelin is a peptide hormone released from the stomach in response to fasting that binds receptors in the CNS and stimulates appetite. `,`Glucagon is released from pancreatic alpha cells in a fashion that is negatively regulated by glucose and insulin. It acts to raise glucose levels in the blood by increasing gluconeogenesis by the liver.`,`Neuropeptide Y is a neurotransmitter produced in the CNS and is a potent stimulator of food consumption and reduction in energy expenditure via actions in the hypothalamus.`,`Adiponectin is an adipocyte-derived cytokine that acts in the liver and skeletal muscle, thereby decreasing free fatty acid levels. There is evidence that adiponectin levels are inappropriately low in obesity, not that tissues are unresponsive to its effects.`,`Leptin is a hormone released from adipocytes that acts on leptin receptors in the hypothalamus and brain stem to suppress appetite and promote energy expenditure. Obesity is associated with leptin resistance; therefore, despite adequate energy reserves, the body remains in an anabolic state.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Leptin is a hormone released from adipocytes that acts on leptin receptors in the hypothalamus and brain stem to suppress appetite and promote energy expenditure. Obesity is associated with leptin resistance; therefore, despite adequate energy reserves, the body remains in an anabolic state.`,
        state: `notAnswered`,
        userAnswered: [],
    },
     {
        q: `It is 1:00 am and a hard-working medical student notes that her concentration is fading because she has not eaten anything in the 7 hours since dinner. She eats some cheese and an apple and resumes studying. Which of the following substances was most likely to have increased rapidly when she became hungry and decreased promptly after she finished her healthy snack?`,
        q2: ``,
        q3: [],
        option: [` Leptin`, `Corticotropin-releasing factor (CRF)`,`Ghrelin`,`Adiponectin`,`Thyrotropin-releasing hormone (TRH)`],
        optionFeedback: [`Leptin is a hormone produced by adipocytes when fat stores are abundant. It is an appetite suppressant.`,`Corticotropin-releasing factor (CRF) is produced in the hypothalamus and stimulates the release of adrenocorticotrophic hormone (ACTH) from the anterior pituitary, increasing the basal metabolic rate and catabolic metabolism.`,`Ghrelin is a peptide produce by gastric epithelial cells that can enter the CNS and directly stimulate appetite centers in the hypothalamus. Ghrelin levels rise before meals and fall between 1 and 2 hours after eating. In obese individuals, the postprandial suppression of ghrelin is attenuated and may contribute to overeating.`,`Adiponectin is a cytokine released from adipocytes that acts in the liver and skeletal muscle to reduce free fatty acid levels.`,`Thyrotropin-releasing hormone (TRH) is produced in the hypothalamus and stimulates the release of thyroid stimulating hormone (TSH) from the anterior pituitary. TRH increases the basal metabolic rate and adaptive thermogenesis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Ghrelin is a peptide produce by gastric epithelial cells that can enter the CNS and directly stimulate appetite centers in the hypothalamus. Ghrelin levels rise before meals and fall between 1 and 2 hours after eating. In obese individuals, the postprandial suppression of ghrelin is attenuated and may contribute to overeating.`,
        state: `notAnswered`,
        userAnswered: [],
    }
    

   ];
