var quiz = [
    {
        q: `A 44-year-old woman is found to have a blood pressure of 150/100 mm Hg on a routine physical examination. Laboratory studies show normal serum potassium, sodium, and natriuretic peptide levels and increased plasma renin activity. Which of the following vascular abnormalities is most likely to be seen in the renal artery?`,
        q2: ``,
        q3: [],
        option: [` Arterial dissection`, ` Arteriovenous fistula`, ` Berry aneurysm`,`Renal artery stenosis`,` Fibrinoid necrosis`],
        optionFeedback: [`Arterial dissection classically involves the aorta and occurs at high frequency in patients with Marfan syndrome.`,`Arteriovenous fistula is an abnormal connection between an artery and a vein; it may be congenital or may form during life due to trauma or local inflammation. Significant shunting of blood to the venous system lowers arterial pressure, increases cardiac preload, and may produce high output cardiac failure. The renal artery is not commonly involved.`,`Berry (saccular) aneurysm is a congenital malformation that occurs at increased frequency in patients with autosomal dominant polycystic kidney disease. It is most common in central nervous system arteries and when ruptured, causes subarachnoid hemorrhage, which is often fatal.`,` Unilateral renal artery stenosis leading to renal “underperfusion” results in increased renin release, which in turn acts on plasma angiotensinogen I; the latter is converted to angiotensinogen II in the periphery, which leads to secondary hypertension by causing vasoconstriction, aldosterone secretion, and increased sodium retention by the kidney. Stenosis can be due to atherosclerosis or renal artery fibromuscular dysplasia. It is important to recognize because stenting of the obstruction can relieve hypertension and its long-term complications.  `,`Fibrinoid necrosis is often seen with severe forms of vasculitis, such as polyarteritis nodosa. Such patients usually have signs of systemic inflammation. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Unilateral renal artery stenosis leading to renal “underperfusion” results in increased renin release, which in turn acts on plasma angiotensinogen I; the latter is converted to angiotensinogen II in the periphery, which leads to secondary hypertension by causing vasoconstriction, aldosterone secretion, and increased sodium retention by the kidney. Stenosis can be due to atherosclerosis or renal artery fibromuscular dysplasia. It is important to recognize because stenting of the obstruction can relieve hypertension and its long-term complications.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 55-year-old woman has had dull, episodic headaches for the past year, but otherwise she feels fine and has had no major medical illnesses or surgical procedures during her lifetime. On physical examination, her blood pressure is 166/112 mm Hg. Her lungs are clear on auscultation, and her heart rate is regular. An abdominal ultrasound scan shows that the left kidney is markedly smaller than the right kidney. A renal angiogram shows a focal stenosis of the left renal artery. Which of the following laboratory findings is most likely to be present in this patient?`,
        q2: ``,
        q3: [],
        option: [`Increased anti–double-stranded DNA titer (1:512)`, ` Increased PR3-ANCA (c-ANCA) titer (1:256)`,`Increased cryoglobulins in blood`,`Increased plasma glucose level (200 mg/dL)`,`Increased plasma renin activity (15 ng/mL/hr)`],
        optionFeedback: [`Increased anti–double-stranded DNA titer (1:512) would be a feature of systemic lupus erythematosus, which is not consistent with the clinical scenario.`,`Increased PR3-ANCA titer (1:256) would be a feature of granulomatosis with polyangiitis and other vasculitides, which is not consistent with the clinical scenario.`,`Increased cryoglobulins in blood might be a feature of hepatitis C, an autoimmune disorder, or a B cell neoplasm, none of which is consistent with the clinical scenario.`,`Increased plasma glucose level (200 mg/dL) would be indicative of diabetes, which is not consistent with the clinical scenario.`,` The most likely explanation for the decreased size of the left kidney is that it is hypoperfused. Unilateral renal hypoperfusion will result in increased release of renin and systemic hypertension. `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale:- The most likely explanation for the decreased size of the left kidney is that it is hypoperfused. Unilateral renal hypoperfusion will result in increased release of renin and systemic hypertension.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A group of subjects whose systemic blood pressure measurements are consistently between 145/95 mm Hg and 165/105 mm Hg is investigated for the cause of hypertension. They are found to have increased cardiac output and peripheral vascular resistance. Renal angiograms show no abnormal findings, and computed tomography scans of the abdomen show no masses. Laboratory studies show normal levels of serum creatinine and urea nitrogen. Which of the following laboratory findings is most likely to be present in this group of subjects?`,
        q2: ``,
        q3: [],
        option: [`. Decreased urinary sodium`, `Elevated plasma renin`,`Hypokalemia`,`Increased urinary catecholamines`,`Decreased angiotensin-converting enzyme activity`],
        optionFeedback: [` The findings are consistent with “essential” or primary hypertension, in which increased retention of sodium increases blood volume and cardiac output, raising blood pressure. `,`Elevated plasma renin is a feature of renal underperfusion caused by conditions such as renal artery stenosis.`,`Hypokalemia is a feature of hyperaldosteronism, such as may occur in individuals with a functional adrenal adenoma or be secondary to reduced renal perfusion.`,`Increased urinary catecholamines may be seen in individuals with tumors that secrete catecholamines, such as pheochromocytomas and paragangliomas.`,`Decreased angiotensin-converting enzyme (ACE) activity would result in hypotension, not hypertension. In line with this, ACE inhibitors are an important class of antihypertensive agent.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The findings are consistent with “essential” or primary hypertension, in which increased retention of sodium increases blood volume and cardiac output, raising blood pressure.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 61-year-old man has reported increasing fatigue over the past year. Laboratory studies show a serum creatinine level of 4.7 mg/dL and blood urea nitrogen level of 44 mg/dL.  An abdominal ultrasound scan shows that his kidneys are symmetrically smaller than normal. A high-magnification microscopic image representative of his kidneys is shown in the figure. These findings are most likely to indicate which of the following underlying conditions?<img src="../images/f007-q004-9780323640251.png" />`,
        q2: ``,
        q3: [],
        option: [` Familial hypercholesterolemia`, `Septic shock`,`Hepatitis B`,`Tertiary syphilis`,`Systemic hypertension`],
        optionFeedback: [`Familial hypercholesterolemia produces “accelerated” early onset atherosclerosis of large- and medium-sized arteries.`,`Septic shock might be associated with evidence of renal damage due to hypoperfusion (e.g., tubular injury), but would not show hyaline arteriosclerosis.`,`Hepatitis B is sometimes associated with renal immune complex disease, taking the form of membranous glomerulonephritis.`,`Tertiary syphilis is associated with granulomatous lesions called gummas that involve a wide variety of tissues.`,` The kidneys show hyaline arteriosclerosis, a characteristic morphologic change associated with systemic hypertension. `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The kidneys show hyaline arteriosclerosis, a characteristic morphologic change associated with systemic hypertension. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 45-year-old man has had poorly controlled hypertension ranging from 150/90 mm Hg to 160/95 mm Hg for the past 11 years. Over the past 3 months, his blood pressure has increased to 250/125 mm Hg. Imaging studies of the heart show left ventricular hypertrophy. Laboratory studies show that his serum creatinine level has increased during this time from 1.7 mg/dL to 6.8 mg/dL.    Which of the following vascular lesions is most likely to be found in this patient’s kidneys?`,
        q2: ``,
        q3: [],
        option: [`Hyaline arteriosclerosis`, `Granulomatous arteritis`,` Renal arterial stenosis`,`Necrotizing arteriolitis`,`Polyarteritis nodosa`],
        optionFeedback: [`Hyaline arteriosclerosis is a feature of chronic, milder forms of systemic hypertension.`,`Granulomatous arteritis is a feature of granulomatosis with polyangiitis, often associated with PR3-ANCA antibodies and is not associated with malignant hypertension.`,`Renal arterial stenosis is classically unilateral and although it is associated with hypertension due to activation of the renin-angiotensin system, the hypertension does not reach the threshold for malignant hypertension, as seen in this patient.`,` The patient has developed “malignant” hypertension (systolic pressure more than 200 mm Hg), which may be associated with vascular injury to small arterioles of sufficient severity to cause necrosis. If untreated, it can lead to renal failure,and cerebral edema, and places the heart at risk for ischemia (due to high wall tensions), arrhythmias, and left-sided failure.  `,`Polyarteritis nodosa is characterized by fibrinoid necrosis of small- to medium-sized muscular arteries resulting from immune complex injury, and is not associated with malignant hypertension.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The patient has developed “malignant” hypertension (systolic pressure more than 200 mm Hg), which may be associated with vascular injury to small arterioles of sufficient severity to cause necrosis. If untreated, it can lead to renal failure,and cerebral edema, and places the heart at risk for ischemia (due to high wall tensions), arrhythmias, and left-sided failure.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 58-year-old man had a myocardial infarction 1 year ago, which was the first major illness in his life. He now wants to prevent another acute coronary event and is advised to begin a program of exercise and to change his diet. After one year, a reduction in the level of which of the following analytes in the serum would the best indicator of the success of his diet and exercise regimen?`,
        q2: ``,
        q3: [],
        option: [`HDL cholesterol `, ` LDL cholesterol`,`Glucose `,`Free fatty acids`,` Triglycerides`],
        optionFeedback: [`HDL cholesterol protects against atherosclerosis by favoring the removal of cholesterol from tissues such as blood vessels. Low levels of HDL is associated with increased atherosclerosis.`,` LDL cholesterol contributes directly to the development of atherosclerotic lesions by inducing proinflammatory changes in endothelium and delivering cholesterol to vessel walls. `,`Glucose levels may indirectly correlate with the risk of atherosclerosis-related morbidity because diabetes is a risk factor; however, it is the changes in lipid levels in diabetics that are thought to contribute to atherosclerotic risk.`,`Free fatty acids do not directly influence the risk of atherosclerosis.`,`Triglycerides are not thought to directly influence the risk of atherosclerosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-LDL cholesterol contributes directly to the development of atherosclerotic lesions by inducing proinflammatory changes in endothelium and delivering cholesterol to vessel walls.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `In an autopsy study of apparently healthy young men between the ages of 20 and 25 years who died in motor vehicle accidents, elevated yellow streaks are found in the abdominal aorta. They are examined microscopically and biochemically to determine their cellular and chemical composition. Some lesions show increased attachment of monocytes to endothelium. In others, foam-filled macrophages are found under the endothelium. Which of the following substances is most likely to be responsible for the transformation of macrophages into foam cells?`,
        q2: ``,
        q3: [],
        option: [` C-reactive protein (CRP)`, `Interleukin-2`,`Glycosylated Hb`,`Oxidized LDL`,`Platelet-derived growth factor`],
        optionFeedback: [`C-reactive protein is a marker of systemic inflammation that is released from hepatocytes; its levels may be associated with atherosclerosis because inflammatory cells are present in atheromatous plaques. `,`Interleukin-2 is a growth factor for activated T cells. It is not considered a factor in the development of atherosclerotic plaques.`,`Glycosylated Hb is formed by non-enzymatic glycosylation of hemoglobin and its plasma levels are elevated in diabetics.`,` So-called fatty streaks form in precisely the same locations in which atherosclerotic lesions appear later in life and contain high levels of oxidized LDL. `,`Platelet-derived growth factor (PDGF) may be released at sites of tissue injury and thrombus formation but has no known role in early atherosclerotic lesions; later in the course of atheroma formation, PDGF released from locally adherent platelets and macrophages can cause smooth muscle proliferation and deposition of extracellular matrix.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- So-called fatty streaks form in precisely the same locations in which atherosclerotic lesions appear later in life and contain high levels of oxidized LDL. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 29-year-old man has a one-year history of angina. On examination, his blood pressure is 120/80 mm Hg. His father died of a heart attack at the age of 40 and the patient’s older brother was recently hospitalized for an acute myocardial infarction. Laboratory studies show total serum cholesterol 385 mg/dL and glucose 85 mg/dL.    A mutation in a gene encoding which of the following is most likely present in this man’s family?`,
        q2: ``,
        q3: [],
        option: [`Angiotensin`, `LDL receptor`,`Endothelin`,`Factor VIII`,` von Willebrand factor`],
        optionFeedback: [`Angiotensin defects would be expected to affect kidney development and blood pressure regulation.`,` The patient has an accelerated form of atherosclerosis due to inheritance of a mutated copy of the LDL receptor, producing familial hypercholesterolemia. Patients who are heterozygous for LDL receptor mutations are typically asymptomatic until adult life when xanthomas of tendon sheath and the effects of coronary artery disease manifest. By contrast, homozygotes are much more severely affected and often die of myocardial infarction before the age of 20. `,`Endothelin is a vasoconstrictor; its defects are not known to be associated with hypercholesterolemia.`,`Factor VIII deficiency leads to hemophilia A, a severe bleeding disorder (Chapter 9).`,`von Willebrand factor deficiency leads to von Willebrand disease, usually marked by a mild bleeding tendency (Chapter 9).`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The patient has an accelerated form of atherosclerosis due to inheritance of a mutated copy of the LDL receptor, producing familial hypercholesterolemia. Patients who are heterozygous for LDL receptor mutations are typically asymptomatic until adult life when xanthomas of tendon sheath and the effects of coronary artery disease manifest. By contrast, homozygotes are much more severely affected and often die of myocardial infarction before the age of 20. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 50-year-old man presents with a 2-year history of exercise-induced angina pectoris that occurs during exercise. On physical examination, his blood pressure is 145/85 mm Hg and his heart rate is 79 bpm and slightly irregular. Coronary angiography shows a fixed 75% narrowing of the anterior descending branch of the left coronary artery. He has smoked two packs of cigarettes for the past 20 years and his serum cholesterol (measured several times) is typically over 230mg/dL.   Which of the following is the earliest event that gives rise to narrowing of the artery?`,
        q2: ``,
        q3: [],
        option: [`Alteration in vasomotor tone`, `Conversion of smooth muscle cells to foam cells`,`Endothelial dysfunction`,`“Danger signals” delivered to macrophages by oxidized HDL`,`Modification of hepatic lipoprotein receptors`],
        optionFeedback: [`Alteration in vasomotor tone may provoke hypertension and endothelial dysfunction, but does not contribute to vascular narrowing per se.`,`Foam cells are derived from macrophages as well as smooth muscle cells but foam cell formation is not an early event.`,` Endothelial dysfunction is believed to be the initiating event in atherosclerosis. It may be caused by biochemical (e.g., oxidized LDL) or mechanical (e.g., hypertension) injury. Oxidized LDL is felt to have a preeminent role. The resulting changes in endothelial gene expression convert the endothelium from an anti-inflammatory, anti-thrombotic interface to one that recruits inflammatory cells and has prothrombotic properties. `,`Oxidized LDL, not HDL, plays a role in atherogenesis.</text>`,`Modification of hepatic lipoprotein receptors is not felt to play a role in the pathogenesis of atherosclerosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Endothelial dysfunction is believed to be the initiating event in atherosclerosis. It may be caused by biochemical (e.g., oxidized LDL) or mechanical (e.g., hypertension) injury. Oxidized LDL is felt to have a preeminent role. The resulting changes in endothelial gene expression convert the endothelium from an anti-inflammatory, anti-thrombotic interface to one that recruits inflammatory cells and has prothrombotic properties`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 63-year-old woman with type II diabetes experiences an episode of chest pain while exercising. She has a 40-pack-year smoking history. On examination, her BMI is 30 and her blood pressure is 135/95 mmHg. Serum LDL cholesterol is 240 mg/dL and HDL is 28 mg/dL.   Angiography reveals proximal coronary arterial narrowing of the right and left anterior descending arteries, with up to 70% stenosis. Which of the following pharmacologic agents ingested in low doses daily is most appropriate for reducing her risk for myocardial infarction?`,
        q2: ``,
        q3: [],
        option: [` Acetaminophen`, `Aspirin`,` Ibuprofen`,`Corticosteroids`,`Insulin`],
        optionFeedback: [`Unlike aspirin, acetaminophen has no effect on platelet function and is not indicated as a preventive measure for cardiac death.`,` Aspirin is a potent inhibitor of platelet activation, due to its inhibitory effects on cyclooxygenase I (COX1), the enzyme that synthesizes the prostaglandin thromboxane A2. Platelet function is central to the formation of thrombi in conditions of high shear, as in arteries, and the ability of aspirin to inhibit thrombosis lowers the risk of an obstruction due to formation of a thrombus over a complex atherosclerotic plaque. Guidelines regarding aspirin therapy as primary prevention of myocardial infarction are continuing to evolve; however, in a patient with multiple cardiovascular risk factors (i.e., hypertension, hyperlipidemia, smoking history), the benefit outweighs the risk of bleeding. `,`Ibuprofen, like aspirin, is an inhibitor of both COX1 and COX2, but, by contrast, is not an irreversible inhibitor. The ability of aspirin to irreversibly inhibit COX1 makes it an especially potent platelet antagonist with favorable COX1 versus COX2 activities at low doses. This is important because COX2 produces lipoxins that are anti-inflammatory and may help protect against atherosclerotic vessel disease.`,`Corticosteroids do not inhibit platelets and have complex effects on the risk of atherosclerosis, in part because they tend to worsen glucose control in individuals with type II diabetes.`,`Insulin may improve glucose control but otherwise will not do much to lower risk in this context.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Aspirin is a potent inhibitor of platelet activation, due to its inhibitory effects on cyclooxygenase I (COX1), the enzyme that synthesizes the prostaglandin thromboxane A2. Platelet function is central to the formation of thrombi in conditions of high shear, as in arteries, and the ability of aspirin to inhibit thrombosis lowers the risk of an obstruction due to formation of a thrombus over a complex atherosclerotic plaque. Guidelines regarding aspirin therapy as primary prevention of myocardial infarction are continuing to evolve; however, in a patient with multiple cardiovascular risk factors (i.e., hypertension, hyperlipidemia, smoking history), the benefit outweighs the risk of bleeding.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An 84-year-old man with a significant smoking history survived a small myocardial infarction 2 years ago. He now reports chest and leg pain during exercise. On physical examination his peripheral pulses are poor in the lower extremities. On physical exam, his blood pressure is 134/92 mm Hg and there is a 7-cm pulsating mass in the midline of the lower abdomen. Serum LDL cholesterol is 252 mg/dL and HDL is 22 mg/dL.  Which of the following vascular lesions is most likely to be present in this patient?`,
        q2: ``,
        q3: [],
        option: [`Aortic dissection`, `Arteriovenous fistula`,`Aortic aneurysm`,`Takayasu arteritis`,`Thromboangiitis obliterans`],
        optionFeedback: [`Aortic dissection typically presents dramatically with severe, “tearing” pain, uneven pulses, and often hypovolemic shock. It is less commonly seen in areas of extensive atherosclerosis since medial fibrosis inhibits dissection propagation.`,`Arteriovenous (AV) fistula often presents with high output cardiac failure and peripheral edema due to “overload” of the venous side of the circulation. AV fistulas may be congenital, surgical (e.g., for dialysis patients) or arise following trauma.`,` In view of the patient’s previous myocardial infarction and hyperlipidemia, it is likely that he has significant atherosclerosis. This patient has three known risk factors for aortic aneurysms: hypertension, atherosclerosis, and smoking. The finding of a pulsatile abdominal mass supports the diagnosis. His leg pain is likely due to obstruction to blood flow and decreased perfusion of the legs secondary to extensive atherosclerosis and the overlying mural thrombus. `,`Takayasu arteritis (pulseless disease) is a granulomatous vasculitis that involves the aorta and its branches, most often in young women. It is not related to smoking. It may present with aneurysmal dilation or severe narrowing of involved vessels, often with evidence of vascular insufficiency in downstream organs.</text>`,`Thromboangiitis obliterans is a severe form of vasculitis that results in obstruction of small arteries in the extremities, sometimes leading to gangrene and amputation. It is strongly associated with smoking but not with aortic aneurysm. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-In view of the patient’s previous myocardial infarction and hyperlipidemia, it is likely that he has significant atherosclerosis. This patient has three known risk factors for aortic aneurysms: hypertension, atherosclerosis, and smoking. The finding of a pulsatile abdominal mass supports the diagnosis. His leg pain is likely due to obstruction to blood flow and decreased perfusion of the legs secondary to extensive atherosclerosis and the overlying mural thrombus.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 23-year-old man experiences sudden onset of severe, sharp chest pain. On physical examination, his temperature is 36.9° C, and his lungs are clear on auscultation. A chest radiograph shows a widened mediastinum. Transesophageal echocardiography shows a dilated aortic root and arch, with a tear in the aortic intima 2 cm distal to the great vessels. A mutation affecting which of the following proteins is the most likely cause of his symptoms?`,
        q2: ``,
        q3: [],
        option: [`Fibrillin`, `PCSK9`,`Phenylalanine hydroxylase (PA`,` Sphingomyelinase`,`Type III collagen`],
        optionFeedback: [` Mutations in the FBN1 gene, which encodes fibrillin-1, cause Marfan syndrome, an autosomal dominant disorder manifested principally in the skeletal system, eyes, and cardiovascular system. Fragmentation of the elastic fibers in the tunica media of the aorta can result in aneurysmal dilation and aortic dissection.  `,`PCSK9 is an enzyme that causes intracellular degradation of LDL receptors in hepatocytes before they reach the cell surface. With fewer LDL receptors on the cell surface, there is reduced uptake of plasma LDL. Families with activating mutations in the gene that encodes this enzyme have features similar to patients with familial hypercholesterolemia.`,`Mutations that cause a severe lack of phenylalanine hydroxylase results in phenylketonuria due to the inability to convert phenylalanine to tyrosine. This disease manifests in childhood and primarily causes neurological symptoms.`,`A primary deficiency of acid sphingomyelinase causes Niemann-Pick disease types A and B.    Type A is characterized by severe neurologic deterioration and massive organomegaly while type B lacks neurologic symptoms.`,`Defects in type III collagen due to mutations in the COL3A1 gene are seen in Ehlers-Danlos syndrome. Like Marfan syndrome, Ehlers-Danlos demonstrates structural failure of organs and tissues; however, aortic aneurysms and dissections are not common in this disease.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-utations in the FBN1 gene, which encodes fibrillin-1, cause Marfan syndrome, an autosomal dominant disorder manifested principally in the skeletal system, eyes, and cardiovascular system. Fragmentation of the elastic fibers in the tunica media of the aorta can result in aneurysmal dilation and aortic dissection `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 75-year-old man has experienced headaches for the past 2 months. On physical examination, his vital signs are temperature, 37° C; pulse, 68 bpm; respirations, 15 breaths/min; and blood pressure, 130/85 mm Hg. His right temporal artery is prominent, palpable, and painful to the touch. His heart rate is regular, and there are no murmurs. A temporal artery biopsy is performed, and the segment of temporal artery excised is grossly thickened and shows focal microscopic granulomatous inflammation. He responds well to corticosteroid therapy. Which of the following complications of this disease is most likely to occur in untreated patients?`,
        q2: ``,
        q3: [],
        option: [`Blindness`, `Gangrene of the toes`,`Acute coronary syndrome`,`Esophageal varices`,`Esophageal varices`],
        optionFeedback: [` Granulomatous inflammation of the temporal artery is diagnostic of temporal arteritis (also called giant cell arteritis). It principally affects large arteries of the head. Blindness occurs due to involvement of the ophthalmic artery, which serves the retina. `,`Gangrene of the toes is a feature of vascular diseases that affect the vessels of the legs, such as diabetic microvascular disease and thromboangiitis obliterans. `,`Acute coronary syndrome is caused by coronary artery obstruction superimposed on atherosclerotic disease.`,`Esophageal varices are associated with liver cirrhosis and, less frequently, portal vein obstruction or hepatic vein thrombosis. Esophageal varices are prone to ruptures that can lead to massive hemorrhage.`,`Renal failure is not a complication of temporal arteritis because this disease does not affect renal vessels and does not cause systemic problems such as hypertension that could damage the kidneys. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Granulomatous inflammation of the temporal artery is diagnostic of temporal arteritis (also called giant cell arteritis). It principally affects large arteries of the head. Blindness occurs due to involvement of the ophthalmic artery, which serves the retina.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 32-year-old woman has had coldness and numbness in her arms and decreased vision in the right eye for the past 5 months. On physical examination, she is afebrile. Her blood pressure is 100/70 mm Hg. Radial pulses are not palpable, but femoral pulses are strong. She has decreased sensation and cyanosis in her arms, but no warmth or swelling. Laboratory studies show serum glucose, 74 mg/dL; creatinine, 1 mg/dL; total serum cholesterol, 165 mg/dL; and negative ANA test result. Her condition remains stable for the next year. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [` Aortic dissection`, ` Kawasaki disease`,` Microscopic polyangiitis`,`Syphilis`,` Takayasu arteritis`],
        optionFeedback: [`Aortic dissection usually presents dramatically with severe, tearing chest or abdominal pain.`,`Kawasaki disease also affects large- to medium-sized arteries, but it is usually associated with fever and rash and is largely a disease of children.`,`Microscopic polyangiitis is a systemic vasculitis that usually presents with constitutional symptoms. It may cause end-organ damage but does not involve large vessels and is not associated with stenosis and aneurysm formation.`,`Tertiary syphilis, if untreated, is a very rare cause of aortic aneurysm, typically many years after the initial infection.`,` Takayasu arteritis (pulseless disease) is a granulomatous vasculitis that affects the aorta and its branches. This involvement produces reduced upper extremity blood pressure and pulse strength, neurologic deficits, and blindness. It is most frequent in young women. `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Takayasu arteritis (pulseless disease) is a granulomatous vasculitis that affects the aorta and its branches. This involvement produces reduced upper extremity blood pressure and pulse strength, neurologic deficits, and blindness. It is most frequent in young women. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 43-year-old man with a recent history of intravenous drug use has experienced malaise, fever, and a 4-kg weight loss over the past month. On physical examination, his blood pressure is 145/90 mm Hg, and he has mild diffuse abdominal pain but no masses or hepatosplenomegaly. Laboratory studies include a blood urea nitrogen concentration of 58 mg/dL (7–18 mg/dL) and a serum creatinine level of 6.7 mg/dL (0.6–1.2 mg/dL). Renal angiography shows right renal artery thrombosis, and the left renal artery and branches show segmental luminal narrowing with focal aneurysmal dilation. During hemodialysis 1 week later, he experiences abdominal pain and diarrhea and is found to have melena. Which of the following serologic laboratory test findings is most likely to be found in this patient?`,
        q2: ``,
        q3: [],
        option: [`Anti-ds DNA`, ` PR3-ANCA (c-ANCA)`,` HIV RNA`,`HBsAg`,` Anti-Scl-70`],
        optionFeedback: [`Anti-ds DNA might indicate the presence of systemic lupus erythematosus, which produces various forms of glomerulonephritis, and can give rise to small vessel vasculitis; however, the mesenteric vessels would not be affected.`,`PR3-ANCA (c-ANCA) is associated with granulomatosis with polyangiitis, which is characterized necrotizing granulomas of upper respiratory tract, necrotizing glomerulonephritis and small vessel vasculitis`,`This patient is at risk for HIV, but HIV infection per se is not associated with vasculitis. `,` The history of intravenous drug use puts this man at increased risk for hepatitis B. Individuals with chronic active hepatitis B associated with circulating hepatitis B surface antigen (HBsAg) may develop polyarteritis nodosa due to the formation of HBsAg-antibody complexes that deposit in the walls of medium-sized arteries, leading to necrotizing inflammation, thrombosis, and aneurysmal dilation. The renal failure indicates involvement of renal arteries, which can be confirmed by angiography. The abdominal pain, diarrhea, and melena are caused by involvement of the mesenteric arteries with consequent ischemia. `,`Anti-Scl-70 autoantibodies are associated with systemic sclerosis, which does not fit the clinical scenario. Systemic sclerosis causes sclerosis (collagen production) of the skin and fibrosis in other organs such as the esophagus. It typically does not involve renal arteries. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The history of intravenous drug use puts this man at increased risk for hepatitis B. Individuals with chronic active hepatitis B associated with circulating hepatitis B surface antigen (HBsAg) may develop polyarteritis nodosa due to the formation of HBsAg-antibody complexes that deposit in the walls of medium-sized arteries, leading to necrotizing inflammation, thrombosis, and aneurysmal dilation. The renal failure indicates involvement of renal arteries, which can be confirmed by angiography. The abdominal pain, diarrhea, and melena are caused by involvement of the mesenteric arteries with consequent ischemia. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 3-year-old child from Osaka, Japan, has developed a fever and a rash and swelling of her hands and feet over the past 2 days. On physical examination, her temperature is 37.8° C.    There is a desquamative skin rash, oral erythema, erythema of the palms and soles, edema of the hands and feet, and cervical lymphadenopathy. The child improves after a course of intravenous immunoglobulin therapy. Which of the following is most likely to be a complication of this child’s disease if it is untreated?`,
        q2: ``,
        q3: [],
        option: [`Asthma`, `Glomerulonephritis`,`Intracranial hemorrhage`,`Myocardial infarction`,`Pulmonary hypertension`],
        optionFeedback: [`The clinical picture is most consistent with Kawasaki disease, which is not complicated by asthma.`,`The clinical picture is most consistent with Kawasaki disease, which is not complicated by glomerulonephritis.`,`The clinical picture is most consistent with Kawasaki disease, which is not complicated by intracranial hemorrhage.`,` The clinical picture is typical of Kawasaki disease, a systemic inflammatory disease of children that is associated with vasculitis, particularly of coronary vessels, putting affected children at risk for myocardial infarction. Other common features include rash, lymphadenopathy, and arthralgias. `,`The clinical picture is most consistent with Kawasaki disease, which is not complicated by pulmonary hypertension.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The clinical picture is typical of Kawasaki disease, a systemic inflammatory disease of children that is associated with vasculitis, particularly of coronary vessels, putting affected children at risk for myocardial infarction. Other common features include rash, lymphadenopathy, and arthralgias.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 50-year-old man has had a chronic cough for the past 18 months. Physical examination shows nasopharyngeal ulcers, and the lungs have diffuse crackles bilaterally on auscultation. Laboratory studies include a blood urea nitrogen level of 75 mg/dL (7–18 mg/dL) and a creatinine concentration of 6.5 mg/dL (0.6–1.2 mg/dL). Urinalysis shows 50 RBCs per high-power field and RBC casts. A chest radiograph shows multiple small, bilateral pulmonary nodules. A transbronchial lung biopsy specimen shows necrotizing inflammation involving the small arteries and arterioles. Which of the following antibodies is most likely to be present in this patient’s serum?`,
        q2: ``,
        q3: [],
        option: [` PR3-ANCA (c-ANCA)`, ` Lupus anticoagulant`,`Anti-ds-DNA`,`Anti-hepatitis C`,`IgM anti-IgG`],
        optionFeedback: [` Necrotizing vasculitis associated with oropharyngeal, pulmonary, and renal disease is consistent with granulomatosis with polyangiitis, which tends to be associated with autoantibodies that recognize the proteins found in the cytoplasmic granules of neutrophils, most commonly proteinase-3 and myeloperoxidase. `,`Lupus anticoagulant is an antibody that binds molecules with negative charges, including phospholipids. These antibodies interfere with coagulation in laboratory tests (particularly, the PTT test), but are associated with clotting in vivo. Lupus anticoagulant may be primary or be present in a subset of patients with SLE but these patients do not have necrotizing granulomas of the respiratory tract.`,`Anti-ds DNA antibodies are commonly seen in patients with lupus, which most commonly is associated with renal, joint, and skin manifestations.`,`Anti-hepatitis C antibodies may be associated with cryoglobulinemia, which usually presents with skin lesions (purpura), arthralgias, and (sometimes) renal disease.`,`IgM and anti-IgG antibodies (rheumatoid factor) are seen in rheumatoid arthritis; they are not associated with vasculitis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Necrotizing vasculitis associated with oropharyngeal, pulmonary, and renal disease is consistent with granulomatosis with polyangiitis, which tends to be associated with autoantibodies that recognize the proteins found in the cytoplasmic granules of neutrophils, most commonly proteinase-3 and myeloperoxidase. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 35-year-old woman with a history of injection drug use has developed a high fever over the past day. On examination, her temperature is 37.6° C.  A heart murmur is auscultated. Blood culture is obtained and grows Staphylococcus aureus. She develops a severe headache. A head computed tomography scan shows an intracranial hemorrhage and multiple small peripheral swellings in cerebral arteries. Which of the following vascular complications has most likely occurred in her brain?`,
        q2: ``,
        q3: [],
        option: [` Granulomatous vasculitis`, `Hyperplastic arteriolosclerosis`,`Atherosclerosis`,`Mycotic aneurysm`,`Immune complex small vessel vasculitis`],
        optionFeedback: [`Granulomatous vasculitis is not associated with S. aureus sepsis, but can be seen in the context of giant cell arteritis.`,`Hyperplastic arteriolosclerosis is associated with hypertension, which is not the case in this patient.`,`Atherosclerosis is more likely to be associated with thrombosis and nonhemorrhagic stroke, and also is unlikely as a cause of a cerebrovascular accident in a 35-year-old woman.`,` The clinicopathologic features are consistent with S. aureus infective endocarditis and seeding of cerebral vessels, with rupture secondary to mycotic aneurysm formation. `,`Immune complex small vessel vasculitis is more likely to present with purpura and renal disease than as hemorrhagic stroke.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The clinicopathologic features are consistent with S. aureus infective endocarditis and seeding of cerebral vessels, with rupture secondary to mycotic aneurysm formation.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 69-year-old woman has been bedridden while recuperating from a bout of viral pneumonia complicated by bacterial pneumonia for the past 2 weeks. Physical examination shows some swelling and tenderness of the right leg, which worsens when she raises or moves the leg. Which of the following terms best describes the condition involving her right leg?`,
        q2: ``,
        q3: [],
        option: [` Disseminated intravascular coagulation`, `Lymphedema`,`Thromboangiitis obliterans`,` Deep vein thrombosis`,`Varicose veins`],
        optionFeedback: [`Disseminated intravascular coagulation usually occurs secondary to a severe systemic inflammatory disorder and, if acute, may present with a combination of thrombi in small vessels and bleeding due to consumption of coagulation factors.`,`Lymphedema usually occurs due to some local event (e.g., surgery, trauma) that compromises lymphatic drainage.`,`Thromboangiitis obliterans typically presents with pain and sometimes gangrene in the distal extremity of a smoker.`,` Deep vein thrombosis (DVT) is the most likely diagnosis in a bedridden patient, particularly in those past the age of 50 years. `,`Varicose veins are superficial and are readily recognized; they may cause pain, but not swelling.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Deep vein thrombosis (DVT) is the most likely diagnosis in a bedridden patient, particularly in those past the age of 50 years. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 10-year-old boy has a 2-cm spongy, dull red, circumscribed lesion on the upper outer left arm. The parents state that this lesion has been present since infancy, and the appearance has not changed appreciably. The lesion is excised, and its microscopic appearance is shown in the figure. Which of the following is the most likely diagnosis?`,
        q2: `<img src="../images/f007-q021-9780323640251.png"/>`,
        q3: [],
        option: [`Angiosarcoma`, ` Hemangioma`,`Kaposi sarcoma`,` Lymphangioma`,`Vasculitis`],
        optionFeedback: [`Angiosarcoma is a vascular lesion of older adults in which vascular spaces are lined with malignant-appearing endothelial cells.`,` The lesion consists of dilated vessels lined by normal-appearing endothelium, consistent with a benign hemangioma. `,`Kaposi sarcoma is a proliferative vascular lesion in severely immunodeficient patients (e.g., individuals with late-stage untreated HIV infection [AIDS]) or elderly individuals, typically beyond the age of 70 years.`,`Lymphangioma in children usually occurs in the head and neck region (cystic hygroma) and is more common in girls with Turner syndrome (45,X karyotype).`,`Vasculitis usually causes an acute or subacute systemic illness. In vasculitis, vessel walls show inflammation.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-  The lesion consists of dilated vessels lined by normal-appearing endothelium, consistent with a benign hemangioma. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 35-year-old man is known to have been HIV-positive for the past 10 years, but has refused treatment with antiviral drugs. Physical examination shows multiple reddish purple, nodular skin lesions comprised of spindle-shaped cells with slit-like spaces containing red cells. These lesions have been slowly increasing for the past year. Which of the following infectious agents is most likely to play a role in the pathogenesis of these skin lesions?`,
        q2: ``,
        q3: [],
        option: [` Human herpes virus 8`, ` Epstein-Barr virus`,` Hepatitis C virus`,`Mycobacterium avium complex `,`Herpes simplex virus 2`],
        optionFeedback: [` The findings are consistent with Kaposi sarcoma, an immunodeficiency-related endothelial proliferation in which the tumor cells are infected with human herpes virus 8 (also known as Kaposi sarcoma herpesvirus, KSHV). In advanced lesions (nodular stage), proliferating spindle cells are dominant.`,`Epstein-Barr virus in the context of HIV infection is most likely to be associated with a B cell lymphoma.`,`Hepatitis C virus is non-transforming and among neoplasms is associated only with hepatocellular carcinoma.`,`Mycobacterium avium complex infection tends to mainly produce disease in the lung and does not induce vascular proliferations.`,`Herpes simplex virus 2 infection is associated with genital herpes, but on occasion can produce disseminated disease in patients with AIDS.    It does not cause vascular lesions, however.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The findings are consistent with Kaposi sarcoma, an immunodeficiency-related endothelial proliferation in which the tumor cells are infected with human herpes virus 8 (also known as Kaposi sarcoma herpesvirus, KSHV). In advanced lesions (nodular stage), proliferating spindle cells are dominant`,
        state: `notAnswered`,
        userAnswered: [],
    }
    

   ];






