var quiz = [
    {
        q: `A 17-year-old man infected with hepatitis A experiences mild nausea for about a week and is slightly jaundiced. Laboratory findings include elevations in the levels of the intra-hepatic enzymes aspartate transaminase (AST) and alanine transaminase (ALT). The increase in enzyme levels in the serum results from which of the following cellular alterations in the hepatocytes?`,
        q2: ``,
        q3: [],
        option: [`Dispersion of ribosomes`, `Formation of blebs in the cell membrane`, `Swelling of the mitochondria`,`Formation of clear vacuoles in the cytoplasm`,`Defects in the cell membrane`],
        optionFeedback: [`Dispersion of ribosomes happens in reversibly injured cells and can result in reduced protein synthesis but would not lead to protein leakage. `,`Formation of blebs can occur in reversible cell injury and in the process of apoptosis but neither leads to protein leakage.`,`Swelling of the mitochondria is also seen in many forms of cell injury but would lead to reduced ATP generation, not protein leakage. `,`Vacuoles in the cytoplasm usually contain water that has entered the cell along with sodium because of reduced ATP production and consequent failure of the ATP-dependent Na<sup>+-</sup>K<sup>+</sup> pump. This occurs in reversible cell injury without disruption of plasma membrane. Accumulation of glycogen or lipids in the cell can also produce vacuoles. None of these would lead to protein leakage. `,` Disruption of the plasma membrane occurs mainly in necrotic cell injury and at late stages of other types of cell injury, and results in leakage of `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-Disruption of the plasma membrane occurs mainly in necrotic cell injury and at late stages of other types of cell injury, and results in leakage of cytosolic enzymes.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 40-year-old man was diagnosed with a carcinoma of the lung. Despite treatment with chemotherapy, he died with widespread metastases. At autopsy, tumors were found in many organs. Histologic examination revealed many foci in which individual tumor cells appeared shrunken and deeply eosinophilic. Their nuclei showed condensed aggregates of chromatin under the nuclear membrane. The process affecting these shrunken tumor cells was triggered by the release of which of the following proteins into the cytosol?`,
        q2: ``,
        q3: [],
        option: [`Lipofuscin`, `Cytochrome c`,`Catalase`,`Phospholipase`,`Bcl2`],
        optionFeedback: [`A. Lipofuscin is a breakdown product of lipids that accumulates in cells undergoing injury or during aging. `,`C. Catalase is an enzyme that controls the activity of reactive oxygen species. `,`D. Activation of phospholipases contributes to plasma membrane damage, which is a hallmark of irreversible cell injury. This typically occurs in cell death by necrosis.`,`E. Bcl2 is a protein that blocks the insertion of pro-apoptotic proteins BAX and BAK into the mitochondrial membrane and thus prevents mitochondrial leakage. In this way,Bcl2 inhibits apoptosis; it is the prototype of the anti-apoptotic proteins. `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale:-The morphologic appearance is characteristic of apoptosis, in which the mitochondrial protein cytochrome c leaks into the cytosol and activates caspases, the enzymes that cause nuclear and plasma membrane alterations culminating in apoptopic death.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 54-year-old man experienced the onset of severe chest pain. An electrocardiogram demonstrated changes consistent with an acute myocardial infarction. Cardiac angiography showed a thrombus (clot) in the left anterior descending coronary artery. He was given tissue plasminogen activator (tPA) to break up the thrombus. However, his serum level of the cardiac protein troponin I increased after his therapy. Which of the following events most likely occurred?`,
        q2: ``,
        q3: [],
        option: [`Necrosis due to reperfusion injury`, `Hyperplasia of myocardial cells`,`Apoptosis of myocardial cells`,`Increased synthesis of troponins`,`Atrophy of myocardial cells`],
    optionFeedback: [`Increased serum troponin I indicates additional myocardial necrosis despite clot dissolution. This is an example of ischemia-reperfusion injury, in which restoration of blood flow to a region that has undergone ischemic damage paradoxically increases the damage. The damage likely has several sources, both intrinsic and extrinsic to the myocardial cells. Intrinsic factors include increased production of reactive oxygen species, “hypercontraction” due to loading of the cells with calcium during the period of ischemia, and mitochondrial damage. Extrinsic factors include the influx of leukocytes and complement, which may augment the damage, upon revascularization, and these increase damage.`,` Hyperplasia refers to increased cell numbers, but myocardial cells are incapable of any significant proliferation. Also, reperfusion would not cause acute hyperplasia (or hypertrophy) of myocardial cells`,`Apoptosis does not increase plasma membrane permeability (except in late stages, when some secondary necrosis may supervene).`,`It is possible that the reperfused myocardial cells increase protein synthesis when they are provided more oxygen and nutrients, but the protein would not leak from healthy cells into the blood.`,` Reperfusion would counteract atrophy by providing more nutrients. Also, atrophy does not cause plasma membrane injury and consequent leakage of intracytoplasmic proteins such as troponin`],
        
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Increased serum troponin I indicates additional myocardial necrosis despite clot dissolution. This is an example of ischemia-reperfusion injury, in which restoration of blood flow to a region that has undergone ischemic damage paradoxically increases the damage. The damage likely has several sources, both intrinsic and extrinsic to the myocardial cells. Intrinsic factors include increased production of reactive oxygen species, “hypercontraction” due to loading of the cells with calcium during the period of ischemia, and mitochondrial damage. Extrinsic factors include the influx of leukocytes and complement, which may augment the damage, upon revascularization, and these increase damage.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `The aortic valve seen in the figure was discovered at autopsy in a 72-year-old man. The heart weighed 580 g and exhibited marked left ventricular hypertrophy and minimal coronary arterial atherosclerosis. A serum chemistry panel (Na, K, Cl, phosphate, calcium) revealed no abnormalities prior to death from heart failure. Which of the following pathologic processes accounts for the appearance of the valve?`,
        q2: `<img src="../images/f001-q004-9780323640251.png" />`,
        q3: [],
        option: [`Metastatic calcification`, `Dystrophic calcification`,`Lipofuscin deposition`,`Hemosiderin deposition`,`Intracellular fat deposition`],
    optionFeedback: [`<!--A.-->Metastatic calcification is the result of increased blood calcium levels, as in some renal and parathyroid diseases, but this patient’s serum calcium was normal. Also, metastatic calcification may occur in healthy tissues, such as gastric mucosa, kidneys, and lungs, not necessarily at sites of chronic injury. `,`<!--B.--><!--Answers:--> Deposits of calcium salts are hard and chalky white. They form at sites of chronic tissue damage, which happens in the aortic valve because of the “wear and tear” associated with normal opening and closing of the valve, and are exacerbated by hypertension because of the increased work`,`<!--C.-->Lipofuscin is a brown pigment derived from lipids that is deposited inside degenerating or aging cells. `,`<!--D.-->Hemosiderin is an iron-containing pigment derived from red cell breakdown, and is usually found inside macrophages, which ingest senescent red cells to sequester potentially dangerous iron ions (which can catalyze the creation of oxidants) and to recycle iron for new red cell synthesis. `,`<!--E.-->Fat is deposited inside cells such as hepatocytes (fatty change or steatosis) in obese individuals and in situations that interfere with lipid metabolism. `],
        
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Deposits of calcium salts are hard and chalky white. They form at sites of chronic tissue damage, which happens in the aortic valve because of the “wear and tear” associated with normal opening and closing of the valve, and are exacerbated by hypertension because of the increased workload of the heart.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 50-year-old man has been smoking two packs of cigarettes per day for the past 20 years. A suspicious nodule appeared in the lung on x-ray, so a bronchoscopy was done to rule out cancer. A biopsy of the nodule was performed. A second biopsy was taken from the bronchial wall away from the nodule, shown here. This appearance shows which of the following changes?`,
        q2: `<img src="../images/f001-q005-9780323640251.png"/>`,
        q3: [],
        option: [`Squamous metaplasia`, `Columnar metaplasia`,`Apoptosis of epithelium`,`Squamous cell hyperplasia`,`Hypertrophy of the epithelium`],
    optionFeedback: [`The normal ciliated columnar epithelium on the left is replaced by stratified squamous epithelium, an example of squamous metaplasia. The chronic irritation caused by smoking causes this change, in which the delicate columnar epithelium is replaced by the more rugged (but less functional) squamous epithelium due to reprogamming of progenitor cells`,`Columnar metaplasia refers to replacement of (usually) squamous epithelium by columnar epithelium, the reverse of this case. It is seen at the esophagogastric junction in Barrett esophagus, and is often the site of dysplastic change and ultimately development of adenocarcinoma.`,`Apoptosis is a form of cell death of epithelial cells, not a change in their phenotype.`,`Squamous cell hyperplasia is an increase in the number (and usually thickness) of squamous epithelial cells. It is seen in areas of the skin that are subjected to mechanical stress (as calluses), in virus-induced warts, and chronic inflammatory skin disorders such as psoriasis.`,`Hypertrophy is increase in the size of cells, usually leading to an increase in the thickness of the tissue (epithelium in this case).`],
        
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The normal ciliated columnar epithelium on the left is replaced by stratified squamous epithelium, an example of squamous metaplasia. The chronic irritation caused by smoking causes this change, in which the delicate columnar epithelium is replaced by the more rugged (but less functional) squamous epithelium due to reprogamming of progenitor cells.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 23-year-old woman has a normal menstrual cycle. Which of the following processes is most likely happening in the endometrium just before the onset of bleeding?`,
        q2: ``,
        q3: [],
        option: [`Apoptosis`, `Caseous necrosis`,`Reperfusion injury`,`Atrophy`,` Liquefactive necrosis`],
    optionFeedback: [`<!--A.--><!--Answers:--> The hormonal alterations during the menstrual cycle result in phases when the endometrium is deprived of growth factors (estrogens). This leads to apoptosis by the intrinsic (mitochondrial) pathway. This is an example of physiologic apoptosis. It culminates in clearance of dead cells without eliciting inflammation, which could be harmful.`,`<!--B.-->Caseous necrosis is the form of necrosis in which dead tissue is replaced with cheese-like material containing cell debris. It is typical of tuberculosis lesions. `,`<!--C.-->Reperfusion injury happens when blood flow is restored to tissues damaged by ischemia. The injury is mostly necrosis, but could include apoptosis of some cells. `,`<!--D.-->Atrophy is reduced size of cells, and hence tissues, as a result of nutrient deprivation or decrease in normal growth factors and stimulation (as in atrophy of denervated muscle). `,`<!--E.-->Liquefactive necrosis is a form of necrosis in which the dead tissue breaks down (liquifies) because of the action of enzymes. All forms of necrosis are associated with release of cellular components that elicit inflammation (unlike apoptosis) as well as enzymes that contribute to tissue breakdown. `],
        
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The hormonal alterations during the menstrual cycle result in phases when the endometrium is deprived of growth factors (estrogens). This leads to apoptosis by the intrinsic (mitochondrial) pathway. This is an example of physiologic apoptosis. It culminates in clearance of dead cells without eliciting inflammation, which could be harmful.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 65-year-old diabetic man who is a chain smoker experiences pain on the left side of his chest that radiates to the left shoulder while mowing his lawn. The next day he again feels the pain, but this time it is more severe, and he is also short of breath. He is taken to the emergency department where his blood pressure is found to be very low and his electrocardiogram is abnormal. He dies 48 hours after admission due to cardiac failure. At autopsy, there is complete occlusion of the left main coronary artery. Microscopically, his myocardium is most likely to show which of the following changes:`,
        q2: ``,
        q3: [],
        option: [`Caseous necrosis`, `Coagulative necrosis`,`Fatty change`,`Scar formation`,` Swelling of the myocardial cells`],
    optionFeedback: [`<!--A.-->Caseous necrosis is an unusual pattern of necrosis, most often seen in tuberculosis, in which the dead tissue is converted to “cheese-like” amorphous material. `,`<!--B.--><!--Answer:--> The coronary thrombosis (secondary to atherosclerosis) resulted in ischemia of the myocardium, leading to necrosis. Because of the rapid pace of the process and loss of enzyme activity,  the cells are dead but not digested, so tissue outlines are preserved, at least for a few days until enzymes from the dead cells and from recruited leukocytes begin to break down the tissue. This type of necrosis is called coagulative (resembling a congealed material). It is typical of ischemic infarcts in most organs (except the brain)`,`<!--C.-->Fatty change is deposition of lipids in cells (most often hepatocytes) without cell death. `,`<!--D.-->Scars are areas with collagen deposition that occurs during the repair of damaged tissues. Since the injury was acute, there has not been time for scar tissue to develop.`,`<!--E.-->Cells may swell because of the influx of water and ions when the plasma membrane is damaged and ion pumps become nonfunctional in the early stages of cell injury. This change by itself is reversible. `],
        
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The coronary thrombosis (secondary to atherosclerosis) resulted in ischemia of the myocardium, leading to necrosis. Because of the rapid pace of the process and loss of enzyme activity,  the cells are dead but not digested, so tissue outlines are preserved, at least for a few days until enzymes from the dead cells and from recruited leukocytes begin to break down the tissue. This type of necrosis is called coagulative (resembling a congealed material). It is typical of ischemic infarcts in most organs (except the brain).`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 53-year-old woman with no prior illnesses has a routine checkup by her physician. On examination she has a blood pressure of 150/95 mm Hg. If her hypertension remains untreated for years, which of the following cellular alterations would most likely be seen in her myocardium?`,
        q2: ``,
        q3: [],
        option: [` Apoptosis`, `Fatty change`,`Hyperplasia`,`Hypertrophy`,` Metaplasia`],
    optionFeedback: [`<!--A.-->Apoptosis may occur in late stages if the hypertrophied myocardium cannot cope with the stress, but this is not the initial response to hypertension. `,`<!--B.-->Fatty change represents a form of reversible cell injury. It is the consequence of abnormal lipid metabolism and is seen most often in hepatocytes (where lipids are packaged with specialized proteins for secretion).`,`<!--C.-->Hyperplasia (increase in cell numbers) is a form of adaptation which occurs in response to growth factors and other stimuli in tissues capable of cell proliferation, such as the liver, but not the myocardium. `,`<!--D.--><!--Answers:--> In response to the increased workload for the heart to pump against high arterial pressure, the myocardial cells undergo compensatory hypertrophy (increase in cell size), enabling them to function despite the greater stress. `,`<!--E.-->Metaplasia is a change of one adult cell type to another, often in response to a chronic irritant.`],

        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-In response to the increased workload for the heart to pump against high arterial pressure, the myocardial cells undergo compensatory hypertrophy (increase in cell size), enabling them to function despite the greater stress.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 20-year-old woman breastfeeds her infant. On examination, her breasts are slightly increased in size. Milk can be expressed from both nipples. Which of the following processes that occurred in her breasts during pregnancy enables her to breastfeed the infant?`,
        q2: ``,
        q3: [],
        option: [` Ductal metaplasia`, `Epithelial dysplasia`,`Intracellular lipid deposition`,`Hormone-induced cellular proliferation`,`Stromal hypertrophy`],
        optionStyleType: `st-upper-alpha`,
    optionFeedback: [`<!--A.-->Metaplasia (change in phenotype of ductal lining cells) does not occur during lactation. `,`<!--B.-->Dysplasia is a premalignant change often in response to external stresses (such as in the bronchial epithelium in smokers). `,`<!--C.-->Lipids are synthesized and secreted in milk, not deposited in epithelial cells. `,`<!--D.--><!--Answers:--> Proliferation of mammary gland epithelial cells induced by prolactin and accompanied by increased production of milk proteins is essential for lactation. `,`<!--E.-->Hypertrophy of the breast stroma does occur during pregnancy, contributing to the increased size, but is not the process that allows lactation.`],

        answer: [3],
        ansText: `Rationale:-Proliferation of mammary gland epithelial cells induced by prolactin and accompanied by increased production of milk proteins is essential for lactation.  .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 16-year-old boy sustained blunt trauma to his abdomen when he struck a bridge abutment at high speed while driving a motor vehicle. Peritoneal lavage shows a hemoperitoneum, and at laparotomy, a small portion of the left lobe of the injured liver is removed. Two months later, a computed tomography (CT) scan of the abdomen shows that the liver has nearly regained its size before the injury. Which of the following processes best explains this CT scan finding?`,
        q2: ``,
        q3: [],
        option: [`Apoptosis`, `Dysplasia`,`Regeneration`,`Hydropic change`,` Steatosis`],
    optionFeedback: [`<!--A.-->Apoptosis leads to cell death and shrinkage of an organ, not restoration. `,`<!--B.-->Dysplasia is a premalignant change often in response to noxious stimuli (such as in the bronchial epithelium in smokers) or infection with oncogenic viruses ( such as HPV infection of the cervical mucosa). `,`<!--C.--><!--Answers:--> Proliferation of liver cells in response to loss of tissue (called <i>compensatory hyperplasia</i>) accounts for restoration of liver size. Liver cells have great capacity to divide and regenerate lost liver mass.`,`<!--D.-->Hydropic change is fluid accumulation in the cytoplasm, sometimes an indicator of early cell injury. `,`<!--E.-->Steatosis is lipid deposition, which occurs in the liver in conditions of abnormal lipid metabolism.`],

        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Proliferation of liver cells in response to loss of tissue (called <i>compensatory hyperplasia</i>) accounts for restoration of liver size. Liver cells have great capacity to divide and regenerate lost liver mass.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 29-year-old man sustains a left femoral fracture in a motorcycle accident. His leg is placed in a plaster cast. After his left leg has been immobilized for 6 weeks, the diameter of the left calf has decreased in size. This change in size is most likely to result from which of the following alterations in his calf muscles?`,
        q2: ``,
        q3: [],
        option: [`Aplasia`, `Atrophy`,` Dystrophy`,` Hyalinosis`,` Hypoplasia`,],
    optionFeedback: [`<!--A.-->Aplasia is failure of development of an organ or tissue.`,`<!--B.--><!--Answers:--> Reduced size of the muscle is caused by atrophy (reduced size of cells), in this case because of disuse; atrophy can be reversed with normal growth stimuli.`,`<!--C.-->Dystrophy is degeneration and loss of a tissue usually because of an underlying disease (often genetic), as in muscular dystrophy; dystrophy is usually irreversible unless the underlying disease can be corrected. `,`<!--D.-->Hyalinosis is deposition of extracellular matrix material, called hyaline because of its staining properties. `,`<!--E.-->Hypoplasia is reduced size of an organ, usually because of a developmental defect that leads to reduced number of cells in the organ.`],

        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Reduced size of the muscle is caused by atrophy (reduced size of cells), in this case because of disuse; atrophy can be reversed with normal growth stimuli .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 34-year-old obese woman has experienced heartburn from gastric reflux for the past 5 years after eating large meals. She undergoes upper gastrointestinal endoscopy, and a biopsy specimen of the distal esophagus is obtained. Which of the following microscopic changes, seen in the figure, has most likely occurred?`,
        q2: `<img src="../images/f001-q014-9780323640251.png"/>`,
        q3: [],
        option: [`Columnar metaplasia`, `Goblet cell hyperplasia`,` Lamina propria atrophy`,`Squamous dysplasia`,`Mucosal hypertrophy`],
    optionFeedback: [`<!--A.--><!--Answer:--> The esophageal epithelium has changed from the normal squamous epithelium to columnar epithelium, with mucus-filled goblet cells resembling intestinal epithelium. This example is of columnar metaplasia in Barrett esophagus, caused by prolonged exposure to acid.`,`<!--B.-->Goblet cell hyperplasia refers to an increased number of goblet cells in intestinal or bronchial columnar epithelium, not a change in the nature of the epithelium. It is commonly seen in the airways in asthma.`,`<!--C.-->Atrophy of the laminar propria is not a known lesion. Atrophy of the intestinal villi is typical of celiac disease.`,`<!--D.-->Dysplasia is a premalignant change, not a change of one adult cell type to another. `,`<!--E.-->Mucosal hypertrophy is increased thickness of mucosal epithelium, as in the airway epithelium in bronchial asthma.`],

        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The esophageal epithelium has changed from the normal squamous epithelium to columnar epithelium, with mucus-filled goblet cells resembling intestinal epithelium. This example is of columnar metaplasia in Barrett esophagus, caused by prolonged exposure to acid.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 38-year-old woman has experienced severe abdominal pain over the past two days. On examination she is hypotensive and in shock. Laboratory studies show elevated serum lipase. From the representative gross appearance of the mesentery shown in the figure, which of the following events has most likely occurred?`,
        q2: `<img src="../images/f001-q015-9780323640251.png"/>`,
        q3: [],
        option: [`Acute pancreatitis`, `Gangrenous cholecystitis`,`Hepatitis B virus infection`,`Small intestinal infarction`,`Tuberculous lymphadenitis`],
    optionFeedback: [`<!--A.--><!--Answer:--> Acute abdomen rapidly leading to shock is suspicious of acute pancreatitis, and the elevated serum lipase confirms the diagnosis. This enzyme is normally inside pancreatic epithelial cells, and is released if these cells are injured. Released fatty acids combine with calcium to form insoluble salts that precipitate in situ, resulting in the chalky white patches seen in the mesentery (fat necrosis).`,`<!--B.-->Gangrenous cholecystitis would show necrosis of the gallbladder with acute inflammation. `,`<!--C.-->Hepatitis B virus infection causes hepatic necrosis and not lesions on the mesentery`,`<!--D.-->Infarction of the small bowel may present with an acute abdominal emergency and may cause acute peritonitis but not elevations of pancreatic enzymes or fat necrosis. `,`<!--E.-->Tuberculous lymphadenitis would show enlarged lymph nodes with granulomatous inflammation and caseous necrosis.`],

        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-  Acute abdomen rapidly leading to shock is suspicious of acute pancreatitis, and the elevated serum lipase confirms the diagnosis. This enzyme is normally inside pancreatic epithelial cells, and is released if these cells are injured. Released fatty acids combine with calcium to form insoluble salts that precipitate in situ, resulting in the chalky white patches seen in the mesentery (fat necrosis).`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 68-year-old woman suddenly lost consciousness and, on awakening 1 hour later, could not speak or move her right arm. Two months later, a computed tomography scan of the head showed a large cystic area in the left parietal lobe. Which of the following pathologic processes has most likely occurred in her brain?`,
        q2: ``,
        q3: [],
        option: [` Fatty change`, `Coagulative necrosis`,` Fat necrosis`,` Amyloidosis`,` Liquefactive necrosis`],
    optionFeedback: [`<!--A.-->Fatty change (steatosis) is lipid deposition, which occurs in the liver in conditions of abnormal lipid metabolism and in some other reversibly injured tissues. It does not occur in the brain. `,`<!--B.-->Coagulative necrosis occurs in ischemic infarcts in many solid organs such as the heart and kidneys; grossly such infarcts appear as pale solid areas. `,`<!--C.-->Fat necrosis occurs in the peritoneum because of the release of digestive enzymes in acute pancreatitis. `,`<!--D.-->Amyloidosis is a disorder characterized by the extracellular deposition of aggregated, often improperly folded proteins, such as immunoglobulin light chains.`,`<!--E.--><!--Answer:--> A cystic mass is likely an infarct secondary to a cerebral artery occlusion. In the brain, ischemic infarcts undergo liquefactive necrosis, in which the tissue is largely dissolved (liquified).`],

        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- A cystic mass is likely an infarct secondary to a cerebral artery occlusion. In the brain, ischemic infarcts undergo liquefactive necrosis, in which the tissue is largely dissolved (liquified).`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A chest radiograph of an asymptomatic 37-year-old man shows a 3-cm nodule in the middle lobe of his right lung. The nodule is excised with a pulmonary wedge resection, and sectioning shows a sharply circumscribed mass with a soft, white center. The microscopic appearance is shown in the figure. The serum interferon gamma release assay is positive. Which of the following pathologic processes has most likely occurred in this nodule?`,
        q2: `<img src="../images/f001-q017-9780323640251.png"/>`,
        q3: [],
        option: [` Apoptosis`, `Caseous necrosis`,`Coagulative necrosis`,`Fat necrosis`,`Liquefactive necrosis`],
    optionFeedback: [`<!--A.-->Apoptosis is a form of regulated cell death that is not associated with inflammation. `,`<!--B.--><!--Answer:--> The pathology is characteristic of tuberculosis with granulomatous inflammation, and the interferon gamma release assay (which measures a T cell response to mycobacterial antigens) is confirmatory. The central necrosis in tuberculous granulomas is responsible for the gross appearance of the lesions, called caseous necrosis because of the crumbling, “cheese-like” appearance. Unlike in coagulative necrosis, cell outlines are not preserved.`,`<!--C.-->Coagulative necrosis occurs in ischemic infarcts in many solid organs such as the heart and kidneys; microscopically, the tissue outlines are preserved. `,`<!--D.-->Fat necrosis occurs in the peritoneum because of release of digestive enzymes in acute pancreatitis. `,`<!--E.-->In liquefactive necrosis, the tissue is largely dissolved.`],

        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The pathology is characteristic of tuberculosis with granulomatous inflammation, and the interferon gamma release assay (which measures a T cell response to mycobacterial antigens) is confirmatory. The central necrosis in tuberculous granulomas is responsible for the gross appearance of the lesions, called caseous necrosis because of the crumbling, “cheese-like” appearance. Unlike in coagulative necrosis, cell outlines are not preserved.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An experimental drug administered to a tissue is found to inhibit cellular oxidative phosphorylation when given in high doses, and ATP production drops to 5% of normal. Which of the following substances is most likely to be present at increased concentration in the culture fluid bathing the tissue?`,
        q2: ``,
        q3: [],
        option: [` Calcium`, ` Glucose`,` Hydrogen peroxide`,`Potassium`,`Sodium`],
    optionFeedback: [`<!--A.-->Calcium enters damaged cells, so its extracellular concentration would not increase; the amount that enters is too small to affect the concentration.`,`<!--B.-->When intracellular glucose is not consumed by oxidative metabolism, it enters other metabolic pathways and does not leave the cell; glucose also fails to enter damaged cells because of failure of the glucose transporter. `,`<!--C.-->H<sub>2</sub>O<sub>2</sub> is produced in ischemic cells due to oxidative stress and is rapidly converted to H<sub>2</sub>O by glutathione peroxidase and catalase.`,`<!--D.--><!--Answers:--> One of the earliest consequences of reduced ATP generation is failure of the ATP-dependent plasma membrane Na<sup>+</sup>-K<sup>+</sup> pump. This results in efflux of intracellular K<sup>+</sup> (whose concentration is higher inside than outside cells) and influx of Na<sup>+</sup> and water (to maintain osmotic balance), resulting in cell swelling. Ultimately the cell undergoes necrosis if ATP production is not restored.`,`<!--E.-->Na<sup>+</sup> is at higher concentration in the extracellular space and enters ischemic cells, so its extracellular concentration would not increase.`],

        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-  One of the earliest consequences of reduced ATP generation is failure of the ATP-dependent plasma membrane Na<sup>+</sup>-K<sup>+</sup> pump. This results in efflux of intracellular K<sup>+</sup> (whose concentration is higher inside than outside cells) and influx of Na<sup>+</sup> and water (to maintain osmotic balance), resulting in cell swelling. Ultimately the cell undergoes necrosis if ATP production is not restored.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `Metabolically active cells are subjected to radiant energy in the form of X-rays in an experiment. Which of the following intracellular enzymes helps to protect the cells from this type of injury?`,
        q2: ``,
        q3: [],
        option: [`Endonuclease`, `Glutathione peroxidase`,`Lactate dehydrogenase`,` Phospholipase`,`Protease`],
    optionFeedback: [`<!--A.-->Endonucleases are activated during the process of apoptosis and cause nuclear fragmentation in the formation of apoptotic bodies. `,`<!--B.--><!--Answers:--> Radiation (radiant energy) interacts with water and other molecules to create damaging reactive oxygen species (ROS). Glutathione peroxidase is an enzyme that destroys (“scavenges”) ROS and reduces their injurious effects.`,`<!--C.-->Lactate dehydrogenase (LDH) is an intracellular enzyme in many cells that is released if cells are injured. Serum LDH levels may be increased in cardiac, hepatic, red cell, and other injuries. `,`<!--D.-->Phospholipases degrade cellular phospholipids and promote cell membrane injury; phospholipases also convert membrane phospholipids to biochemically active compounds. Phospholipase A2 (PLA2) generates arachidonic acid, the precursor of prostaglandins and leukotrienes, and phospholipase C gamma (PLC&#947;) generates second messengers. `,`<!--E.-->Proteases are enzymes that cleave proteins and have many diverse functions.`],

        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Radiation (radiant energy) interacts with water and other molecules to create damaging reactive oxygen species (ROS). Glutathione peroxidase is an enzyme that destroys (“scavenges”) ROS and reduces their injurious effects.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 63-year-old man has a 2-year history of worsening congestive heart failure. An echocardiogram shows mitral valve stenosis with left atrial dilation. A mural thrombus is present in the left atrium. One month later, he experiences left flank pain in the area overlying the kidney and notes hematuria. The representative appearance of the lesion is shown in the figure. Which of the following intracellular biochemical changes is most likely to have occurred in the affected cells?`,
        q2: `<img src="../images/f001-q020-9780323640251.png"/>`,
        q3: [],
        option: [`Increased ATP`, ` Reduced calcium`,` Increased lactate`,`Increased triglycerides`,`Reduced superoxide dismutase`],
    optionFeedback: [`<!--A.-->ATP is decreased in ischemic cells. `,`<!--B.-->Calcium enters ischemic cells and may activate numerous injurious pathways. `,`<!--C.--><!--Answers:--> This patient developed a renal infarct (manifested by flank pain and hematuria) due to emboli from the mural thrombus in the heart. The pale, wedge-shaped area represents coagulative necrosis (“pale infarct”). Microscopically, coagulative necrosis is seen as a region where cellular outlines are preserved but nuclei are lost. Lactate (lactic acid) accumulates in ischemic cells because of failure of oxidative phosphorylation and a compensatory increase in anaerobic glycolysis.`,`<!--D.-->Triglycerides are deposited in cells in patients with obesity and metabolic disorders, but not in ischemic cells. `,`<!--E.-->Superoxide dismutase is an enzyme that scavenges ROS. Its levels may not change significantly in ischemic cells. `],

        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-This patient developed a renal infarct (manifested by flank pain and hematuria) due to emboli from the mural thrombus in the heart. The pale, wedge-shaped area represents coagulative necrosis (“pale infarct”). Microscopically, coagulative necrosis is seen as a region where cellular outlines are preserved but nuclei are lost. Lactate (lactic acid) accumulates in ischemic cells because of failure of oxidative phosphorylation and a compensatory increase in anaerobic glycolysis.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 22-year-old woman with leukemia undergoes bone marrow transplantation and receives a partially mismatched donor marrow. One month later, she has a scaling skin rash. A skin biopsy is obtained, and on microscopic examination, it has the cellular change shown in the figure. This change most likely results from which of the following biochemical reactions?`,
        q2: `<img src="../images/f001-q022-9780323640251.png"/>`,
        q3: [],
        option: [`Activation of caspases`, `Elaboration of lipases`,`Increase in glycolysis`,`Peroxidation of lipids`,`Reduction of ATP synthesis`],
    optionFeedback: [`<!--A.--><!--Answers:--> The histologic features are characteristic of apoptotic cells (cell shrinkage, brightly eosinophilic, dense cytoplasm and condensed nucleus) which accumulate in the epidermis (and colonic epithelium and liver bile ducts) in graft-vs-host disease (Chapter 4), which this patient has developed. Apoptosis results from the activation of caspases, cytosolic proteases with multiple targets. Apoptotic cells are eosinophilic and show fragmented nuclei (and cytoplasm) but there is no attendant inflammation (as in this case).`,`<!--B.-->Lipases released from pancreatic acinar cells in acute pancreatitis are responsible for the fat necrosis seen in the mesentery, but play no role in apoptosis. `,`<!--C.-->Anaerobic glycolysis is increased in cell ischemia, which culminates in necrosis, not apoptosis. `,`<!--D.-->Lipid peroxidation is one of the actions of reactive oxygen species, whose production is increased in cells damaged by ischemia and other insults. This process is part of necrotic cell death. `,`<!--E.-->ATP synthesis is reduced in cells undergoing ischemia and ultimately necrosis, but not in apoptosis.`],

        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The histologic features are characteristic of apoptotic cells (cell shrinkage, brightly eosinophilic, dense cytoplasm and condensed nucleus) which accumulate in the epidermis (and colonic epithelium and liver bile ducts) in graft-vs-host disease (Chapter 4), which this patient has developed. Apoptosis results from the activation of caspases, cytosolic proteases with multiple targets. Apoptotic cells are eosinophilic and show fragmented nuclei (and cytoplasm) but there is no attendant inflammation (as in this case).`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 47-year-old man has a lung carcinoma with metastases. He receives chemotherapy. A month later, histologic examination of a metastatic lesion shows many foci in which individual tumor cells appear shrunken and deeply eosinophilic. Their nuclei exhibit condensed aggregates of chromatin under the nuclear membrane. The pathologic process affecting these shrunken tumor cells is most likely triggered by release of which of the following substances into the cytosol?`,
        q2: ``,
        q3: [],
        option: [` Bcl2`, `Catalase`,` Cytochrome c`,`Lipofuscin`,`Phospholipase`],
    optionFeedback: [`<!--A.-->Bcl2 levels decrease in cells undergoing apoptosis. It is also largely confined to mitochondrial membranes and is not released into the cytosol.`,`<!--B.-->Catalase is an enzyme that scavenges reactive oxygen species; it is not involved in apoptosis. `,`<!--C.--><!--Answers:--> Chemotherapy damages DNA and triggers the mitochondrial (intrinsic) pathway of apoptosis. Cytochrome<i> c</i> released from mitochondria is a key intermediary in this process because it activates caspase-9, which results in the downstream changes that culminate in apoptotic death.`,`<!--D.--><!--Answers:-->Lipofuscin is a pigment derived from peroxidation of lipids and is an indicator of past reactive oxygen species–mediated injury. It often accumulates in aging, degenerating, and atrophic cells. `,`<!--E.-->Phospholipase cleaves membrane phospholipids and causes fragmentation of cell membranes, which occurs in necrosis.`],

        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Chemotherapy damages DNA and triggers the mitochondrial (intrinsic) pathway of apoptosis. Cytochrome<i> c</i> released from mitochondria is a key intermediary in this process because it activates caspase-9, which results in the downstream changes that culminate in apoptotic death.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 45-year-old woman has had worsening dyspnea for the past 5 years. A computed tomography scan of the chest shows severe emphysema. Laboratory studies show reduced levels of α<sub>1</sub>-antitrypsin in the plasma. Molecular studies show a mutation in the α<sub>1</sub>-antitrypsin gene. A liver biopsy specimen examined microscopically shows abundant PAS-positive globules comprised of α<sub>1</sub>-antitrypsin within hepatocytes. Which of the following is the most likely cellular consequence of α<sub>1</sub>-antitrypsin retention in hepatocytes?`,
        q2: ``,
        q3: [],
        option: [`Decrease in synthesis of chaperones`, `Increase in production of reactive oxygen species`,`Recruitment of inflammatory cells`,`Apoptosis due to endoplasmic reticulum stress`,`Lipid peroxidation of endoplasmic reticulum membranes`],
    optionFeedback: [`<!--A.-->Chaperones increase as part of the UPR in an attempt to reduce the load of misfolded proteins in the endoplasmic reticulum. `,`<!--B.-->Reactive oxygen species are produced during ischemic and other forms of injury, which typically culminate in necrosis. `,`<!--C.-->Inflammatory cells (leukocytes) are recruited in response to necrotic cells to clear the damage, but not with apoptotic cells (which are cleared rapidly by phagocytes without eliciting potentially harmful inflammation). `,`<!--D.--><!--Answers:--> The mutation leads to misfolding of the α<sub>1</sub>-antitrypsin protein and its accumulation in the endoplasmic reticulum (ER). When the amount of accumulated protein exceeds the capacity of the cell’s unfolded protein response (UPR) to handle the load, the result is activation of sensors that trigger apoptosis by the mitochondrial (intrinsic) pathway, thus eliminating a cell that cannot function properly.`,`<!--E.-->Lipid peroxidation of various membranes is one of the actions of reactive oxygen species, whose production is increased in cells damaged by ischemia and other insults. This process is part of necrotic cell death, not apoptosis.`],

        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The mutation leads to misfolding of the α<sub>1</sub>-antitrypsin protein and its accumulation in the endoplasmic reticulum (ER). When the amount of accumulated protein exceeds the capacity of the cell’s unfolded protein response (UPR) to handle the load, the result is activation of sensors that trigger apoptosis by the mitochondrial (intrinsic) pathway, thus eliminating a cell that cannot function properly.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `At autopsy, the heart of a 93-year-old man weighs only 250 g (normal 330 g) and has small right and left ventricles. The myocardium is firm, with a dark chocolate-brown color throughout. The coronary arteries show minimal atherosclerotic changes. An excessive amount of which of the following substance would most likely be found in the myocardial fibers of this heart?`,
        q2: ``,
        q3: [],
        option: [`Bilirubin`, `Glycogen`,` Hemosiderin`,` Hemosiderin`,`Melanin`],
    optionFeedback: [`<!--A.-->Bilirubin is derived from the breakdown of heme. It accumulates in hepatocytes in disorders associated with biliary obstruction or bilirubin metabolism.`,`<!--B.-->Glycogen accumulates in cells in metabolic diseases such as diabetes and inherited enzyme defects (lysosomal storage diseases). Because it is dissolved during routine tissue preparation, it is not readily visible unless special procedures are used to visualize it.`,`<!--C.-->Hemosiderin is derived from hemoglobin and accumulates in macrophages in situations of excessive red cell hemolysis (e.g., hemolytic anemias) and in parenchymal cells in the genetic disease hemochromatosis, which results in dilated cardiomyopathy in later stages, rather than a smaller-than-normal heart. `,`<!--D.--><!--Answer:--> The reduced size is an indication of atrophy (of unknown cause in this case). The pigment lipofuscin, derived from peroxidation of lipids, is an indicator of past reactive oxygen species–mediated injury. It often accumulates in aging, degenerating, and atrophic cells.`,`<!--E.-->Melanin is not found in the heart.`],

        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The reduced size is an indication of atrophy (of unknown cause in this case). The pigment lipofuscin, derived from peroxidation of lipids, is an indicator of past reactive oxygen species–mediated in .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 70-year-old man with hypercalcemia died suddenly. At autopsy, microscopic examination showed noncrystalline amorphous deposits of calcium salts in gastric mucosa, renal interstitium, and alveolar walls of lungs. Which of the following underlying conditions would most likely explain these findings?`,
        q2: ``,
        q3: [],
        option: [`Hyperparathyroidism`, `Disseminated tuberculosis`,`Generalized atherosclerosis`,`Normal aging process`,`Normal aging process`],
    optionFeedback: [`<!--A.--><!--Answer:--> Hypercalcemia with metastatic calcification in multiple tissues is most often a reflection of primary hyperparathyroidism, which is usually caused by excessive parathyroid hormone (PTH) production due to diffuse parathyroid hyperplasia (or, less commonly, a parathyroid adenoma). Some tumors produce PTH-related protein, and cancer-associated hypercalcemia is a classical paraneoplastic syndrome (and the most common cause of hypercalcemia). Most of these patients, however, do not develop widespread metastatic calcification (perhaps because the hypercalcemia is not as prolonged as in parathyroid disease).`,`<!--B.-->Disseminated (miliary) tuberculosis would produce granulomas with caseous necrosis in multiple tissues that can calcify; this would be a form of dystrophic calcification not associated with hypercalcemia. `,`<!--C.-->Atherosclerotic lesions do contain calcium deposits, but they are also examples of dystrophic calcification, limited to arteries, and not associated with hypercalcemia. `,`<!--D.-->Calcium deposits are not associated with normal aging. `,`<!--E.-->Aortic stenosis is often associated with calcification of aortic valves. This is an example of dystrophic calcification, resulting from repeated mechanical damage to the valves.`],

        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Hypercalcemia with metastatic calcification in multiple tissues is most often a reflection of primary hyperparathyroidism, which is usually caused by excessive parathyroid hormone (PTH) production due to diffuse parathyroid hyperplasia (or, less commonly, a parathyroid adenoma). Some tumors produce PTH-related protein, and cancer-associated hypercalcemia is a classical paraneoplastic syndrome (and the most common cause of hypercalcemia). Most of these patients, however, do not develop widespread metastatic calcification (perhaps because the hypercalcemia is not as prolonged as in parathyroid disease).`,
        state: `notAnswered`,
        userAnswered: [],
    }

   ];






