var quiz = [
    {
        q: `A 31-year-old, sexually active, healthy woman has a 1-week history of a mucopurulent vaginal discharge. On pelvic examination, the cervix appears erythematous around the os, but no erosions or mass lesions are present. A Pap test shows numerous neutrophils, but no dysplastic cells. Which of the following infectious agents is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Candida albicans`, `Chlamydia trachomatis`, `Herpes simplex virus`,` Human papillomavirus`,`Neisseria gonorrhoeae`],
        optionFeedback: [`Candida albicans typically causes infection in the setting of disturbed vaginal microbiome (e.g., after antibiotic therapy or in the setting of poorly controlled diabetes). The discharge is white and thick and yeast and pseudo-hyphae can be visualized microscopically.`,`The mucopurulent discharge, erythema, and neutrophils suggest cervicitis. Chlamydia infection is the most common cause of cervicitis in sexually active women. It is the most frequent sexually transmitted disease in the United States.`,`Herpes simplex virus lesions usually take the form of ulcers, typically on the labia.`,`Human papillomavirus infection is usually asymptomatic; it can give rise to condyloma, dysplasia, and neoplasia.`,`Neisseria gonorrhoeae infection also often presents with a mucopurulent discharge but is less common than chlamydia.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The mucopurulent discharge, erythema, and neutrophils suggest cervicitis. Chlamydia infection is the most common cause of cervicitis in sexually active women. It is the most frequent sexually transmitted disease in the United States `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 31-year-old diabetic woman has had vulvar pruritus along with a thick, whitish, odorless, vaginal discharge for the past week. On pelvic examination, the cervix appears erythematous, but there are no erosions or masses. A Pap test shows budding cells and pseudohyphae. No dysplastic cells are present. Which of the following infectious agents is most likely to produce these findings?`,
        q2: ``, 
        q3: [],
        option: [`Candida albicans`, `Chlamydia trachomatis`,`Neisseria gonorrhoeae`,`Trichomonas vaginalis`,`Human papilloma virus`],
        optionFeedback: [`Candida albicans typically causes infection in the setting of disturbed vaginal microbiome (e.g., after antibiotic therapy or in the setting of poorly controlled diabetes). The discharge is white and thick and yeast and pseudo-hyphae can be visualized microscopically.`,`Chlamydia trachomatis causes a mucopurulent discharge. Budding cells and pseudohyphae are not seen.`,`Neisseria gonorrhoeae causes a mucopurulent discharge. Budding cells and pseudohyphae are not seen. Gram-negative diplococci can be seen in neutrophils `,`Trichomonas vaginalis is a protozoan that may cause a frothy malodorous discharge and can be seen on Pap test. Budding cells and pseudohyphae are not seen.`,`Human papilloma virus infection is usually asymptomatic. Budding cells and pseudohyphae are not seen.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale:- Candida albicans typically causes infection in the setting of disturbed vaginal microbiome (e.g., after antibiotic therapy or in the setting of poorly controlled diabetes). The discharge is white and thick and yeast and pseudo-hyphae can be visualized microscopically.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 17-year-old sexually active female has had pelvic pain for 1 week. A pelvic examination shows mild erythema of the ectocervix and pain on palpation of right adnexa. A Pap test shows many neutrophils but no dysplastic cells. A cervical culture grows Neisseria gonorrhoeae. If the infection is not adequately treated, she will be at greatest risk for which of the following complications?`,
        q2: ``,
        q3: [],
        option: [`Cervical carcinoma`, ` Dysfunctional uterine bleeding`,` Ectopic pregnancy`,`Endometrial hyperplasia`,`Endometriosis`],
        optionFeedback: [`Cervical carcinoma is associated with human papilloma virus infection.`,`Dysfunctional uterine bleeding occurs in the absence of an organic cause; it results from hormonal imbalance, most often due to anovulatory cycles.`,`The right adnexal pain is concerning for an ascending gonorrheal infection that is involving the tube and ovary. If untreated, such infections can lead to tubal scarring, which increases the risk of ectopic pregnancy.`,`Endometrial hyperplasia is caused by hyperestrinism.`,`Endometriosis is caused by ectopic endometrial stroma and glands and is unrelated to gonorrhea.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The right adnexal pain is concerning for an ascending gonorrheal infection that is involving the tube and ovary. If untreated, such infections can lead to tubal scarring, which increases the risk of ectopic pregnancy.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 36-year-old sexually active woman presents with a 5-year history of warty vulvar lesions that have been increasing in size and number. On physical examination, there are multiple 0.5- to 2-cm red-pink, flattened lesions with rough surfaces present on the vulva and perineum. One of the larger lesions is excised; its microscopic appearance is shown in the figure. Which of the following infectious agents is most likely to produce these lesions?`,
        q2: `<img src="../images/f015-q004-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Candida albicans`, `Chlamydia trachomatis`,`Trichomonas vaginalis`,` Human papillomavirus`,`Treponema pallidum`],
        optionFeedback: [`Candida albicans typically results in vaginitis associated with thick, white discharge. Koilocytosis is not associated with this infection. `,`Chlamydia trachomatis most often is associated with mucopurulent vaginal discharge. Koilocytosis is not associated with this infection.`,`Trichomonas vaginalis causes a frothy malodorous vaginal discharge. Koilocytosis is not associated with this infection.`,`The gross and microscopic findings are diagnostic of condyloma acuminatum, a genital wart cause by low-risk HPV infection. Grossly, they are flat or papillary and microscopically, they are characterized by koilocytosis (perinuclear cytoplasmic vacuolization). `,`Treponema pallidum is most often associated with chancre, a painless “clean” ulcer on the labia or the perineum. Koilocytosis is not associated with this infection.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The gross and microscopic findings are diagnostic of condyloma acuminatum, a genital wart cause by low-risk HPV infection. Grossly, they are flat or papillary and microscopically, they are characterized by koilocytosis (perinuclear cytoplasmic vacuolization).  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A healthy 30-year-old woman presents for a routine health maintenance examination. Physical exam is unremarkable. A screening Pap test shows cells consistent with a low-grade squamous intraepithelial lesion (LSIL). Subsequent cervical biopsy specimens confirm the presence of LSIL.   Which of the following risk factors is most likely related to her Pap test findings?`,
        q2: ``,
        q3: [],
        option: [`Diethylstilbestrol (DES) exposure`, ` Multiple sexual partners`,`Oral contraceptive use`,`Prior treatment for a malignancy`,` Smoking`],
        optionFeedback: [`Diethylstilbestrol (DES) exposure during pregnancy is associated with the rare tumor clear cell carcinoma of the vagina that affects the female child. DES was used to prevent threatened abortions in the 1940s through 1960s.`,`A history of multiple sexual partners increases the probability of infection with high risk HPV, the cause of cervical squamous intraepithelial lesions (SIL).`,`Oral contraceptive use does not increase the risk for LSIL.`,`Prior treatment for a malignancy does not increase the risk for LSIL. Chemotherapy for treatment of certain malignant tumors is sometimes followed by leukemia.`,`Smoking does not increase the risk for LSIL.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- A history of multiple sexual partners increases the probability of infection with high risk HPV, the cause of cervical squamous intraepithelial lesions (SIL).`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 33-year-old woman presents for a routine health maintenance examination. On physical examination, there are no abnormal findings. A Pap test shows abnormalities; therefore, colposcopy and a biopsy are performed. The figure shows the microscopic appearance of the biopsy specimen. Which of the following is the best strategy to prevent the development of this lesion?`,
        q2: `<img src="../images/f015-q006-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Avoidance of tobacco products`, `Consumption of a diet rich in vegetables`,`Maintenance of an ideal body weight`,`Use of oral contraceptives`,`Vaccination for human papillomavirus`],
        optionFeedback: [`Avoidance of tobacco products will not decrease the chances of HPV infection.`,`Consumption of a diet rich in vegetables will not decrease the chances of HPV infection.`,`Maintenance of an ideal body weight will not decrease the chances of HPV infection.`,`Use of oral contraceptives will not decrease the chances of HPV infection.`,`The lesion shown is high-grade squamous intraepithelial lesion (HSIL), a precursor of cervical cancer caused by high-risk HPV infection. Except for sexual abstinence, vaccination for human papillomavirus is the only way of preventing HPV infection. Despite its efficacy (nearly complete protection against high-risk oncogenic HPV types 16 and 18 which account for approximately 70% of cervical cancers), the vaccine does not protect against all high-risk HPV types and current guidelines recommend that cervical cancer screening be continued as in the past.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The lesion shown is high-grade squamous intraepithelial lesion (HSIL), a precursor of cervical cancer caused by high-risk HPV infection. Except for sexual abstinence, vaccination for human papillomavirus is the only way of preventing HPV infection. Despite its efficacy (nearly complete protection against high-risk oncogenic HPV types 16 and 18 which account for approximately 70% of cervical cancers), the vaccine does not protect against all high-risk HPV types and current guidelines recommend that cervical cancer screening be continued as in the past. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 34-year-old woman who has been using oral contraceptives for 10 years has a routine Pap test for the first time. The results indicate that dysplastic cells are present, consistent with a high-grade squamous intraepithelial lesion (HSIL). Surgical excision confirms HSIL.    Which of the following is the most likely molecular pathogenesis for this finding?`,
        q2: ``,
        q3: [],
        option: [`Estrogenic stimulation of cell proliferation`, `Inheritance of a tumor suppressor gene mutation`,`Recurrent gonococcal cervicitis`,`Upregulation of BCL2 gene`,`Viral inactivation of the RB1 gene product`],
        optionFeedback: [`Oral contraceptive use is not associated with HSIL.`,`HSIL and cervical carcinoma are not among the various cancers that are highly associated with inheritance of a defective copy of a tumor suppressor gene.`,` Gonococcal cervicitis is not related to HSIL; gonorrhea and HSIL may coexist because of similar risk factors (such as multiple sex partners).`,`Upregulation of BCL2 gene expression is not related to HSIL.`,`The RB1 gene product, RB, is inactivated by the E7 protein encoded in the genome of high-risk strains of HPV.   Viral E7 protein binds the hypophosphorylated (active) form of RB, promotes its degradation via the proteasome pathway, and also inhibits p21 and p27, two important cyclin-dependent kinase inhibitors. Removal of these controls not only enhances cell cycle progression, but also impairs the ability of cells to repair DNA damage. This defect in DNA repair is exacerbated by the viral E6 proteins of high-risk HPV subtypes, which bind to the tumor suppressor protein p53 and promote its degradation by the proteasome. In addition, E6 up-regulates the expression of telomerase, which leads to cellular immortalization.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The RB1 gene product, RB, is inactivated by the E7 protein encoded in the genome of high-risk strains of HPV. Viral E7 protein binds the hypophosphorylated (active) form of RB, promotes its degradation via the proteasome pathway, and also inhibits p21 and p27, two important cyclin-dependent kinase inhibitors. Removal of these controls not only enhances cell cycle progression, but also impairs the ability of cells to repair DNA damage. This defect in DNA repair is exacerbated by the viral E6 proteins of high-risk HPV subtypes, which bind to the tumor suppressor protein p53 and promote its degradation by the proteasome. In addition, E6 up-regulates the expression of telomerase, which leads to cellular immortalization. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 13-year-old girl reached menarche at the age of 12. She now has abnormal uterine bleeding, with menstrual periods that are 2 to 7 days long and 2 to 6 weeks apart. The amount of bleeding varies from minimal spotting to a very heavy flow. Physical examination is unremarkable. A pelvic ultrasound scan shows no abnormalities. Which of the following is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [` Anovulatory cycles`, `Ectopic pregnancy`,`Endometrial carcinoma`,`HPV infection`,`Endometrial hyperplasia`],
        optionFeedback: [`During puberty, ovulation may be irregular, leading to anovulatory cycles with little or no shedding of the endometrial lining, followed by ovulatory cycles during which excess shedding occurs. `,`Ectopic pregnancy presents with pain and sometimes massive bleeding, leading to shock.`,`Endometrial carcinoma is a disease of middle-aged adult women.`,`HPV infection is sexually transmitted and would present with genital warts or potentially cervical neoplasia; the latter occurs years after initial infection. `,`Endometrial hyperplasia is a disorder mainly seen in premenopausal or perimenopausal women with hyperestrinism, sometimes due to obesity.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-During puberty, ovulation may be irregular, leading to anovulatory cycles with little or no shedding of the endometrial lining, followed by ovulatory cycles during which excess shedding occurs. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 35-year-old woman presents with infertility. She has had dysmenorrhea, dyspareunia, and pelvic pain on defecation for 4 years. Laparoscopic examination reveals red-blue nodules on the surface of the uterus and extensive adhesions between ovaries and the fallopian tubes. Histologic examination of a biopsy from one of the nodules shows hyperplastic endometrial glands surrounded by endometrial stroma with associated hemorrhage. Molecular analysis is negative for mutations in PTEN, TP53, or mismatch repair genes. Which of the following is the most appropriate treatment modality in this case?`,
        q2: ``,
        q3: [],
        option: [`Estrogen inhibitors`, `Chemotherapy`,`Antibiotics`,`Insulin`,` Oophorectomy`],
        optionFeedback: [`The findings given are consistent with endometriosis, the presence of ectopic endometrial glands and stroma. Compared to normal endometrium, endometriotic tissue expresses higher levels of inflammatory mediators because factors made by stromal cells recruit and activate macrophages. Stromal cells also make aromatase, leading to local production of estrogens. Hence antiinflammatory agents and estrogen inhibitors are used to treat endometriosis.`,`Chemotherapy is not indicated in this benign condition.`,`Since endometriosis is not caused by infections, antibiotics are not useful.`,`Insulin is used to treat diabetes, which is not a risk factor for endometriosis.`,`Oophorectomy is not necessary, since hormone levels can be manipulated medically. `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The findings given are consistent with endometriosis, the presence of ectopic endometrial glands and stroma. Compared to normal endometrium, endometriotic tissue expresses higher levels of inflammatory mediators because factors made by stromal cells recruit and activate macrophages. Stromal cells also make aromatase, leading to local production of estrogens. Hence antiinflammatory agents and estrogen inhibitors are used to treat endometriosis. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 42-year-old woman has had menometrorrhagia for the past 2 months. Her BMI is 32. She has no history of prior irregular menstrual bleeding, and she has not yet reached menopause. On physical examination, there are no vaginal or cervical lesions, and the uterus appears normal in size, but there is a right adnexal mass. An abdominal ultrasound scan shows the presence of a 7-cm solid right adnexal mass. Endometrial biopsy shows hyperplastic endometrium, but no cellular atypia. What is the most likely lesion that underlies her menstrual abnormalities?`,
        q2: ``,
        q3: [],
        option: [`Corpus luteum dysfunction`, ` Endometriosis`,`Granulosa cell tumor`,` Mature cystic teratoma`,` Metastasis`],
        optionFeedback: [`Corpus luteum dysfunction would not be associated with a 7-cm solid mass. Corpus luteum cysts do not produce estrogens.`,`Endometriosis usually produces cystic lesions associated with pain. Endometriosis affecting the ovary can produce a mass, but endometrial tissue does not produce large amounts of estrogens.`,`The size of the mass is consistent with a neoplasm, and the presence of endometrial hyperplasia suggests hyperestrinism. Granulosa cell tumors produce estrogens.`,`Mature cystic teratoma is a cystic lesion. Teratomas do not contain estrogen-producing tissue.`,`Metastases are unlikely in the absence of other symptoms and, when present, they do not produce estrogens.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The size of the mass is consistent with a neoplasm, and the presence of endometrial hyperplasia suggests hyperestrinism. Granulosa cell tumors produce estrogens. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 62-year-old woman noticed a blood-tinged vaginal discharge twice during the past month. Her last menstrual period was 10 years ago and she has never been pregnant. Bimanual pelvic examination reveals an increase in the size of the uterus with no palpable adnexal masses. There are no cervical erosions or masses. Her body mass index is 33. Her medical history indicates that for the past 30 years she has had hypertension and type 2 diabetes. An endometrial biopsy specimen is most likely to show which of the following?`,
        q2: ``,
        q3: [],
        option: [`Endometrial carcinoma`, `Choriocarcinoma`,` Leiomyosarcoma`,`Endometritis`,`Squamous cell carcinoma`],
        optionFeedback: [`Endometrial carcinoma, which is associated with vaginal bleeding and an increase in uterine size, is likely in this postmenopausal woman. She has multiple risk factors for endometrial cancer, including obesity, hypertension, and diabetes.`,`Choriocarcinoma occurs in the setting of pregnancy or the immediate postpartum setting.`,`Uterine leiomyosarcoma is much rarer than endometrial carcinoma and is not associated with obesity, hypertension, or diabetes.`,`Endometritis would not increase the size of the uterus and is not associated with the listed risk factors. Chronic endometritis most commonly comes to clinical attention due to abnormal uterine bleeding.`,`Squamous cell carcinoma is very rare in the uterus.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Endometrial carcinoma, which is associated with vaginal bleeding and an increase in uterine size, is likely in this postmenopausal woman. She has multiple risk factors for endometrial cancer, including obesity, hypertension, and diabetes. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 55-year-old nulliparous woman has a six-month history of menorrhagia. On physical examination, her blood pressure is 154/93 mm Hg; there are no cervical lesions or adnexal masses, and the uterus is normal in size. She is 155 cm (5 feet, 1 inch) tall and weighs 74.5 kg (body mass index 38). Hemoglobin A1c concentration is 9.8% (&lt;6%.). The endometrial biopsy is shown in the figure; molecular analysis reveals mutation of the PTEN gene. Which of the following alterations plays an important role in the pathogenesis of this lesion?`,
        q2: `<img src="../images/f015-q013-9780323640251r.png" alt="icon"/>`,
        q3: [],
        option: [`Estrogen excess`, `Increased prostaglandins`,` Nonenzymatic glycosylation`,`Increased triglyceride synthesis`,`Increased expression of HIF (hypoxia-induced factor)`],
        optionFeedback: [`The biopsy shows endometrial carcinoma and the patient has the classical risk factors: obesity, hypertension, and diabetes. Mutation of the PTEN gene is often seen in patients with endometrial cancer. Hyperestrogenic states give rise to endometrial hyperplasia and endometrial cancer in a stepwise manner.`,`Increased prostaglandin synthesis occurs in endometriosis.`,`Nonenzymatic glycation is a complication of diabetes; it is not involved in the pathogenesis of endometrial cancer.`,`Increased triglyceride synthesis bears no relationship to this cancer.`,`HIF expression is most characteristic of renal cell carcinoma, in which HIF protein is stabilized by loss of the von-Hippel Lindau (VHL) tumor suppressor gene. It is not associated with endometrial carcinoma.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The biopsy shows endometrial carcinoma and the patient has the classical risk factors: obesity, hypertension, and diabetes. Mutation of the PTEN gene is often seen in patients with endometrial cancer. Hyperestrogenic states give rise to endometrial hyperplasia and endometrial cancer in a stepwise manner.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A healthy 49-year-old woman has had a feeling of pelvic heaviness for the past 11 months and history of abnormal bleeding. Her physician palpates an enlarged nodular uterus on pelvic examination. A Pap test shows no abnormalities. Pelvic CT scan shows multiple solid uterine masses; there is no evidence of necrosis or hemorrhage.. Based on the gross and microscopic appearance of the masses from a similar case, which of the following treatment options is most appropriate?`,
        q2: `<img src="../images/f015-q014-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Palliative care for metastatic disease`, `Surgery `,`Chemotherapy`,` Estrogen receptor blockade is required to prevent recurrence `,`Antitubercular drugs`],
        optionFeedback: [`Metastasis to the uterus is unusual, and if it were to occur would likely be infiltrative, hemorrhagic, necrotic, or have other gross features that would betray its malignant nature. `,`The gross appearance of these tumors is highly characteristic of uterine leiomyomas (fibroids), one of the most common benign neoplasms. Myomectomy can be performed for isolated lesions, and hysterectomy is the definitive cure.`,`Chemotherapy is not required for the treatment of uterine leiomyoma.`,`Following hysterectomy, there is no chance of recurrence. `,`Antitubercular drugs have no role in this setting.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The gross appearance of these tumors is highly characteristic of uterine leiomyomas (fibroids), one of the most common benign neoplasms. Myomectomy can be performed for isolated lesions, and hysterectomy is the definitive cure.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 28-year-old woman presents with a week-long history of fever, pelvic pain, and a feeling of pelvic heaviness. Pelvic examination reveals a palpable, painful left adnexal mass. At laparoscopy an indistinct left fallopian tube that is part of a 5-cm circumscribed, red-tan mass involving the left adnexal region is identified. Which of the following infectious agents is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Chlamydia trachomatis`, `HIV`,`Herpes simplex virus`,`Mycobacterium tuberculosis`,`Treponema pallidum`],
        optionFeedback: [`The findings are consistent with a tubo-ovarian abscess (TOA), a feature of inflammatory pelvic disease. TOA is most often associated with chlamydial or gonococcal infections; however, these organisms may be difficult to isolate from the abscess, and sometimes polymicrobial infections are present. `,`HIV is not associated with pelvic inflammatory disease.`,`Herpes simplex virus is associated with ulcerated lesions of the labia and perineum.`,`Mycobacterium tuberculosis may infect the upper genital tract, but this is a rare complication of TB.`,`Treponema pallidum typically presents with painless ulcer with a clean base on the labia or perineum.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The findings are consistent with a tubo-ovarian abscess (TOA), a feature of inflammatory pelvic disease. TOA is most often associated with chlamydial or gonococcal infections; however, these organisms may be difficult to isolate from the abscess, and sometimes polymicrobial infections are present `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 35-year-old woman has had increasing abdominal enlargement for the past 6 months. She states that she feels like she is pregnant, but results of a pregnancy test are negative. A pelvic ultrasound scan shows bilateral ovarian masses. The masses are surgically removed. On gross examination, the masses contain cysts with complex papillary projections filled with clear serous fluid. Microscopic examination shows that the papillae are lined by pleomorphic, malignant-appearing cells that have invaded the underlying stroma. There is a family history of similar tumors in a maternal aunt and a cousin. Which of the following molecular findings are most likely to be present in normal skin fibroblasts of this patient?`,
        q2: ``,
        q3: [],
        option: [`Homozygous loss of PTEN gene`, `Microsatellite instability`,`Mutational inactivation of one copy of BRCA1 gene`,` Amplification of HER2neu (ERBB2) gene`,`Homozygous loss of RB gene`],
        optionFeedback: [`Loss of the PTEN tumor suppressor gene is associated with several tumors, particularly those that are estrogen dependent, namely breast cancer and endometrial carcinoma; it may be lost in endometrioid-type ovarian cancer, but not in papillary serous type.`,`Microsatellite instability is a feature of cancers other than ovarian cancer, particularly a subset of colonic adenocarcinoma; it is also seen at lower frequency in many other cancers.`,`The morphologic findings are consistent with papillary serous carcinoma, an aggressive type of ovarian cancer that occurs with high frequency in patients who inherit a defective copy of the BRCA1 tumor suppressor gene. The presence of the mutation in normal fibroblasts indicates it is a germline genetic abnormality. `,`Amplification of the HER2neu gene is not seen in papillary serous ovarian cancer; it is mainly a feature of a subset of breast cancers. It is not a germline genetic abnormality. `,`Loss of the RB gene is classically seen in retinoblastoma and osteosarcoma, and also in a number of other cancers, such as small cell carcinoma of the lung.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The morphologic findings are consistent with papillary serous carcinoma, an aggressive type of ovarian cancer that occurs with high frequency in patients who inherit a defective copy of the BRCA1 tumor suppressor gene. The presence of the mutation in normal fibroblasts indicates it is a germline genetic abnormality. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 40-year-old woman has noticed progressive enlargement of the abdomen over the past 5 months. Physical examination shows no palpable masses, but a fluid wave is present. Paracentesis yields 500 mL of slightly cloudy fluid. Cytologic examination of the fluid shows malignant cells. An abdominal ultrasound scan demonstrates a 15-cm multilobular mass that involves the right adnexal region. The uterus is normal in size. Serum CA-125 level is elevated; human chorionic gonadotropin (HCG) is normal. Molecular analysis shows the presence of mutations in the TP53 tumor suppressor gene. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Mucinous cystadenocarcinoma`, `Choriocarcinoma`,`Dermoid cyst`,`Papillary serous carcinoma`,`Malignant teratoma`],
        optionFeedback: [`Mucinous cystadenocarcinoma is usually associated with RAS mutations (not TP53 mutations) and is less aggressive than papillary serous carcinomas.`,`Choriocarcinoma most often arises in the uterus as a complication of pregnancy. It often metastasizes widely but does not seed the peritoneal cavity and does not cause ascites. It is also associated with increased serum HCG, which is produced by the tumor cells. `,`Dermoid cyst is a benign ovarian teratoma that does not seed the peritoneal cavity and does not cause ascites.`,`The most likely ovarian carcinoma to present with ascites is aggressive papillary serous carcinoma with TP53 mutation. `,`Malignant teratoma may metastasize, but does not seed the peritoneal cavity and does not cause ascites. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The most likely ovarian carcinoma to present with ascites is aggressive papillary serous carcinoma with TP53 mutation `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 33-year-old woman has had dull, constant abdominal pain for 6 months. On physical examination, the only finding is a right adnexal mass. CT scan of the pelvis shows a 7-cm circumscribed cystic mass on the right ovary with large irregular calcifications. The right fallopian tube and ovary are surgically excised. The gross appearance of the ovary, which has been opened, is shown in the figure. Microscopic examination of this lesion is most likely to show which of the following?`,
        q2: `<img src="../images/f015-q018-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Mature squamous epithelium`, `Papillary structures lined by ciliated epithelium`,`Mucin-secreting cells`,`Primitive neural tissue`,` Sheets of trophoblasts and syncytial cells`],
        optionFeedback: [`The findings are consistent with a mature cystic teratoma (dermoid cyst), which contains mature squamous epithelium and sometimes other structures and tissues such as teeth and hair. The illustrated tumor has a large ball of hair. `,`Papillary serous tumors have a more complex lining with papillae; although they may contain small areas of calcification called psammoma bodies, large calcifications (e.g., bony structures and teeth) are absent. `,`Ovarian mucinous tumors are not associated with calcifications and they do not contain structures such as hair.`,`Fetal and embryonal tissue including primitive neural tissue, are seen in immature (malignant) teratoma. Grossly, immature ovarian teratomas are typically solid and may have areas of hemorrhage and necrosis. The tumor is found chiefly in prepubertal adolescents and young women, the mean age being 18 years.`,`Sheets of trophoblasts and syncytial cells are features of choriocarcinoma, which usually occurs in the uterus as a complication of pregnancy, is not cystic, and is often grossly hemorrhagic.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The findings are consistent with a mature cystic teratoma (dermoid cyst), which contains mature squamous epithelium and sometimes other structures and tissues such as teeth and hair. The illustrated tumor has a large ball of hair.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 36-year-old primigravida develops peripheral edema late in the second trimester. On physical examination, her blood pressure is 155/95 mm Hg. Urinalysis shows 2+ proteinuria, but no blood, glucose, or ketones. At 36 weeks, she gives birth to a normal viable but low-birth-weight infant. Her blood pressure returns to normal, and she no longer has proteinuria. Which of the following pathologic findings is most likely to be found on examination of the placenta?`,
        q2: ``,
        q3: [],
        option: [`Chorioamnionitis`, `Complete mole`,`Hydropic villi`,`Multiple infarcts`,` Partial mole`],
        optionFeedback: [`Chorioamnionitis is most often associated with premature labor; it does not result in the findings seen in this case.`,`Complete moles develop from diploid fertilized ova in which all of the DNA is paternal; it is incompatible with embryogenesis.`,`Hydropic villi are a feature of complete and partial moles, which are incompatible with fetal development to term.`,`The clinicopathologic findings are consistent with preeclampsia, a condition in which abnormalities of placental vessels lead to placental hypoxia producing placental infarcts. There is also generalized endothelial dysfunction causing proteinuria, hypertension, and (if severe) liver dysfunction. Delivery of the fetus and the placenta is curative.`,`Partial mole develops from triploid fertilized ova, created by fertilization of an ovum with two sperms. Some fetal development is seen, but it is incompatible with fetal development to term. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The clinicopathologic findings are consistent with preeclampsia, a condition in which abnormalities of placental vessels lead to placental hypoxia producing placental infarcts. There is also generalized endothelial dysfunction causing proteinuria, hypertension, and (if severe) liver dysfunction. Delivery of the fetus and the placenta is curative. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 35-year-old primigravida woman at 30 weeks' gestation develops worsening headaches along with a 3-kg weight gain over 1 week. This morning she had a generalized seizure. On physical examination, her blood pressure is 190/115 mm and she has peripheral edema. Fetal heart sounds are normal and movements are present. Laboratory studies show hemoglobin, 12.5 g/dL (12–16 g/dL); hematocrit, 37.6% (36%–46%); MCV, 92 &#181;m<sup>3</sup> (80–100 &#181;m<sup>3</sup>); platelet count, 199,000/mm<sup>3</sup> (150,000–400, 000/mm<sup>3</sup>). Urinalysis shows 2+ proteinuria, but no hematuria, RBCs, WBCs, or casts. Which of the following is the most likely underlying factor in the causation of her disease?`,
        q2: ``,
        q3: [],
        option: [` Impaired renal perfusion`, `Disseminated intravascular coagulation`,`Gestational trophoblastic disease`,`Ovarian neoplasm producing estrogen`,`Placental ischemia`],
        optionFeedback: [`Impaired renal perfusion may be a secondary event in eclampsia following development of vascular leak and hypertension. It is not a cause of the condition.`,`Disseminated intravascular coagulation is a secondary event in eclampsia that is usually seen in the setting of liver dysfunction and severe hypertension with widespread endothelial dysfunction.`,`Gestational trophoblastic disease would likely present as a uterine mass, rising HCG levels, and possibly metastasis.`,`Ovarian neoplasms producing estrogen would present with endometrial hyperplasia causing abnormal bleeding and do not usually present during pregnancy.`,`The patient has developed eclampsia, in which abnormal placental vessels lead to chronic placental ischemia, setting into motion a series of events that lead to increases in vascular permeability, renal dysfunction, liver dysfunction, and increasingly severe hypertension.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The patient has developed eclampsia, in which abnormal placental vessels lead to chronic placental ischemia, setting into motion a series of events that lead to increases in vascular permeability, renal dysfunction, liver dysfunction, and increasingly severe hypertension.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 21-year-old G2, P1 woman is in the early second trimester. She has noted a small amount of vaginal bleeding for the past week and has had marked nausea and vomiting for 3 weeks. On physical examination, the uterus measures large for dates. On ultrasound examination, no fetus is identified. The gross appearance of tissue obtained by dilation and curettage is shown in the figure. Serum levels of which of the following is most likely to be greatly increased?`,
        q2: `<img src="../images/f015-q021-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`AST and ALT`, `α-Fetoprotein`,`Estradiol`,`Human chorionic gonadotropin (HCG)`,`D-dimer`],
        optionFeedback: [`AST and ALT are measures of liver damage, which does not occur in molar pregnancies.`,`α-Fetoprotein is elevated in yolk sac tumor and hepatocellular carcinoma, neither of which will present as a uterine mass.`,`Estradiol is not produced by gestational mole; some ovarian tumors like granulosa cell tumor make estradiol.`,`The curettage shows hydropic villi, consistent with a gestational mole, which produces large amounts of HCG.    `,`D-dimer elevation is a feature of disseminated intravascular coagulation (DIC), which is not typically seen in gestational moles.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The curettage shows hydropic villi, consistent with a gestational mole, which produces large amounts of HCG`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 23-year-old woman notices a bloody, brownish vaginal discharge. The next day she has shortness of breath. A chest radiograph shows numerous 2- to 5-cm nodules in both lungs. Laboratory studies show that her serum human chorionic gonadotropin levels are markedly elevated. A necrotic hemorrhagic mass is obtained by dilation and curettage. Histologic examination of the non-necrotic areas is shown in the figure. Chromosome analysis of these cells shows a 46,XX karyotype. Which of the following cells are most likely present in this mass lesion?`,
        q2: `<img src="../images/f015-q022-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Squamous stratified`, ` Smooth muscle `,`Serous epithelial`,` Mucin-secreting epithelium `,`Syncytiotrophoblast`],
        optionFeedback: [`Squamous stratified epithelium might be seen in dermoid cysts as well as squamous carcinomas, neither of which would present as vaginal discharge.`,`Malignant smooth muscle cells are a feature of leiomyosarcoma. This might cause vaginal discharge and be associated with lung metastases, but it is a tumor of older adults. Histologically, leiomyosarcomas show nuclear pleomorphism, mitotic activity and necrosis and range from well-differentiated tumors similar to leiomyomas to highly anaplastic tumors.`,`Serous epithelial neoplasms of the uterus could present with vaginal discharge, but they are also tumors of older adults. The microscopic picture is not consistent with this diagnosis.`,`Mucin-secreting epithelium is seen in mucinous adenocarcinomas, which do not occur in the uterus and is very unlikely to be associated with vaginal discharge and lung metastases.`,`The clinicopathologic features are consistent with choriocarcinoma, a tumor comprised of malignant trophoblasts and syncytiotrophoblasts. The tumor cells secrete HCG and metastases to distant organs such as lungs are common.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The clinicopathologic features are consistent with choriocarcinoma, a tumor comprised of malignant trophoblasts and syncytiotrophoblasts. The tumor cells secrete HCG and metastases to distant organs such as lungs are common. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 24-year-old woman is breastfeeding 3 weeks after giving birth to a normal term infant. She notices fissures in the skin around her left nipple. Over the next 3 days, a 5-cm region near the nipple becomes erythematous and tender. Purulent exudate from a small abscess drains through a fissure. Which of the following organisms is most likely to be cultured from the exudate?`,
        q2: ``,
        q3: [],
        option: [`Candida albicans`, `Lactobacillus acidophilus`,`Listeria monocytogenes`,`Staphylococcus aureus`,` Streptococcus viridans`],
        optionFeedback: [`Candida albicans causes few, if any, breast infections.`,`Lactobacillus acidophilus is a normal component of vaginal flora.`,`Listeria monocytogenes is a cause of severe systemic infections, particularly in the immunosuppressed. It is often spread by consumption of contaminated dairy products and does not cause breast abscess.`,`The clinical findings are classic for a breast abscess, which typically is caused by Staphylococcus aureus in the setting of breastfeeding.`,`Streptococcus viridans are a component of normal oral flora. It sometimes causes subacute infective endocarditis; it is not a cause of breast abscess.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The clinical findings are classic for a breast abscess, which typically is caused by Staphylococcus aureus in the setting of breastfeeding. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 27-year-old G3, P3 woman feels a lump in her right breast. She has normal menstrual cycles and her last child was born 5 years ago. On examination, a 1.5-cm, nonpainful, discrete, freely mobile mass is palpated beneath the lateral edge of the areola. Microscopic examination of a biopsy specimen is illustrated. Which of the following treatment plans would be best for this patient?`,
        q2: `<img src="../images/f015-q024-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [` Simple mastectomy `, `Simple mastectomy with axillary lymph node dissection `,`Radiation therapy `,`No further treatment`,`Sentinel lymph node biopsy`],
        optionFeedback: [`Simple mastectomy is overtreatment of a benign tumor.`,`Simple mastectomy with axillary lymph node dissection is performed for breast malignancies.`,`Radiation therapy may be needed for breast malignancies.`,`The clinical and microscopic findings are consistent with fibroadenoma, a benign neoplasm of intralobular stroma. No treatment is needed, but some women prefer to have it removed by lumpectomy (surgical excision). Laser and cryoablation are other modes of treatment.`,`Sentinel lymph node biopsy is performed for breast malignancies to ascertain lymph node spread.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The clinical and microscopic findings are consistent with fibroadenoma, a benign neoplasm of intralobular stroma. No treatment is needed, but some women prefer to have it removed by lumpectomy (surgical excision). Laser and cryoablation are other modes of treatment.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 47-year-old woman presents for a routine health examination. Her physical exam is notable only for a barely palpable mass in the right breast. A mammogram reveals an irregular, 1.5-cm area of density with scattered microcalcifications in the upper outer quadrant. A biopsy specimen from this area is obtained and microscopically shows simple cysts lined by a layer of cells with apocrine metaplasia. Which of the following is the most appropriate next step for this patient?`,
        q2: ``,
        q3: [],
        option: [`Recommend smoking cessation`, `Continued breast cancer screening`,`Simple mastectomy`,` Test for BRCA1 mutation`,`Prescribe broad-spectrum antibiotic therapy`],
        optionFeedback: [`Cessation of smoking cigarettes is a good general health measure but will not decrease the risk of breast cancer.`,`The findings are consistent with nonproliferative fibrocystic changes, which do not increase the risk of breast cancer. Routine screening for breast cancer should continue.`,`Mastectomy is not indicated as a treatment for fibrocystic disease. `,`Testing for mutations in the BRCA1 tumor suppressor gene is based on family history of breast cancer.`,`Broad-spectrum antibiotic therapy has no role in the treatment of fibrocystic changes.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The findings are consistent with nonproliferative fibrocystic changes, which do not increase the risk of breast cancer. Routine screening for breast cancer should continue. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 25-year-old woman sees her physician after finding a lump in her right breast. On physical examination, a 2-cm, firm, non-movable mass is palpated in the upper outer quadrant. No overlying skin lesions and no axillary lymphadenopathy are present. The figure shows an excisional biopsy specimen. Family history is relevant for Ashkenazi Jewish descent and the presence of similar lesions in the patient’s mother, maternal aunt, and maternal grandmother. Her 18-year-old sister wants to determine whether she is genetically at risk of developing the same disease. A mutated gene encoding which of the following is most likely to place her at a high risk?`,
        q2: `<img src="../images/f015-q026-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`BRCA1`, `Estrogen receptor (ER)`,`HER2`,`TP53`,`Progesterone receptor (PR)`],
        optionFeedback: [`The clinical features and histology are characteristic of infiltrating ductal carcinoma. BRCA1 mutations are frequently associated with familial breast cancer (as well as ovarian cancer), particularly in individuals who are of Ashkenazi Jewish descent.`,`Germline estrogen receptor (ER) mutations are not a cause of familial cancer; some breast cancers express estrogen receptors.`,`Germline HER2 mutations are not a cause of familial cancer; amplification of HER2 gene may be seen in some breast cancers, and in such cases, it can be targeted with antibodies directed against HER2.`,`Germline TP53 mutations are associated with Li-Fraumeni syndrome, a familial cancer syndrome in which patients are at high risk of developing many different types of cancer, not only breast cancer. `,`Germline progesterone receptor (PR) mutations are not a cause of familial cancer; PR may be expressed in some breast cancers.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The clinical features and histology are characteristic of infiltrating ductal carcinoma. BRCA1 mutations are frequently associated with familial breast cancer (as well as ovarian cancer), particularly in individuals who are of Ashkenazi Jewish descent. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 66-year-old nulliparous woman received hormone replacement therapy for 7 years following menopause at age 53 years. Her BMI is 33. She now undergoes screening mammography, and an irregular mass is identified in the right breast. An excisional biopsy yields a 1.5-cm mass that microscopically has invasive cells that are positive for estrogen receptor but negative for HER2, and have a low proliferation index (less than 10%). Following surgical removal of the mass, which of the following clinical scenarios is most likely over the next year?`,
        q2: ``,
        q3: [],
        option: [`Detection of cancer in the left breast`, `Need for immunotherapy`,`Low likelihood of recurrence`,`Development of axillary lymph node metastases`,`Occurrence of skeletal metastases`],
        optionFeedback: [`The risk of cancer in the contralateral breast is increased in cases of invasive lobular carcinoma or lobular carcinoma in situ.`,`Immunotherapy is unlikely to be needed in this patient with a small ER+ tumor with a low proliferation fraction.`,`Small ER+ cancers with low proliferation fractions have a low likelihood of recurrence.`,`Chances of axillary lymph node metastasis are low in this patient with a small ER+ tumor with a low proliferation fraction.`,`Chances of skeletal metastases are low in this patient with a small ER+ tumor with a low proliferation fraction.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Small ER+ cancers with low proliferation fractions have a low likelihood of recurrence.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 49-year-old woman felt a lump in her left breast 1 week ago. On examination, a firm, irregular mass is palpable in the upper outer quadrant of her left breast. There are no overlying skin lesions. The gross appearance of the excised specimen is shown in the figure. Which of the following additional findings is she most likely to have on physical examination?`,
        q2: `<img src="../images/f015-q029-9780323640251.png" alt="icon"/>`,
        q3: [],
        option: [`Axillary lymphadenopathy`, `Bloody discharge from the nipple`,`Ovarian mass`,`Cushingoid facies`,`Malignancy in the contralateral breast`],
        optionFeedback: [`The image provided and characteristics of the mass are consistent with infiltrating carcinoma, which is likely to spread first to axillary lymph nodes.`,`Bloody discharge from the nipple is a relatively uncommon symptom of infiltrating carcinoma. It may be seen occasionally with centrally placed lesions that are close to the nipple such as an intraductal papilloma.`,`Ovarian mass might be indicative of metastasis. This is unlikely at presentation and, when it occurs, is likely to involve both ovaries. Ovarian cancers may coexist with breast cancers in women with germline mutations of BRCA1 or BRCA2 genes.`,`Cushingoid facies suggests a paraneoplastic syndrome produced by hypercortisolism. This is rare in breast cancer; it is most commonly seen in small cell carcinoma of the lung and other tumors that produce ACTH.`,`Mass in the contralateral breast (synchronous carcinoma) is uncommon in patients with breast cancer.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The image provided and characteristics of the mass are consistent with infiltrating carcinoma, which is likely to spread first to axillary lymph nodes. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A study of women with breast carcinoma is performed to determine the presence and extent of estrogen receptor (ER) and progesterone receptor (PR) expression in the carcinoma cells. Abundant ER and PR are found in the carcinoma cells of some patients. These receptors are not present in the cells of other patients. The patients with positivity for ER and PR are likely to exhibit which of the following traits?`,
        q2: ``,
        q3: [],
        option: [`Greater immunogenicity`, `Greater likelihood of metastases`,`Greater risk of familial breast cancer`,`Higher response to therapy`,`Higher tumor stage`],
        optionFeedback: [`ER/PR-positive tumors are not thought to be particularly immunogenic.`,`ER/PR-positive tumors tend to be slow growing and less likely to be associated with early metastases (although late metastases are more frequent than in other molecular subtypes).`,`Familial breast cancer (e.g., BRCA1-related disease) is often ER/PR negative.`,`Generally, ER/PR-positive tumors are highly responsive to therapy with anti-estrogens.`,`ER/PR-positive tumors tend to be slow growing and less likely to be associated with early metastases; therefore, they are not associated with higher tumor stage on average.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Generally, ER/PR-positive tumors are highly responsive to therapy with anti-estrogens.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 79-year-old, previously healthy woman feels a lump in her right breast. The physician palpates a 2-cm firm mass in the upper outer quadrant. Nontender right axillary lymphadenopathy is present. A lumpectomy with axillary lymph node dissection is performed. Microscopic examination shows that the mass is an infiltrating ductal carcinoma. Five of 10 axillary nodes contain metastases. Immunohistochemistry shows that the tumor cells are positive for estrogen and progesterone receptor (ER/PR), negative for HER2 expression. Which of the following is the most important prognostic factor for this patient?`,
        q2: ``,
        q3: [],
        option: [`Age at diagnosis`, `Estrogen receptor expression`,`Histologic subtype of carcinoma`,`Lack of HER2 expression in the carcinoma`,`Presence of lymph node metastases`],
        optionFeedback: [`Diagnosis at older age, on average, is associated with less aggressive forms of ER+ breast cancer.`,`Estrogen receptor expression is typical of most cancers arising in this age group and is less important than lymphatic spread as a prognostic factor.`,`Histologic subtype of carcinoma correlates with grade and behavior, but is less important than staging.`,`Lack of HER2 expression in the carcinoma also is less important than staging in predicting outcome.`,`Presence of lymph node metastases portends a worse outcome as it indicates increased tumor stage. The staging of solid cancers is based on the size of the primary lesion, its extent of spread to regional lymph nodes, and the presence or absence of blood-borne metastases. The major staging system currently in use is the American Joint Committee on Cancer Staging. This system uses a classification called the TNM system—T for primary tumor, N for regional lymph node involvement, and M for metastases.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-Presence of lymph node metastases portends a worse outcome as it indicates increased tumor stage. The staging of solid cancers is based on the size of the primary lesion, its extent of spread to regional lymph nodes, and the presence or absence of blood-borne metastases. The major staging system currently in use is the American Joint Committee on Cancer Staging. This system uses a classification called the TNM system—T for primary tumor, N for regional lymph node involvement, and M for metastases. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 51-year-old woman has noticed an area of swelling with tenderness in her right breast that has worsened over the past 2 months. On physical examination, the 7-cm area of erythematous skin is tender with edematous surface that appears “finely pitted”. The breast is swollen, the nipple is retracted and there is right axillary nontender lymphadenopathy. Excisional biopsy of skin and breast is most likely to show which of the following lesions?`,
        q2: ``,
        q3: [],
        option: [`Acute mastitis`, `Atypical epithelial hyperplasia`,`Fat necrosis`,` Inflammatory carcinoma`,`Proliferative disease with atypia`],
        optionFeedback: [`Acute mastitis might produce swelling, but the other findings would be absent.`,`Atypical epithelial hyperplasia would typically be asymptomatic.`,`Fat necrosis might produce swelling and tenderness, but would not account for the lymphadenopathy or other features seen in this patient.`,`The physical findings are consistent with inflammatory carcinoma, including the swollen and pitted (“peau d’orange”) appearance of the skin, nipple retraction, breast swelling, and painless axillary lymphadenopathy. The skin changes and breast swelling are secondary to extensive invasion and proliferation of carcinoma cells in the lymphatics, which cause edema in the adjacent tissue. These tumors are high stage and usually high grade. `,`Proliferative disease with atypia would also likely be asymptomatic.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The physical findings are consistent with inflammatory carcinoma, including the swollen and pitted (“peau d’orange”) appearance of the skin, nipple retraction, breast swelling, and painless axillary lymphadenopathy. The skin changes and breast swelling are secondary to extensive invasion and proliferation of carcinoma cells in the lymphatics, which cause edema in the adjacent tissue. These tumors are high stage and usually high grade.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 27-year-old woman in the third trimester of her third pregnancy discovers a lump in her left breast. On physical examination, a 2-cm, discrete, freely movable mass in the upper left quadrant is palpable. After the birth of a term infant, the mass appears to decrease in size. The infant is breastfed without difficulty. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Fibroadenoma`, `Intraductal papilloma`,`Lobular carcinoma in situ`,` Medullary carcinoma`,`Phyllodes tumor`],
        optionFeedback: [`The fact that the mass is freely movable and discrete is suggestive of a benign tumor, most commonly a fibroadenoma. These benign tumors are hormone sensitive and often grow during pregnancy and regress after delivery. Biopsy is required for definitive diagnosis. `,`Intraductal papilloma is more likely to present with bloody nipple discharge.`,`Lobular carcinoma in situ is generally nonpalpable.`,`Medullary carcinoma does not regress post-delivery.`,`Phyllodes tumor, like fibroadenoma, is derived from intralobular stromal cells. Unlike fibroadenoma, this tumor represents a low-grade malignancy that would not be expected to regress following delivery.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The fact that the mass is freely movable and discrete is suggestive of a benign tumor, most commonly a fibroadenoma. These benign tumors are hormone sensitive and often grow during pregnancy and regress after delivery. Biopsy is required for definitive diagnosis.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 24-year-old woman has a one-month history of a lump in her right breast. She is concerned because her sister was diagnosed with a poorly differentiated triple negative breast cancer at age 31. Ultrasonography of the breast shows a solid mass. Fine needle aspiration is attempted but no diagnostic cells are obtained. Mammography is performed and there is a single, 1-cm density with small clustered calcifications in the right breast but no lesions of the opposite breast. Which of the following is the best course of action for this patient?`,
        q2: ``,
        q3: [],
        option: [`Biopsy to obtain tissue from the lesion`, `Continued monthly breast self-examination`,`Genetic testing for BRCA1 mutation`,`Hormonal therapy with tamoxifen`,`Radiologic imaging to detect metastases`],
        optionFeedback: [`The clinical and radiologic findings are suspicious for breast cancer. Definite determination of malignancy and benignancy can only be made by biopsy. All suspicious breast masses should be evaluated with a tissue biopsy. `,`Continued monthly breast self-examination is inadequate once a mass has been detected.`,`Genetic testing for BRCA1 mutations will not influence whether a tissue biopsy should be obtained. If the mass proves to be malignant, testing for mutations in BRCA1 and  BRCA2 genes would be warranted because her sister also had breast cancer. `,`Hormonal therapy with tamoxifen can only be started after tissue diagnosis and determination of the ER/PR status of the tumor.`,`Radiologic imaging to detect metastases is premature, in lieu of a tissue diagnosis of breast cancer.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The clinical and radiologic findings are suspicious for breast cancer. Definite determination of malignancy and benignancy can only be made by biopsy. All suspicious breast masses should be evaluated with a tissue biopsy. `,
        state: `notAnswered`,
        userAnswered: [],
    }
    
    

   ];






