var quiz = [
    {
        q: `A female infant born at term shows failure to thrive and fails to achieve developmental milestones. She is the parents’ first child; pedigree reveals no other affected individuals for four generations on both sides of the family. Tissue fibroblasts obtained from this child show a 46,XX karyotype. Cultured fibroblasts show absence of the enzyme phenylalanine hydroxylase. What is the most likely recurrence risk for this condition in siblings of this infant?`,
        q2: ``,
        q3: [],
        option: [` 3%`, ` 8%`, ` 15%`,` 25%`,` 50%`],
    optionFeedback: [`The probability of being affected of less than 25% would hold for traits with incomplete penetrance, but phenylalanine hydroxylase deficiency is a highly penetrant trait.`,`The probability of being affected of less than 25% would hold for traits with incomplete penetrance, but phenylalanine hydroxylase deficiency is a highly penetrant trait.`,`The probability of being affected of less than 25% would hold for traits with incomplete penetrance, but phenylalanine hydroxylase deficiency is a highly penetrant trait.`,` Phenylalanine hydroxylase deficiency is the cause of phenylketonuria and is an autosomal recessive disorder in which heterozygotes are asymptomatic carriers. The most likely scenario is that both parents are heterozygotes; based on random assortment of gametes, each child has a 1 in 4 chance of being homozygous for the trait.  `,`50% probability of being affected would correspond to an autosomal dominant trait, which would mean that one of the parents would be affected. If this disease were not as highly penetrant as phenylalanine hydroxylase deficiency, it is possible that the patient with the mutation would not show signs of disease.`],
    optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- Phenylalanine hydroxylase deficiency is the cause of phenylketonuria and is an autosomal recessive disorder in which heterozygotes are asymptomatic carriers. The most likely scenario is that both parents are heterozygotes; based on random assortment of gametes, each child has a 1 in 4 chance of being homozygous for the trait.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 22-year-old man has a sudden loss of vision in the right eye. On physical examination, there is a subluxation of the lens in the right eye. An echocardiogram shows a floppy mitral valve and dilated aortic arch. One of the patient’s two brothers and his maternal aunt are similarly affected. He is prescribed β-adrenergic and angiotensin receptor blocking drugs. A mutation affecting the gene encoding which of the following proteins is most likely to be present in this patient?`,
        q2: ``,
        q3: [],
        option: [`Collagen`, `Dystrophin`,`Fibrillin-1`,` NF1 protein`,`Spectrin`],
    optionFeedback: [`Mutations affecting collagen genes are found in Ehlers-Danlos syndrome (EDS) and related disorders. In EDS the skin is hyperextensible and joints are hypermobile. The skin also is fragile and vulnerable to trauma. The defect in connective tissue also may lead to spontaneous rupture of the colon and large arteries; rupture of the cornea and retinal detachment; and diaphragmatic hernia.`,`Mutations affecting the gene encoding dystrophin are found in muscular dystrophy. Patients have muscle weakness.`,` The phenotype (subluxation of lens, floppy mitral valve, and aortic aneurysm) and pattern of inheritance (autosomal dominant) is classic for Marfan syndrome, which is caused by mutations in the gene FBN1. FBN1 encodes fibrillin-1, a structural protein that contributes to the elasticity of tissues such as the aorta, heart valves, and support structures of the lens.<br/><br/>Incorrect answers:`,`Mutations affecting the NF1 gene are found in neurofibromatosis-1, characterized by widespread tumors of nerves.`,`Mutations affecting the gene encoding spectrin are found in hereditary spherocytosis and other red cell disorders. Patients have hemolytic anemia.`],
    optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale:- The phenotype (subluxation of lens, floppy mitral valve, and aortic aneurysm) and pattern of inheritance (autosomal dominant) is classic for Marfan syndrome, which is caused by mutations in the gene FBN1. FBN1 encodes fibrillin-1, a structural protein that contributes to the elasticity of tissues such as the aorta, heart valves, and support structures of the lens  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 4-year-old girl has sudden onset right hip pain. On examination, the child’s right hip is dislocated. The child can bend her thumb backward to touch the forearm. Her skin is noted to be extraordinarily stretchable. Radiographs of her spine show marked lateral and anterior curvature. Her brother is similarly affected, but her parents and younger sister are unaffected. Laboratory investigations reveal reduced levels of lysyl hydroxylase. Which of the following is the most likely cause for this child’s findings?`,
        q2: ``,
        q3: [],
        option: [`Congenital syphilis with involvement of the bones`, `Defect in collagen maturation`,` Defect in vitamin D synthesis`,`Deficient collagen alpha chain synthesis`,` Defect in vitamin C synthesis`],
    optionFeedback: [`Syphilis is an acquired disorder and the phenotype is not consistent with congenital syphilis. `,`Mutations in enzymes are usually autosomal recessive since the amount of enzyme produced by one allele is typically sufficient to prevent a disease state. Based on the presentation, collagen or other structural support molecules are likely affected. Lysyl hydroxylase is an enzyme that introduces crosslinks into collagen that stabilize collagen fibrils and, as with most enzyme defects, only causes disease if individuals inherit two defective alleles. Deficiency of this enzyme is one of several causes of Ehlers-Danlos syndrome, which manifests with defects in connective tissues. `,` Vitamin D abnormalities are mainly associated with bone defects (rickets and osteomalacia) and metabolic disturbances of calcium and phosphate. `,`Collagen abnormalities could cause a similar phenotype but would follow an autosomal dominant mode of inheritance, as in inherited disorders affecting structural proteins. `,`  `],
    optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Mutations in enzymes are usually autosomal recessive since the amount of enzyme produced by one allele is typically sufficient to prevent a disease state. Based on the presentation, collagen or other structural support molecules are likely affected. Lysyl hydroxylase is an enzyme that introduces crosslinks into collagen that stabilize collagen fibrils and, as with most enzyme defects, only causes disease if individuals inherit two defective alleles. Deficiency of this enzyme is one of several causes of Ehlers-Danlos syndrome, which manifests with defects in connective tissues. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A clinical study is undertaken with subjects from families in which complications of atherosclerotic cardiovascular disease and tendinous xanthomas occurred before age 30 years. The affected individuals benefit from treatment with pharmacologic agents that inhibit HMG-CoA reductase. Affected individuals in these families are most likely to have a mutation in a gene encoding a cell surface receptor for which of the following molecules?`,
        q2: ``,
        q3: [],
        option: [`Triglycerides`, ` Free fatty acids`,`LDL cholesterol`,` Insulin`,` HDL cholesterol`],
    optionFeedback: [`Triglycerides are hydrolyzed by lipoprotein lipase and are taken up into cells as free fatty acids in a receptor-independent fashion.`,`Free fatty acids are taken up into cells in a receptor-independent fashion.`,` The clinical phenotype is consistent with familial hypercholesterolemia (early onset atherosclerosis), an autosomal dominant disorder caused by defects in the gene encoding the LDL receptor. Because of the resulting defect in LDL uptake, hepatocyte synthesis of cholesterol is increased, leading to high levels of circulating LDL. The rate-limiting step in cholesterol synthesis is catalyzed by HMG-CoA reductase, thus the efficacy of HMG-CoA reductase inhibitors in this disorder.  `,`Insulin receptor defects are a rare cause of insulin resistance and diabetes.`,`HDL cholesterol is cleared by receptors, but high levels of HDL are not associated with cardiovascular disease and may be protective.`],
    optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The clinical phenotype is consistent with familial hypercholesterolemia (early onset atherosclerosis), an autosomal dominant disorder caused by defects in the gene encoding the LDL receptor. Because of the resulting defect in LDL uptake, hepatocyte synthesis of cholesterol is increased, leading to high levels of circulating LDL. The rate-limiting step in cholesterol synthesis is catalyzed by HMG-CoA reductase, thus the efficacy of HMG-CoA reductase inhibitors in this disorder. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 1-year-old female infant has failure to thrive, poor neurologic development, and poor motor function. Physical examination shows accentuation of the macula (“cherry red spot”) compared to the pale surrounding choroid. The infant’s muscle tone is poor. Both parents and a brother and sister are healthy, with no apparent abnormalities. One brother with a similar condition died at the age of 18 months. This genetic disorder most likely resulted from a mutation involving a gene encoding which of the following?`,
        q2: ``,
        q3: [],
        option: [`Mitochondrial enzyme`, `Lysosomal enzyme`,` Cell surface receptor protein`,`Structural protein`,` An ion channel`],
    optionFeedback: [`Mitochondrial enzyme defects are often associated with muscle disorders and may show an unusual pattern of maternally determined inheritance because all mitochondria in the fertilized zygote come from the mother. Since this patient has two unaffected siblings, mitochondrial inheritance is unlikely.`,` The phenotype is consistent with Tay-Sachs disease, an autosomal recessive disorder caused by mutations in the gene encoding the lysosomal enzyme hexosaminidase A.  `,`Disorders caused by defects in cell surface receptor proteins often have autosomal dominant modes of inheritance. Cell surface receptors typically control complex intracellular pathways resulting in a cascade of events that magnify the loss of one allele, as in familial hypercholesterolemia.`,`Disorders caused by defects in structural proteins such as collagen often have autosomal dominant modes of inheritance because one mutant allele interferes with the formation of the complete functional molecule (called dominant negative effect). `,`Disorders caused by defects in ion channels are associated with other phenotypes, for example, cystic fibrosis and sudden infant death syndrome (SIDS).`],
    optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The phenotype is consistent with Tay-Sachs disease, an autosomal recessive disorder caused by mutations in the gene encoding the lysosomal enzyme hexosaminidase A.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 22-year-old woman delivers an apparently healthy female infant after an uncomplicated pregnancy. By 4 years of age, the girl has progressive, severe neurologic deterioration. Physical examination shows marked hepatosplenomegaly. A bone marrow biopsy specimen shows numerous foamy, vacuolated macrophages. An assay for glucocerebrosidase shows normal activity. Measuring the level of which of the following enzymes is most likely to aid in the diagnosis of this condition?`,
        q2: ``,
        q3: [],
        option: [` α1-Antitrypsin`, ` Glucose-6-phosphatase`,`Sphingomyelinase`,` HMG CoA reductase`,`Lysyl oxidase`],
    optionFeedback: [`α1-Antitrypsin deficiency is associated with emphysema and liver disease, neither of which are seen in this patient.`,`Glucose-6-phosphatase deficiency causes von Gierke disease, a glycogen storage disease that is not associated with neurologic degeneration.`,` The phenotype is consistent with Niemann-Pick disease, an autosomal recessive lysosomal storage disease caused by inherited sphingomyelinase deficiency. The clinical history would also be consistent with type II Gaucher disease, but the normal glucocerebrosidase activity excludes this diagnosis. `,`HMG-CoA reductase deficiency causes hyperlipidemia and accelerated atherosclerosis.`,`Lysyl oxidase deficiency causes defects in collagen maturation and joint and bone abnormalities.`],
    optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The phenotype is consistent with Niemann-Pick disease, an autosomal recessive lysosomal storage disease caused by inherited sphingomyelinase deficiency. The clinical history would also be consistent with type II Gaucher disease, but the normal glucocerebrosidase activity excludes this diagnosis. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 10-year-old boy presents with cough and fever. Upon admission, he is found to have pneumonia. On physical examination, there is hepatosplenomegaly. No external anomalies are present. Laboratory findings include anemia and leukopenia. A bone marrow biopsy is performed, and high magnification of the sample shows the findings depicted in the figure. Enzyme replacement therapy with which of the following is most likely to be beneficial?`,
        q2: `<img src="../images/f006-q008-9780323640251.png"/>`,
        q3: [],
        option: [` Lysosomal glucosidase`, `Glucocerebrosidase`,`Glucose-6-phosphatase`,`Hexosaminidase A`,` Lysyl hydroxylase`],
    optionFeedback: [`Lysosomal glucosidase deficiency causes Pompe disease, a glycogen storage disorder that leads to cardiac dysfunction and death early in life.`,` The phenotype is consistent with Gaucher disease, which is caused by deficiency of the lysosomal enzyme glucocerebrosidase. This leads to the accumulation of macrophages, particularly in the bone marrow and the spleen, that are stuffed with swollen lysosomes, producing a cytoplasmic appearance that looks like wrinkled tissue paper. `,`Glucose-6-phosphatase deficiency causes a different form of glycogen storage disease (von Gierke disease) that is associated with hypoglycemia and other metabolic abnormalities.`,`Hexosaminidase A deficiency causes Tay-Sachs disease, a generally fatal disorder affecting the central nervous system.`,`Lysyl hydroxylase deficiency causes a form of Ehlers-Danlos syndrome, associated with joint and skin hyperdistensibility and sometimes blood vessel fragility.`],
    optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The phenotype is consistent with Gaucher disease, which is caused by deficiency of the lysosomal enzyme glucocerebrosidase. This leads to the accumulation of macrophages, particularly in the bone marrow and the spleen, that are stuffed with swollen lysosomes, producing a cytoplasmic appearance that looks like wrinkled tissue paper. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 2-year-old child has failure to thrive since infancy. Physical examination shows hepatomegaly. Laboratory studies show a blood glucose level of 31 mg/dL. A liver biopsy specimen shows cells filled with clear vacuoles that stain positive for glycogen. Which of the following conditions is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [` Hurler syndrome`, ` McArdle disease`,`Pompe disease`,` Tay-Sachs disease`,` von Gierke disease`],
    optionFeedback: [`Hurler disease is a lysosomal storage disorder associated with accumulation of mucopolysaccharides in lysosomes associated with corneal clouding, coronary arterial and valvular deposits and death in childhood.`,`McArdle disease is also a glycogen storage disorder, but it preferentially affects the skeletal muscles. `,`Pompe disease is also a glycogen storage disorder, but it preferentially affects the heart. `,`Tay-Sachs disease is a lysosomal storage disorder associated with accumulation of sphingolipids in lysosomes and a clinical phenotype dominated by central nervous system abnormalities. `,` Hepatomegaly and low glucose levels are consistent with von Gierke disease, which is caused by a deficiency of glucose-6-phosphatase, an enzyme required for the breakdown of glycogen. As a result, PAS-positive glycogen accumulates in hepatocytes. Hypoglycemia occurs because of failure to mobilize glucose. `],
    optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-Hepatomegaly and low glucose levels are consistent with von Gierke disease, which is caused by a deficiency of glucose-6-phosphatase, an enzyme required for the breakdown of glycogen. As a result, PAS-positive glycogen accumulates in hepatocytes. Hypoglycemia occurs because of failure to mobilize glucose `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 25-year-old woman stops going to her aerobic exercise class because of severe muscle cramps that have occurred during every session for the past 2 months. Four hours after each session, she notices that her urine is a brown color. On physical examination, she has normal muscle development and strength. An inherited defect in which of the following substances is most likely to explain her findings?`,
        q2: ``,
        q3: [],
        option: [` Dystrophin`, `Fibrillin-1`,` Glucose-6-phosphatase`,`Lysosomal glucosidase deficiency`,` Muscle phosphorylase`],
    optionFeedback: [`Defects in dystrophin cause Duchenne and Becker muscular dystrophies. There is muscle weakness but not cramps after exercise `,`Defects in fibrillin-1 are associated with Marfan syndrome and cause abnormalities in the skeleton, the eye, and the cardiovascular system.`,`Defects in glucose-6-phosphatase are associated with von Gierke disease, a different glycogen storage disorder affecting the breakdown of glycogen, leading to its accumulation in the liver and hypoglycemia.`,`Defects in lysosomal glucosidase deficiency are associated with Pompe disease, a different glycogen storage disorder that leads to cardiac dysfunction and death early in life.`,` The clinical presentation is consistent with McArdle disease, a glycogen storage disorder caused by a deficiency in muscle phosphorylase, which is required to break down glycogen. In its absence, exercise may lead to rhabdomyolysis and associated myoglobinuria (myoglobin can produce dark-colored urine and renal failure).  `],
    optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The clinical presentation is consistent with McArdle disease, a glycogen storage disorder caused by a deficiency in muscle phosphorylase, which is required to break down glycogen. In its absence, exercise may lead to rhabdomyolysis and associated myoglobinuria (myoglobin can produce dark-colored urine and renal failure). `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 4-month-old male infant has failure to thrive and abdominal enlargement. On physical examination, the infant has marked muscle weakness and hepatosplenomegaly. A chest radiograph shows marked cardiomegaly. He dies of congestive heart failure at age 19 months. The microscopic appearance of myocardial fibers at autopsy is shown in the figure. A deficiency of which of the following enzymes is most likely to be present in this infant?<img src="../images/f006-q011-9780323640251.png" alt="" data-uuid="3d6a61a1bde04934b367b90e428715f0"/>`,
        q2: ``,
        q3: [],
        option: [` Glucocerebrosidase`, `Glucose-6-phosphatase`,`Hexosaminidase A`,`Lysosomal glucosidase`,`Sphingomyelinase`],
    optionFeedback: [`Glucocerebrosidase deficiency causes Gaucher disease, a disease characterized by the accumulation of macrophages, particularly in the bone marrow and the spleen, that are stuffed with swollen lysosomes, producing a cytoplasmic appearance that looks like wrinkled tissue paper.`,`Glucose-6-phosphatase deficiency causes von Gierke disease, a glycogen storage disorder affecting the breakdown of glycogen, leading to its accumulation in the liver and hypoglycemia.`,`Hexosaminidase A deficiency causes Tay-Sachs disease, a lysosomal storage disorder associated with accumulation of sphingolipids in lysosomes and a clinical phenotype dominated by central nervous system abnormalities.`,` The phenotype is consistent with Pompe disease, which is caused by deficiency of lysosomal glucosidase, an enzyme that is required for glycogen breakdown in cardiomyocytes. `,`Sphingomyelinase deficiency causes Neimann-Pick disease. Although there is some overlap in the clinical presentation, the histologic findings of abundant glycogen (the clear spaces) are not seen in Niemann-Pick disease.`],   
               optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The phenotype is consistent with Pompe disease, which is caused by deficiency of lysosomal glucosidase, an enzyme that is required for glycogen breakdown in cardiomyocytes. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A healthy 20-year-old woman, G3, P2, Ab1, has previously given birth to a live-born infant and a stillborn infant, both with trisomy of one of the autosomes. Neither she nor her husband has any physical abnormalities. Which of the following karyotypic abnormalities is most likely to be present in this woman?`,
        q2: ``,
        q3: [],
        option: [`Deletion of q arm: del(22q)`, `Isochromosome: 46,X,i(Xq)`,`Paracentric inversion: inv(18)`,`Ring chromosome: r(13)`,`Robertsonian translocation: t(14;21)`],
    optionFeedback: [`This chromosomal aberration produces disease in carriers (i.e., Di George syndrome). `,`This chromosomal aberration results in partial monosomy of the X chromosome resulting in Turner syndrome.`,`This chromosomal aberration usually has no consequences for parent or offspring since there is minimal loss of chromosomal material.`,`This chromosomal aberration has a variable phenotype depending on amount of chromosome 13 loss. Patients may have facial dysmorphology, growth delay and severe intellectual disability.`,` The presence of a Robertsonian t(14;21) translocation in a parent greatly increases the risk of trisomy 21 in each offspring The extra chromosomal material is present as a translocation of the long arm of chromosome 21 to chromosome 14 or 22. Trisomy 21 is one of the few autosomal trisomies that is compatible with a live birth.  `],   
               optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The presence of a Robertsonian t(14;21) translocation in a parent greatly increases the risk of trisomy 21 in each offspring The extra chromosomal material is present as a translocation of the long arm of chromosome 21 to chromosome 14 or 22. Trisomy 21 is one of the few autosomal trisomies that is compatible with a live birth `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 6-year-old boy is found to have severe learning difficulties. His IQ is 50. On physical examination, he has oblique palpebral fissures with prominent epicanthal folds. A transverse crease is seen on the palm of each hand. On auscultation of the chest, a systolic murmur is detected. Which of the following diseases is he most likely to develop by age 20 years?`,
        q2: ``,
        q3: [],
        option: [` Acute leukemia`, `Acute myocardial infarction (MI)`,`Aortic dissection`,`Chronic renal failure`,` Hepatic cirrhosis`],
    optionFeedback: [` The phenotype of this boy is consistent with Down syndrome (trisomy 21), a disorder that places carriers at increased risk of both acute myeloid leukemia (AML) and acute lymphoblastic leukemia (ALL) during childhood and adolescence. These patients are also susceptible as adults to early onset Alzheimer disease.`,`Acute MI is associated with familial hypercholesterolemia.`,`Aortic dissection is associated with Marfan syndrome.`,`Chronic renal failure is associated with a variety of inherited and acquired disorders other than Down syndrome, such as polycystic kidney disease and diabetes, respectively.`,`Hepatic cirrhosis is associated with a variety of inherited and acquired disorders other than Down syndrome, such as hemochromatosis and hepatitis C infection, respectively.`],   
           optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The phenotype of this boy is consistent with Down syndrome (trisomy 21), a disorder that places carriers at increased risk of both acute myeloid leukemia (AML) and acute lymphoblastic leukemia (ALL) during childhood and adolescence. These patients are also susceptible as adults to early onset Alzheimer disease `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 12-year-old boy has had a cough and earache for the past 2 days. He has a history of recurrent infections, including otitis media, diarrhea, and pneumonia. Physical examination shows a cleft palate and a murmur suggestive of congenital heart disease. A thoracic computed tomography scan shows a small thymus. Results of laboratory studies suggest mild hypoparathyroidism. Which of the following tests is most likely to be helpful in establishing the diagnosis?`,
        q2: ``,
        q3: [],
        option: [` Adenosine deaminase assay in lymphocytes`, `HIV-1 RNA level`,` FISH analysis with a probe for chromosome 22q11.2`,` Assay for parathyroid hormone-related protein in the serum`,` PCR analysis for trinucleotide repeats on the X chromosome`],
    optionFeedback: [`Adenosine deaminase deficiency is associated with severe combined immunodeficiency and does not cause developmental abnormalities.`,`HIV-1 infection leads to T cell immunodeficiency and does not cause developmental abnormalities.`,` The phenotype of this boy is consistent with deletion 22 syndrome, caused by deletion of 22q11.2. It is variably associated with developmental abnormalities of the heart, face, palate, thymus, and parathyroid glands, depending on the precise size and location of the deletion. Those in whom T cell deficiency and hypocalcemia dominate are said to have DiGeorge syndrome, whereas those in whom facial dysmorphology and cardiac defects dominate are said to have velocardiofacial syndrome.  `,`Assays for parathyroid hormone-related protein (PTHrP) are most relevant in patients suspected of having paraneoplastic hypercalcemia (Chapter 5).`,`PCR analysis of trinucleotide repeats is used to diagnose fragile X syndrome, a disease characterized by intellectual disability, a long face with a large mandible, large, everted ears, and large testicles (macro-orchidism).`],
    optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The phenotype of this boy is consistent with deletion 22 syndrome, caused by deletion of 22q11.2. It is variably associated with developmental abnormalities of the heart, face, palate, thymus, and parathyroid glands, depending on the precise size and location of the deletion. Those in whom T cell deficiency and hypocalcemia dominate are said to have DiGeorge syndrome, whereas those in whom facial dysmorphology and cardiac defects dominate are said to have velocardiofacial syndrome.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 27-year-old man and his 24-year-old wife have been trying to conceive a child for 6 years. Physical examination of the man shows bilateral gynecomastia, reduced testicular size, reduced body hair, and increased length between the soles of his feet and the pubic bone. A semen analysis indicates oligospermia. Laboratory studies show increased follicle-stimulating hormone level and slightly decreased testosterone level. Which of the following karyotypes is this man most likely to have?`,
        q2: ``,
        q3: [],
        option: [`46,X,i(Xq)`, `47,XYY`,` 47,XXY`,`46,XX/47,XX,+21`,`46,XY,del(22q11)`],
    optionFeedback: [`46,X,i(Xq) would be associated with female sex and Turner syndrome phenotype.`,`47,XYY would be associated with male sex and an essentially normal phenotype.`,` The phenotype of this man is consistent with Klinefelter syndrome, which is caused in phenotypic males by an extra copy of the X chromosome.  `,`46,XX/47,XX,+21; this person is a mosaic with two populations of cells, one of which carries an extra chromosome 21. This karyotype would be associated with female sex and, depending on the ratio of the two cell populations, various features of Down syndrome.`,`46,XY,del(22q11) would be associated with deletion 22 syndrome.`],
    optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The phenotype of this man is consistent with Klinefelter syndrome, which is caused in phenotypic males by an extra copy of the X chromosome`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 25-year-old woman with amenorrhea has never had menarche. On physical examination, she is 145 cm (4 ft 9 in) tall. There are extra folds of skin at her neck and she has a broad chest, and widely spaced nipples. Strong pulses are palpable in the upper extremities, but there are only weak pulses in the lower extremities. On abdominal magnetic resonance imaging, her ovaries are small, elongated, and tubular. Which of the following karyotypes is she most likely to have?`,
        q2: ``,
        q3: [],
        option: [`45,X/46,XX`, `46,X,X(fra)`,`47,XXY`,` 47,XXX`,` 47,XX,+21`],
    optionFeedback: [` The phenotype in this woman is consistent with Turner syndrome, which is caused by partial or complete monosomy for the X chromosome. Based on the karyotype, this individual is a mosaic, a condition that often is associated with less severe phenotypes, depending on the fraction of normal (46,XX) and 45,X cells in the affected individual. `,`46,X,X(fra) is associated with fragile X syndrome, a trinucleotide repeat disorder which is an important cause of severe intellectual disability.`,`47,XXY is associated with Klinefelter syndrome characterized by male hypogonadism.`,`47,XXX is associated with mild or no abnormalities and normal or increased height.`,`47,XX,+21 is associated with Down syndrome.`],
    optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The phenotype in this woman is consistent with Turner syndrome, which is caused by partial or complete monosomy for the X chromosome. Based on the karyotype, this individual is a mosaic, a condition that often is associated with less severe phenotypes, depending on the fraction of normal (46,XX) and 45,X cells in the affected individual. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `Intellectual disability has affected several generations of a family, and most of the affected individuals have been males. The severity has increased with each passing generation. Genetic testing is performed, and about 20% of the males who have the genetic abnormality are unaffected. Which of the following types of mutations is most likely involved in the pathogenesis of this disorder?`,
        q2: ``,
        q3: [],
        option: [`Frameshift mutation`, `Missense mutation`,`Mitochondrial DNA mutation`,` Nonsense mutation`,`Trinucleotide repeat mutation`],
    optionFeedback: [`This type of mutation does not demonstrate anticipation across generation and is therefore inconsistent with the clinical scenario.  `,`This type of mutation does not demonstrate anticipation across generation and is therefore inconsistent with the clinical scenario.  `,`This type of mutation does not demonstrate anticipation across generation and is therefore inconsistent with the clinical scenario.  `,`This type of mutation does not demonstrate anticipation across generation and is therefore inconsistent with the clinical scenario.  `,` The phenotype and pattern of inheritance is consistent with fragile X syndrome, which is caused by a trinucleotide repeat mutation in the X-linked fragile X mental retardation gene (FMR1). Like other trinucleotide repeat mutation disorders, fragile X syndrome demonstrates anticipation, in which the disorder tends to become more severe in each successive generation due to further expansion of the size of the trinucleotide repeat mutation. Enlargement of the size of the mutation occurs during gametogenesis only in females, and the penetrance of the disorder is higher in males than females, who may still be affected due to the phenomenon of X inactivation. `],
    optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The phenotype and pattern of inheritance is consistent with fragile X syndrome, which is caused by a trinucleotide repeat mutation in the X-linked fragile X mental retardation gene (FMR1). Like other trinucleotide repeat mutation disorders, fragile X syndrome demonstrates anticipation, in which the disorder tends to become more severe in each successive generation due to further expansion of the size of the trinucleotide repeat mutation. Enlargement of the size of the mutation occurs during gametogenesis only in females, and the penetrance of the disorder is higher in males than females, who may still be affected due to the phenomenon of X inactivation.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 3-year-old boy has had progressive developmental delay, ataxia, seizures, and inappropriate laughter since infancy. The child has a normal karyotype of 46,XY, but DNA analysis shows that he has inherited both copies of chromosome 15 from his father. These findings are most likely caused by which of the following genetic mechanisms?`,
        q2: ``,
        q3: [],
        option: [` Genomic imprinting`, ` Maternal inheritance`,` Mutation of mitochondrial DNA`,`Trinucleotide repeat expansion`,` Robertsonian translocation`],
    optionFeedback: [` The phenotype and the described paternal uniparental disomy (inheriting both chromosome 15 copies from the father) are consistent with Angelman syndrome. During gametogenesis in males, a small region of chromosome 15 containing a gene called UBE3A is silenced by genomic imprinting (DNA methylation); as a result, UBE3A expression depends on the maternal copy of the gene. With paternal uniparental disomy, UBE3A expression fails completely, producing Angelman syndrome.  `,`Maternal inheritance pattern is associated with mitochondrial mutations.`,`Maternal inheritance pattern is associated with mitochondrial mutations.`,`Trinucleotide repeat expansions are associated with anticipation, not genomic imprinting. `,`Robertsonian translocations are associated with recurrent fetal loss and often recurrent Down syndrome.`],
    optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The phenotype and the described paternal uniparental disomy (inheriting both chromosome 15 copies from the father) are consistent with Angelman syndrome. During gametogenesis in males, a small region of chromosome 15 containing a gene called UBE3A is silenced by genomic imprinting (DNA methylation); as a result, UBE3A expression depends on the maternal copy of the gene. With paternal uniparental disomy, UBE3A expression fails completely, producing Angelman syndrome.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 32-year-old woman has had three pregnancies, all ending in stillbirths in the first trimester. On physical examination, she and the father of all her pregnancies have no significant findinss. Which of the following laboratory tests is most appropriate to perform on both parents for elucidating potential causes for recurrent fetal loss?`,
        q2: ``,
        q3: [],
        option: [`Genome-wide association study`, ` Fluorescence in situ hybridization`,`Karyotyping`,` PCR analysis`,` Sequencing of mitochondrial DNA`],
    optionFeedback: [`Genome-wide association studies have been useful for identifying genetic variants with weak associations in diseases with a genetic component.`,`Fluorescence in situ hybridization can be useful in identifying specific, suspected chromosomal aberrations, but is not a good screening test.`,` In this scenario, it is likely that one of the two parents carries some sort of balanced chromosomal aberration, leading to the production of aneuploid conceptuses that are incompatible with full-term development. Karyotyping should be performed on both parents. `,`PCR analysis can be useful for identifying specific suspected genetic aberrations, but is not a good screening test.`,`Mitochondrial defects are not a cause of recurrent fetal loss.`],
    optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- In this scenario, it is likely that one of the two parents carries some sort of balanced chromosomal aberration, leading to the production of aneuploid conceptuses that are incompatible with full-term development. Karyotyping should be performed on both parents. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An 11-year-old boy had increasing episodes of diarrhea for the past 3 years. The child’s stools are bulky and foul-smelling. He also has a history of multiple respiratory tract infections. On auscultation, diffuse crackles are heard over both lungs. Laboratory testing shows stool fat of greater than 10 g/day (normal &lt;7g/day). Sputum cultures have grown Pseudomonas aeruginosa and Burkholderia cepacia. Which of the following underlying metabolic defects is most likely responsible for this disease?`,
        q2: ``,
        q3: [],
        option: [`Impaired activation of complement proteins`, `Impaired synthesis of adenosine deaminase`,` Impaired epithelial cell transport of chloride ions`,`Impaired synthesis of phenylalanine hydroxylase`,`Impaired synthesis of LDL receptors`],
    optionFeedback: [`Impaired activation of complement proteins is associated with increased susceptibility to Neisseria infections but not fat malabsorption.`,`Defects in adenosine deaminase are associated with severe combined immunodeficiency.`,` The phenotype is consistent with cystic fibrosis, an autosomal recessive disorder caused by a defect in CFTR, a transmembrane transporter with complex effects on ion transport. In sweat glands, the net effect of this defect is production of sweat that is abnormally salty. In pulmonary epithelium (specifically in a specialized cell type called the ionocyte), the pancreas, and the epididymis, the net effect of CFTR deficiency is the production of secretions that are dehydrated and viscous, leading to obstruction and chronic bacterial infection of the lung , exocrine pancreatic insufficiency, and azoospermia. `,`Impaired synthesis of phenylalanine hydroxylase is associated with phenylketonuria.`,`Impaired synthesis of LDL receptors is associated with familial hypercholesterolemia.`],
    optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The phenotype is consistent with cystic fibrosis, an autosomal recessive disorder caused by a defect in CFTR, a transmembrane transporter with complex effects on ion transport. In sweat glands, the net effect of this defect is production of sweat that is abnormally salty. In pulmonary epithelium (specifically in a specialized cell type called the ionocyte), the pancreas, and the epididymis, the net effect of CFTR deficiency is the production of secretions that are dehydrated and viscous, leading to obstruction and chronic bacterial infection of the lung , exocrine pancreatic insufficiency, and azoospermia. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 15-year-old girl has had a fever and productive cough for the past 4 days. She was born at term but developed abdominal distention in the first week of life from meconium ileus. Subsequently, she developed diarrhea and fat malabsorption. She has had frequent bouts of pneumonia with cough productive of thick mucoid sputum for 8 years. Which of the following is the most important (primary) underlying cause of this disease?`,
        q2: ``,
        q3: [],
        option: [` Abnormal folding of CFTR protein`, ` Mutation of gene for TGFβ receptor`,` Genetic lack of surfactant protein`,`Poor absorption of vitamin D`,` Genetic defect in ciliary function`],
    optionFeedback: [` The phenotype is consistent with cystic fibrosis. One of the most common mutations seen in this disease is a single codon deletion in CFTR (del508) that leads to expression of a protein that misfolds and fails to function. This is significant because drugs have been developed that improve the proper folding and function of this mutant, an approach that may be an effective treatment for this subtype of cystic fibrosis.<br/><br/>Incorrect answers:`,` Marfan syndrome is caused by a mutation in the fibrillin gene, which in turn gives rise to excessive TGF-beta signaling. Mutations of the TGF-beta receptor can also increase TGF-beta signaling and give rise to a less common variant of Marfan syndrome.`,` Surfactant protein is required for the opening up of lung alveoli soon after birth, allowing normal gaseous exchange. Genetic lack of surfactant protein would be associated with respiratory distress at birth.`,`Poor absorption of vitamin D would be associated with rickets.`,`Genetic defect in ciliary function would be associated with increased risk of pulmonary infection, infertility in males, and sometimes situs inversus.`],
            optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The phenotype is consistent with cystic fibrosis. One of the most common mutations seen in this disease is a single codon deletion in CFTR (del508) that leads to expression of a protein that misfolds and fails to function. This is significant because drugs have been developed that improve the proper folding and function of this mutant, an approach that may be an effective treatment for this subtype of cystic fibrosis`,
        state: `notAnswered`,
        userAnswered: [],
    }
    

   ];






