var quiz = [
    {
        q: `A 5-year-old boy who presents with history of recurrent infections with gram-positive bacteria such as <i>Staphylococcus aureus</i> is found to have a genetic disorder that leads to a deficiency of   β2-integrins. Which of the following abnormalities of neutrophil function is most likely responsible for his clinical symptoms?`,
        q2: ``,
        q3: [],
        option: [`Normal rolling but weak adhesion to endothelial cell`, `Failure to migrate to the site of infection after leaving the vasculature`, `Reduced respiratory burst after phagocytosis of bacteria`,`Diminished phagocytosis of bacteria opsonized with immunoglobin G`,`Failure to generate hydroxyl-halide radicals (HOCI)`],
        optionFeedback: [`Integrins are involved in firm attachment of neutrophils to endothelium at the site of infection or tissue injury, a critical step in recruitment of leukocytes from the circulation into inflamed tissues.`,`Migration of leukocytes after they leave blood vessels is mediated mainly by chemokines. Integrins do contribute to adhesion of cells to extracellular matrix, but extravascular migration is not directly impacted by deficiency of integrins.`,`This reaction requires NADPH oxidase and does not involve integrins. It occurs after activated leukocytes have migrated to the site of infection.`,`This reaction is the consequence of leukocyte activation, and does not involve integrins. It occurs after the cells have migrated to the site of infection.`,`This reaction requires the enzyme myeloperoxidase and does not involve integrins. It occurs after activated leukocytes have migrated to the site of infection.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Integrins are involved in firm attachment of neutrophils to endothelium at the site of infection or tissue injury, a critical step in recruitment of leukocytes from the circulation into inflamed tissues.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 6-year-old boy presents with a history of recurrent infections with pyogenic bacteria (e.g., <i>Staphylococcus aureus, Streptococcus pneumoniae</i>). After infections, there is an expected increase in the total white blood cell (WBC) count, of which 90&#37; are neutrophils. However, histologic examination of tissues reveals very few neutrophils. An analysis of patient’s neutrophil function by in vivo live cell imaging of venules shows a defect in rolling. A defect or deficiency affecting which of the following molecules is likely to be responsible for the increased susceptibility to infection in this patient?`,
        q2: ``,
        q3: [],
        option: [`Selectins`, `Integrins`,` Leukotriene B<sub>4</sub> `,` NADPH oxidase`,`Defensins`],
        optionFeedback: [`Selectins and their ligands are expressed on leukocytes and activated endothelial cells and mediate low-affinity interactions that form and are broken by the shear force of flowing blood. Because of these interactions, the leukocytes roll along the endothelium at sites of inflammation. This is the first step in the passage of leukocytes from the circulation into tissues, and it slows down the flowing leukocytes, giving them the chance to initiate the second step of firm attachment (which is mediated by integrins).`,`Integrins are involved in firm adhesion of leukocytes to endothelium.`,`Leukotriene B<sub>4</sub> is a chemotactic agent. `,`NADPH oxidase catalyzes the generation of reactive oxygen species, part of the respiratory burst. `,`Defensins are anti-microbial peptides stored in leukocyte granules.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale:-  Selectins and their ligands are expressed on leukocytes and activated endothelial cells and mediate low-affinity interactions that form and are broken by the shear force of flowing blood. Because of these interactions, the leukocytes roll along the endothelium at sites of inflammation. This is the first step in the passage of leukocytes from the circulation into tissues, and it slows down the flowing leukocytes, giving them the chance to initiate the second step of firm attachment (which is mediated by integrins) .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 15-year-old boy presents with recurrent (but not life-threatening) bacterial and fungal infections. Laboratory tests show normal numbers of white blood cells and, during episodes of infection, there is an appropriate increase in circulating white blood cells (including neutrophils). However, staining of neutrophils for myeloperoxidase is very weak to absent. Which of the following is the most likely cause of increased susceptibility to infections in this patient?`,
        q2: ``,
        q3: [],
        option: [` Defective neutrophil degranulation`, ` Defective production of prostaglandins`,`An inability to produce hydroxyl-halide radicals`,`Decreased oxygen consumption after phagocytosis`,`An inability to produce hydrogen peroxide`],
        optionFeedback: [`Degranulation is triggered by calcium influx and cytoskeletal activation in response to stimuli that activate neutrophils.`,`Prostaglandins are produced by phospholipase A2-mediated digestion of membrane phospholipids to generate arachidonic acid, which is then converted to prostaglandins by the action of cyclooxygenase. `,`Upon activation, neutrophils produce reactive oxygen species such as superoxide in granules, which are converted to the more potent microbicidal halides by the action of the granule enzyme myeloperoxidase. These halides (and other free radicals) destroy phagocytosed microbes.  `,`Oxygen consumption is increased in activated neutrophils, not decreased. `,`Hydrogen peroxide is also derived from the reactive oxygen species superoxide, but this process does not require myeloperoxidase.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Upon activation, neutrophils produce reactive oxygen species such as superoxide in granules, which are converted to the more potent microbicidal halides by the action of the granule enzyme myeloperoxidase. These halides (and other free radicals) destroy phagocytosed microbes. .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `Two weeks after an acute myocardial infarction, the necrotic myocardium has largely been replaced by capillaries, fibroblasts, and collagen. A variety of inflammatory cells are present. Which of the following inflammatory cell types in such a lesion plays an important part at this point in the healing process?`,
        q2: ``,
        q3: [],
        option: [` Macrophages`, `Plasma cells`,`Neutrophils`,`Eosinophils`,`Epithelioid cells`],
        optionFeedback: [`Macrophages remove noxious agents such as microbes and the debris of damaged cells. They also produce growth factors that promote angiogenesis and deposition of collagen, the two key processes in tissue repair (healing). Different subsets of macrophages may be primarily involved in destroying microbes, clearing damaged tissues, and promoting repair.`,`Plasma cells are antibody-secreting cells that play important roles in defense against microbes but not in tissue repair.`,`Neutrophils are important for destroying ingested microbes and the removal of dead cells, but are only minor sources of the growth factors that contribute to tissue repair.`,`The physiologic function of eosinophils is mainly to destroy helminthic parasites. They also contribute to tissue injury in allergic reactions. `,`Epithelioid cells are a type of activated macrophages with abundant eosinophilic cytoplasm. They are found in granulomas, in which macrophage activation is a prominent process.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Macrophages remove noxious agents such as microbes and the debris of damaged cells. They also produce growth factors that promote angiogenesis and deposition of collagen, the two key processes in tissue repair (healing). Different subsets of macrophages may be primarily involved in destroying microbes, clearing damaged tissues, and promoting repair.   .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 32-year-old woman has a one-month history of chronic cough with fever. A chest radiograph shows many small, ill-defined, nodular opacities in all lung fields. A transbronchial biopsy reveals circumscribed collections of epithelioid cells as well as lymphocytes and plasma cells. This patient is most likely infected with which of the following?`,
        q2: ``,
        q3: [],
        option: [`Staphylococcus aureus`, `Plasmodium falciparum`,`Candida albicans`,`Mycobacterium tuberculosis`,`Klebsiella pneumoniae`],
        optionFeedback: [`S.aureus elicits acute inflammatory reactions that are rich in neutrophils and are usually short-lived.`,`The malarial parasite P. falciparum causes a form of malaria in which central nervous system symptoms may be prominent, caused mainly by occlusion of small blood vessels by parasitized red cells and other host cells. T cells and macrophages are the primary cells involved in the inflammatory response to malaria.`,`The fungus C. albicans causes mucocutaneous acute, and sometimes chronic, inflammation in immunocompetent individuals. In individuals with neutrophil defects, it may cause disseminated infections.`,`Collections of epithelioid cells (activated macrophages) with other immune cells are typical of granulomatous inflammation. The microbe that most often induces this type of inflammatory reaction is M. tuberculosis.`,`K. pneumoniae elicits acute inflammation without the formation of granulomas.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-Collections of epithelioid cells (activated macrophages) with other immune cells are typical of granulomatous inflammation. The microbe that most often induces this type of inflammatory reaction is M. tuberculosis. .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 43-year-old man has a two-month history of a cough with fever. A chest radiograph reveals nodular densities, some with calcification, located mainly in the upper lobes. The microscopic appearance of a lung biopsy is shown. Which of the following mediators is most important in the pathogenesis of this lesion?`,
        q2: `<img src="../images/f002-q006-9780323640251.png"/>`,
        q3: [],
        option: [`Complement C5a`, `Interferon-γ`,`Bradykinin`,` Nitric oxide`,`Prostaglandin`],
        optionFeedback: [`The complement system is involved in innate immune reactions and in antibody- and immune complex–mediated reactions, not in T cell– and macrophage-dependent granulomatous inflammation.`,`This lesion is typical of granulomatous inflammation, a type of chronic inflammation that is dominated by activated macrophages. In most cases, the macrophages are activated by CD4+ T cells, which produce the cytokine interferon-γ, the most potent macrophage-activating cytokine.`,`Bradykinin is a peptide that causes vascular dilation.`,`Nitric oxide is a microbicidal substance produced by macrophages that contributes to the destruction of phagocytosed microbes. It is also a vasodilator.`,`Prostaglandins are products of arachidonic acid that have numerous actions on blood vessels and leukocytes in acute inflammation but are not potent macrophage activators.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-This lesion is typical of granulomatous inflammation, a type of chronic inflammation that is dominated by activated macrophages. In most cases, the macrophages are activated by CD4+ T cells, which produce the cytokine interferon-γ, the most potent macrophage-activating cytokine.   .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 12-month-old boy with a six-month history of repeated infections presents with pneumonia and elevated numbers of neutrophils in the peripheral blood. Chest X-ray shows a lung abscess, and aspiration of the abscess shows neutrophils. Laboratory studies show that his neutrophils phagocytose and kill bacteria normally in the presence of normal human serum, but not the patient’s serum. The neutrophils migrate normally in a chemotaxis assay. Serum complement levels are normal. Which of the following is the most likely cause for the patient’s increased susceptibility to infection?`,
        q2: ``,
        q3: [],
        option: [` Deficiency of integrins`, ` Neutrophil microtubular defect`,`Immunoglobulin deficiency`,`Defective generation of neutrophil hydrogen peroxide`,`Deficiency of selectins`],
        optionFeedback: [`Integrins are involved in leukocyte migration into tissues, so their deficiency would result in reduced numbers of neutrophils in the abscess.`,`Microtubular defects interfere with degranulation, but the normal neutrophil function in the presence of normal serum rules out a cell-intrinsic defect.`,`The fact that neutrophils are elevated in the blood and present in the tissues rules out a migration defect, as does the normal chemotaxis assay. The neutrophils can destroy bacteria in the presence of normal serum but not in the patient’s serum, suggesting that there is a deficiency of some circulating factor involved in microbial killing. The major candidates are antibodies and complement proteins, and complement levels are normal, pointing to antibodies as the problem. In this case, in the absence of antibodies, the microbes are not adequately opsonized, and therefore not properly phagocytosed and destroyed intracellularly.`,`If neutrophils had a defect in the generation of oxygen-derived free radicals, they would not be able to kill organisms even in the presence of normal serum.`,`Selectins are involved in leukocyte migration into tissues, so their deficiency would result in reduced numbers of neutrophils in the abscess.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The fact that neutrophils are elevated in the blood and present in the tissues rules out a migration defect, as does the normal chemotaxis assay. The neutrophils can destroy bacteria in the presence of normal serum but not in the patient’s serum, suggesting that there is a deficiency of some circulating factor involved in microbial killing. The major candidates are antibodies and complement proteins, and complement levels are normal, pointing to antibodies as the problem. In this case, in the absence of antibodies, the microbes are not adequately opsonized, and therefore not properly phagocytosed and destroyed intracellularly.   .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 35-year-old man has a three-month history of mid-epigastric pain. An upper gastrointestinal endoscopy shows a shallow ulceration of the gastric antrum. Microscopic examination of a biopsy from the ulcer base shows an increased number of capillaries and a mononuclear cell infiltrate composed of lymphocytes, plasma cells, and macrophages. This histologic appearance is indicative of which of the following forms of inflammation?`,
        q2: ``,
        q3: [],
        option: [`Acute inflammation`, ` Chronic inflammation`,` Fibrinous inflammation`,`Granulomatous inflammation`,`Serous inflammation`],
        optionFeedback: [`The dominant cells in acute inflammation are neutrophils.`,`Mononuclear cell infiltrates are typical of chronic inflammation. Angiogenesis is often prominent, especially as part of the repair process.`,`Fibrinous inflammation is characterized by layers of fibrin, and is often seen on serosal surfaces (pleura, pericardium).`,`Granulomatous inflammation is also a form of chronic inflammation, but its hallmark is the presence of activated macrophages (epithelioid cells) that form clusters called granulomas. `,`Serous inflammation is a collection of clear fluid, often representing a transudate, with variable and usually low numbers of inflammatory cells.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- Mononuclear cell infiltrates are typical of chronic inflammation. Angiogenesis is often prominent, especially as part of the repair process.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 53-year-old woman has had a two-day history of high fever and cough productive of yellowish sputum. Her vital signs include temperature of 39.5° C, pulse 103 bpm, respirations 25 per min, and blood pressure 100/60 mm Hg. On auscultation of the chest, crackles are audible in both lung bases. A chest radiograph shows bilateral, patchy pulmonary infiltrates. The microscopic appearance of her lung is shown in the figure. Which of the following inflammatory cell types is most likely to be seen in greatly increased numbers in her sputum specimen?`,
        q2: `<img src="../images/f002-q009-9780323640251.png"/>`,
        q3: [],
        option: [`Langhans giant cells`, `Macrophages`,`Mast cells`,`Neutrophils`,`T lymphocytes`],
        optionFeedback: [`Langhans giant cells are large multinucleate cells with peripheral nuclei. They are derived by fusion of activated macrophages and are characteristic of tuberculous granulomas.`,`Macrophages are abundant in chronic inflammatory reactions, not acute inflammation.`,`Mast cells are not usually seen in pneumonia. They may be abundant in some chronic allergic reactions involving the lung, such as asthma.`,`The clinical history and X-ray are typical of acute pneumonia, and the pathology shows vascular congestion and alveoli packed with neutrophils. These neutrophils would be shed in the sputum.`,`T lymphocytes are abundant in chronic inflammatory reactions.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The clinical history and X-ray are typical of acute pneumonia, and the pathology shows vascular congestion and alveoli packed with neutrophils. These neutrophils would be shed in the sputum.    .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 72-year-old man with severe emphysema has had worsening right ventricular failure for the past 5 years. For the past 4 days, he has had fever and increasing dyspnea. A chest radiograph shows patchy areas of consolidation and an accumulation of fluid in the pleural spaces. Fluid obtained by thoracentesis appears yellowish-green, has a specific gravity of 1.030 (normal &#126;1.00), and contains degenerating neutrophils.  Which of the following is the most likely cause of this fluid accumulation?`,
        q2: ``,
        q3: [],
        option: [`Decreased intravascular colloid osmotic pressure`, `Increased intravascular hydrostatic pressure`,`Lymphatic obstruction`,`Increased renal sodium retention`,`Increased vascular permeability`],
        optionFeedback: [`Colloid osmotic pressure falls mainly because of decreased production of albumin (as in liver disease) or increased loss of albumin (as in kidney disease). Decreased colloid osmotic pressure leads to transudation of fluid and edema in multiple tissues.`,`Hydrostatic pressure of the blood increases in conditions of compromised venous return, as in congestive heart failure. The increased pressure also leads to transudation of plasma and edema formation. This could have happened in this patient if he had congestive heart failure not complicated by pneumonia.`,`Blocked lymphatic drainage, as may occur with metastasis of cancers to lymph nodes, may lead to lymphedema, usually comprised of a protein-poor, transudate-like fluid.`,`Reduced renal perfusion activates the renin-angiotensin system, leading to sodium retention and increased blood pressure and blood volume. This does not cause edema, by itself, but it often occurs as a maladaptive response in the setting of left-sided heart failure, in which fluid “overload” due to sodium retention may exacerbate pulmonary edema and pulmonary effusions. The effusions that are seen are transudates, however, unlike what is seen here.`,`The clinical history of fever and worsening pulmonary function and the X-ray are indicative of acute pneumonia. The pleural fluid has a high specific gravity, indicating leakage of plasma proteins, and contains neutrophils. These are typical of exudates, which result from increased vascular permeability (as in acute inflammation).`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The clinical history of fever and worsening pulmonary function and the X-ray are indicative of acute pneumonia. The pleural fluid has a high specific gravity, indicating leakage of plasma proteins, and contains neutrophils. These are typical of exudates, which result from increased vascular permeability (as in acute inflammation).   .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An 80-year-old man develops cough, fever with chills and rigors, and hypotension. Laboratory tests show neutrophilic leukocytosis, and blood cultures are positive for gram-negative bacteria. Despite intravenous antibiotics and supportive therapy, he dies a few days later. At autopsy, lesions similar to those illustrated in the kidneys are found in multiple organs. Microscopic examination shows liquefactive necrosis and accumulation of neutrophils. The movement of these neutrophils into the tissues is most likely to be mediated by which of the following substances?`,
        q2: `<img src="../images/f002-q012-9780323640251.png"/>`,
        q3: [],
        option: [`Bradykinin`, ` Chemokines`,`Complement C3a`,`Histamine`,`Prostaglandins`],
        optionFeedback: [`Bradykinin dilates vessels and increases vascular permeability but does not directly recruit leukocytes.`,`This patient has developed sepsis secondary to disseminated bacterial infection. The figure shows multiple renal abscesses. Histologically, these lesions would demonstrate liquefactive necrosis and neutrophils. In this setting, the major stimulus for leukocyte recruitment is the secretion of chemokines by leukocytes and other cells participating in the inflammatory response.  `,`C3a causes release of histamine from mast cells. It is not chemotactic. By contrast, C5a is chemotactic.`,`Histamine also dilates vessels and increases vascular permeability but is not a chemoattractant for leukocytes. `,`Different prostaglandins cause vasodilation or vasoconstriction but are not major chemoattractants for neutrophils; leukotrienes, the other major class of arachidonic acid-derived mediators, are potent chemotactic agents. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- This patient has developed sepsis secondary to disseminated bacterial infection. The figure shows multiple renal abscesses. Histologically, these lesions would demonstrate liquefactive necrosis and neutrophils. In this setting, the major stimulus for leukocyte recruitment is the secretion of chemokines by leukocytes and other cells participating in the inflammatory response.  .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `In working up the cause of recurrent infections in a 5-year-old boy, neutrophils collected from peripheral blood are analyzed for a “burst” of oxygen consumption following incubation with live bacteria. This respiratory burst is an essential step for which of the following events in an acute inflammatory response?`,
        q2: ``,
        q3: [],
        option: [`Attachment to endothelial cells`, ` Generation of microbicidal activity`,`Increased production in bone marrow`,` Opsonization of bacteria`,`Phagocytosis of bacteria`],
        optionFeedback: [`Leukocytes do attach to endothelial cells as a prelude to their migration through vessels to sites of inflammation, but this reaction is mediated mainly by cytokines, not by reactive oxygen species.`,`The respiratory burst is an NADPH-dependent oxidation reaction in phagolysosomes that leads to the production of reactive oxygen species (ROS), a type of free radical that destroys ingested microbes. ROS that are released into the extracellular environment also kill microbes outside the neutrophils. `,`Leukocyte production in the bone marrow increases during inflammation to meet the increased demand and replace cells that die after they enter inflammatory sites. This increased marrow output is mediated by cytokines that act as growth factors for hematopoietic progenitors, such as G-CSF (granulocyte colony-stimulating factor) and GM-CSF (granulocyte-macrophage colony-stimulating factor).`,`Bacteria are opsonized by antibodies, complement products (mainly C3b and C4b), and plasma proteins, and are phagocytosed via leukocyte plasma membrane receptors. Reactive oxygen species are not involved in opsonization.`,`Phagocytosis occurs after leukocytes recognize opsonized microbes through plasma membrane receptors, including receptors that specifically bind the Fc region of antibodies, complement products, or plasma proteins called lectins that recognize sugar-moieties on microbes. Phagocytosis also is independent of the respiratory burst following phagocytosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The respiratory burst is an NADPH-dependent oxidation reaction in phagolysosomes that leads to the production of reactive oxygen species (ROS), a type of free radical that destroys ingested microbes. ROS that are released into the extracellular environment also kill microbes outside the neutrophils.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `In an experiment, peripheral blood cells are isolated and placed into a culture medium that preserves their metabolic activity. Interferon-γ is added to this culture, along with viable Escherichia coli organisms. Which of the following blood cell types in this medium is the most likely to have bactericidal activity against E.   coli?`,
        q2: ``,
        q3: [],
        option: [`Basophil`, `B lymphocyte`,` CD4+ lymphocyte`,`Monocyte`,`CD8+ lymphocyte`],
        optionFeedback: [`Basophils are the circulating counterparts of tissue mast cells. They may be involved in allergic reactions, but they do not respond to IFN-γ and are not microbicidal.`,`B lymphocytes are stimulated by IFN-γ (together with antigen and other signals) to produce some IgG types (more so in mice than in humans), but these cells are not microbicidal.`,`CD4+ T cells respond to IFN-γ by differentiating into Th1 cells, which can produce IFN-γ and activate the microbicidal function of monocytes and macrophages, but CD4+ T cells are not themselves microbicidal.`,`IFN-γ is the most potent cytokine known for activating blood monocytes and tissue macrophages. This pathway of activation (called the classical pathway) induces strong microbicidal activity in the cells. `,`CD8+ cells are not microbicidal, although they can kill cells harboring microbes in the cytosol.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- IFN-γ is the most potent cytokine known for activating blood monocytes and tissue macrophages. This pathway of activation (called the classical pathway) induces strong microbicidal activity in the cells.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A woman who is allergic to cats visits a neighbor who has several pet cats. During the visit, she inhales cat dander, and within minutes, she develops nasal congestion with abundant nasal secretions. Which of the following substances is most likely to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`Bradykinin`, `Complement C3`,`Histamine`,`Interleukin-1 (IL-1)`,`Tumor necrosis factor (TNF) `],
        optionFeedback: [`Bradykinin causes vasodilation.`,`Breakdown products of the C3 component of complement are involved in opsonization and chemotaxis of leukocytes.`,`Acute allergic reactions are caused by the release of mediators from mast cells. The most important mediator for nasal congestion and mucus production is histamine.  `,`IL-1 is a cytokine involved in leukocyte recruitment and other reactions of inflammation.`,`TNF is a cytokine involved in leukocyte recruitment and other reactions of inflammation.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Acute allergic reactions are caused by the release of mediators from mast cells. The most important mediator for nasal congestion and mucus production is histamine.  .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 35-year-old woman takes acetylsalicylic acid (aspirin) for arthritis characterized by pain, redness, and swelling of joints. Although her joint pain is reduced with this therapy, the redness and swelling are unaffected. Aspirin reduces her pain primarily by inhibiting the synthesis of which of the following substances?`,
        q2: ``,
        q3: [],
        option: [`Complement C1q`, `Histamine`,`Leukotriene E<sub>4</sub>`,`Nitric oxide`,`Prostaglandins`],
        optionFeedback: [`C1q binds to antibodies (and mannose-binding lectin) and initiates the classical (and lectin) pathways of complement activation.`,`Histamine is a vasoactive amine produced by mast cells and other cells and induces vasodilation and smooth muscle contraction.`,`Leukotrienes are synthesized by the action of lipoxygenase, which is not inhibited by nonsteroidal anti-inflammatory drugs. It is inhibited, however, by steroids.`,`Nitric oxide (NO) is synthesized by the action of nitric oxide synthase, which is also not inhibited by nonsteroidal anti-inflammatory drugs.`,`Aspirin, the oldest nonsteroidal anti-inflammatory drug, works by inhibiting the enzyme cyclooxygenase and thus the synthesis of prostaglandins (and thromboxanes). Remarkably, aspirin has been used to treat inflammation since about 1900, but its mechanism of action was defined only in the 1970s. None of the other substances is inhibited by aspirin.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-Aspirin, the oldest nonsteroidal anti-inflammatory drug, works by inhibiting the enzyme cyclooxygenase and thus the synthesis of prostaglandins (and thromboxanes). Remarkably, aspirin has been used to treat inflammation since about 1900, but its mechanism of action was defined only in the 1970s. None of the other substances is inhibited by aspirin.   .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `In an experiment, bacteria are inoculated into aliquots of normal human blood that have been treated with an anticoagulant. It is observed that the bacteria are phagocytosed by neutrophils and undergo lysis. Which of the following blood plasma components is most likely to facilitate these effects?`,
        q2: ``,
        q3: [],
        option: [` Complement`, `Fibrin`,` Kallikrein`,`Plasmin`,`Thrombin`],
        optionFeedback: [`Activation of complement either directly by bacteria (alternative and lectin pathways) or following binding of antibodies (classical pathway) generates products, mainly C3b, that opsonize the bacteria and promote their phagocytosis by neutrophils, followed by intracellular killing.`,`Fibrin is produced during blood clotting. It is not involved in phagocytosis.`,`Kallikrein is a serine protease that cleaves precursor proteins (kininogens) in the plasma to generate active kinins such as bradykinin. These cause vasodilation, pain, smooth muscle contraction, and increased vascular permeability.`,`Plasmin is an enzyme that breaks down clots (and cleaves other plasma proteins). It is not involved in phagocytosis.`,`Thrombin is produced during blood clotting. It is not involved in phagocytosis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Activation of complement either directly by bacteria (alternative and lectin pathways) or following binding of antibodies (classical pathway) generates products, mainly C3b, that opsonize the bacteria and promote their phagocytosis by neutrophils, followed by intracellular killing.  .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 95-year-old woman touches a pot of boiling water. Within 2 hours, she has marked erythema of the skin of the fingers of her hand, and small blisters appear on the finger pads. Which of the following inflammatory responses does this represent? `,
        q2: ``,
        q3: [],
        option: [`Fibrinous inflammation`, `Granulomatous inflammation`,`Purulent inflammation`,`Serous inflammation`,`Ulceration`],
        optionFeedback: [`In fibrinous inflammation, a mesh of fibrin is deposited on an inflamed serosal surface (e.g., pleura, pericardium).`,`Granulomatous inflammation is a form of chronic inflammation characterized by foci of activated macrophages (granulomas).`,`Purulent inflammation contains pus, a mixture of dead bacteria, neutrophils, and devitalized tissue. It is seen in acute infections by bacteria (called pyogenic—pus-forming—bacteria).`,`Blisters (vesicles) are caused by necrosis of epithelial cells and accumulation of fluid under the dead epithelium because of locally increased vascular permeability. This type of acute inflammation is called <i>serous</i> because the yellowish fluid resembles serum.`,`An ulcer is a discontinuity in a surface epithelium, such as the skin, stomach, or duodenum.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-Blisters (vesicles) are caused by necrosis of epithelial cells and accumulation of fluid under the dead epithelium because of locally increased vascular permeability. This type of acute inflammation is called <i>serous</i> because the yellowish fluid resembles serum.   .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 24-year-old, sexually active woman has experienced lower abdominal pain for the past day. Her temperature is 37.9° C, and on palpation, the left lower abdomen is markedly tender. Laboratory findings include a total WBC count of 29,000/mm<sup>3</sup> with 75&#37; segmented neutrophils, 6&#37; bands, 14&#37; lymphocytes, and 5% monocytes. A serum human chorionic gonadotropin (hCG) test is negative. Laparotomy reveals a distended, fluid-filled, reddened left fallopian tube that is about to rupture. A left salpingectomy is performed. Which of the following tissue changes is most likely to be seen on microscopic examination of the excised fallopian tube?`,
        q2: ``,
        q3: [],
        option: [` Fibroblastic proliferation`, `Caseous necrosis`,` Liquefactive necrosis`,`Eosinophil cell infiltrates`,`Squamous metaplasia`],
        optionFeedback: [`Fibroblast proliferation is seen during repair by scarring and is not a component of acute inflammation.`,`Caseous necrosis is a special type of necrosis in which the tissue in the center of granulomas dies, developing an amorphous “cheese-like,” crumbling consistency.`,`The clinical history and laboratory findings indicate acute abdominal inflammation likely secondary to a bacterial infection. Laparotomy reveals acute salpingitis. The fallopian tube is distended by the accumulation of pus, a collection of dead neutrophils, bacteria, and tissue, formed as a result of liquefactive necrosis.`,`Eosinophilic inflammation is typical of helminthic infections and allergic reactions.`,`Squamous metaplasia is the conversion of one type of epithelium (usually columnar) to tougher squamous epithelium as a reaction to chronic exposure to irritants.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The clinical history and laboratory findings indicate acute abdominal inflammation likely secondary to a bacterial infection. Laparotomy reveals acute salpingitis. The fallopian tube is distended by the accumulation of pus, a collection of dead neutrophils, bacteria, and tissue, formed as a result of liquefactive necrosis. .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 47-year-old woman has had a cough productive of yellowish sputum for the past 2 days. On examination, her temperature is 38.3° C. A chest radiograph shows bilateral patchy infiltrates. Her peripheral blood shows leukocytosis. She is treated with antibiotics. A week later she is afebrile. Which of the following is the most likely outcome of her pulmonary disease?`,
        q2: ``,
        q3: [],
        option: [`Chronic inflammation`, `Fibrous scarring`,`Organization`,`Resolution`,`Ulceration`],
        optionFeedback: [`In chronic inflammation there would be continuing inflammation, tissue damage, and attempts at repair.`,`Fibrous scarring is a mechanism of repair of injured tissues in which the tissue cannot regenerate fully and is replaced by collagenous scar.`,`Organization is repair in organs such as the lung, with limited ability for regeneration, when there has been extensive tissue destruction and heavy fibrin exudation that cannot be cleared by macrophages.`,`The history, X-ray results, and leukocytosis from the acute episode are typical of pneumonia. The return to an afebrile state follows resolution of the acute inflammation. `,`An ulcer is a discontinuity in a surface epithelium, such as the skin, stomach, or duodenum.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The history, X-ray results, and leukocytosis from the acute episode are typical of pneumonia. The return to an afebrile state follows resolution of the acute inflammation.  .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 29-year-old woman with a congenital ventricular septal defect (VSD) and a history of intravenous drug use has had a persistent temperature of 38.6° C and headache for the past 3 weeks. A head computed tomography (CT) scan shows an enhancing 3-cm ring-like lesion, suggestive of a cavity, in the right parietal lobe of her brain. Which of the following actions by inflammatory cells has most likely produced this CT finding?`,
        q2: ``,
        q3: [],
        option: [`Elaboration of nitric oxide (NO) by macrophages`, `Formation of immunoglobulin by B lymphocytes`,` Generation of prostaglandin by endothelium`,`Production of interferon-γ by T lymphocytes`,`Release of lysosomal enzymes from neutrophils`],
        optionFeedback: [`NO is a microbicidal substance produced by activated macrophages. It does not destroy tissues, an essential aspect of liquefactive necrosis.`,`Antibodies are produced by B cells and do not cause liquefactive necrosis.`,`Prostaglandins are produced by endothelial and other cells and have important effects on vessels, but do not cause liquefactive necrosis of tissues.`,`Interferon-γ is a cytokine produced by T cells that activates macrophages. It does not cause liquefactive necrosis.`,`Fever with neurologic symptoms and a focal cavitary lesion in the brain are typical of a brain abscess. The VSD permits bacteria from a peripheral site to bypass the lungs (where they are often cleared), enter the arterial circulation, and seed the brain. Brain abscesses represent liquefactive necrosis caused by destructive enzymes released from the lysosomes of activated neutrophils.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Fever with neurologic symptoms and a focal cavitary lesion in the brain are typical of a brain abscess. The VSD permits bacteria from a peripheral site to bypass the lungs (where they are often cleared), enter the arterial circulation, and seed the brain. Brain abscesses represent liquefactive necrosis caused by destructive enzymes released from the lysosomes of activated neutrophils. .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An 8 year old girl has had difficulty swallowing for the past day. On examination, her pharynx is swollen and erythematous, with an overlying yellow exudate. Laboratory studies show neutrophilia. Streptococcus pyogenes (group A streptococcus) is cultured from her pharynx. Which of the following substances is most likely to increase in response to pyrogens released by this organism?`,
        q2: ``,
        q3: [],
        option: [`Lipoxins`, `Immunoglobulin E (IgE)`,`Interleukin-12 (IL-12)`,`Nitric oxide (NO)`,`Prostaglandins`],
        optionFeedback: [`Lipoxins are arachidonic acid metabolites related to prostaglandins but they suppress inflammation and are not involved in causing fever.`,`IgE is an antibody that coats mast cells and induces their degranulation in allergic reactions but does not cause fever.`,`IL-12 is a cytokine produced by activated macrophages and dendritic cells. It stimulates IFN-γ roduction from T lymphocytes and NK cells but does not cause fever.`,`NO is a microbicidal substance produced by activated macrophages. It does not cause fever.`,`Pyrogens are fever-producing substances released by microbes (called exogenous pyrogens) or cytokines such as IL-1 and TNF released by host inflammatory cells responding to the microbes (endogenous pyrogens). They stimulate prostaglandin production in the hypothalamus, which resets the thermostat that controls body temperature.  Nonsteroidal antiinflammatory drugs, by inhibiting prostaglandin synthesis, reduce fever.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Pyrogens are fever-producing substances released by microbes (called exogenous pyrogens) or cytokines such as IL-1 and TNF released by host inflammatory cells responding to the microbes (endogenous pyrogens). They stimulate prostaglandin production in the hypothalamus, which resets the thermostat that controls body temperature.  Nonsteroidal antiinflammatory drugs, by inhibiting prostaglandin synthesis, reduce fever.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 41-year-old man has a 2-day history of severe headache. On examination, his temperature is 39.2° C.   A lumbar puncture is performed, and the cerebrospinal fluid obtained has a white blood cell count of 910/mm<sup>3</sup> (normal 0-5/mm<sup>3</sup>), with 94&#37; neutrophils and 6&#37; lymphocytes. Which of the following substances is the most likely mediator for the fever observed in this man?`,
        q2: ``,
        q3: [],
        option: [`Bradykinin`, `Histamine`,`Leukotriene B<sub>4</sub>`,`Nitric oxide (NO)`,`Interleukin-1 (IL-1)`],
        optionFeedback: [`Bradykinin is also produced during inflammatory reactions and acts on blood vessels, but does not cause fever.`,`Histamine is also produced during inflammatory reactions and acts on blood vessels, but does not cause fever.`,`Leukotriene B<sub>4</sub> is produced during inflammatory reactions and promotes leukocyte chemotaxis (leukotrienes) but does not cause fever.`,`NO is produced during inflammatory reactions, acts on blood vessels, and kills microbes, but it does not cause fever.`,`Cytokines, including TNF and IL-1,  produced by activated macrophages and other host cells cause fever by acting on the hypothalamus.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-Cytokines, including TNF and IL-1,  produced by activated macrophages and other host cells cause fever by acting on the hypothalamus.  .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 43-year-old man with a ventricular septal defect (VSD) has had a cough and fever for the past 2 days. On examination, he has a temperature of 38.6° C and a cardiac murmur. A blood culture grows <i>Streptococcus,</i> viridans group. Laboratory testing reveals polymorphonuclear leukocytosis and elevation in the levels of several acute phase reactants. Which of the following acute phase reactants stimulates phagocytosis?`,
        q2: ``,
        q3: [],
        option: [`Hepcidin`, ` C-reactive protein (CRP)`,`Fibrinogen`,`IL-1`,`TNF`],
        optionFeedback: [`Hepcidin regulates iron levels, and its increased production during chronic inflammatory disorders is responsible for the “anemia of chronic disease,” in which iron is sequestered in macrophages away from erythroid progenitors in the bone marrow.`,`The clinical history indicates a disseminated bacterial infection resulting from the spread of bacteria from a peripheral source (such as the pharynx) through the VSD into the arterial circulation. Of the acute-phase proteins listed, CRP is the only one that coats bacteria and promotes their phagocytosis.`,`Fibrinogen promotes clotting of blood and aggregation of erythrocytes (the latter responsible for the increased erythrocyte sedimentation rate seen in inflammation).`,`IL-1 is a cytokine that promotes leukocyte adhesion to the endothelium, leading to leukocyte recruitment to sites of inflammation. It causes fever, but is not involved in phagocytosis of microbes.`,`TNF is a cytokine that promotes leukocyte adhesion to the endothelium, leading to leukocyte recruitment to sites of inflammation. Like IL-1, it causes fever, but is not involved in phagocytosis of microbes.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The clinical history indicates a disseminated bacterial infection resulting from the spread of bacteria from a peripheral source (such as the pharynx) through the VSD into the arterial circulation. Of the acute-phase proteins listed, CRP is the only one that coats bacteria and promotes their phagocytosis. .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `In an experiment, a group of test animals is infected with hepatitis A virus. Two months later, complete recovery of the normal liver architecture is observed microscopically. A control test group is infected with bacterial organisms, and after the same period of time, fibrous scars from resolving hepatic abscesses are seen microscopically. Which of the following factors best explains the different outcomes for the two test groups?`,
        q2: ``,
        q3: [],
        option: [`Extent of damage to the biliary ducts`, `Extent of the hepatocyte injury`,`Injury to the connective tissue framework`,`Location of the lesion within the liver`,`Class of infectious agent that has caused of the liver injury`],
        optionFeedback: [`The extent of injury to biliary cells does not directly influence repair by regeneration versus scarring.`,`The extent of injury to hepatocytes does not directly influence repair by regeneration versus scarring.`,`Complete restoration of liver architecture after the viral infection is an example of repair by regeneration, whereas the presence of scars after the bacterial infection reflects repair by laying down of fibrous tissue (scarring). The different outcomes in the same organ are mainly because of the extent of damage to the connective tissue framework. When damage is extensive, normal architecture cannot be restored and scarring follows. In other organs (e.g., heart), scarring may occur because the cells are not capable of regeneration.`,`The location of injury in the liver does not directly influence repair by regeneration versus scarring.`,`The preservation of supporting structures and not the nature of the infectious agent influences repair by regeneration versus scarring.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Complete restoration of liver architecture after the viral infection is an example of repair by regeneration, whereas the presence of scars after the bacterial infection reflects repair by laying down of fibrous tissue (scarring). The different outcomes in the same organ are mainly because of the extent of damage to the connective tissue framework. When damage is extensive, normal architecture cannot be restored and scarring follows. In other organs (e.g., heart), scarring may occur because the cells are not capable of regeneration.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 54-year-old man undergoes laparoscopic hernia repair. In spite of the small size of the incisions, he has poor wound healing. Further history reveals that his usual diet has poor nutritional value and is deficient in vitamin C.   Synthesis of which of the following extracellular matrix components is most affected by this deficiency?`,
        q2: ``,
        q3: [],
        option: [` Collagen`, `Elastin`,` Fibronectin`,`Integrin`,` Laminin`],
        optionFeedback: [`Multiple factors can impair wound healing. Vitamin C is involved in the biosynthesis of collagen (Chapter 19), so in this case, deficiency of collagen is the most likely explanation.`,`Elastin is a component of the extracellular matrix, but its synthesis does not require vitamin C.`,`Fibronectin is a component of the extracellular matrix, but its synthesis does not require vitamin C.`,`Integrins are membrane receptors on leukocytes and other cells that bind to various extracellular matrix proteins.`,`Laminin is a component of the extracellular matrix, but its synthesis does not require vitamin C.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Multiple factors can impair wound healing. Vitamin C is involved in the biosynthesis of collagen (Chapter 19), so in this case, deficiency of collagen is the most likely explanation.   .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `In an experiment, glass beads are embolized into the coronary arteries of rats, resulting in myocardial injury. After 7 days, sections of the myocardium are studied using light microscopy. The microscopic appearance of one of these sections is shown in the figure. Which of the following mediators is most likely being expressed to produce this appearance?`,
        q2: `<img src="../images/f002-q028-9780323640251.png"/>`,
        q3: [],
        option: [`Interleukin-5 (IL-5)`, ` Leukotriene B<sub>4</sub> (LTB4)`,`Thromboxane A<sub>2</sub> (TXA2)`,`Tumor necrosis factor (TNF)`,`Vascular endothelial growth factor (VEGF) `],
        optionFeedback: [`IL-5 is a cytokine that activates eosinophils.`,`LTB4 is an arachidonic acid-derived mediator that induces leukocyte chemotaxis `,`TXA2 is an arachidonic acid-derived mediator that causes vasoconstriction and platelet aggregation.`,`TNF is a cytokine involved in leukocyte recruitment in inflammation that has systemic effects.`,`The histology shows abundant small blood vessels and proliferating fibroblasts in an edematous background, an appearance that is characteristic of granulation tissue. The formation of new vessels is driven mainly by VEGF. Other growth factors contribute to fibroblast proliferation.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The histology shows abundant small blood vessels and proliferating fibroblasts in an edematous background, an appearance that is characteristic of granulation tissue. The formation of new vessels is driven mainly by VEGF.    Other growth factors contribute to fibroblast proliferation.   .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 24-year-old man with acute appendicitis undergoes surgical removal of an inflamed appendix. The incision site is sutured. Four weeks later, a trichrome-stained section representative of the site with blue-appearing collagen is shown in the figure. Which of the following mediators is most likely responsible for the appearance of the healing wound?`,
        q2: `<img src="../images/f002-q029-9780323640251.png"/>`,
        q3: [],
        option: [`TNF`, `TGF-β`,`C-reactive protein`,` Platelet activating factor (PAF)`,`IL-17`],
        optionFeedback: [`TNF is a cytokine involved in recruitment of leukocytes to sites of inflammation.`,`The presence of collagen indicates scarring. The most potent stimulator of collagen synthesis in fibroblasts is TGF-β. `,`C-reactive protein is an acute phase reactant that can bind to microbial cell walls and act as an opsonin. It can also fix complement.`,`PAF is an aggregator of platelets; its significance as a mediator of inflammation is unclear.`,`IL-17 is a cytokine involved in recruitment of leukocytes to sites of inflammation.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The presence of collagen indicates scarring. The most potent stimulator of collagen synthesis in fibroblasts is TGF-β. .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 40-year-old man underwent laparotomy for a perforated sigmoid colon diverticulum. A wound infection complicated the postoperative course, and surgical wound dehiscence occurred. Primary closure was no longer possible, and the wound was left to heal by secondary intention. Six weeks later, the wound is only 10&#37; of its original size. Which of the following processes best accounts for the observed decrease in wound size over the past 6 weeks?`,
        q2: ``,
        q3: [],
        option: [`Elaboration of adhesive glycoproteins`, ` Increase in synthesis of collagen`,` Inhibition of metalloproteinases`,`Myofibroblast contraction`,`Resolution of subcutaneous edema`],
        optionFeedback: [`Adhesive glycoproteins are typically ligands for integrins, which leukocytes and fibroblasts use to attach to the extracellular matrix (ECM) and migrate along the ECM.`,`Increased synthesis of collagen would not directly lead to contraction of a wound, but mature collagen is remodeled and becomes denser, changes that could contribute to reduced scar size during late stages of healing.`,`Inhibition of metalloproteinases occurs during scar formation and serves to maintain the integrity of the scar.`,`Fibrous scars contract as they mature, mainly because of the contractile activity of cells called myofibroblasts, which often accumulate in scars.`,`Edema does resolve as scarring starts and may be a prelude to the laying down of collagen, but it does not itself contribute much to scar contraction.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-Fibrous scars contract as they mature, mainly because of the contractile activity of cells called myofibroblasts, which often accumulate in scars .`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A man suffered multiple injuries on his back and upper arm due to an industrial accident in a steel mill. Most wounds were too large to be sutured. With optimal wound care, healing continued, but the site continued to evolve over the next 2 months, resulting in the appearance shown in the figure. Which of the following following processes has occurred in this patient? <p><img src="../images/f002-q031-9780323640251.png" alt="" data-uuid="8efc6316ebee4503a78382de65a5094a"/></p>`,
        q2: ``,
        q3: [],
        option: [`Dehiscence`, `Keloid formation`,` Organization`,`Resolution`,`Primary union`],
        optionFeedback: [`Dehiscence refers to breakdown of a wound or scar.`,`These hypertrophic accumulations of connective tissue that extend beyond the original wound are called keloids. Why they develop in some individuals is not known.`,`Organization is repair by scarring in a parenchymal organ such as the lung or liver.`,`Resolution is restoration of normal architecture after injury, usually reflecting repair by regeneration.`,`Primary union is a term used to designate closure of skin wounds without scarring, as after surgical incisions.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-These hypertrophic accumulations of connective tissue that extend beyond the original wound are called keloids. Why they develop in some individuals is not known. .`,
        state: `notAnswered`,
        userAnswered: [],
    }

   ];






