var quiz = [
    {
        q: `A 66-year-old man has had a three-year history of cough and worsening shortness of breath. On physical examination, his pulse is 77 bpm and blood pressure is 110/80 mm Hg. Ejection fraction is normal and he does not have anginal pain. His liver span is increased to 14 cm. He has pitting edema to his knees. Jugular venous distention is noted to the angle of the jaw at a 45-degree elevation of his head while lying down. Which of the following is the most likely cause of his heart disease?`,
        q2: ``,
        q3: [],
        option: [`Anemia`, `Essential hypertension`, `Aortic stenosis`,` Systemic lupus erythematosus`,` Chronic obstructive pulmonary disease`],
        optionFeedback: [`Anemia can lead to high output cardiac failure if severe, but cannot explain the history of cough. `,`Essential hypertension often causes left-sided heart failure that can manifest as shortness of breath due to pulmonary edema. Jugular venous pressure is not elevated unless there is concomitant right heart failure`,`Aortic stenosis often causes left-sided heart failure due to left ventricular outflow obstruction. `,`Systemic lupus erythematosus (SLE) may cause interstitial lung disease, but is a much less frequent cause of pulmonary fibrosis and secondary heart failure than chronic obstructive pulmonary disease. SLE is associated with Libman-Sacks endocarditis, however.`,`<!--Answers:-->     The findings in this patient are consistent with isolated right-sided heart failure (cor pulmonale) secondary to chronic obstructive pulmonary disease (COPD). Chronic lung disease associated with poor ventilation of alveoli results in vasoconstriction and pulmonary hypertension, which may, over time, lead to right-sided heart failure.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The findings in this patient are consistent with isolated right-sided heart failure (cor pulmonale) secondary to chronic obstructive pulmonary disease (COPD). Chronic lung disease associated with poor ventilation of alveoli results in vasoconstriction and pulmonary hypertension, which may, over time, lead to right-sided heart failure.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 62-year-old woman has a 2-year history of increasing dyspnea. She now awakens at night with air hunger and cough productive of frothy sputum. On examination, she has rales in all lung fields. Echocardiography shows a decreased ejection fraction of 30% with concentric increase in left ventricular wall size. The valves appear normal. Which of the underlying diseases does she most likely have?`,
        q2: ``,
        q3: [],
        option: [` Amyloidosis`, `Pulmonary fibrosis`,`Hypertension`,` Obstructive sleep apnea`,`Pericarditis`],
        optionFeedback: [`Cardiac amyloidosis produces restrictive heart disease, sometimes accompanied by arrhythmia due to conduction defects. It is not associated with ventricular hypertrophy or systolic failure.`,`Pulmonary fibrosis, as with other lung disorders associated with hypoxemia, may result in right-sided heart disease.`,`<!--Answers:-->     Concentric left ventricular hypertrophy is a typical response to chronic hypertension with pressure overload of the heart, leading eventually to left-sided heart failure, high pulmonary vein pressures, pulmonary edema, dyspnea and cough.  `,`Obstructive sleep apnea, as with other lung disorders associated with hypoxemia, may result in right-sided heart disease.`,`Pericarditis, if chronic, can produce a restrictive cardiac picture and is not associated with left ventricular hypertrophy.  `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale:-  Concentric left ventricular hypertrophy is a typical response to chronic hypertension with pressure overload of the heart, leading eventually to left-sided heart failure, high pulmonary vein pressures, pulmonary edema, dyspnea and cough. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 41-year-old woman has been awakened at night with “air hunger” for the past year. She sleeps better when sitting up in bed. She does not have liver or spleen enlargement. Chest computed tomography scans suggest bilateral pulmonary edema. Her serum natriuretic peptide is &gt;400 pg/mL (very high). What cardiac disease best explains her presentation?`,
        q2: ``,
        q3: [],
        option: [`Multiple pulmonary thromboemboli`, `Fibrinous pericarditis`,` Giant cell myocarditis`,`Libman-Sacks endocarditis`,`Rheumatic mitral stenosis`],
        optionFeedback: [`Pulmonary thromboembolism, if recurrent, may lead to right-sided heart failure. `,`Fibrinous pericarditis usually is associated with pain and friction rubs, but does not produce heart failure. `,`Giant cell myocarditis may produce heart failure associated with cardiac dilation, but usually presents acutely or sub acutely and often is associated with other findings, such as chest pain or arrhythmia. `,`Libman-Sacks endocarditis is often associated with systemic lupus erythematosus and usually presents with valvulitis leading to thrombi formation. It may lead to thromboembolism and/or valve regurgitation, but usually does not produce stenotic valve lesions. `,`<!--Answers:-->   The findings in this patient are consistent with left-sided heart failure associated with atrial dilation (elevation in level of atrial natriuretic peptide) and pulmonary edema, all of which are classic findings in mitral stenosis. Rheumatic heart disease is the most common cause of mitral stenosis.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The findings in this patient are consistent with left-sided heart failure associated with atrial dilation (elevation in level of atrial natriuretic peptide) and pulmonary edema, all of which are classic findings in mitral stenosis. Rheumatic heart disease is the most common cause of mitral stenosis`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 50-year-old man has had increasing abdominal discomfort and swelling of his legs for the past 2 years. He has smoked cigarettes for 35 years and has a chronic cough productive of sputum. On physical examination, he has jugular venous distention, even when sitting upright. The liver is enlarged and tender and can be palpated 10 cm below the right costal margin. Pitting edema is observed on the lower extremities. A chest radiograph shows bilateral pleural effusions, and increased bronchovascular markings. Which of the following is the most common cause of these clinical features?`,
        q2: ``,
        q3: [],
        option: [`Idiopathic pulmonary fibrosis`, `Chronic obstructive pulmonary disease (COPD)`,` Primary pulmonary hypertension`,`Pulmonary valve stenosis`,` Eisenmenger syndrome`],
        optionFeedback: [`Idiopathic pulmonary fibrosis may be associated with smoking, but would produce increased interstitial markings along with cystic spaces (honeycomb lung).`,`<!--Answers:-->    Smoking commonly leads to COPD, frequently with both chronic bronchitis and emphysema. Chronic bronchitis often produces hypoxia, leading to pulmonary hypertension and eventual right-sided heart failure, which is evident in this patient.  `,`Primary pulmonary hypertension is a rare cause of right-sided heart failure and is not associated with smoking.`,`Pulmonary valve stenosis is almost always a congenital malformation. It is a rare cause of right-sided heart failure and is not smoking-related.`,`Eisenmenger syndrome is seen when, in the setting of a left-to-right shunt (e.g., ventricular septal defect), the pulmonary vascular resistance approaches systemic levels and the left-to-right shunt shifts to a right-to-left shunt (converting non-cyanotic heart disease to cyanotic heart disease). This condition is not related to smoking. `],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Smoking commonly leads to COPD, frequently with both chronic bronchitis and emphysema. Chronic bronchitis often produces hypoxia, leading to pulmonary hypertension and eventual right-sided heart failure, which is evident in this patient. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An infant born at term is noted to have cyanosis during the first week of life. On examination, a heart murmur is auscultated. Abnormal findings with echocardiography include an overriding aorta and pulmonic stenosis. This infant is likely to have which of the following additional heart defects?`,
        q2: ``,
        q3: [],
        option: [` Atrial septal defect`, ` Ventricular septal defect`,` Coarctation of the aorta`,`Ventricular aneurysm`,`Patent ductus arteriosus`],
        optionFeedback: [`Atrial septal defects are usually isolated and do not produce cyanosis.`,`<!--Answers:-->   Cyanosis indicates the presence of a significant right-to-left shunt, which in the context of overriding aorta and pulmonic stenosis is likely to be caused by tetralogy of Fallot: overriding aorta, pulmonic stenosis, ventricular septal defect, and right ventricular thickening.  `,`Coarctation of the aorta, depending on level, is associated with difference in blood pressure above and below the level of the coarctation.`,`Ventricular aneurysms are acquired lesions, usually secondary to myocardial infarction.`,`Patent ductus arteriosus causes left-to-right shunting and is not a part of the tetralogy of Fallot.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Cyanosis indicates the presence of a significant right-to-left shunt, which in the context of overriding aorta and pulmonic stenosis is likely to be caused by tetralogy of Fallot: overriding aorta, pulmonic stenosis, ventricular septal defect, and right ventricular thickening.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 77-year-old woman fell and fractured her ankle. She has spent most of her time in bed for the past 16 days. She develops sudden chest pain, dyspnea, and diaphoresis. On examination, she has left thigh swelling and tenderness. A chest computed tomography scan shows areas of decreased attenuation in the right and left pulmonary arteries. A day later she has difficulty speaking. Magnetic resonance angiography shows focal occlusion of a left middle cerebral artery branch. Which of the following cardiac lesions is she most likely to have?`,
        q2: ``,
        q3: [],
        option: [`Ventricular septal defect`, `Calcific aortic stenosis`,`Nonbacterial thrombotic endocarditis`,` Patent foramen ovale`,`Ventricular aneurysm`],
        optionFeedback: [`Ventricular septal defect (VSD) would likely have been identified earlier in life, whereas patent foramen ovale is often asymptomatic. Paradoxical emboli can occur in the setting of VSD.`,`Calcific aortic stenosis is associated with left-sided hypertrophy and possible heart failure, but not embolism.`,`Nonbacterial thrombotic endocarditis may produce embolism but is usually associated with diseases that cause general debility such as hypercoagulable states due to underlying cancers, particularly mucinous adenocarcinomas`,`<!--Answers:-->   The clinical scenario is classic for deep venous thrombosis and pulmonary thromboembolism at presentation. The occurrence of a stroke the next day is consistent with a paradoxical embolism, defined as a thrombus originating in the venous system (the lower leg in this case) that passes, usually through a patent foramen ovale, and lodges in a systemic arterial vessel, such as a cerebral artery.  `,`Ventricular aneurysms also may produce thromboembolisms, but usually occur following myocardial infarction, for which there is no history. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The clinical scenario is classic for deep venous thrombosis and pulmonary thromboembolism at presentation. The occurrence of a stroke the next day is consistent with a paradoxical embolism, defined as a thrombus originating in the venous system (the lower leg in this case) that passes, usually through a patent foramen ovale, and lodges in a systemic arterial vessel, such as a cerebral artery.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 15-year-old boy complains of pain in his legs when he runs more than 300 m (about ¼ mile). Physical examination shows temperature 36.8° C; pulse 76 bpm; respirations 22 breaths/min; and blood pressure 165/90 mm Hg. The radial pulses are 4+, and the dorsalis pedis pulses are 1+. Arterial blood gas measurement shows a normal oxygen saturation level. Which of the following congenital cardiovascular anomalies is most likely to be present in this patient?`,
        q2: ``,
        q3: [],
        option: [`Aortic valve stenosis`, `Coarctation of the aorta`,`Patent ductus arteriosus`,`Transposition of the great arteries`,`Tricuspid valve atresia`],
        optionFeedback: [`Aortic valve stenosis is rarely congenital and cannot explain the pulse differences.`,`<!--Answers:-->  Coarctation of the aorta may be preductal or postductal. The post ductal form allows adequate perfusion of the upper part of the body but the lower part (supplied by the aorta distal to the narrowing) is underperfused, resulting in a difference in pulse strength in the upper and lower extremities. Impaired perfusion of the kidney causes release of renin and secondary hypertension. Poor blood supply to the legs is responsible for pain in the legs (claudication) following exercise.  `,`Patent ductus arteriosus usually presents early in life due to left to right shunting.`,`Transposition of the great vessels is a severe congenital anomaly that presents early in life with cyanosis.`,`Tricuspid valve atresia would present early in life with right-sided ventricular hypoplasia and is incompatible with life in the absence of other cardiac defects (e.g., atrial and ventricular septal defects).`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Coarctation of the aorta may be preductal or postductal. The post ductal form allows adequate perfusion of the upper part of the body but the lower part (supplied by the aorta distal to the narrowing) is underperfused, resulting in a difference in pulse strength in the upper and lower extremities. Impaired perfusion of the kidney causes release of renin and secondary hypertension. Poor blood supply to the legs is responsible for pain in the legs (claudication) following exercise `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A group of pregnant women was accidentally exposed to a chemical teratogen. A cohort amongst them gave birth to children with congenital malformations. A systematic analysis of the relationship between the time of exposure and duration of pregnancy revealed that women at certain age of gestation were at a much higher risk for giving birth to a baby with congenital malformations. At which of the following ages of gestation were the infants most susceptible to develop malformations due to teratogen exposure?`,
        q2: ``,
        q3: [],
        option: [`First two weeks`, `Three to eight weeks`,`Twelve to fifteen weeks`,`Twenty to twenty-four weeks`,`Twenty-six to twenty-nine weeks`],
        optionFeedback: [`Teratogenic exposures very early in development usually cause intrauterine death.`,`<!--Answers:-->     During embryogenesis, the critical time period during which tissues and organs form is between weeks 3 and 8 post-fertilization. Agents that damage cells or derange critical signaling pathways that control differentiation most readily produce teratogenic effects during this time period. `,`Teratogenic exposures after 12 weeks either have no effect or cause growth retardation.`,`Teratogenic exposures after 12 weeks either have no effect or cause growth retardation.`,`Teratogenic exposures after 12 weeks either have no effect or cause growth retardation.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- During embryogenesis, the critical time period during which tissues and organs form is between weeks 3 and 8 post-fertilization. Agents that damage cells or derange critical signaling pathways that control differentiation most readily produce teratogenic effects during this time period. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 60-year-old man has a 6-year history of angina on exertion. A coronary angiogram performed 2 years ago showed 75% stenosis of the left circumflex coronary artery and 50% stenosis of the right coronary artery. For the past 3 weeks, the frequency and severity of his anginal attacks have increased, and pain sometimes occurs even when he is lying in bed. Today he was brought to the emergency department after experiencing severe chest pain radiating to the jaw. On physical examination, his blood pressure is 110/80 mm Hg and pulse is 85 bpm with irregular beats. An electrocardiogram shows ST segment elevation. Laboratory studies show serum glucose 188 mg/dL, creatinine 1.2 mg/dL, and troponin I 1.5 ng/mL.  Which of the following pathologic findings is most likely to be present?`,
        q2: ``,
        q3: [],
        option: [`Rupture of an atheromatous plaque `, ` Constrictive pericarditis with calcification`,`Mural thrombosis with systemic embolism`,`Extensive myocardial fiber hypertrophy with focal ischemia`,` Sub-endocardial infarction `],
        optionFeedback: [`<!--Answers:-->  The patient has developed unstable angina, which usually occurs when there is an acute change in a stable coronary arterial lesion, such as fissuring of an atheromatous plaque, leading to exposure of procoagulants and superimposed thrombosis. None of the other possible answers produce unstable angina. `,`Constrictive pericarditis causes restrictive heart disease and is not a cause of unstable angina.`,`Mural thrombosis with systemic embolism would most often present with stroke or potentially myocardial infarction, if embolism occurs to a coronary vessel.`,`Myocardial fiber hypertrophy and ischemia is a feature of hypertension, which appears to be absent.`,`Subendocardial infarction (limited to inner one third of the myocardium) would be associated with elevated troponin I levels and either no change in ST segment or ST segment depression rather than elevation.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The patient has developed unstable angina, which usually occurs when there is an acute change in a stable coronary arterial lesion, such as fissuring of an atheromatous plaque, leading to exposure of procoagulants and superimposed thrombosis. None of the other possible answers produce unstable angina. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 37-year-old woman has the sudden onset of chest pain. On examination, she is afebrile, has tachycardia, and is hypotensive. An electrocardiogram shows ST segment elevation and pathologic Q waves. The representative microscopic appearance of her left circumflex artery is shown in the figure. Which of the following is the most likely risk factor in the pathogenesis of this lesion?<img src="../images/f008-q010-9780323640251.png" alt="" data-uuid="3dd4ec87ff134183a9f949f4dc1239a2"/>`,
        q2: ``,
        q3: [],
        option: [`Acute promyelocytic leukemia`, `Chronic alcoholism`,` Diabetes mellitus`,` Marfan syndrome`,` Polyarteritis nodosa`],
        optionFeedback: [`Acute promyelocytic leukemia is associated with disseminated intravascular coagulation and increased risk of bleeding, but not myocardial infarction.`,`Chronic alcoholism may produce dilated cardiomyopathy, but is not associated with an increased risk of coronary artery disease.`,`<!--Answers:-->  The patient is having an acute myocardial infarction due to obstruction of her left circumflex artery. Diabetes mellitus significantly increases the risk of myocardial infarction due to hypercholesterolemia and consequent increased risk of atherosclerosis. Premenopausal women are protected from ischemic heart diseases unless they are diabetic.  `,`Marfan syndrome is associated with aortic dissection.`,`Polyarteritis nodosa may cause myocardial infarction due to luminal occlusion secondary to fibrinoid necrosis affecting all layers of the wall. Inflammation of the vessel walls causes thrombus formation  with subsequent intimal proliferation and fibrosis. However, this disease is usually associated with symptoms of systemic inflammation (fever, weight loss, muscle and joint pain) and renal dysfunction.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The patient is having an acute myocardial infarction due to obstruction of her left circumflex artery. Diabetes mellitus significantly increases the risk of myocardial infarction due to hypercholesterolemia and consequent increased risk of atherosclerosis. Premenopausal women are protected from ischemic heart diseases unless they are diabetic.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 56-year-old man experiences episodes of severe substernal chest pain every time he exercises moderately. The episodes have become more frequent and severe over the past year, but they can be relieved by sublingual nitroglycerin. On physical examination, he is afebrile, his pulse is 78 bpm and regular, and there are no murmurs or gallops. Laboratory studies show creatinine 1.1 mg/dL, glucose 130 mg/dL, and total serum cholesterol 223 mg/dL.   Which of the following cardiac lesions is most likely to be present in this man?`,
        q2: ``,
        q3: [],
        option: [`Calcific aortic stenosis`, `Coronary atherosclerosis`,` Restrictive cardiomyopathy`,` Rheumatic mitral stenosis`,`Fibrinous pericarditis`],
        optionFeedback: [`Calcific aortic stenosis becomes symptomatic in the 60s and 70s. It may give rise to syncope and exacerbate angina, and it is associated with a systolic murmur.`,`<!--Answers:-->  The quality of the pain and the relief of the pain with nitroglycerin are consistent with stable angina, which is caused by coronary artery disease.  `,`Restrictive cardiomyopathy is rare and associated with diastolic heart failure without anginal symptoms.`,`Rheumatic mitral stenosis is associated with a diastolic murmur and symptoms related to pulmonary edema and (eventually) right-sided heart failure. `,`The quality of the pain associated with fibrinous pericarditis (acute in onset, sharp, unrelated to exertion, better sitting up than lying down, unrelieved by nitroglycerin) is completely different from that described in this case.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The quality of the pain and the relief of the pain with nitroglycerin are consistent with stable angina, which is caused by coronary artery disease `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 58-year-old woman has a 4-day history of increasing chest pain and dyspnea. She experiences sudden cardiac arrest, from which she was resuscitated. The representative light microscopic appearance of her left ventricular free wall is shown in the figure. Elevation in serum levels of which of the following would be most useful in arriving at the diagnosis?<img src="../images/f008-q012-9780323640251.png" alt="" data-uuid="1c81a2f279764826bfbe3b6fe220009e"/>`,
        q2: ``,
        q3: [],
        option: [`Total creatinine kinase (CK)`, `Lactic dehydrogenase (LDH)`,`Troponin T and I`,`LDL cholesterol`,` C-reactive protein (CRP)`],
        optionFeedback: [`Elevated total CK could indicate damage to cardiac or skeletal muscle and is, therefore, not specific for myocardial infarction.`,`Elevated LDH can be seen after myocardial necrosis, but it has been replaced as a cardiac biomarker by troponins, which are more specific to the myocardium. Elevated LDH is most useful in the diagnosis of red cell hemolysis and aggressive B cell lymphomas.`,`<!--Answers:-->  The figure shows coagulative necrosis of the myocardium, with dense infiltration with neutrophils. Highly sensitive and specific serum tests are used to detect troponin T and I, structural proteins that are released into the circulation from necrotic cardiomyocytes following myocardial infarction.  `,`Elevated LDL cholesterol is useful to identify individuals at higher risk for coronary artery disease, but is not used to diagnose myocardial infarction.`,`CRP is a marker of systemic inflammation. Since inflammation is present in atheromatous plaques, CRP levels may be elevated in patients who have myocardial infarction. However, since CRP is a marker of systemic inflammation occurring anywhere in the body and from any cause, it is not useful in the diagnosis of myocardial infarction.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- The figure shows coagulative necrosis of the myocardium, with dense infiltration with neutrophils. Highly sensitive and specific serum tests are used to detect troponin T and I, structural proteins that are released into the circulation from necrotic cardiomyocytes following myocardial infarction`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `In a study, the gross and microscopic appearances of the hearts of patients who died of myocardial infarction are correlated with the degree of coronary atherosclerosis, its complications, clinical symptoms, and therapies given before death. In some cases, hemorrhage and contraction bands are seen in necrotic myocardial fibers. This morphologic appearance is most likely due to`,
        q2: ``,
        q3: [],
        option: [`Coronary artery spasm`, `Anti-arrhythmic drug usage`,`Acute left heart failure`,`Septic embolization`,`Reperfusion injury`],
        optionFeedback: [`Coronary artery spasm might be associated with ischemia leading to angina, infarction, or arrhythmia.`,`Anti-arrhythmic drugs may be associated with a number of side effects and complications, including cardiac conduction abnormalities, but are not associated with contraction bands.`,`Acute left heart failure might be seen in someone status post-myocardial infarction, but is not associated with contraction bands.`,`Septic embolization occurs when fragments of infected valvular vegetations dislodge and travel to other organs, producing abscesses. `,`<!--Answers:-->   Contraction bands are caused by reperfusion of ischemic cardiomyocytes that have accumulated calcium during the period of hypoxia. The excessive calcium, in the setting of restoration of blood flow, leads to hypercontraction of myofibrils, seen as contraction bands. `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Contraction bands are caused by reperfusion of ischemic cardiomyocytes that have accumulated calcium during the period of hypoxia. The excessive calcium, in the setting of restoration of blood flow, leads to hypercontraction of myofibrils, seen as contraction bands. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 50-year-old man with diabetes and hypertension has had pain in the left shoulder and arm for the past 12 hours. Over the next 6 hours, he develops shortness of breath, which persists for 2 days. On day 3, he visits the physician. On physical examination, his temperature is 37.1°C, pulse is 82 bpm, respirations are 18 breaths/min, and blood pressure is 160/100 mm Hg. Laboratory studies show that the troponin I level is elevated. He continues to experience dyspnea for the next 3 days. On day 7, he suddenly develops evidence of severe right-sided heart failure followed by a period of continued cardiac electrical activity without a pulse, ending in death. Which of the following complications has he most likely developed?`,
        q2: ``,
        q3: [],
        option: [`Aortic valve perforation`, `Rupture of the left ventricle`,` Left ventricular aneurysm`,`Papillary muscle rupture`,`Pericarditis`],
        optionFeedback: [`Aortic valve perforation is most likely with infective endocarditis.`,`<!--Answers:-->  The period of time from three to seven days after a myocardial infarction is when the infarcted heart muscle is weakest and most likely to rupture. The presence of continued cardiac electrical activity without a pulse is evidence of hemopericardium (cardiac tamponade), a classic finding in left ventricular rupture. `,`Left ventricular aneurysms may be associated with heart failure and/or thrombosis and embolism, but usually have fibrotic walls that are not prone to rupture. They appear at later time points (weeks to months) after myocardial infarction.`,`A second possible acute event post-myocardial infarction is papillary muscle rupture, which also can occur within this time frame and can be fatal; however, it is not associated with cardiac tamponade. Papillary muscle rupture results in the acute onset of severe mitral regurgitation that can lead to cardiogenic shock and pulmonary edema.`,`Chronic pericarditis can lead to restrictive heart failure, but is not associated with ventricular rupture.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-The period of time from three to seven days after a myocardial infarction is when the infarcted heart muscle is weakest and most likely to rupture. The presence of continued cardiac electrical activity without a pulse is evidence of hemopericardium (cardiac tamponade), a classic finding in left ventricular rupture. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 69-year-old man with metabolic syndrome had chest pain and an elevated serum troponin I level 1 year ago. An echocardiogram showed an ejection fraction of 28%. He now has markedly reduced exercise tolerance. On physical examination, his temperature is 37°C, pulse is 68 bpm, respirations are 17 breaths/min, and blood pressure is 130/80 mm Hg. Diffuse crackles are heard on auscultation of the lungs. The representative gross appearance of his heart is shown in the figure. Which of the following complications of this disease has this patient most likely developed?<img src="../images/f008-q015-9780323640251.png" alt="" data-uuid="ab493c4dd6db47ffba0bee707d890469"/>`,
        q2: ``,
        q3: [],
        option: [`Atrial myxoma`, ` Ventricular aneurysm `,`Constrictive pericarditis`,`Left ventricular hypertrophy`,`Infective endocarditis`],
        optionFeedback: [`Atrial myxoma may be associated with paroxysmal feelings of chest pain or tightness, dizziness, shortness of breath, or palpitations. It usually does not lead to heart failure.`,`<!--Answers:-->  The patient is status post-myocardial infarction and has evidence of cardiac failure. Among the listed entities, only ventricular aneurysm is a complication of myocardial infarction. Large aneurysms may be associated with low ejection fractions and heart failure. `,`Constrictive pericarditis, if severe, may lead to heart failure, but is not a complication of myocardial infarction.`,`Left ventricular hypertrophy may lead to heart failure, but there is no history of sustained hypertension in this patient, which is its most common cause.`,`Infective endocarditis would present with symptoms of a systemic illness (e.g., fever, chills).`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-  The patient is status post-myocardial infarction and has evidence of cardiac failure. Among the listed entities, only ventricular aneurysm is a complication of myocardial infarction. Large aneurysms may be associated with low ejection fractions and heart failure. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 72-year-old man with poorly controlled diabetes has a 5-year history of worsening exercise tolerance. During the past year, he has had chest pain with minimal exertion. On physical examination he has bilateral pulmonary rales and pitting edema of his legs. He has an irregular heart rate. A chest radiograph shows prominent right and left heart borders. Echocardiography shows decreased left ventricular ejection fraction (25%), with diminished wall motion. Laboratory studies show an elevated serum natriuretic peptide. Which of the following pathologic findings is most likely present in this man?`,
        q2: ``,
        q3: [],
        option: [`Coronary stenosis occluding 90% of lumen`, `Aneurysm of left ventricle with mural thrombus`,` Rupture of the left ventricle`,`Mitral and tricuspid valve thickening`,`Myocardial reperfusion injury `],
        optionFeedback: [`<!--Answers:--> The findings in this man indicate the presence of biventricular heart failure associated with atrial dilation. There is no history of overt myocardial infarction, and diabetes (particularly when poorly controlled) is often associated with diffuse coronary atherosclerotic disease. The overall picture is therefore most consistent with ischemic heart disease, a frequent cause of heart failure, likely due to multiple critical stenoses (&gt;90%) in coronary arteries.  `,`Ventricular aneurysm with mural thrombus follows myocardial infarction (for which there is no history) and often presents with embolic phenomena (e.g., stroke).`,`Rupture of the left ventricle would present dramatically with cardiac tamponade and acute heart failure.`,`Mitral and tricuspid valve thickening might be associated with stenosis, which typically would produce atrial dilation rather than ventricular hypertrophy.`,`Myocardial reperfusion injury is seen following myocardial infarction, for which no evidence is provided.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The findings in this man indicate the presence of biventricular heart failure associated with atrial dilation. There is no history of overt myocardial infarction, and diabetes (particularly when poorly controlled) is often associated with diffuse coronary atherosclerotic disease. The overall picture is therefore most consistent with ischemic heart disease, a frequent cause of heart failure, likely due to multiple critical stenoses (&gt;90%) in coronary arteries.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 50-year-old man experiences the sudden onset of severe substernal chest pain that radiates to the neck. On physical examination, he is afebrile, but has tachycardia, hyperventilation, and hypotension. No cardiac murmurs are heard on auscultation. Emergent coronary angiography shows a thrombotic occlusion of the left circumflex artery, and areas of 50% to 70% narrowing in the proximal circumflex and anterior descending arteries. Which of the following complications of this disease is most likely to occur within 1 hour of these events?`,
        q2: ``,
        q3: [],
        option: [`Myocardial rupture`, `Pericarditis`,`Papillary muscle rupture`,`Ventricular fibrillation`,`Thromboembolism`],
        optionFeedback: [`Myocardial rupture rarely occurs before 48 hr post-myocardial infarction.`,`Pericarditis is a delayed complication. It most often appears 2 to 4 days following a transmural myocardial infarction; occasionally, a later, transient form of pericarditis called Dressler syndrome that is associated with fever, pleuritic pain, and a friction rub appears 2 to 3 weeks after myocardial infarction.`,`Papillary muscle rupture rarely occurs before 48 hr post-myocardial infarction.`,`<!--Answers:--> The history along with coronary angiography suggests an acute coronary event leading to myocardial ischemia. Ischemic heart muscles are prone to irregularities of electrical conduction that can lead to ventricular fibrillation and cardiac arrest. The remaining possible answers are potential complications of myocardial infarction, but do not occur acutely. `,`Thromboembolism (e.g., from a ventricular aneurysm) is a delayed complication. Mural thrombi may embolize and can form in areas of infarction or ventricular aneurysms, usually several days to several weeks after myocardial infarction. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The history along with coronary angiography suggests an acute coronary event leading to myocardial ischemia. Ischemic heart muscles are prone to irregularities of electrical conduction that can lead to ventricular fibrillation and cardiac arrest. The remaining possible answers are potential complications of myocardial infarction, but do not occur acutely.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 59-year-old man has experienced chronic fatigue for the past 18 months. A chest radiograph shows bilateral pulmonary edema and a prominent left heart border. The representative gross appearance of his heart is shown in the figure. Laboratory studies show serum glucose 74 mg/dL, total cholesterol 189 mg/dL, total protein 7.1 g/dL, albumin 5.2 g/dL, creatinine 3.1 mg/dL, and urea nitrogen 60 mg/dL.   Based on the clinical and morphologic features, which of the following is the most likely underlying cause of his disease?<img src="../images/f008-q018-9780323640251.png" alt="" data-uuid="4449e82a706e499b8d67d05f0a4a5fc4"/>`,
        q2: ``,
        q3: [],
        option: [`Dilated cardiomyopathy`, `Diabetes `,`Pulmonary hypertension`,`Emphysema`,`Systemic hypertension`],
        optionFeedback: [`Dilated cardiomyopathy is associated with dilation of all four chambers and is hence incompatible with the appearance of the heart.`,`Diabetes mellitus could be associated with heart failure and renal failure, but the single glucose measurement provided is normal, and, in the absence of hypertension, diabetic vascular complications would not produce ventricular hypertrophy. `,`Isolated pulmonary hypertension would produce right-sided heart enlargement.`,`Emphysema over time also would place the patient at risk for right-sided heart failure.`,`<!--Answers:--> The findings of left heart failure, left ventricular hypertrophy, and renal insufficiency are consistent with hypertensive heart disease, a complication of longstanding hypertension.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The findings of left heart failure, left ventricular hypertrophy, and renal insufficiency are consistent with hypertensive heart disease, a complication of longstanding hypertension.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 77-year-old woman has had episodes of syncope with exertion for the past month. On physical examination, she is afebrile. Her pulse is 66 bpm, respirations are 14 breaths/min, and blood pressure is 125/85 mm Hg. On auscultation, a systolic ejection murmur is heard. There are a few crackles over the lung bases posteriorly. From the representative gross appearance of the opened aorta shown in the figure, which of the following most likely contributed to the development of this lesion?<img src="../images/f008-q019-9780323640251.png" alt="" data-uuid="24643262becd4b6ea69fcf665872e027"/>`,
        q2: ``,
        q3: [],
        option: [`Age-associated degeneration`, `Chromosomal aneuploidy`,` Hypercalcemia `,`Systemic lupus erythematosus`,`Marfan syndrome`],
        optionFeedback: [`<!--Answers:--> Calcific degeneration leading to stenosis of the aortic valve is most often a “wear and tear” phenomenon of aging and therefore represents a form of dystrophic calcification. It occurs more often and at earlier ages in individuals with bicuspid aortic valve.  `,`Chromosomal aneuploidy is incompatible with presentation in a 77-year-old woman and is not associated with isolated aortic stenosis.`,`Hypercalcemia is associated with other complications (renal stones, altered sensorium) as well as “metastatic calcification” in tissues such as the stomach, kidney, and lung. `,`Systemic lupus erythematosus is associated with Libman-Sacks endocarditis, in which vegetations are formed on valves injured by immune complex deposition. There is no calcific degeneration`,`Marfan syndrome is associated with aortic dissection due to weakness of the aortic wall, but aortic valves are not affected by this disease.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Calcific degeneration leading to stenosis of the aortic valve is most often a “wear and tear” phenomenon of aging and therefore represents a form of dystrophic calcification. It occurs more often and at earlier ages in individuals with bicuspid aortic valve.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 65-year-old healthy woman presents for her annual check-up. The only finding is a midsystolic click on auscultation of the heart. Within 5 years she has increasing dyspnea. Echocardiography now shows mitral regurgitation from prolapse of a leaflet. This patient is most likely to be at an increased risk of developing which of the following complications?`,
        q2: ``,
        q3: [],
        option: [`Infective endocarditis`, `al valve. Abnormal heart valves are more likely to be seeded by bacteria (especially Streptococcus viridans), leading to infective endocarditis`,`Subluxation of ocular lenses`,`Rheumatic fever`,`Systemic lupus erythematosus`],
        optionFeedback: [`<!--Answers:-->  The clinical presentation (mid systolic click, mitral valve prolapse) is typical of “floppy” mitral valve. Abnormal heart valves are more likely to be seeded by bacteria (especially Streptococcus viridans), leading to infective endocarditis.  `,` Dystrophic calcification is associated with valvular stenosis, not regurgitation. `,` Subluxation of ocular lenses is a feature of Marfan syndrome, which is associated with aortic dissection. `,` Rheumatic fever is associated with mitral valvular stenosis, not regurgitation. `,` SLE may be associated with Libman-Sacks endocarditis, in which small sterile thrombi form on valves, most commonly the mitral valve. This process does not lead to valvular stenosis or insufficiency.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-al valve. Abnormal heart valves are more likely to be seeded by bacteria (especially Streptococcus viridans), leading to infective endocarditis `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An 11-year-old boy had a sore throat, tonsillar exudates, and fever 3 weeks ago when a throat culture was positive for group A β-hemolytic Streptococcus. One month later, on follow-up examination, the child is afebrile, his pulse is 85 bpm, respirations are 18 breaths/min, and blood pressure is 90/50 mm Hg. He exhibits involuntary movements and complains of joint pains. Over the next 2 days he has several episodes of atrial fibrillation, accompanied by signs of acute left ventricular failure. Which of the following is the most likely underlying mechanism of cardiac failure in this child?`,
        q2: ``,
        q3: [],
        option: [`Antibody-mediated injury to the heart`, `Infection of the heart by streptococci`,`Superimposed viral infection of the myocardium`,`Nonbacterial thrombotic endocarditis`,`Presence of congenital heart disease`],
        optionFeedback: [`<!--Answers:--> This scenario, which includes evidence of heart failure, chorea, and arthritis, is classic for acute rheumatic fever. In rheumatic heart disease, antibodies against Streptococcal antigens cross-react with host antigens, including antigens expressed by cardiac valves and cardiomyocytes. Such antibodies cause injury to the heart. `,`A patient with endocarditis would not be afebrile and would not have chorea, which is thought to be caused by autoantibodies that recognize antigens expressed in the basal ganglia of the brain.`,`Viral myocarditis would usually present with heart failure without other symptoms; it is not a complication of rheumatic fever.`,`Nonbacterial thrombotic endocarditis is characterized by deposition of small, sterile, nondestructive thrombotic masses on cardiac valves. It usually presents with embolic phenomena and is most commonly associated with hypercoagulable states that occur with some cancers.`,`The presentation and subacute course are not consistent with congenital heart disease.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-  This scenario, which includes evidence of heart failure, chorea, and arthritis, is classic for acute rheumatic fever. In rheumatic heart disease, antibodies against Streptococcal antigens cross-react with host antigens, including antigens expressed by cardiac valves and cardiomyocytes. Such antibodies cause injury to the heart`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 26-year-old woman with a previous history of rheumatic fever has had a fever for 7 days. On physical examination, her temperature is 38.2° C, pulse is 100 bpm, respirations are 19 breaths/min, and blood pressure is 90/60 mm Hg. A cardiac murmur is heard on auscultation. Laboratory findings include hemoglobin 13.1 g/dL, platelet count 233,300/mm<sup>3</sup>, and white blood cell count 19,200/mm<sup>3</sup>. Blood cultures are positive for gram-positive bacteria. An echocardiogram shows a 1.5-cm vegetation on the mitral valve. Which of the following complications is this patient most likely to develop?`,
        q2: ``,
        q3: [],
        option: [`Cerebral abscess`, `Dilated cardiomyopathy`,` Myxomatous mitral valve degeneration`,`Pericardial effusion with tamponade`,`Pulmonary infarction`],
        optionFeedback: [`<!--Answers:--> The patient has developed infective endocarditis superimposed on an abnormal heart valve due to prior rheumatic fever. The resulting infected vegetations may embolize and seed many tissues, including the brain, where the result might be a cerebral abscess.  `,`Dilated cardiomyopathy is most often caused by inherited abnormalities in the contractile apparatus of cardiomyocytes or exposure to toxins, such as doxorubicin. Mural thrombi may be present and can be the source of emboli, but these emboli are sterile and hence are not associated with acute inflammation (which this patient has).`,`Myxomatous mitral valve degeneration results from a defect in connective tissue of the valve, which may be inherited (as in Marfan syndrome) or acquired. It is not a feature of infective endocarditis.`,`Pericardial effusion with tamponade is not a complication of infective endocarditis per se, although it could occur with acute rheumatic fever complicated by pericarditis.`,`Pulmonary infarction is unlikely because left-sided emboli do not travel to the lung.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The patient has developed infective endocarditis superimposed on an abnormal heart valve due to prior rheumatic fever. The resulting infected vegetations may embolize and seed many tissues, including the brain, where the result might be a cerebral abscess.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 19-year-old man has had a low-grade fever for 3 weeks. On physical examination, his temperature is 38.3° C, pulse is 104 bpm, respirations are 28 breaths/min, and blood pressure is 95/60 mm Hg. A tender spleen tip is palpable. There are splinter hemorrhages under the fingernails and tender hemorrhagic nodules on the palms and soles. A heart murmur is heard on auscultation. Which of the following infectious agents is most likely to be cultured from this patient’s blood?`,
        q2: ``,
        q3: [],
        option: [`Coxsackievirus B`, `Mycobacterium tuberculosis`,`Pseudomonas aeruginosa`,`Streptococcus viridans`,`Trypanosoma cruzi`],
        optionFeedback: [`Coxsackie B virus is associated with chronic myocarditis. `,`   M. tuberculosis endocarditis is very rare and occurs mainly in individuals with widely disseminated tuberculosis. More commonly, tuberculosis causes pericarditis.`,`Pseudomonas aeruginosa is a rare cause of endocarditis, mainly found in intravenous drug users. It causes an acute endocarditis that worsens over days, not weeks.`,`<!--Answers:--> The findings—prolonged low-grade fever, heart murmur, mild splenomegaly, and splinter hemorrhages—are all classic features of subacute infective endocarditis, which is often caused by Streptococcus viridans.  `,`Trypanosoma cruzi is associated with myocarditis.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-The findings—prolonged low-grade fever, heart murmur, mild splenomegaly, and splinter hemorrhages—are all classic features of subacute infective endocarditis, which is often caused by Streptococcus viridans. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 71-year-old woman has had a 10-kg weight loss accompanied by increasingly severe nausea for the past 8 months and has recently vomited blood. On physical examination, she is afebrile. Laboratory studies show hemoglobin 8.4 g/dL, platelet count 227,100/mm<sup>3</sup>, and white blood cell count 6180/mm<sup>3</sup>. Blood cultures are sterile. Biopsy specimens obtained by upper gastrointestinal endoscopy show adenocarcinoma of the stomach. Computed tomography scan of the head shows a cystic area in the right frontal lobe. Which of the following cardiac lesions is most likely to be present in this woman?`,
        q2: ``,
        q3: [],
        option: [` Calcific aortic valvular stenosis`, `Infective endocarditis`,`Aortic dissection`,`Right ventricular mural thrombosis`,`Nonbacterial thrombotic endocarditis`],
        optionFeedback: [`Calcific aortic valvular stenosis is not associated with adenocarcinoma and is unlikely to produce emboli.`,`Infective endocarditis is not associated with adenocarcinoma and would present with signs of infection.`,`    Aortic dissection is not associated with adenocarcinoma, presents acutely and does not cause embolic infarcts.`,`Right ventricular mural thrombosis is not associated with adenocarcinoma and emboli would not enter the systemic circulation (unless there is a right-to-left shunt).`,`<!--Answers:--> Patients with gastric cancer and other forms of adenocarcinoma are at high risk of developing thrombotic complications, possibly related to procoagulants released from tumor cells. One manifestation of this prothrombotic state is nonbacterial thrombotic endocarditis, in which sterile, platelet-rich thrombi form on heart valves, most commonly on the left side of the heart. These may produce emboli that can travel to the brain, leading to stroke, which may explain this patient’s cystic brain lesion (possible old infarct).  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-Patients with gastric cancer and other forms of adenocarcinoma are at high risk of developing thrombotic complications, possibly related to procoagulants released from tumor cells. One manifestation of this prothrombotic state is nonbacterial thrombotic endocarditis, in which sterile, platelet-rich thrombi form on heart valves, most commonly on the left side of the heart. These may produce emboli that can travel to the brain, leading to stroke, which may explain this patient’s cystic brain lesion (possible old infarct).   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 44-year-old previously healthy man has experienced worsening exercise tolerance accompanied by marked shortness of breath for the past 6 months. He has diffuse rales in all lung fields and pitting edema to the knees. A chest radiograph shows cardiomegaly and pulmonary edema with pleural effusions. An echocardiogram shows four-chamber cardiac enlargement and mitral and tricuspid valvular regurgitation, with an ejection fraction of 30%. A coronary angiogram shows a 10% to 20% narrowing of the major coronary arteries. A germline mutation in a gene encoding which of the following proteins is the most likely basis of this disease?`,
        q2: ``,
        q3: [],
        option: [`Transthyretin`, ` Low density lipoprotein receptor`,`Muscle phosphorylase`,` A contractile protein`,`Alpha chain of collagen`],
        optionFeedback: [`Transthyretin mutations are associated with cardiac amyloidosis, a restrictive cardiomyopathy.`,`Mutations in the gene encoding the low density lipoprotein receptor are associated with familial hypercholesterolemia and accelerated atherosclerosis.`,`Mutation of a gene encoding muscle phosphorylase causes a form of glycogen storage disease affecting skeletal muscles. Affected individuals have muscle cramps and myoglobinuria. Cardiac muscle is not affected.`,`<!--Answers:--> The features (four-chamber cardiac enlargement and mitral and tricuspid valvular regurgitation, with an ejection fraction of 30%) are consistent with dilated cardiomyopathy (DCM). DCM has many causes, but in an adult without any evidence of atherosclerotic coronary artery disease, there is likely to be a genetic cause. The most frequent causative mutations affect genes that encode components of the contractile apparatus (e.g., beta myosin heavy chain) or cytoskeletal proteins that are components of the sarcomere that also contribute to force generation (e.g., titin).  `,`Mutations in collagen genes are usually associated with joint, soft tissue, or vascular abnormalities, not heart disease.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The features (four-chamber cardiac enlargement and mitral and tricuspid valvular regurgitation, with an ejection fraction of 30%) are consistent with dilated cardiomyopathy (DCM). DCM has many causes, but in an adult without any evidence of atherosclerotic coronary artery disease, there is likely to be a genetic cause. The most frequent causative mutations affect genes that encode components of the contractile apparatus (e.g., beta myosin heavy chain) or cytoskeletal proteins that are components of the sarcomere that also contribute to force generation (e.g., titin).`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 56-year-old man has experienced increased fatigue and decreased exercise tolerance for the past 2 years. On physical examination, his temperature is 37° C, pulse is 75 bpm, respirations are 17 breaths/min, and blood pressure is 115/75 mm Hg. On auscultation, diffuse crackles are audible. The abdomen is distended with a fluid wave, and there is bilateral pitting edema to the knees. A chest radiograph shows pulmonary edema, pleural effusions, and marked cardiomegaly. An echocardiogram shows reduced right and left ventricular wall motion, with an ejection fraction of 30%. Chronic use of which of the following substances has most likely produced these findings?`,
        q2: ``,
        q3: [],
        option: [`Acetaminophen`, `Cocaine`,`Ethanol`,` Nicotine`,`Antacids`],
        optionFeedback: [` Acetaminophen is associated with acute liver failure when taken at toxic doses.`,` Cocaine is associated with arrhythmia and vasospasm, not dilated cardiomyopathy.`,`<!--Answers:--> The findings in this patient (pulmonary edema, low ejection fraction, peripheral edema, cardiomegaly with reduced wall motion of both ventricles) are consistent with dilated cardiomyopathy and biventricular heart failure, possibly complicated by hepatic disease leading to ascites. Of the listed drugs, only ethanol is a common cause of cardiomyopathy, typically in heavy drinkers (6 or more drinks per day). `,` Nicotine use in the form of tobacco smoking is most commonly associated with coronary artery disease and myocardial infarction.`,` Antacids are not associated with cardiac disease.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-The findings in this patient (pulmonary edema, low ejection fraction, peripheral edema, cardiomegaly with reduced wall motion of both ventricles) are consistent with dilated cardiomyopathy and biventricular heart failure, possibly complicated by hepatic disease leading to ascites. Of the listed drugs, only ethanol is a common cause of cardiomyopathy, typically in heavy drinkers (6 or more drinks per day) `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 10-year-old girl who developed normally has chronic progressive exercise intolerance. Her physical exam findings are unremarkable. A chest radiograph shows cardiomegaly and mild pulmonary edema. An echocardiogram shows severe left ventricular hypertrophy, a prominent interventricular septum and slight thickening of the right ventricle. During systole, the anterior leaflet of the mitral valve moves into the outflow tract of the left ventricle. The ejection fraction is abnormally high, and the ventricular volume and cardiac output are both low. Which of the following is the most likely cause of the cardiac abnormalities in this patient?`,
        q2: ``,
        q3: [],
        option: [`Antibody response against myocardial fiber`, `Mutation of a gene that encodes a cytoskeletal protein`,`Excessive iron absorption`,`Hypercalcemia`,` Coxsackie B enterovirus infection`],
        optionFeedback: [`Antibody response against myocardial fibers is a feature of rheumatic heart disease, which does not lead to hypertrophic cardiomyopathy.`,`<!--Answers:--> Left ventricular hypertrophy and a prominent interventricular septum, the movement during systole of the anterior leaflet of the mitral valve into the outflow tract of the left ventricle, and abnormally high ejection fraction are diagnostic of hypertrophic cardiomyopathy. Hypertrophic cardiomyopathy is caused by mutations in contractile or cytoskeletal proteins that compose the sarcomere, the contractile unit of cardiac myofibrils. These mutations tend to increase contractility, rather than impair it (which is what happens in dilated cardiomyopathy).  `,`Excessive absorption of iron is associated with hemochromatosis, which may lead to dilated cardiomyopathy presenting as heart failure in older adults.`,`Hypercalcemia is associated with metastatic calcification and can affect many organs, including the heart. However, it does not present with the anatomic findings in this patient. `,`Coxsackie B enterovirus infection is associated with myocarditis, which may lead to a dilated cardiomyopathy.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:-Left ventricular hypertrophy and a prominent interventricular septum, the movement during systole of the anterior leaflet of the mitral valve into the outflow tract of the left ventricle, and abnormally high ejection fraction are diagnostic of hypertrophic cardiomyopathy. Hypertrophic cardiomyopathy is caused by mutations in contractile or cytoskeletal proteins that compose the sarcomere, the contractile unit of cardiac myofibrils. These mutations tend to increase contractility, rather than impair it (which is what happens in dilated cardiomyopathy).   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 17-year-old girl jumps up for a block in the third match of a volleyball tournament and suddenly collapses. She requires cardiopulmonary resuscitation. A similar episode occurs a month later. She has been healthy all her life and had mentioned only limited episodes of chest pain in games during the current school year. Genetic analysis reveals a mutation in the gene encoding the beta-myosin heavy chain, which is involved in contraction of cardiac muscle fibers. Which of the following pathologic findings of the heart is most likely to be present in this girl?`,
        q2: ``,
        q3: [],
        option: [`Extensive myocardial hemosiderin deposition`, `Haphazardly arranged hypertrophied septal myocytes`,`Large, friable vegetations with destruction of aortic valve cusps`,`Mitral valvular stenosis with left atrial enlargement`,` Endomyocardial fibrosis`],
        optionFeedback: [` Extensive myocardial hemosiderin deposition can be seen in hemochromatosis, which may present with clinical features of dilated cardiomyopathy in older adults and is usually caused by mutations in the HFE gene. `,`<!--Answers:--> The gene encoding the beta-myosin heavy chain is one of the genes that is most commonly mutated in hypertrophic cardiomyopathy, which histologically is marked by haphazardly arranged hypertrophied septal myocytes. Other mutations in the beta-myosin heavy chain are associated with dilated cardiomyopathy; these mutations cause loss-of-function, whereas those associated with hypertrophy cause gain-of-function. Dilated cardiomyopathy is most commonly diagnosed in patients between the ages of 20 to 50 years and presents with signs of slowly progressive congestive heart failure. `,`Large, friable vegetations with destruction of aortic valve cusps is a feature of infective endocarditis, which would present as a systemic illness (e.g., fever, chills).`,`Mitral valvular stenosis with left atrial enlargement is a feature of rheumatic heart disease, another acquired disorder with a different clinical course.`,`Endomyocardial fibrosis is an idiopathic disease of children and young adults seen in Africa. Extensive fibrosis of the endocardium and subendocardium causes restrictive cardiomyopathy. This disease has been linked to nutritional deficiencies and/or inflammation linked to helminthic infections.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The gene encoding the beta-myosin heavy chain is one of the genes that is most commonly mutated in hypertrophic cardiomyopathy, which histologically is marked by haphazardly arranged hypertrophied septal myocytes. Other mutations in the beta-myosin heavy chain are associated with dilated cardiomyopathy; these mutations cause loss-of-function, whereas those associated with hypertrophy cause gain-of-function. Dilated cardiomyopathy is most commonly diagnosed in patients between the ages of 20 to 50 years and presents with signs of slowly progressive congestive heart failure.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `An 86-year-old man has a 7-year history of increasing dyspnea and reduced exercise tolerance. On physical examination, he is afebrile and has a blood pressure of 135/85 mm Hg. An irregular heart rate averaging 76 bpm is audible on auscultation of the chest. A chest radiograph shows mild cardiomegaly and mild pulmonary edema. Echocardiography demonstrates abnormal ventricular wall thickening, with reduced left and right ventricular wall motion, and an ejection fraction estimated to be 25%. An endomyocardial biopsy specimen shows amorphous pink-staining deposits between myocardial fibers, but no inflammation or necrosis. Echocardiography would most likely show which of the following hemodynamic changes in the heart?`,
        q2: ``,
        q3: [],
        option: [`Dynamic obstruction to ventricular outflow`, `Impaired ventricular diastolic filling`,`Increased end-systolic volume`,`Mitral and tricuspid valvular insufficiency`,`Aortic valve insufficiency`],
        optionFeedback: [`Dynamic obstruction to ventricular outflow is a feature of hypertrophic cardiomyopathy, which is associated with haphazard arrangement of cardiac myofibrils.`,`<!--Answers:--> The amorphous pink material seen on biopsy is amyloid, which may deposit in the heart and lead to stiffening of the cardiac chambers. This in turn reduces the relaxation of the heart during diastole, decreasing ventricular filling, ventricular stroke volume, and cardiac output (diastolic heart failure). All of these are characteristic of restrictive cardiomyopathy. Cardiac amyloidosis can occur in the setting of systemic amyloidosis (e.g., multiple myeloma) or can be predominantly restricted to the heart as in this case (senile cardiac amyloidosis). Senile cardiac amyloidosis is due to deposition of normal (or mutant) transthyretin, a liver-synthesized circulating protein that transports thyroxine and retinol. `,`Increased end-systolic volume is associated with heart dilation, which is not a feature of amyloidosis, a disorder associated with restrictive cardiomyopathy.`,`Mitral and tricuspid valve insufficiency are associated with dilated cardiomyopathy, not restrictive cardiomyopathy.`,`Aortic valve insufficiency can occur in rheumatic heart disease and in conditions associated with aortic arch dilation, such as syphilis and Marfan syndrome.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText: `Rationale:- The amorphous pink material seen on biopsy is amyloid, which may deposit in the heart and lead to stiffening of the cardiac chambers. This in turn reduces the relaxation of the heart during diastole, decreasing ventricular filling, ventricular stroke volume, and cardiac output (diastolic heart failure). All of these are characteristic of restrictive cardiomyopathy. Cardiac amyloidosis can occur in the setting of systemic amyloidosis (e.g., multiple myeloma) or can be predominantly restricted to the heart as in this case (senile cardiac amyloidosis). Senile cardiac amyloidosis is due to deposition of normal (or mutant) transthyretin, a liver-synthesized circulating protein that transports thyroxine and retinol`,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 38-year-old, previously healthy woman reports having suddenly lost consciousness four times in the past 6 months. In three instances, she was unconsciousness for only a few minutes. After the fourth episode 1 month ago, she was unconscious for 6 hours and had weakness in her right arm and difficulty speaking. On physical examination, she is afebrile, and her blood pressure is normal, as is the electrocardiogram. A mid-systolic murmur was noted that was position dependent. She has good carotid pulses with no bruits. Which of the following cardiac lesions is most likely to be present in this woman?`,
        q2: ``,
        q3: [],
        option: [` Bicuspid aortic valve`, `Coronary artery thrombosis`,` Left atrial myxoma`,`Mitral valve stenosis`,`Pericardial effusion`],
        optionFeedback: [`Bicuspid aortic valve would likely present with symptoms of aortic stenosis, which usually occurs in older adults and is associated with less dramatic symptoms, such as chest pain and dyspnea on exertion.`,`Coronary artery thrombosis could lead to ischemia-related arrhythmias, but is more likely to present with other symptoms, such as angina or myocardial infarction.`,`<!--Answers:--> Atrial myxoma is most common in women in their 30s and 40s. When pedunculated, these tumors are sufficiently mobile to cause position-dependent murmurs and intermittent obstruction of the mitral valve (when located in the left atrium, which is true of approximately 80% of cases). Patients with left-sided tumors are at risk for sudden death due to severe mitral obstruction. Fragments of the tumor can embolize systemically (e.g., to the brain), as seems to have occurred in this patient. Of the other diagnoses, none results in the type of “drop attacks” that this patient is suffering.`,`Mitral valve stenosis would be expected to present with symptoms related to pulmonary edema (i.e., dyspnea on exertion, orthopnea).`,`Pericardial effusion might be due to pericarditis (for which there is no evidence) and might cause symptoms related to slow onset cardiac tamponade, such as dyspnea, chest discomfort, and peripheral edema due to diminished cardiac output. It is not associated with the type of “drop attacks” that are occurring in this patient. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-Atrial myxoma is most common in women in their 30s and 40s. When pedunculated, these tumors are sufficiently mobile to cause position-dependent murmurs and intermittent obstruction of the mitral valve (when located in the left atrium, which is true of approximately 80% of cases). Patients with left-sided tumors are at risk for sudden death due to severe mitral obstruction. Fragments of the tumor can embolize systemically (e.g., to the brain), as seems to have occurred in this patient. Of the other diagnoses, none results in the type of “drop attacks” that this patient is suffering `,
        state: `notAnswered`,
        userAnswered: [],
    }
    

   ];






