var quiz = [
    {
        q: `Patients with chronic hepatitis B virus (HBV) or hepatitis C virus (HCV) infection are at greatly increased risk of developing hepatocellular carcinomas. Which of the following best accounts for this predisposition?`,
        q2: ``,
        q3: [],
        option: [`The consistent integration of these viruses in the vicinity of protooncogenes`, `The ability of these viruses to disable DNA repair`, `Mutations incurred during regeneration following virus-induced cellular injury`,`The ability of viral genes to inactivate RB expression`,` The ability of these viruses to compromise the host immune response`],
        optionFeedback: [`Hepatitis C is an RNA virus that does not integrate into the genomes of hepatocytes. Hepatitis B sometimes integrates, but this appears to be a random process and there is limited evidence at present that this integration event either activates oncogenes or silences tumor suppressor genes. `,`Certain “professional” transforming DNA viruses, such as high-risk human papilloma viruses (HPVs), carry viral genes that encode proteins that inhibit the p53 tumor suppressor, the guardian of the genome, thereby abrogating protective responses to DNA damage; however, hepatitis viruses do not encode such proteins. `,`    In patients who are carriers of hepatitis B or C, chronic infection leads to sustained hepatocyte injury, mainly due to the host immune response to virus-infected hepatocytes. Chronic injury and compensatory hepatocyte proliferation are believed to increase the rate of the random acquisition of driver gene mutations in proto-oncogenes and tumor suppressor genes, which over time may lead to acquisition of cancer hallmarks and outgrowth of fully transformed cells. In addition, host inflammatory and stromal cells may produce growth factors that stimulate tumor cell proliferation and angiogenesis. Chronic injury also underlies the increased risk of hepatocellular carcinoma in diseases that are NOT infectious, such as primary hemochromatosis, Wilson disease, and α<sub>1</sub>-antitrypsin deficiency.  `,`This is true of high-risk HPV, which expresses a viral protein, E7, that is an inhibitor of the RB tumor suppressor, but is not true of hepatitis viruses. `,`Some transforming viruses express factors that dampen the ability of the host to recognize virally infected cells (for example, Epstein-Barr virus expresses a homologue of the immunosuppressive cytokine IL-10), but no such activity has been associated with hepatitis viruses.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- In patients who are carriers of hepatitis B or C, chronic infection leads to sustained hepatocyte injury, mainly due to the host immune response to virus-infected hepatocytes. Chronic injury and compensatory hepatocyte proliferation are believed to increase the rate of the random acquisition of driver gene mutations in proto-oncogenes and tumor suppressor genes, which over time may lead to acquisition of cancer hallmarks and outgrowth of fully transformed cells. In addition, host inflammatory and stromal cells may produce growth factors that stimulate tumor cell proliferation and angiogenesis. Chronic injury also underlies the increased risk of hepatocellular carcinoma in diseases that are NOT infectious, such as primary hemochromatosis, Wilson disease, and α<sub>1</sub>-antitrypsin deficiency. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 30-year-old sexually active woman presents with vaginal bleeding and discharge. Colposcopic examination reveals an ulcerated lesion arising from the squamocolumnar junction of the uterine cervix. Biopsy results show an invasive tumor containing areas of squamous epithelium in which pearls of keratin can be seen. Molecular analysis reveals the presence of human papillomavirus (HPV) type 16 DNA within the tumor cells. Which of the following molecular abnormalities in this tumor is directly related to infection with HPV-16?`,
        q2: ``,
        q3: [],
        option: [`Trapping of the RAS protein in a GTP-bound state`, ` Increased expression of laminin receptor genes`,` Decreased stability of DNA repair proteins`,` Functional inactivation of the RB protein`,`Increased expression of epidermal growth factor receptor`],
        optionFeedback: [`RAS proteins are not targeted by E7 or the other important HPV oncoprotein, E6, a protein that inhibits the function of the p53 tumor suppressor. `,`Laminin is a basement membrane protein; it is not a target of E6 or E7. `,`High risk HPV infection has no direct effect on DNA repair proteins. By inhibiting p53 via the viral E6 oncoprotein, however, it can indirectly cause genomic instability by impairing DNA repair. This second indirect effect of high-risk HPV infection (inhibition of p53) is an important contributor to the virus’ ability to cause cancer. `,`The viral E7 proteins encoded by high-risk HPVs such as HPV-16 bind and inhibit RB, a critical regulator of the G1/S cell cycle checkpoint, thereby preventing cell cycle arrest. This has two oncogenic effects: (1) it increases cellular proliferation; and (2) by preventing cell cycle arrest, which is a normal part of DNA repair, it accelerates the acquisition of genomic aberrations that may lead to activation of oncogenes and inactivation of tumor suppressor genes.  `,`Epidermal growth factor receptor is not a target of the oncoproteins of high-risk HPV.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale:-  The viral E7 proteins encoded by high-risk HPVs such as HPV-16 bind and inhibit RB, a critical regulator of the G1/S cell cycle checkpoint, thereby preventing cell cycle arrest. This has two oncogenic effects: (1) it increases cellular proliferation; and (2) by preventing cell cycle arrest, which is a normal part of DNA repair, it accelerates the acquisition of genomic aberrations that may lead to activation of oncogenes and inactivation of tumor suppressor genes.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A girl is born with a single functional copy of a tumor suppressor gene. At the age of 1 year, the remaining normal allele is lost through mutation, resulting in the development of a tumor from a cell that has lost both copies of the gene. Cell cycle analysis of tumor cells shows that control of transition from G1 to the S phase is lost. Which of the following neoplasms is most likely to arise via this mechanism?`,
        q2: ``,
        q3: [],
        option: [`Retinoblastoma`, ` Breast carcinoma`,`Adenocarcinoma of colon`,`Ovarian carcinoma`,`Chronic myeloid leukemia`],
        optionFeedback: [`In its hereditary from, retinoblastoma stems from inheritance of one defective copy of the RB gene, which encodes the retinoblastoma protein, RB. RB integrates pro-growth and anti-growth signals to control progression from the G1 to the S phases of the cell cycle, beyond which cells proceed through mitosis and divide. RB is active in its hypophosphorylated state, a form that inhibits the expression of genes needed for DNA synthesis. Pro-growth signals phosphorylate and inhibit RB, allowing cells to move from the G1 phase into S phase. In patients with one defective copy of the RB gene, sporadic mutations almost inevitably lead to complete loss of RB function in at least a few retinoblasts, rapidly proliferating cells that are found in the developing retina. This leads to unbridled proliferation and (with acquisition of additional mutations), retinoblastoma, an aggressive tumor, usually in both eyes.  `,`Familial breast cancer is most commonly associated with inherited mutations in tumor suppressor genes that are important in maintaining genomic stability (BRCA1, BRCA2, TP53). `,`Familial colon cancer is most commonly associated with mutations in tumor suppressor genes that are required for DNA mismatch repair (Lynch Syndrome) or in the tumor suppressor gene APC, which encodes a negative regulator of the Wnt signaling pathway. `,`Familial ovarian cancer is most commonly associated with inherited mutations in tumor suppressor genes that are important in maintaining genomic stability (BRCA1, BRCA2, TP53). `,`Chronic myeloid leukemia (CML) is associated with a gain of function BCR-ABL fusion gene, which encodes a constitutively active tyrosine kinase. CML is not an inherited form of cancer.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- In its hereditary from, retinoblastoma stems from inheritance of one defective copy of the RB gene, which encodes the retinoblastoma protein, RB.    RB integrates pro-growth and anti-growth signals to control progression from the G1 to the S phases of the cell cycle, beyond which cells proceed through mitosis and divide. RB is active in its hypophosphorylated state, a form that inhibits the expression of genes needed for DNA synthesis. Pro-growth signals phosphorylate and inhibit RB, allowing cells to move from the G1 phase into S phase. In patients with one defective copy of the RB gene, sporadic mutations almost inevitably lead to complete loss of RB function in at least a few retinoblasts, rapidly proliferating cells that are found in the developing retina. This leads to unbridled proliferation and (with acquisition of additional mutations), retinoblastoma, an aggressive tumor, usually in both eyes.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 60-year-old man presents with increasing fatigue. Physical examination is unremarkable. Laboratory investigations show he is anemic. Stool examination is positive for occult blood. Radiologic investigation revealed an irregular mass in the descending colon. During colonoscopy, a biopsy was performed, illustrated here. Which of the following molecular abnormalities in this lesion is most likely to render the cells resistant to chemotherapy-induced death?`,
        q2: `<img src="../images/f005-q004-9780323640251.png"/>`,
        q3: [],
        option: [` Mutational inactivation of the RB gene`, `Amplification of the RAS gene`,` Mutational inactivation of the TP53 gene`,` Overexpression of the APC gene`,` Loss of heterozygosity of the NF-1 gene`],
        optionFeedback: [`Mutational inactivation of RB may increase proliferation, which in some instances might increase sensitivity to chemotherapy. `,`RAS is activated by point mutations, not by amplification. RAS is not directly involved in cell death pathways triggered by chemotherapeutic agents. `,` One of the ways that many forms of chemotherapy kill cells is by inducing DNA damage, which leads to activation of the p53 protein. p53 causes cell cycle arrest, providing time for DNA repair, and if the damage is too severe, activates members of the BCL2 family that trigger apoptosis via the intrinsic (mitochondrial) pathway. If p53 function is lost (by mutation of TP53 or overexpression of p53 inhibitors such as MDM2), this response fails and cells may survive damage that would otherwise kill them. Moreover, DNA damage goes unrepaired, leading to genomic instability and rapid accumulation of a high burden of mutations. It is increasingly apparent that loss of p53 function is a common cause of resistance to chemotherapy in a broad spectrum of cancers.  `,`APC is a tumor suppressor and is lost in cancer; it is not overexpressed. `,`NF1 protein is a negative regulator of RAS and its loss promotes growth.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- One of the ways that many forms of chemotherapy kill cells is by inducing DNA damage, which leads to activation of the p53 protein. p53 causes cell cycle arrest, providing time for DNA repair, and if the damage is too severe, activates members of the BCL2 family that trigger apoptosis via the intrinsic (mitochondrial) pathway. If p53 function is lost (by mutation of TP53 or overexpression of p53 inhibitors such as MDM2), this response fails and cells may survive damage that would otherwise kill them. Moreover, DNA damage goes unrepaired, leading to genomic instability and rapid accumulation of a high burden of mutations. It is increasingly apparent that loss of p53 function is a common cause of resistance to chemotherapy in a broad spectrum of cancers.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
      {
        q: `A 47-year-old man presents with increasing fatigue. The peripheral blood shows a total leukocyte count of 167,500/mL with mature and immature myeloid cells (myelocytes, metamyelocytes, neutrophils) predominating. Cytogenetic analysis of cells obtained from the bone marrow reveal a t(9:22) translocation. Which of the following agents is most likely to be beneficial in the treatment of this condition?`,
        q2: ``,
        q3: [],
        option: [` Tyrosine kinase inhibitor`, `All-trans retinoic acid`,`HER2 inhibitor`,` Anti-retroviral agents`,`Anti-hepatitis C drugs`],
        optionFeedback: [`t( 9:22) is characteristic of chronic myeloid leukemia. This translocation causes the formation of a BCR-ABL fusion gene whose protein product has constitutive tyrosine kinase activity, which in turn causes uncontrolled cell proliferation. Several inhibitors of BCR-ABL are highly effective in treating chronic myeloid leukemia.  `,`All-trans retinoic acid (ATRA) is a highly specific targeted treatment for acute promyelocytic leukemia, which is caused by a t(15;17) that fuses part of the PML gene to the retinoic acid receptor alpha (RARA) gene. The fusion protein blocks maturation of hematopoietic progenitor cells and thus allows immature cells to proliferate unchecked. ATRA binds to the PML-RARA protein and inhibits its function, in part by triggering its proteolytic degradation. This removes the differentiation blockade and induces the terminal differentiation of leukemia cells into neutrophils, which have short lifespans and rapidly die, resulting in clearance of the leukemia from the marrow and the blood. `,`HER2 inhibitors are used in cancers that have amplification of the HER2 gene, which encodes a receptor tyrosine kinase that is a member of the EGF receptor family. HER2 amplification is seen in carcinomas, particularly a subset of breast cancers. `,`Anti-retroviral agents are not used to treat human cancers; they can help to prevent cancer in those with HIV infection by controlling the virus and thus restoring host immunity. `,`Anti-hepatitis C drugs help to prevent hepatocellular carcinoma by curing the infection, which otherwise may become chronic, leading to liver damage, cirrhosis, and sometimes hepatocellular carcinoma.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-t( 9:22) is characteristic of chronic myeloid leukemia. This translocation causes the formation of a BCR-ABL fusion gene whose protein product has constitutive tyrosine kinase activity, which in turn causes uncontrolled cell proliferation. Several inhibitors of BCR-ABL are highly effective in treating chronic myeloid leukemia.   `,
        state: `notAnswered`,
        userAnswered: [],
    },

    
    {
        q: `The high-power microscopic appearance of a neoplasm from a 58-year-old woman is shown in the figure. All areas of the tumor have similar morphology. This neoplasm is best described as a(n)?`,
        q2: `<img src="../images/f005-q006-9780323640251.png"/>`,
        q3: [],
        option: [`Adenoma`, `Adenocarcinoma`,` Squamous cell carcinoma`,`Leiomyoma`,`Anaplastic carcinoma`],
        optionFeedback: [`Adenoma is a benign glandular tumor. One would see well-organized glands without cytologic atypia or abnormal mitotic figures. `,`Adenocarcinoma would also form glands or gland-like structures, but would have malignant features, such as cellular atypia, invasion of surrounding tissues, and/or metastasis. `,`Squamous cell carcinomas show features of squamous differentiation, such as formation of squamous “pearls” (collections of dying squamous epithelial cells and keratin). `,`Leiomyoma is a benign spindle cell tumor in which the tumor cells are usually organized in fascicles (bundles), and cellular atypia and mitotic activity are minimal. `,`The tumor exhibits significant pleomorphism, hyperchromasia, and atypical mitotic figures, all features of a poorly differentiated, “anaplastic” cancer. This tumor is so poorly differentiated that immunohistochemical stains for epithelial markers would likely be needed to confirm its identity as a carcinoma (versus, for example, a poorly differentiated sarcoma).  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The tumor exhibits significant pleomorphism, hyperchromasia, and atypical mitotic figures, all features of a poorly differentiated, “anaplastic” cancer. This tumor is so poorly differentiated that immunohistochemical stains for epithelial markers would likely be needed to confirm its identity as a carcinoma (versus, for example, a poorly differentiated sarcoma).   `,
        state: `notAnswered`,
        userAnswered: [],
    },
     
        {
        q: `A 70-year-old woman presented with a 4-month history of weight loss and increasing jaundice. An abdominal computed tomography scan revealed a mass in the head of the pancreas. Molecular analysis of neoplastic cells showed high level activation of MAP kinases (MAPK) because a mutation greatly reduced the GTPase activity of a protein encoded by the mutated gene. Mutation of which of the following genes is most likely responsible for these alterations?`,
        q2: ``,
        q3: [],
        option: [` MYC`, `ABL`,` RAS`,` ERBB2/HER2`,` RET`],
        optionFeedback: [`MYC is an oncogenic transcription factor that is often overexpressed due to chromosomal translocation, such as the (8;14) translocation that is typically seen in Burkitt lymphoma. `,`ABL is a non-receptor tyrosine kinase that is activated by the (9;22) translocation in chronic myeloid leukemia. `,`RAS is a GTP binding protein that has an intrinsic GTPase activity that “flips” RAS into its inactive state. Mutations seen in cancer abrogate this GTPase activity. `,`HER2 is a receptor tyrosine kinase that is often overexpressed due to amplification, mainly in subsets of breast adenocarcinoma. `,`RET is a receptor tyrosine kinase that is activated by translocation in several cancers, including a small subset of non–small cell lung adenocarcinomas, and by point mutations in medullary thyroid cancer. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- RAS is a GTP binding protein that has an intrinsic GTPase activity that “flips” RAS into its inactive state. Mutations seen in cancer abrogate this GTPase activity. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `An isolated 4 mm polyp is found by colonoscopy in the sigmoid colon of a 50-year-old woman. The excised polyp histologically reveals well-differentiated glands without invasion of the stalk. Which of the following would distinguish whether the polyp represents hyperplasia of the colonic mucosa or a neoplastic adenoma?`,
        q2: ``,
        q3: [],
        option: [`Histochemical staining for mucin`, ` Determination of the frequency of cells in the S phase`,` Determination of clonality by sequencing of DNA`,`Immunoperoxidase staining for presence of keratin`,` Immunoperoxidase staining for CD34 to assess angiogenesis`],
        optionFeedback: [`Both normal and neoplastic epithelium may contain mucin-containing cells. `,`Both normal and neoplastic tissues may contain proliferating cells. `,` Hyperplastic polyps are thought to be due to decreased epithelial cell turnover and delayed shedding of surface cells. It is a polyclonal lesion. By contrast, adenomas are true neoplasms and therefore have acquired clonal genetic abnormalities in oncogenes and tumor suppressor genes; in typical adenomas, these may include mutations of APC and KRAS. `,`Both normal and neoplastic epithelium may contain keratin-expressing cells. `,`Vascularity may be increased in both neoplastic and non-neoplastic tissues; for example, inflamed tissues or tissues undergoing repair may show increased vascularity.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-Hyperplastic polyps are thought to be due to decreased epithelial cell turnover and delayed shedding of surface cells. It is a polyclonal lesion. By contrast, adenomas are true neoplasms and therefore have acquired clonal genetic abnormalities in oncogenes and tumor suppressor genes; in typical adenomas, these may include mutations of APC and KRAS.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 29-year-old woman presents with a 1-month history of a neck mass. On physical examination, a palpable nodule is identified in the right lobe of her thyroid gland. A fine-needle aspirate of the nodule reveals cells consistent with a carcinoma of the thyroid. No other family members are affected by this disorder. Which of the following would you consider to be most relevant in her past history?`,
        q2: ``,
        q3: [],
        option: [`Cigarette smoking`, `Corticosteroid therapy`,` Radiation therapy in childhood`,`Use of oral contraceptives`,`Exposure to asbestos compounds`],
        optionFeedback: [`Cigarette smoking is associated with many cancers, but not thyroid cancer. `,`Corticosteroid therapy is not associated with cancer. `,`  Radiation is known to increase risk for thyroid cancer, especially if the exposure is to radioactive iodine, as occurred following the nuclear reactor accident at Chernobyl in Ukraine in 1986.  `,`Use of oral contraceptives, as currently formulated, shows a possible weak association with breast cancer and a weak protective effect against ovarian cancer. They are not associated with thyroid cancer. `,`Asbestos is associated with mesothelioma and lung cancer, the latter particularly in those who also smoke.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Radiation is known to increase risk for thyroid cancer, especially if the exposure is to radioactive iodine, as occurred following the nuclear reactor accident at Chernobyl in Ukraine in 1986`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 64-year-old man has an episode of hemoptysis. A chest radiograph reveals a 5-cm right upper lobe lung mass. A fine-needle aspirate of this mass yields cells consistent with small cell carcinoma. On physical examination, the patient is found to have puffiness of the face, pedal edema, and systolic hypertension. A bone scan shows no metastases. Serum level of which of the following is most likely to be elevated?`,
        q2: ``,
        q3: [],
        option: [`Parathyroid hormone (PTH)-related protein`, ` Erythropoietin`,`Corticotrophin (ACTH)`,`Insulin`,`Angiotensin`],
        optionFeedback: [`Parathyroid hormone (PTH)-related protein increases bone resorption by binding to receptors on osteoblasts, creating signals that stimulate the release of RANKL, a factor that activates osteoclasts. High levels of parathyroid hormone (PTH)-related protein lead to hypercalcemia. This form of paraneoplastic syndrome is associated with non–small cell lung cancer, particularly squamous cell carcinoma of the lung. `,`Erythropoietin drives red cell production from the bone marrow. It is sometimes produced by renal cell carcinoma, hepatocellular carcinoma, and several other tumors. `,`    Hypertension, “moon” facies, and edema are all signs of elevated cortisol levels. ACTH increases expression of corticosteroids such as cortisol from the adrenal cortex. Small cell carcinoma shows neuroendocrine differentiation and often expresses hormones that are not typically released by pulmonary epithelial cells, such as ACTH.    This is a classic example of a paraneoplastic syndrome.  `,`Insulin overproduction leads to hypoglycemia and is most often seen in insulin-producing islet cell tumors. Hypoglycemia may be seen as a paraneoplastic syndrome in fibrosarcomas, other mesenchymal tumors and ovarian carcinomas due to elaboration of insulin and insulin-like substance. `,`Angiotensin is the final product in a hormone “cascade” involving renin, a renal hormone produced in response to renal “underperfusion.” Angiotensin overproduction has been described as a rare cause of paraneoplastic hypertension, most commonly associated with hepatocellular carcinoma.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Hypertension, “moon” facies, and edema are all signs of elevated cortisol levels. ACTH increases expression of corticosteroids such as cortisol from the adrenal cortex. Small cell carcinoma shows neuroendocrine differentiation and often expresses hormones that are not typically released by pulmonary epithelial cells, such as ACTH.    This is a classic example of a paraneoplastic syndrome. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 66-year-old man with chronic cough and recent hemoptysis has a chest radiograph that shows a 6-cm right lung mass. A sputum cytologic analysis reveals cells consistent with squamous cell carcinoma. Where are metastases from this neoplasm most likely to be found?`,
        q2: ``,
        q3: [],
        option: [` Chest wall muscle`, ` Ribs`,` Hilar lymph nodes`,` Liver`,` Brain`],
        optionFeedback: [`Local invasion of chest wall muscle can occur late in the course after spread to the pleura but is unlikely at presentation. Local invasion is not considered metastatic disease but as a sign of local aggression. `,`Rib involvement would be an example of hematogenous spread, which also can occur later in the course. Cancers most likely to spread to bone include breast, lung, thyroid, kidney, and prostate carcinomas. `,`   Carcinomas usually spread via the lymphatics and, therefore, the initial metastasis of a lung cancer is the hilar lymph nodes, a major drainage site of pulmonary lymphatics.  `,`Liver metastases are associated with hematogenous spread and are most common in the setting of colon carcinoma due to tumor cells entering the portal circulation. `,`The brain can be a site of hematogenous spread with many aggressive cancers, including carcinomas, melanomas, and germ cell tumors. In those with lung cancer, brain metastases tend to occur later in the course of the disease.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-Carcinomas usually spread via the lymphatics and, therefore, the initial metastasis of a lung cancer is the hilar lymph nodes, a major drainage site of pulmonary lymphatics.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 33-year-old woman has a routine physical examination. There are no abnormal findings. As part of the pelvic examination, a Pap test is performed. Cytological examination of the cells obtained from the Pap test demonstrates severe epithelial dysplasia. Based on this observation, what would you tell this patient?`,
        q2: ``,
        q3: [],
        option: [` This lesion could progress to invasive cervical carcinoma.`, ` An ovarian teratoma is most likely coexistent`,`There has been regression of an earlier cervical carcinoma`,` Antibiotic therapy will cure the lesion`,`Your female relatives are at risk for the same disease`],
        optionFeedback: [`Severe dysplasia (often referred to as high risk squamous intraepithelial lesion [HSIL]) caused by high-risk human papillomavirus infection is an important precursor lesion to cervical carcinoma. Furthermore, an early cervical carcinoma may also be present. Therefore, clinical follow up with repeat examination and biopsy and, if necessary surgery, are recommended.  `,`There is no association between ovarian teratoma and high risk squamous intraepithelial lesion, as teratomas are not related to human papillomavirus infection. `,`Once established, cervical carcinoma (unlike squamous intraepithelial lesions) does not regress. The presence of high risk squamous intraepithelial lesions, by contrast, raises the possibility that an early cervical carcinoma might be present and is an indication for surgical removal (conization). `,`Human papillomavirus cannot be treated with antibiotics. It can be prevented in most cases, however, by current vaccines. `,`Human papillomavirus is a classic infectious cause of cancer; risk is not inherited and therefore is not shared by family members.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- Severe dysplasia (often referred to as high risk squamous intraepithelial lesion [HSIL]) caused by high-risk human papillomavirus infection is an important precursor lesion to cervical carcinoma. Furthermore, an early cervical carcinoma may also be present. Therefore, clinical follow up with repeat examination and biopsy and, if necessary surgery, are recommended.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A family history of colon cancer is elicited from a 36-year-old man. Based on this history, a screening colonoscopy is performed, and the cecum and ascending colon are found to contain five polyps, ranging from 0.5 to 2 cm in diameter. They are excised and examined microscopically. The 2-cm polyp contains a focus of adenocarcinoma. Inherited mutations in genes encoding which of the following types of proteins are most likely to be involved in the causation of this tumor?`,
        q2: ``,
        q3: [],
        option: [` Growth factor receptors`, `Adhesion molecules`,`DNA mismatch repair`,`Cyclin dependent kinases`,` Regulator of apoptosis`],
        optionFeedback: [`Inherited mutations in growth factor receptor genes are associated with a variety of disorders, many non-neoplastic (i.e., achondroplastic dwarfism), but are not associated with colon cancer. `,`Inherited defects in E-cadherin are associated with gastric and breast cancer, but not colon cancer. `,`  A family history of right-sided colon cancer and the finding of scattered polyps elsewhere in the colon are consistent with a diagnosis of hereditary nonpolyposis colon cancer. Affected individuals often present with cancer at early ages that may arise from sessile serrated polyps; however, the polyps are not nearly as numerous as in the other major inherited disorder associated with colon cancer, familial adenomatous polyposis coli, which is caused by mutations in the APC tumor suppressor gene.  `,`Inherited gain of function mutations in cyclin dependent kinase 4 (CDK4) and loss of function mutations in its antagonist, p16 (encoded by the CDKN2A gene) are associated with familial forms of melanoma, but not colon cancer. `,`Loss of pro-apoptotic (Bax, Bak) and activation of anti-apoptotic factors (e.g., Bcl2) are not associated with familial forms of cancer. Overexpression of BCL2, as in follicular lymphomas, protects tumor cells from apoptosis and thus favors survival of cancer cells.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- A family history of right-sided colon cancer and the finding of scattered polyps elsewhere in the colon are consistent with a diagnosis of hereditary nonpolyposis colon cancer. Affected individuals often present with cancer at early ages that may arise from sessile serrated polyps; however, the polyps are not nearly as numerous as in the other major inherited disorder associated with colon cancer, familial adenomatous polyposis coli, which is caused by mutations in the APC tumor suppressor gene.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 15-year-old boy presents with swelling of the lower end of the femur close to the knee joint. X-rays show a mass arising from the femur that invades surrounding soft tissue. A biopsy reveals an osteosarcoma. The attending physician tells the family that this tumor is very aggressive and very likely to develop metastases. Which of the following is most likely to be the initial site of metastases?`,
        q2: ``,
        q3: [],
        option: [`Liver`, ` Inguinal lymph nodes`,` Lungs`,`Brain`,`Adrenal glands`],
        optionFeedback: [`This is a very common site of metastasis from gastrointestinal tract whose venous drainage is via the portal vein, which supplies the liver. Thus, liver metastases are common in patients with colonic adenocarcinoma and pancreatic adenocarcinoma. `,`Most sarcomas do not commonly spread through lymphatic channels. Inguinal lymph nodes, by contrast, would be a common site for metastasis from a melanoma involving the lower limbs. `,`    Osteosarcoma, as is true of sarcomas generally, has a propensity to spread through blood vessels. The first capillary bed that metastasizing cells in the blood reach from the lower limbs is the lungs.  `,`The brain might be a site of secondary metastasis from lung but would be a very uncommon site for initial metastasis. An exception might be a patient with a patent foramen ovale. Tumors that commonly metastasize to the brain early in their course include lung carcinoma and certain forms of germ cell tumors. `,`This is an unusual site of metastasis except for squamous cell carcinoma of the lung, which seems to have a “tropism” for the adrenal gland. `],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Osteosarcoma, as is true of sarcomas generally, has a propensity to spread through blood vessels. The first capillary bed that metastasizing cells in the blood reach from the lower limbs is the lungs.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 32-year-old woman presents with a 2-month history of dull pelvic pain. Physical examination shows a right adnexal mass. An abdominal ultrasound scan shows a 7.5-cm cystic ovarian mass. The mass is surgically excised. The surface of the mass is smooth and not adherent to surrounding pelvic structures. On gross examination, the cystic mass is filled with hair. Microscopically, squamous epithelium, tall columnar glandular epithelium, cartilage, and fibrous connective tissue are present and resemble normal tissue counterparts. Which of the following is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Adenocarcinoma`, ` Fibroadenoma`,` Hamartoma`,` Mesothelioma`,`Teratoma`],
        optionFeedback: [`Adenocarcinomas are composed of malignant glands of epithelial origin; they lack the other tissue types seen in this specimen. `,`Fibroadenomas contain both benign glands and benign spindled cells resembling fibroblasts but would not contain the other elements seen in this tumor. `,`Hamartoma (frequently a misnomer, because these are usually clonal neoplasms) is composed of a benign neoplastic stromal component and reactive epithelial cells, often gland-forming. It also does not contain some of the elements seen in this neoplasm (e.g., hair, several types of epithelium). `,`Mesothelioma is composed only of the lining cells of the peritoneum or other serosal surfaces.`,`The presence of tissues from multiple germ layers and of multiple types is diagnostic of teratoma, a type of germ cell tumor. The features in this case are classic for a mature cystic teratoma, also known as a dermoid cyst.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The presence of tissues from multiple germ layers and of multiple types is diagnostic of teratoma, a type of germ cell tumor. The features in this case are classic for a mature cystic teratoma, also known as a dermoid cyst.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A Pap test performed on a specimen from a 29-year-old woman during a routine health maintenance examination is abnormal. She is currently asymptomatic. She has a history of multiple sexual partners. Cervical biopsy specimens are obtained and the microscopic appearance is shown in the figure. Which of the following is the most likely diagnosis?`,
        q2: `<img src="../images/f005-q017-9780323640251.png"/>`,
        q3: [],
        option: [`Adenocarcinoma`, `Carcinoma in situ`,` Dysplasia`,` Squamous metaplasia`,` Squamous cell carcinoma`],
        optionFeedback: [`Adenocarcinoma is associated with malignant glands, sometimes with mucus production. `,`Carcinoma in situ would be confined to the surface of the cervix without any breach of the basement membrane; nests of invasive cells are evident here. `,`Dysplasia also is confined to the surface epithelium; when it involves the entire thickness of the cervical epithelium it is called carcinoma in situ. `,`Squamous metaplasia is confined to the surface epithelium and by definition does not exhibit cellular atypia.`,`This is an invasive tumor composed of poorly differentiated squamous cells, some forming keratin pearls—features compatible with invasive cervical carcinoma. Multiple sexual partners increases the risk of HPV infection, which is the major cause of cervical cancer.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- This is an invasive tumor composed of poorly differentiated squamous cells, some forming keratin pearls—features compatible with invasive cervical carcinoma. Multiple sexual partners increases the risk of HPV infection, which is the major cause of cervical cancer.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 44-year-old woman feels painless lumps in her armpit, which were not present a month ago. On examination, right axillary lymphadenopathy is present. The nodes are firm and immobile, seeming to be “stuck down” on surrounding soft tissue. Which of the following is the most likely lesion in her right breast?`,
        q2: ``,
        q3: [],
        option: [` Acute mastitis with abscess`, ` Fibroadenoma`,`Infiltrating ductal carcinoma`,` Carcinoma in situ`,` Teratoma`],
        optionFeedback: [`Acute mastitis with abscess would be expected to be associated with a painful breast mass; moreover, the lymph nodes might be fluctuant (soft) if associated with necrosis. `,`Fibroadenoma is a benign disorder and is not associated with lymph node involvement. `,`  Painless, firm lymph nodes that are fixed are likely to be a malignant process. In a woman of this age, breast cancer is the most likely diagnosis, and infiltrating ductal carcinoma is the most likely subtype.  `,`Carcinoma in situ by definition is not associated with lymphatic spread. `,`Teratoma does not occur in the breast and, even if malignant in origin (e.g., from the ovary), would not spread to axillary lymph nodes.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Painless, firm lymph nodes that are fixed are likely to be a malignant process. In a woman of this age, breast cancer is the most likely diagnosis, and infiltrating ductal carcinoma is the most likely subtype.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 54-year-old woman notes a lump in her right breast. Physical examination shows a 2-cm mass fixed to the underlying tissues beneath the areola and three firm, nontender, lymph nodes palpable in the right axilla. There is no family history of cancer. An excisional breast biopsy is performed, and microscopic examination shows the findings in the figure. Which of the following molecular abnormalities, if seen in her tumor, could be directly exploited therapeutically?`,
        q2: `<img src="../images/f005-q019-9780323640251.png"/>`,
        q3: [],
        option: [`Amplification of the HER2 gene`, `Deletion of one copy of BRCA1 gene`,` Overexpression of cyclin D1`,`Inactivation of one BRCA2 gene copy`,` Loss of E-cadherin expression`],
        optionFeedback: [`The image shows a poorly differentiated carcinoma. Amplification of HER2 is a relatively common feature in poorly differentiated breast carcinoma, and the product of the gene, a receptor tyrosine kinase that is a member of the EGF receptor family, can be targeted with inhibitory antibodies or small molecule drugs.  `,`Deletion of one copy of BRCA1 gene is associated with poorly differentiated breast carcinomas that are often “triple negative,” but this lesion is not currently a target for therapy. `,`Cyclin D1 is not the target of therapy; rather, enzymes that are activated by cyclin D1 (CDK4 and CDK6) are the targets of drug therapy. `,`Inactivation of one BRCA2 gene copy is associated with breast carcinoma, but this lesion is not a target for therapy. `,`Loss of E-cadherin expression is associated with lobular carcinoma and is not therapeutically targetable.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- The image shows a poorly differentiated carcinoma. Amplification of HER2 is a relatively common feature in poorly differentiated breast carcinoma, and the product of the gene, a receptor tyrosine kinase that is a member of the EGF receptor family, can be targeted with inhibitory antibodies or small molecule drugs. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `The mother of a 5-year-old boy notices that his abdomen has enlarged in the past 6 months. On physical examination there is an ill-defined abdominal mass. An abdominal computed tomography scan shows a 9-cm mass in the region of the right adrenal gland. The mass is removed and microscopically shows primitive hyperchromatic cells. Cytogenetic analysis of tumor cells shows many double minutes. Which of the following genes is most likely to have undergone alterations to produce these findings?`,
        q2: ``,
        q3: [],
        option: [`ABL`, `BCL2`,`KRAS`,`NMYC`,`RB`],
        optionFeedback: [`ABL is usually converted to an oncogene by chromosomal rearrangements that create a fusion gene encoding a chimeric ABL protein that is constitutively active (e.g., BCR-ABL). `,`BCL2 is most commonly converted to an oncogene by chromosomal rearrangements that place BCL2 next to a strong enhancer and drive high-level BCL2 protein expression. Such an event occurs in follicular lymphoma. `,`KRAS is typically activated by point mutations in several cancers, but this is a rare event in neuroblastoma. `,`One of the most common solid tumors in pediatric age groups is neuroblastoma, an aggressive neoplasm composed of proliferating neuroblasts. A subset of these tumors has amplification of the NMYC oncogene. The amplified chromosomal region may be extrachromosomal and appear as numerous small chromosomal fragments known as double minutes, or may be integrated into a chromosome, producing a so-called homogeneously staining region. `,`RB is a tumor suppressor gene that is lost through disruptive point substitutions or deletions. It is not amplified in any tumor. `],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- One of the most common solid tumors in pediatric age groups is neuroblastoma, an aggressive neoplasm composed of proliferating neuroblasts. A subset of these tumors has amplification of the NMYC oncogene. The amplified chromosomal region may be extrachromosomal and appear as numerous small chromosomal fragments known as double minutes, or may be integrated into a chromosome, producing a so-called homogeneously staining region. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 55-year-old man has had hemoptysis and worsening cough for the past month. On physical examination, wheezes are auscultated over the right lung posteriorly. A chest radiograph shows a 6-cm right perihilar mass. A fine-needle aspiration biopsy is performed and yields cells with the microscopic appearance of non–small cell carcinoma with squamous differentiation. Molecular analysis of the neoplastic cells shows a TP53 gene mutation. Which of the following derangements is the most likely consequence of this mutation?`,
        q2: ``,
        q3: [],
        option: [`Inability to hydrolyze GTP`, `Uncontrolled tyrosine kinase activation`,`Loss of cell cycle arrest after DNA damage`,`Loss of mismatch repair`,` Activation of telomerase`],
        optionFeedback: [`Inability to hydrolyze GTP is a feature of gain of function mutations in RAS proteins. `,`Uncontrolled tyrosine kinase activation is a feature of point substitutions, in-frame insertions, and gene rearrangements that activate a host of different tyrosine kinases (e.g., ABL). `,`  Sensors of DNA damage transmit signals that stabilize the p53 protein, which turns on the expression of genes such as CDKN1A (which encodes p21) whose products block cell cycle progression. In the absence of p53, this fails to occur.  `,`Loss of mismatch repair is seen in certain tumors due to mutations in a group of genes that work together to fix DNA mismatches created by errors in DNA replication. If their function is lost, a mutator phenotype results that increases the mutation rate and may lead to cancer. `,`Activation of telomerase occurs in many cancers through several mechanisms, including mutations in the telomerase promoter that lead to its “re-expression”.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- Sensors of DNA damage transmit signals that stabilize the p53 protein, which turns on the expression of genes such as CDKN1A (which encodes p21) whose products block cell cycle progression. In the absence of p53, this fails to occur`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 26-year-old man with a family history of colon carcinoma undergoes a surveillance colonoscopy. It reveals hundreds of polyps in the colon, and two focal 0.5-cm ulcerations. A biopsy from an ulcer reveals irregularly shaped glands that have penetrated into the muscular layer. Which of the following molecular events is believed to occur very early in the evolution of his colonic disease process?`,
        q2: ``,
        q3: [],
        option: [` Activation of the WNT signaling pathway`, ` Inability to hydrolyze GTP-bound RAS`,`Microsatellite instability`,`Loss of cell cycle control`,`Failure of DNA repair by homologous recombination`],
        optionFeedback: [`The findings are consistent with familial adenomatous polyposis (FAP), an autosomal dominant trait associated with loss of function mutations in the APC tumor suppressor gene. In FAP, one copy of APC is lost in the germline and hence is a very early event in development of colon cancer. APC normally acts as an inhibitor of WNT signaling, and when the normal allele in patients with FAP is lost through a spontaneous, sporadic mutation, the absence of APC leads to increased WNT signaling and expression of oncogenic genes such as MYC.  `,`Inability to hydrolyze GTP-bound RAS is a feature of a variety of cancers, but these are sporadic, acquired mutations. `,`Microsatellite instability is a feature of Lynch syndrome, due to mutations in mismatch repair genes. Affected individuals also are prone to colon cancer, but the phenotype is usually associated with small numbers of polyps, not the hundreds that are seen with FAP.    `,`Loss of cell cycle control is a feature of familial tumors associated with germline mutations in RB (familial retinoblastoma) and certain regulators of RB function. `,`Failure of DNA repair by homologous recombination is a feature of tumors that arise in individuals who inherit loss of function mutations in the BRCA1 or BRCA2 tumor suppressor genes.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The findings are consistent with familial adenomatous polyposis (FAP), an autosomal dominant trait associated with loss of function mutations in the APC tumor suppressor gene. In FAP, one copy of APC is lost in the germline and hence is a very early event in development of colon cancer. APC normally acts as an inhibitor of WNT signaling, and when the normal allele in patients with FAP is lost through a spontaneous, sporadic mutation, the absence of APC leads to increased WNT signaling and expression of oncogenic genes `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 33-year-old man has a 10-day history of cough with hemoptysis. He has a 45 pack-year history of smoking. A chest computed tomography scan shows a 5-cm right hilar mass. Bronchoscopy is performed, and lung biopsies reveal small cell lung carcinoma. His family history shows three first-degree maternal relatives who developed leukemia, sarcoma, and carcinoma before age 40 years. Germline inheritance of mutation in which of the following genes is most likely responsible for this phenotype?`,
        q2: ``,
        q3: [],
        option: [`APC`, `BCL2`,`KRAS`,`NF1`,` TP53`],
        optionFeedback: [`APC mutations are primarily associated with familial adenomatous polyposis and colon cancer. `,`BCL2 mutations are not associated with a familial cancer syndrome. `,`KRAS mutations are not associated with a familial cancer syndrome. `,`Germline inheritance of loss of function mutations  affecting the NF1 gene cause neurofibromatosis-1, associated with skin lesions, neurofibromas, and an increased risk of malignant nerve sheath tumors and certain gliomas in the brain.`,`The diversity of tumor types is consistent with Li-Fraumeni syndrome, a cancer-prone syndrome caused by loss-of-function mutations in the TP53 tumor suppressor gene.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- The diversity of tumor types is consistent with Li-Fraumeni syndrome, a cancer-prone syndrome caused by loss-of-function mutations in the TP53 tumor suppressor gene.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 30-year-old man has a 15-year history of increasing numbers of benign skin nodules. On physical examination, the firm, nontender, subcutaneous nodules average 0.5 to 1 cm. Further examination shows numerous oval 1- to 5-cm flat, light brown skin macules. A biopsy specimen of one skin nodule shows that it is attached to a peripheral nerve. Which of the following molecular abnormalities is most likely related to his clinical presentation?`,
        q2: ``,
        q3: [],
        option: [` Decreased susceptibility to apoptosis`, ` Impaired functioning of mismatch repair`,` Increased epidermal growth factor receptor signaling`,`Lack of nucleotide excision repair`,`Increased activation of the RAS gene`],
        optionFeedback: [`Decreased susceptibility to apoptosis is a phenotype associated with many cancers, particularly lymphoid neoplasms that overexpress BCL2. `,`Impaired functioning of mismatch repair is a feature of Lynch syndrome associated with an increased risk of colon cancer and other malignancies. `,`Increased epidermal growth factor receptor signaling is a feature of many cancers, sometimes due to mutations that turn on the tyrosine kinase activity of this receptor (e.g., in lung cancer). `,`Lack of nucleotide excision repair is a feature of xeroderma pigmentosa, a disorder associated with a very high incidence of skin cancers.`,`The findings are consistent with neurofibromatosis-1 (NF-1), caused by germline loss-of-function mutations in the NF1 tumor suppressor gene. NF1 encodes a protein that stimulates GTP hydrolysis, thereby inactivating RAS.    `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:-The findings are consistent with neurofibromatosis-1 (NF-1), caused by germline loss-of-function mutations in the NF1 tumor suppressor gene. NF1 encodes a protein that stimulates GTP hydrolysis, thereby inactivating RAS.    `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 53-year-old man diagnosed with oral cancer and treated with radiation and chemotherapy 1 year ago now has a positron emission tomography (PET) scan of his neck that shows a single focus of increased uptake. This focus is resected and microscopic examination shows that it is a metastasis. Which of the following processes explains the patient’s positive PET scan?`,
        q2: ``,
        q3: [],
        option: [`Aerobic glycolysis`, ` VEGF production`,`Autophagy`,`Epithelial mesenchymal transition`,` Telomerase activation`],
        optionFeedback: [`PET scanning is performed with a positron-emitting labeled derivative of glucose (<sup>18</sup>F-fluordeoxyglucose [FDG]) that is taken up through glucose channels but not metabolized. One feature of rapidly growing cells is a switch to “Warburg” metabolism (aerobic glycolysis), in which cells take up large amounts of glucose and use this fuel for anabolic metabolism. Such tumors are “PET avid,” taking up large amounts of FDG.    `,`VEGF production is associated with angiogenesis, a common feature of growing tumors. `,`Autophagy is typically not seen in tumor cells, despite marginal environmental conditions. `,`Epithelial mesenchymal transition occurs when epithelial cells upregulate genes more typical of mesenchymal cells, changing their shape and enhancing cell motility and tumor invasiveness. `,`Telomerase activation is a feature of many cancers that promotes their immortalization, their ability to replicate endlessly.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- PET scanning is performed with a positron-emitting labeled derivative of glucose (<sup>18</sup>F-fluordeoxyglucose [FDG]) that is taken up through glucose channels but not metabolized. One feature of rapidly growing cells is a switch to “Warburg” metabolism (aerobic glycolysis), in which cells take up large amounts of glucose and use this fuel for anabolic metabolism. Such tumors are “PET avid,” taking up large amounts of FDG.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 40-year-old man notices an increasing number of lumps in his groin and armpit over the past 5 months. On physical examination, he has generalized nontender lymph node enlargement and hepatosplenomegaly. An axillary lymph node biopsy shows a malignant tumor of small, irregular lymphoid cells arranged in vague nodules. Immunostaining with antibody to BCL2 is positive in the cytoplasm of the tumor cells. Which of the following processes has been dysregulated in this neoplasm?`,
        q2: ``,
        q3: [],
        option: [`Apoptosis`, `VEGF production`,`Tyrosine kinase activity `,` G1 to S transition`,` DNA repair`],
        optionFeedback: [`The features are consistent with follicular lymphoma, which is highly associated with a t(14;18) that increases expression of BCL2 protein, an inhibitor of the intrinsic (mitochondrial) apoptosis pathway.  `,`VEGF production is increased in many cancers and stimulates angiogenesis but it does not play a significant role in follicular lymphoma (in which angiogenesis is not a prominent feature). BCL2 does not play a role in the regulation of VEGF production.`,`Tyrosine kinase activity is a driver in malignancies with activating mutations in tyrosine kinase genes, which are not associated with follicular lymphoma. BCL2 does not play a role in regulating tyrosine kinase activity. `,`G1 to S transition abnormalities are associated with RB loss or increased expression of D cyclins; the latter is seen in mantle cell lymphoma, but not follicular lymphoma. BCL2 does not play a role in the G1 to S transition.`,`DNA repair abnormalities (e.g., because of mutations in TP53) are not typically associated with follicular lymphoma. BCL2 does not play a role in DNA repair.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-The features are consistent with follicular lymphoma, which is highly associated with a t(14;18) that increases expression of BCL2 protein, an inhibitor of the intrinsic (mitochondrial) apoptosis pathway. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `In an experiment, cells from human malignant neoplasms explanted into tissue culture medium continue to replicate. This allows development of “immortal” tumor cell lines that are extremely useful for the study of tumor biology and responses to therapeutic modalities. Which of the following cellular processes is most likely to endow these tumor cells with limitless replicative ability?`,
        q2: ``,
        q3: [],
        option: [`Secretion of VEGF`, `Release of cytochrome c into the cytoplasm`,`Phosphorylation of RB`,`DNA replication repair`,`Telomere maintenance`],
        optionFeedback: [`Secretion of VEGF is important for driving angiogenesis, but does not immortalize cells. `,`Release of cytochrome c into the cytoplasm is an activator of mitochondrial (intrinsic) apoptosis and would tend to oppose establishment of a cell line. `,`Phosphorylation of RB by cyclin D/CDK4/CDK6 complexes would tend to drive growth but since it does not prevent shortening of telomeres, eventual activation of DNA damage pathways would lead to cell death. `,`DNA replication repair might limit DNA damage but has no direct role in imparting the property of endless replication.`,`Telomere maintenance is essential for endless self-renewal, a feature of cancer cells. Normal cells can double 60 to 70 times, after which they lose the ability to divide and enter senescence. This phenomenon is due to progressive shortening of telomeres at the ends of chromosomes. In cancer cells, telomeres are maintained, most commonly due to upregulation of the enzyme telomerase.  `],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText: `Rationale:- Telomere maintenance is essential for endless self-renewal, a feature of cancer cells. Normal cells can double 60 to 70 times, after which they lose the ability to divide and enter senescence. This phenomenon is due to progressive shortening of telomeres at the ends of chromosomes. In cancer cells, telomeres are maintained, most commonly due to upregulation of the enzyme telomerase. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 48-year-old woman notices a lump in her left breast. On physical examination she has a firm, nonmovable, 2-cm mass in the upper outer quadrant of the left breast. There are enlarged, firm, nontender lymph nodes in the left axilla. A fine-needle aspiration biopsy is performed, and the cells present are consistent with carcinoma. A lumpectomy with axillary lymph node dissection is performed, and carcinoma is present in two of eight axillary nodes. Reduced expression of which of the following molecules by the tumor cells most likely facilitated lymph node metastases?`,
        q2: ``,
        q3: [],
        option: [`Estrogen receptors`, ` HER2`,` E-cadherin`,` Progesterone receptors`,` Tyrosine kinases`],
        optionFeedback: [`Estrogen receptor activation contributes to tumor cell growth and survival but is not known to directly contribute to metastasis. `,`HER2 signaling drives pro-growth pathways and Warburg metabolism via increased tyrosine kinase receptor mediated signaling. `,`E-cadherin is an adhesion molecule and tumor suppressor that acts as an intercellular "glue"; its loss allows cells to infiltrate tissues as single cells. E-cadherin function is lost in almost all epithelial cancers, either by mutational inactivation of E-cadherin genes, activation of β-catenin genes, or inappropriate expression of the SNAIL and TWIST transcription factors, which suppress E-cadherin expression. `,`The role of progesterone receptor (PR) activation in breast cancer is less well understood than that of estrogen receptors (ER), but it appears to oppose some aspects of the effect of estrogen, possibly explaining why breast cancers that are positive for both ER and PR tend to have a somewhat better prognosis than those that are just ER-positive. `,`Tyrosine kinases such as HER2 drive pro-growth pathways and activate Warburg metabolism.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:- E-cadherin is an adhesion molecule and tumor suppressor that acts as an intercellular "glue"; its loss allows cells to infiltrate tissues as single cells. E-cadherin function is lost in almost all epithelial cancers, either by mutational inactivation of E-cadherin genes, activation of β-catenin genes, or inappropriate expression of the SNAIL and TWIST transcription factors, which suppress E-cadherin expression.`,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    
    
    {
        q: `A study of cancer patients treated with the alkylating agent cyclophosphamide shows that they are at a higher risk of developing secondary cancers compared with a control group not receiving chemotherapy. Which of the following is the most likely mechanism by which this agent causes carcinogenesis in these treated cancer patients?`,
        q2: ``,
        q3: [],
        option: [`Activation of protein kinase C`, ` Activation of endogenous viruses`,`Direct DNA damage`,`Inhibition of DNA repair`,` Inhibition of telomerase`],
        optionFeedback: [`Activation of protein kinase C may be caused by exposure to phorbol esters, compounds that act as tumor promoters by stimulating proliferation. `,`Activation of endogenous viruses does not appear to be a cause of cancer in humans. `,`   Cyclophosphamide acts by crosslinking DNA, a form of damage that cannot be easily repaired and leads to mutations that may be carcinogenic.  Direct DNA damage is the mechanism by which alkylating agents are effective chemotherapeutic agents against cancer.`,`Inhibition of DNA repair is most commonly associated with loss of function of tumor suppressor genes, particularly TP53. `,`Inhibition of telomerase is anti-oncogenic, not oncogenic.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText: `Rationale:-Cyclophosphamide acts by crosslinking DNA, a form of damage that cannot be easily repaired and leads to mutations that may be carcinogenic.  Direct DNA damage is the mechanism by which alkylating agents are effective chemotherapeutic agents against cancer. `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 61-year-old man with a history of chronic viral hepatitis has noted a 6-kg weight loss over the past 5 months. Physical examination shows no masses or palpable lymphadenopathy. An abdominal computed tomography scan shows a 10-cm mass in the right lobe of the liver. A stool guaiac test result is negative. An elevation in the serum level of which of the following molecules is most likely to be seen?`,
        q2: ``,
        q3: [],
        option: [`Alpha-fetoprotein`, `Lactate dehydrogenase (LDH)`,` Human chorionic gonadotropin (HCG)`,`Carcinoembryonic antigen`,`Prostate-specific antigen (PSA)`],
        optionFeedback: [`Alpha-fetoprotein is often produced by hepatocellular carcinoma, a tumor that arises in increased frequency in individuals with chronic viral hepatitis.  `,`LDH is found in all cells and tissues, including cancer cells and high levels are found in many forms of tissue injury. This is neither specific nor sensitive as a tumor marker. `,`HCG is elevated in patients with choriocarcinoma and some mixed germ cell tumors. `,`Carcinoembryonic antigen is increased in individuals with a variety of carcinomas, such as colon cancers, but is neither sensitive nor specific enough to be used as a diagnostic or screening test. `,`PSA is elevated in patients with prostate cancer, but also in some benign and inflammatory lesions such as benign prostatic hypertrophy and prostatitis. Although it has been used for screening, it is particularly useful in monitoring the effect of therapy.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:-Alpha-fetoprotein is often produced by hepatocellular carcinoma, a tumor that arises in increased frequency in individuals with chronic viral hepatitis.   `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 69-year-old man has a 3-month history of chronic cough. On physical examination, there is mild stridor on inspiration over the right lung. A chest radiograph shows a 5-cm right hilar lung mass, and a fine-needle aspiration biopsy specimen of the mass shows a squamous cell carcinoma. He is treated with an antibody that causes tumor regression. Which of the following molecules is the most likely target for the antibody used?`,
        q2: ``,
        q3: [],
        option: [` PD-1 expressed on T cells`, ` CD8 expressed on T cells`,`MHC class 1 molecules expressed on tumor cells`,` B7 expressed on antigen presenting cells`,`CD4 expressed on T cells`],
        optionFeedback: [`PD-1 is a receptor that, when stimulated by ligands such as PD-1 ligand expressed on tumor cells or macrophages, leads to T cell “exhaustion.” This suppresses the ability of cytotoxic CD8+ T cells to recognize and kill tumor cells expressing tumor neoantigens. Blockade of this response by antibodies against PD1 or PD-1L can restore tumor immunity and lead to tumor regression.  `,`CD8 expressed on T cells is important in generating cytotoxic T cell responses, but an antibody to this protein would not be therapeutic. `,`MHC class 1 molecules expressed on tumor cells may also play a positive role in cytotoxic T cell responses but antibodies to MHC class 1 have no therapeutic role.`,`B7 expressed on antigen presenting cells serves as a costimulator of T cell responses, and thereby contributes positively to tumor immunity. `,`CD4 expressed on T cells is necessary for antigen-dependent helper T cell responses, which may also contribute to tumor immunity.`],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText: `Rationale:- PD-1 is a receptor that, when stimulated by ligands such as PD-1 ligand expressed on tumor cells or macrophages, leads to T cell “exhaustion.” This suppresses the ability of cytotoxic CD8+ T cells to recognize and kill tumor cells expressing tumor neoantigens. Blockade of this response by antibodies against PD1 or PD-1L can restore tumor immunity and lead to tumor regression.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    
    {
        q: `A 76-year-old woman has reported a change in the quality of her stools during the past month. On physical examination, there are no abnormal findings, but a stool sample is positive for occult blood. A colonoscopy is performed and a constricting mass involving the lower sigmoid colon is found. She undergoes a partial colectomy. Which of the following techniques used during surgery can best aid the surgeon in determining whether the resection is adequate to reduce the probability of a recurrence?`,
        q2: ``,
        q3: [],
        option: [` Electron microscopy`, `Fine-needle aspiration`,`Flow cytometry`,` Frozen section`,` Serum carcinoembryonic antigen assay`],
        optionFeedback: [`Electron microscopy requires special tissue fixation and processing and cannot be performed rapidly.`,`Fine-needle aspiration is usually used to establish or evaluate the possibility of cancer pre-surgery. `,`Flow cytometry is typically used to evaluate hematolymphoid malignancies and takes too much time to be useful in evaluating masses found at surgery. `,`Frozen section, which may be performed within minutes, can be used to assess the status of resection margins, whether enlarged lymph nodes contain metastatic cancer, and sometimes clarify unexpected findings at the time of surgery (e.g., a small nodule on the liver).   `,`Serum carcinoembryonic antigen assay may be used to follow the response to therapy once a diagnosis of cancer has been established.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:-Frozen section, which may be performed within minutes, can be used to assess the status of resection margins, whether enlarged lymph nodes contain metastatic cancer, and sometimes clarify unexpected findings at the time of surgery (e.g., a small nodule on the liver).    `,
        state: `notAnswered`,
        userAnswered: [],
    },

      {
        q: `A 54-year-old woman presents with a one-month history of fatigue, weakness and unintentional weight loss. On physical exam, she is jaundiced and extremely thin with muscle wasting at her temples and of her arms and legs. Computed tomography reveals a 3-cm mass in the head of the pancreas and a biopsy is diagnosed as pancreatic carcinoma. Which of the following is most likely responsible for her body habitus?`,
        q2: ``,
        q3: [],
        option: [`Adrenocorticotrophic hormone (ACTH)`, ` Antidiuretic hormone (ADH)`,`Epidermal growth factor`,`Erythropoietin`,`Tumor necrosis factor (TNF)`],
        optionFeedback: [`ACTH may be secreted by small cell carcinoma of the lung and pancreatic carcinoma to cause Cushing syndrome, which is not associated with cachexia. `,`Small cell carcinoma of the lung may secrete ADH to cause a paraneoplastic syndrome characterized by increased water retention and decreased serum sodium. `,`Epidermal growth factor secretion by carcinomas of the stomach and lung causes acanthosis nigricans, which may be one of the earliest manifestations of an undiagnosed malignancy. canthosis nigricans is characterized by thickened, hyperpigmented skin with a “velvet-like” texture that most commonly appears in the flexural areas (axillae, skin folds of the neck, groin, and anogenital regions).`,`Erythropoietin may be secreted by renal cell carcinoma, cerebellar hemangioma and hepatocellular carcinoma, resulting in polycythemia.`,`Patients with advanced tumors may present with progressive weakness, anorexia and anemia, a condition referred to as cachexia. It is thought that TNF and other cytokines produced by tumor cells or by macrophages in response to tumor cells account for this syndrome. TNF suppresses appetite and inhibits the action of lipoprotein lipase.  `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale:- Patients with advanced tumors may present with progressive weakness, anorexia and anemia, a condition referred to as cachexia. It is thought that TNF and other cytokines produced by tumor cells or by macrophages in response to tumor cells account for this syndrome. TNF suppresses appetite and inhibits the action of lipoprotein lipase.  `,
        state: `notAnswered`,
        userAnswered: [],
    },
    {
        q: `A 58-year-old woman presents with a one-week history of a breast mass. Examination reveals a 3 cm fixed mass in the upper outer quadrant and two palpable axillary lymph nodes. A lumpectomy with axillary lymph node dissection is performed. Pathologic evaluation yields a diagnosis of high grade infiltrating ductal carcinoma with four lymph nodes positive for metastatic carcinoma. Which of the following is most important in determining this patient’s prognosis?`,
        q2: ``,
        q3: [],
        option: [`Abnormal mitotic figures`, `Cytokeratin expression`,`Degree of mitotic activity`,`Number of positive lymph nodes`,`Presence of necrosis`],
        optionFeedback: [`Abnormal mitotic figures can be seen in any malignancy and are not a prognostic risk factor. `,`Cytokeratin expression can be useful in identifying a tumor as a carcinoma, but does not relate to this patient’s prognosis. `,`Mitotic activity is a factor in determining tumor grade: higher grade tumors typically show abundant mitotic figures. However, tumor stage is more important in prognosis than grade. `,`The number of positive lymph nodes is a component of staging whereas the other factors relate to tumor grade. When compared with grading, staging has proved to be more important in determining prognosis. `,`Necrosis is seen when a rapidly growing tumor outpaces its blood supply. It is an indicator of aggressive behavior and a component of some grading systems (e.g., sarcoma). However, necrosis is related to tumor grade and not stage.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText: `Rationale:- The number of positive lymph nodes is a component of staging whereas the other factors relate to tumor grade. When compared with grading, staging has proved to be more important in determining prognosis.`,
        state: `notAnswered`,
        userAnswered: [],
    }


   ];






